;;;; Concrete Tutorial 01 dispatches and the existing iframe surface.
(in-package #:dreyeck/clog-tutorial/reading/tests)

(defun %check-execution (execution observation body &optional (before "rgb(0, 0, 0)"))
  (assert (typep execution 'r:tutorial-01-dispatch-execution))
  (%check-binding observation body)
  (let* ((context (r:execution-context execution))
         (heading (first (test-created body)))
         (steps (r:execution-steps execution)))
    (assert (eq heading (gethash "Heading" context)))
    (dolist (key '("Body" "Window" "Event key" "Connection/event table" "CLOG dispatcher"
                   "Tutorial callback" "ON-NEW-WINDOW"))
      (assert (eq (gethash key context) (r::%object observation key))))
    (assert (equal '(:dispatcher-entered :color-write :dispatcher-returned :css-observed)
                   (mapcar (lambda (step) (getf step :kind)) steps)))
    (assert (eq (gethash "CLOG dispatcher" context) (getf (first steps) :dispatcher)))
    (assert (eq heading (getf (second steps) :target)))
    (assert (eq :green (getf (second steps) :value)))
    (assert (eq heading (getf (fourth steps) :target)))
    (assert (equal before (getf (fourth steps) :before)))
    (assert (equal "rgb(0, 128, 0)" (getf (fourth steps) :after)))
    (assert (equal before (r:execution-color-before execution)))
    (assert (equal "rgb(0, 128, 0)" (r:execution-color-after execution)))
    (assert (eq :returned-normally (r:execution-completion execution)))))

(defun %assert-execution-released (execution)
  (assert (eq :released (r:execution-completion execution)))
  (assert (zerop (hash-table-count (r:execution-context execution))))
  (assert (null (r:execution-steps execution)))
  (assert (null (r::%execution-frame execution)))
  (assert (null (r:execution-color-before execution)))
  (assert (null (r:execution-color-after execution)))
  (let ((view (r:dispatch-execution execution)))
    (assert (search "Execution released" (hv:view-html view)))
    (assert (null (hv:view-references view)))))

(defclass color-contract-element (test-element) ())
(defvar *color-contract-calls* nil)
(defvar *color-contract-values* nil)
(defvar *color-contract-error* nil)
(defmethod (setf clog:color) (value (heading color-contract-element))
  (push (list value heading) *color-contract-calls*)
  (when *color-contract-error* (error *color-contract-error*))
  (values-list *color-contract-values*))

(defun %check-color-contract ()
  (let* ((body (%test-body 1))
         (heading (make-instance 'color-contract-element :data (test-data body)
                                :connection-id (clog::connection-id body) :html-id "contract-heading"))
         (value (list :original-value))
         (context (make-hash-table :test #'equal)))
    (setf (gethash "Heading" context) heading)
    (dolist (results '(nil (first second)))
      (dolist (active '(nil t))
        (let* ((*color-contract-calls* nil) (*color-contract-values* results)
               (*color-contract-error* nil)
               (execution (make-instance 'r:tutorial-01-dispatch-execution
                                         :number 1 :context context :frame nil))
               (r::*executing-tutorial-01* (when active execution)))
          (assert (equal results (multiple-value-list (funcall #'(setf clog:color) value heading))))
          (assert (= 1 (length *color-contract-calls*)))
          (assert (eq value (caar *color-contract-calls*)))
          (assert (eq heading (second (first *color-contract-calls*))))
          (assert (= (if active 1 0) (length (r:execution-steps execution)))))))
    (let* ((*color-contract-calls* nil)
           (*color-contract-error* (make-condition 'simple-error :format-control "original COLOR error"))
           (execution (make-instance 'r:tutorial-01-dispatch-execution :number 2 :context context :frame nil))
           (r::*executing-tutorial-01* execution))
      (assert (eq *color-contract-error*
                  (handler-case (funcall #'(setf clog:color) value heading) (error (condition) condition))))
      (assert (= 1 (length *color-contract-calls*)))
      (assert (= 1 (length (r:execution-steps execution)))))
    (let* ((execution (make-instance 'r:tutorial-01-dispatch-execution :number 3 :context context :frame nil))
           (r::*executing-tutorial-01* execution)
           (*color-contract-calls* nil) (*color-contract-error* nil)
           (proxy (make-instance 'color-contract-element :data (test-data body)
                                 :connection-id (clog::connection-id heading) :html-id (clog:html-id heading))))
      ;; Even within the dynamic boundary, another proxy and public mode are excluded.
      (funcall #'(setf clog:color) value proxy)
      (%served (lambda () (funcall #'(setf clog:color) value heading)))
      (assert (= 2 (length *color-contract-calls*)))
      (assert (null (r:execution-steps execution))))))

(defun %check-execution-unwind-release ()
  (dolist (mode '(:error :throw :release))
    (r:observe-tutorial-01)
    (let* ((body (%test-body 1)) (calls 0) (execution nil)
           (condition (make-condition 'simple-error :format-control "original dispatch error")))
      (%installed-window 1 body)
      (let* ((observation (first (r::%live-windows 1)))
             (heading (first (test-created body)))
             ;; A boundary probe in test metadata; the installed tutorial is untouched.
             (dispatcher (lambda (data)
                           (assert (eq data body)) (incf calls)
                           (setf execution r::*executing-tutorial-01*)
                           (when (eq mode :release) (r:release-tutorial-observations))
                           (funcall #'(setf clog:color) :green heading)
                           (ecase mode
                             (:error (error condition))
                             (:throw (throw 'test-dispatch-exit :escaped))
                             (:release (values :first :second))))))
        (setf (gethash "CLOG dispatcher" (r:observation-objects observation)) dispatcher)
        (ecase mode
          (:error (assert (eq condition (handler-case (r::%observe-dispatch observation dispatcher body)
                                          (error (original) original)))))
          (:throw (assert (eq :escaped (catch 'test-dispatch-exit
                                        (r::%observe-dispatch observation dispatcher body)))))
          (:release (assert (equal '(:first :second)
                                   (multiple-value-list (r::%observe-dispatch observation dispatcher body))))))
        (assert (= 1 calls))
        (assert (null r::*executing-tutorial-01*))
        (assert (null (slot-value observation 'r::pending)))
        (if (eq mode :release)
            (progn (%assert-execution-released execution)
                   (assert (null (r:observed-dispatches observation))))
            (progn
              (assert (eq :did-not-return-normally (r:execution-completion execution)))
              (assert (equal '(:dispatcher-entered :color-write :dispatcher-unwound :css-observed)
                             (mapcar (lambda (step) (getf step :kind)) (r:execution-steps execution))))
              (assert (search "did not return normally" (hv:view-html (r:dispatch-execution execution))))
              (r:release-tutorial-observations)
              (%assert-execution-released execution)))))))

(defun check-dispatch-execution ()
  (let ((r::*observe-tutorial-01* nil) (r::*observe-tutorial-02* nil)
        (r::*tutorial-01-windows* nil) (r::*tutorial-02-windows* nil)
        (r::*observation-hook* nil) (r::*previous-clog-debug* nil)
        (r::*executing-tutorial-01* nil) (clog::*clog-debug* nil))
    (%developing
     (lambda ()
       (call-with-clog
        (lambda ()
          ;; Arming alone, and mounting alone, do not offer a live iframe yet.
          (assert (null (r:tutorial-01-live-page)))
          (tut:install-tutorial-1-route)
          (assert (null (r:tutorial-01-live-page)))
          (r:observe-tutorial-01)
          (let* ((handler (tut:tutorial-1-handler)) (original (fdefinition handler)) (calls 0))
            (unwind-protect
                 (progn
                   (setf (fdefinition handler) (lambda (&rest args) (incf calls) (apply original args)))
                   (dotimes (i 3)
                     (let ((live (r:tutorial-01-live-page)))
                       (assert (typep live 'html-inspector-views/standard::web-page))
                       (assert (equal "/clog-tutorial/01" (slot-value live 'html-inspector-views/standard::url)))
                       (assert (search "iframe" (hv:view-html (hv:👀content live))))
                       (assert (search "/clog-tutorial/01" (hv:view-html (hv:👀content live)))))
                     (let ((view (r:tutorial-01-reading)))
                       (assert (not (search "<iframe" (hv:view-html view))))
                       (assert (find-if (lambda (ref) (typep (cdr ref) 'html-inspector-views/standard::web-page))
                                        (hv:view-references view)))))
                   (assert (zerop calls))
                   (assert (null (r::%live-windows 1))))
              (setf (fdefinition handler) original)))
          (%served
           (lambda ()
             (assert (null (r:tutorial-01-live-page)))
             (assert (notany (lambda (ref) (typep (cdr ref) 'html-inspector-views/standard::web-page))
                            (hv:view-references (r:tutorial-01-reading))))))
          (clog:set-on-new-window nil :path "/clog-tutorial/01")
          (assert (null (r:tutorial-01-live-page)))))
       (r:observe-tutorial-01)
       (%check-color-contract)
       (%check-execution-unwind-release)
       (r:observe-tutorial-01)
       (let* ((body (%test-body 1)) (other (%test-body 1)))
         (%installed-window 1 body)
         (let* ((observation (first (r::%live-windows 1)))
                (heading (first (test-created body))))
           (%click observation)
           (let* ((execution (getf (first (r:observed-dispatches observation)) :execution))
                  (steps (copy-tree (r:execution-steps execution)))
                  (effects (list *click-registrations* *event-registrations* *color-writes*)))
             (%check-execution execution observation body)
             (assert (= 1 (r:execution-number execution)))
             (let ((view (r:dispatch-execution execution)))
               (dolist (key '("Heading" "Body" "Window" "Event key" "Connection/event table"
                              "CLOG dispatcher" "Tutorial callback" "ON-NEW-WINDOW"))
                 (assert (find (gethash key (r:execution-context execution)) (hv:view-references view)
                               :key #'cdr :test #'eq)))
               (dolist (key '("CLOG dispatcher" "Tutorial callback" "ON-NEW-WINDOW"))
                 (assert (find-if (lambda (ref) (%source-code-link-p ref (gethash key (r:execution-context execution))))
                                  (hv:view-references view))))
               (dolist (view (hv:all-views execution))
                 (when (typep view 'hv:html-view) (hv:view-html view))))
             (hv:view-html (r:tutorial-01-reading))
             (assert (equal effects (list *click-registrations* *event-registrations* *color-writes*)))
             (assert (equal steps (r:execution-steps execution)))
             (assert (= 1 (length (r:observed-dispatches observation))))
             ;; Ordinary setters on this heading or another window do not enter the trace.
             (funcall #'(setf clog:color) :green heading)
             (funcall #'(setf clog:color) :green (clog:create-child other "<h1>unrelated</h1>"))
             (assert (equal steps (r:execution-steps execution)))
             ;; Identity and ordering mutation controls, independent of rendered text.
             (let* ((write (second (r:execution-steps execution)))
                    (proxy (make-instance 'test-element :data (test-data body)
                                         :connection-id (clog::connection-id heading) :html-id (clog:html-id heading))))
               (unwind-protect
                    (progn (setf (getf write :target) proxy)
                           (%must-detect (lambda () (%check-execution execution observation body))))
                 (setf (getf write :target) heading)))
             (unwind-protect
                  (progn (rotatef (first (r:execution-steps execution)) (second (r:execution-steps execution)))
                         (%must-detect (lambda () (%check-execution execution observation body))))
               (rotatef (first (r:execution-steps execution)) (second (r:execution-steps execution))))
             (%click observation)
             (let ((second (getf (second (r:observed-dispatches observation)) :execution)))
               (%check-execution second observation body "rgb(0, 128, 0)")
               (assert (= 2 (r:execution-number second)))
               (assert (not (eq execution second)))
               (r:release-tutorial-observations)
               (%assert-execution-released execution)
               (%assert-execution-released second)))))
       ;; Real CLOG disconnect cleanup also clears a record held independently.
       (let ((clog-connection::*connection-data* (make-hash-table :test #'equal))
             (clog-connection::*connection-ids* (make-hash-table :test #'equal))
             (clog-connection::*connections* (make-hash-table :test #'eq))
             (clog-connection:*reconnect-delay* nil))
         (r:observe-tutorial-01)
         (multiple-value-bind (body connection) (%lifecycle-window 1)
           (declare (ignore body))
           (let ((observation (first (r::%live-windows 1))))
             (%click observation)
             (let ((execution (getf (first (r:observed-dispatches observation)) :execution)))
               (clog-connection::handle-close-connection connection)
               (assert (null (r::%live-windows 1)))
               (%assert-execution-released execution)))))
       (r:release-tutorial-observations))))
  (format t "~&Tutorial 01 dispatch execution tests passed: original objects, ordered COLOR evidence, pure rendering, scoped setter/values/errors, release/disconnect, existing Web Page construction and public gate.~%")
  t)
