;;;; Run the installed tutorial functions and CLOG's real SET-ON-CLICK /
;;;; SET-EVENT chain. Only browser DOM/transport operations are substituted.
;;;; The separate browser witness checks those boundaries against Chrome.
(in-package #:dreyeck/clog-tutorial/reading/tests)

(defvar *click-registrations* 0)
(defvar *event-registrations* 0)
(defvar *color-writes* 0)

(defclass test-dom ()
  ((data :initarg :data :reader test-data)
   (tag :initarg :tag :initform "undefined" :reader test-tag)
   (html :initarg :html :initform "" :accessor test-html)
   (color :initform "rgb(0, 0, 0)" :accessor test-color)))
(defclass test-element (test-dom clog:clog-element) ())
(defclass test-section (test-element clog::clog-section) ())
(defclass test-body (test-dom clog:clog-body)
  ((created :initform nil :accessor test-created)))
(defclass test-window (test-dom clog:clog-window) ())
(defclass test-document (test-dom clog:clog-document) ())

;; Independent boundary probes see the arguments before the integration's
;; less-specific :AROUND methods. The identity assertions do not rely only
;; on the integration's own retained metadata.
(defmethod clog:set-on-click :around ((heading test-element) callback
                                     &key one-time cancel-event)
  (declare (ignore one-time cancel-event))
  (incf *click-registrations*)
  (setf (gethash "original callback supplied" (test-data heading)) callback)
  (call-next-method))
(defmethod clog::set-event :around ((heading test-element) event dispatcher
                                  &rest options &key &allow-other-keys)
  (declare (ignore options))
  (incf *event-registrations*)
  (when (equal event "click")
    (setf (gethash "original dispatcher supplied" (test-data heading)) dispatcher))
  (call-next-method))

(defmethod clog:connection-data ((object test-dom))
  (if (gethash "use real connection lifecycle" (test-data object))
      (clog-connection:get-connection-data (clog::connection-id object))
      (test-data object)))
(defmethod clog:html-tag ((object test-dom)) (test-tag object))
(defmethod clog:outer-html ((object test-dom)) (test-html object))
(defmethod clog:color ((object test-dom)) (test-color object))
(defmethod (setf clog:color) (value (object test-dom))
  (incf *color-writes*)
  (setf (test-color object) (if (eq value :green) "rgb(0, 128, 0)" value))
  value)
(defmethod (setf clog:title) (value (object test-document))
  (setf (test-html object) value))
(defmethod clog:height ((body test-body)) (* 34 (length (test-created body))))
(defmethod clog:scroll-to ((window test-window) x y)
  (push (list x y) (gethash "scroll calls" (test-data window))))
(defmethod clog::bind-event-script ((object test-dom) event script)
  (setf (gethash (format nil "script:~A:~A" (clog:html-id object) event)
                 (test-data object)) script))
(defmethod clog:first-child ((object test-dom) &key no-attach)
  (declare (ignore no-attach))
  (make-instance 'test-element :data (test-data object)
                 :connection-id (clog::connection-id object) :html-id "undefined"))
(defmethod clog:create-child ((body test-body) html &key html-id auto-place clog-type)
  (declare (ignore auto-place))
  (let* ((tag (string-downcase (subseq html 1 (min (or (position #\Space html) (length html))
                                                 (position #\> html)))))
         (child (make-instance (if (eq clog-type 'clog::clog-section) 'test-section 'test-element)
                              :data (test-data body) :tag tag :html html
                              :connection-id (clog::connection-id body)
                              :html-id (or html-id (format nil "original-~D" (length (test-created body)))))))
    (setf (clog:parent child) body
          (test-created body) (append (test-created body) (list child)))
    child))

(defun %test-body (number &optional (connection (symbol-name (gensym "window-"))))
  (let* ((data (make-hash-table :test #'equal))
         (body (make-instance 'test-body :data data :tag "body"
                              :connection-id connection :html-id 0
                              :window (make-instance 'test-window :data data :connection-id connection :html-id "window")
                              :html-document (make-instance 'test-document :data data :connection-id connection :html-id "document"))))
    (setf (gethash "clog-body" data) body
          (gethash "clog-path" data) (format nil "/clog-tutorial/~2,'0D" number))
    body))

(defun %installed-window (number body)
  (let ((handler (ecase number (1 (tut:tutorial-1-handler)) (2 (tut:tutorial-2-handler)))))
    ;; The actual CLOG ON-CONNECT boundary, without opening a socket.
    (if clog::*clog-debug* (funcall clog::*clog-debug* handler body)
        (funcall handler body))))

(defun %click (observation)
  (funcall (gethash (r::%object observation "Event key")
                    (r::%object observation "Connection/event table")) ""))

(defun %check-binding (observation body)
  (assert (eq body (r::%object observation "Body")))
  (assert (eq (first (test-created body)) (r::%object observation "Heading")))
  (assert (eq body (clog:parent (r::%object observation "Heading"))))
  (assert (eq (clog:window body) (r::%object observation "Window")))
  (assert (eq (test-data body) (r::%object observation "Connection/event table")))
  (assert (eq (r::%object observation "Registered observer")
              (gethash (r::%object observation "Event key") (test-data body))))
  (assert (functionp (r::%object observation "Tutorial callback")))
  (assert (functionp (r::%object observation "CLOG dispatcher")))
  (assert (eq (r::%object observation "Tutorial callback")
              (gethash "original callback supplied" (test-data body))))
  (assert (eq (r::%object observation "CLOG dispatcher")
              (gethash "original dispatcher supplied" (test-data body))))
  (assert (not (eq (r::%object observation "Registered observer")
                   (r::%object observation "CLOG dispatcher")))))

(defun %check-color (observation body)
  (%check-binding observation body)
  (assert (null (slot-value observation 'r::pending)))
  (let ((frames (r:observed-dispatches observation)))
    (assert (every (lambda (frame) (and (getf frame :completed) (not (getf frame :overlapping)))) frames))
    (assert (equal '("rgb(0, 0, 0)" "rgb(0, 128, 0)")
                   (mapcar (lambda (frame) (getf frame :color-before)) frames)))
    (assert (equal '("rgb(0, 128, 0)" "rgb(0, 128, 0)")
                   (mapcar (lambda (frame) (getf frame :color-after)) frames)))
    (assert (every (lambda (frame) (eq (getf frame :heading) (first (test-created body)))) frames))))

(defun %check-output (observation body)
  (%check-binding observation body)
  (assert (null (slot-value observation 'r::pending)))
  (let ((frames (r:observed-dispatches observation)))
    (assert (every (lambda (frame) (and (getf frame :completed) (not (getf frame :overlapping)))) frames))
    (assert (equal '(0 1 2) (mapcar (lambda (frame) (getf frame :counter-before)) frames)))
    (assert (equal '(1 2 3) (mapcar (lambda (frame) (getf frame :counter-after)) frames)))
    (assert (equal '(1 2 3) (mapcar (lambda (frame) (length (getf frame :paragraphs))) frames)))
    (assert (equal '(1 3 6) (mapcar (lambda (frame) (getf frame :total-after)) frames)))
    (assert (equal (rest (test-created body))
                   (loop for frame in frames append (getf frame :paragraphs))))
    (assert (equal (rest (test-created body)) (r:observed-paragraphs observation)))
    (assert (every (lambda (paragraph) (eq (clog:parent paragraph) body))
                   (r:observed-paragraphs observation)))))

(defun %must-detect (thunk)
  (assert (handler-case (progn (funcall thunk) nil) (error () t))))

(defun %check-inspection-pure (observation body)
  (let ((registrations (list *click-registrations* *event-registrations* *color-writes*))
        (created (copy-list (test-created body)))
        (dispatches (copy-tree (r:observed-dispatches observation)))
        (heading (first (test-created body)))
        (color (test-color (first (test-created body))))
        (counter (when (typep observation 'r:tutorial-02-counter-output) (r:observed-counter observation))))
    (dolist (view (hv:all-views observation))
      (when (typep view 'hv:html-view) (hv:view-html view)))
    (let* ((view (etypecase observation
                   (r:tutorial-01-click-color (r:click-color observation))
                   (r:tutorial-02-counter-output (r:counter-output observation))))
           (references (nth-value 1 (%rendered view))))
      (when (null (r:observed-dispatches observation))
        (assert (search "No click observed" (hv:view-html view))))
      (dolist (key '("ON-NEW-WINDOW" "Heading" "Body" "Window" "Tutorial callback"
                     "CLOG dispatcher" "Registered observer" "Connection/event table"))
        (assert (find (r::%object observation key) references :key #'cdr :test #'eq)))
      (dolist (key '("ON-NEW-WINDOW" "Tutorial callback" "CLOG dispatcher"))
        (assert (find-if (lambda (ref) (%source-code-link-p ref (r::%object observation key))) references))))
    (dolist (object (cons heading (when (typep observation 'r:tutorial-02-counter-output)
                                   (r:observed-paragraphs observation))))
      (dolist (title '("Tree" "HTML" "<span style=\"color: #666;\">Slots</span>"))
        (let ((view (find title (hv:all-views object) :key #'hv:view-title :test #'equal)))
          (assert view) (hv:view-html view))))
    (assert (equal registrations (list *click-registrations* *event-registrations* *color-writes*)))
    (assert (equal created (test-created body)))
    (assert (equal dispatches (r:observed-dispatches observation)))
    (assert (eq heading (first (test-created body))))
    (assert (equal color (test-color heading)))
    (when (typep observation 'r:tutorial-02-counter-output)
      (assert (eql counter (r:observed-counter observation))))))

(defun check-runtime-observations ()
  ;; Check the actual freshly loaded state before binding isolated fixtures.
  (assert (and (null r::*observe-tutorial-01*) (null r::*observe-tutorial-02*)
               (null r::*tutorial-01-windows*) (null r::*tutorial-02-windows*)
               (null r::*initializing-tutorial*) (null r::*registering-click*)
               (null r::*observing-output*) (null r::*observation-hook*)))
  (let ((r::*observe-tutorial-01* nil) (r::*observe-tutorial-02* nil)
        (r::*tutorial-01-windows* nil) (r::*tutorial-02-windows* nil)
        (clog::*clog-debug* nil) (r::*observation-hook* nil) (r::*previous-clog-debug* nil))
    ;; Loading/rendering alone, and a public image even with an old flag,
    ;; must not install any forwarding observer.
    (%developing (lambda ()
                   (%installed-window 1 (%test-body 1))
                   (%installed-window 2 (%test-body 2))
                   (hv:view-html (r:tutorial-01-reading))
                   (hv:view-html (r:tutorial-02-reading))))
    (assert (and (null r::*tutorial-01-windows*) (null r::*tutorial-02-windows*)
                 (null r::*observe-tutorial-01*) (null r::*observe-tutorial-02*)))
    (%served (lambda () (%must-detect #'r:observe-tutorial-01) (%must-detect #'r:observe-tutorial-02)))
    (%developing
     (lambda ()
       (let ((routes (dreyeck/clog-tutorial/tests::%routes)))
         (r:observe-tutorial-01) (r:observe-tutorial-02)
         (assert (equal routes (dreyeck/clog-tutorial/tests::%routes))))
       (let ((body1 (%test-body 1)) (body2 (%test-body 2)) (other-body (%test-body 2)))
         (%installed-window 1 body1)
         (let ((one (first (r::%live-windows 1))))
           (%check-binding one body1)
           (%check-inspection-pure one body1)
           (%click one) (%click one)
           (%check-color one body1)
           (%check-inspection-pure one body1)
           ;; Same HTML id is not original Lisp identity.
           (let* ((objects (r:observation-objects one))
                  (original (gethash "Heading" objects))
                  (proxy (make-instance 'test-element :data (test-data body1)
                                        :connection-id (clog::connection-id original)
                                        :html-id (clog:html-id original))))
             (unwind-protect
                  (progn (setf (gethash "Heading" objects) proxy)
                         (%must-detect (lambda () (%check-color one body1))))
               (setf (gethash "Heading" objects) original)))
           (let ((frame (first (r:observed-dispatches one))))
             (unwind-protect
                  (progn (setf (getf frame :color-after) "rgb(0, 0, 0)")
                         (%must-detect (lambda () (%check-color one body1))))
               (setf (getf frame :color-after) "rgb(0, 128, 0)"))))
         (let* ((one (first (r::%live-windows 1)))
                (table (r::%object one "Connection/event table"))
                (key (r::%object one "Event key"))
                (original (gethash key table)))
           (unwind-protect
                (progn (setf (gethash key table) (r::%object one "CLOG dispatcher"))
                       (%must-detect (lambda () (%check-color one body1))))
             (setf (gethash key table) original)))
         (%installed-window 2 body2)
         (let ((two (first (r::%live-windows 2))))
           (%check-inspection-pure two body2)
           (dotimes (i 3) (%click two))
           (%check-output two body2)
           (%check-inspection-pure two body2)
           (%installed-window 2 other-body)
           (let ((other (first (r::%live-windows 2))))
             (assert (not (eq (r::%object two "Tutorial callback") (r::%object other "Tutorial callback"))))
             (assert (zerop (r:observed-counter other)))
             (assert (null (r:observed-paragraphs other)))
             ;; The observation's projection is not the tutorial's X cell.
             ;; Even a corrupted prior projection cannot change the callback
             ;; or replace evidence derived from this dispatch's real output.
             (setf (r:observed-counter other) 99)
             (%click other)
             (assert (= 1 (r:observed-counter other)))
             (assert (= 0 (getf (first (r:observed-dispatches other)) :counter-before)))
             (assert (= 3 (r:observed-counter two)))
             (assert (= 6 (length (r:observed-paragraphs two)))))
           (let ((frame (second (r:observed-dispatches two))))
             (unwind-protect
                  (progn (setf (getf frame :counter-after) 99)
                         (%must-detect (lambda () (%check-output two body2))))
               (setf (getf frame :counter-after) 2)))
           (let* ((frame (first (r:observed-dispatches two)))
                  (original (first (getf frame :paragraphs)))
                  (proxy (make-instance 'test-element :data (test-data body2)
                                        :connection-id (clog::connection-id original)
                                        :html-id (clog:html-id original))))
             (setf (clog:parent proxy) body2)
             (unwind-protect
                  (progn (setf (getf frame :paragraphs) (list proxy))
                         (%must-detect (lambda () (%check-output two body2))))
               (setf (getf frame :paragraphs) (list original))))
           (let ((paragraph (first (r:observed-paragraphs two))))
             (unwind-protect
                  (progn (setf (clog:parent paragraph) other-body)
                         (%must-detect (lambda () (%check-output two body2))))
               (setf (clog:parent paragraph) body2)))
           (let ((first-frame (first (r:observed-dispatches two))))
             (unwind-protect
                  (progn (setf (getf first-frame :paragraphs) nil)
                         (%must-detect (lambda () (%check-output two body2))))
               (setf (getf first-frame :paragraphs) (list (first (r:observed-paragraphs two))))))))))
    (%developing (lambda ()
    ;; The forwarding boundary preserves data identity, multiple values and
    ;; the original signalled condition; observation does not swallow errors.
    (let* ((body (%test-body 1))
           (observation (r::%retain-click 1 (clog:create-child body "<h1>control</h1>") #'identity))
           (data (list :original-data)) (calls 0))
      (assert (equal '(a b) (multiple-value-list
                             (r::%observe-dispatch observation
                              (lambda (received) (assert (eq data received)) (incf calls) (values 'a 'b)) data))))
      (assert (= 1 calls))
      (let ((condition (make-condition 'simple-error :format-control "original callback error")))
        (assert (eq condition (handler-case
                                  (r::%observe-dispatch observation (lambda (received) (declare (ignore received)) (error condition)) data)
                                (error (caught) caught))))
        (assert (not (getf (second (r:observed-dispatches observation)) :completed)))))
    (let* ((body (%test-body 2))
           (observation (r::%retain-click 2 (clog:create-child body "<h1>overlap control</h1>") #'identity))
           (first (r::%begin-dispatch observation)) (second (r::%begin-dispatch observation)))
      (r::%finish-dispatch observation first t)
      (r::%finish-dispatch observation second t)
      (assert (null (r:observed-counter observation)))
      (assert (every (lambda (frame) (and (getf frame :overlapping) (null (getf frame :counter-after))))
                     (r:observed-dispatches observation))))
    ))
    (let ((r::*observe-tutorial-01* t))
      (%served (lambda ()
                 (let ((before (length r::*tutorial-01-windows*)))
                   (%installed-window 1 (%test-body 1))
                   (assert (= before (length r::*tutorial-01-windows*))))))))
  (format t "~&CLOG runtime observations passed: original identities, dispatch chain, colors, 1/3/6 output, independent windows, pure inspection, error/return preservation and mutation controls.~%")
  t)

(defun check-observe-play-result ()
  (let ((r::*observe-tutorial-01* nil) (r::*observe-tutorial-02* nil)
        (r::*tutorial-01-windows* nil) (r::*tutorial-02-windows* nil)
        (clog::*clog-debug* nil) (r::*observation-hook* nil) (r::*previous-clog-debug* nil))
    (%developing
     (lambda ()
       (dolist (number '(1 2))
         (let* ((name (ecase number (1 'r:observe-tutorial-01) (2 'r:observe-tutorial-02)))
                (routes (dreyeck/clog-tutorial/tests::%routes))
                (effects (list *click-registrations* *event-registrations* *color-writes*))
                (thunk (make-instance 'ap::example-thunk :example name :fn (symbol-function name)))
                ;; Same example-thunk evaluation used by the Play button.
                (result (hv:eval-thunk thunk)))
           (assert result) ; Never open Play's result Inspector on CL:NIL.
           (assert (hash-table-p result))
           (assert (equal (format nil "Tutorial ~2,'0D" number) (gethash "Tutorial" result)))
           (assert (equal "Observation armed" (gethash "Observation" result)))
           (assert (zerop (gethash "Observed windows" result)))
           (assert (equal "No observed window yet" (gethash "Window state" result)))
           (let ((items (find "Items" (hv:all-views result) :key #'hv:view-title :test #'equal)))
             (assert items)
             (multiple-value-bind (html references) (%rendered items)
               (assert (search "Observation armed" html))
               (assert (search "No observed window yet" html))
               (assert (notany (lambda (reference) (null (cdr reference))) references))))
           (assert (equal routes (dreyeck/clog-tutorial/tests::%routes)))
           (assert (equal effects (list *click-registrations* *event-registrations* *color-writes*)))
           (assert (and (null r::*tutorial-01-windows*) (null r::*tutorial-02-windows*)))
           ;; Only a subsequent original window creates a runtime observation.
           (let ((body (%test-body number)))
             (%installed-window number body)
             (let ((observation (first (r::%live-windows number)))
                   (again (hv:eval-thunk thunk)))
               (assert (= 1 (gethash "Observed windows" again)))
               (assert (equal "Observed windows available in the reading" (gethash "Window state" again)))
               (assert (null (r:observed-dispatches observation)))
               (assert (= 1 (length (test-created body))))
               (assert (equal "rgb(0, 0, 0)" (test-color (first (test-created body)))))
               (when (= number 2) (assert (zerop (r:observed-counter observation))))))
           (r:release-tutorial-observations))))))
  (format t "~&Observe Play results passed for 01/02: armed status inspected through Items, never NIL; no window, registration or dispatch from arming/rendering; new-window sequence preserved.~%")
  t)

(defun %lifecycle-window (number)
  (let* ((body (%test-body number))
         (id (clog::connection-id body))
         (connection (gensym "disposable-websocket-")))
    (setf (gethash "use real connection lifecycle" (test-data body)) t
          (gethash id clog-connection::*connection-data*) (test-data body)
          (gethash id clog-connection::*connection-ids*) connection
          (gethash connection clog-connection::*connections*) id)
    (%installed-window number body)
    (values body connection)))

(defun %assert-released (observation)
  (assert (not (r::observation-active-p observation)))
  (assert (= 1 (hash-table-count (r:observation-objects observation))))
  (assert (integerp (r::%object observation "Window number")))
  (dolist (key '("Heading" "Body" "Window" "Tutorial callback" "CLOG dispatcher"
                 "Registered observer" "Connection/event table" "ON-NEW-WINDOW"))
    (assert (null (r::%object observation key))))
  (assert (null (r:observed-dispatches observation)))
  (assert (null (slot-value observation 'r::pending)))
  (when (typep observation 'r:tutorial-02-counter-output)
    (assert (null (r:observed-paragraphs observation)))
    (assert (null (r:observed-counter observation)))))

(defun check-observation-lifecycle ()
  (let ((r::*observe-tutorial-01* nil) (r::*observe-tutorial-02* nil)
        (r::*tutorial-01-windows* nil) (r::*tutorial-02-windows* nil)
        (r::*observation-hook* nil) (r::*previous-clog-debug* nil)
        (clog::*clog-debug* nil)
        (clog-connection::*connection-data* (make-hash-table :test #'equal))
        (clog-connection::*connection-ids* (make-hash-table :test #'equal))
        (clog-connection::*connections* (make-hash-table :test #'eq))
        (clog-connection:*reconnect-delay* nil))
    (%developing
     (lambda ()
       (r:observe-tutorial-01) (r:observe-tutorial-02)
       (dolist (number '(1 2))
         (multiple-value-bind (body-a connection-a) (%lifecycle-window number)
           ;; Keep A, its table and observation strongly reachable in this
           ;; test. Passing must not depend on garbage collection.
           (let* ((a (first (r::%live-windows number)))
                  (table (r::%object a "Connection/event table"))
                  (key (r::%object a "Event key"))
                  (dispatcher (r::%object a "CLOG dispatcher"))
                  (observer (gethash key table)))
             (%click a)
             (assert (= 1 (length (r:observed-dispatches a))))
             (clog-connection::handle-close-connection connection-a)
             (assert (null (clog-connection:get-connection-data (clog::connection-id body-a))))
             ;; This is the reading's normal registry lookup/cleanup path.
             (assert (null (r::%live-windows number)))
             (%assert-released a)
             (assert (eq dispatcher (gethash key table)))
             (assert (not (eq observer (gethash key table))))
             (assert (null (ecase number (1 r::*tutorial-01-windows*) (2 r::*tutorial-02-windows*))))
             ;; Opt-in remains enabled: B observes without enabling again.
             (multiple-value-bind (body-b connection-b) (%lifecycle-window number)
               (let ((b (first (r::%live-windows number))))
                 (assert (not (eq a b))) (%click b)
                 (assert (= 1 (length (r:observed-dispatches b))))
                 (ecase number
                   (1 (assert (equal "rgb(0, 128, 0)" (test-color (first (test-created body-b))))))
                   (2 (assert (= 1 (r:observed-counter b)))
                      (assert (= 1 (length (r:observed-paragraphs b))))))
                 (clog-connection::handle-close-connection connection-b)
                 (assert (null (r::%live-windows number)))
                 (%assert-released b)))))
         ;; Repeated close/open cycles are pruned at registration, even with
         ;; every old observation deliberately pinned by this test.
         (let ((retired nil))
           (dotimes (i 16)
             (multiple-value-bind (body connection) (%lifecycle-window number)
               (declare (ignore body))
               (let* ((pointers (ecase number (1 r::*tutorial-01-windows*) (2 r::*tutorial-02-windows*)))
                      (observation (trivial-garbage:weak-pointer-value (first pointers))))
                 (assert (= 1 (length pointers)))
                 (assert (every (lambda (old) (not (r::observation-active-p old))) retired))
                 (%click observation) (push observation retired)
                 (clog-connection::handle-close-connection connection))))
           (assert (null (r::%live-windows number)))
           (mapc #'%assert-released retired)))
       ;; Disabling releases state and prevents subsequently opened windows
       ;; from being retained. Original tutorial behavior still works.
       (r:release-tutorial-observations)
       (dolist (number '(1 2))
         (multiple-value-bind (body connection) (%lifecycle-window number)
           (let* ((heading (first (test-created body)))
                  (dispatcher (gethash (format nil "~A:click" (clog:html-id heading)) (test-data body))))
             (funcall dispatcher "ordinary click")
             (assert (null (r::%live-windows number)))
             (ecase number
               (1 (assert (equal "rgb(0, 128, 0)" (test-color heading))))
               (2 (assert (= 2 (length (test-created body)))))))
           (clog-connection::handle-close-connection connection))))))
  (format t "~&Observation lifecycle passed without GC: A dispatch -> CLOG disconnect -> registry cleanup/releases bindings -> B dispatch; repeated cycles bounded; disabled windows not retained.~%")
  t)

;; Primary-method boundary fixtures deliberately return arbitrary/zero values.
;; Compare with the integration methods physically absent, not with a copy of
;; their implementation. Raw keyword lists include omissions and duplicates.
(defclass audit-element (test-element) ())
(defclass audit-body (test-body) ())
(defvar *audit-calls* nil)
(defvar *audit-results* nil)
(defvar *audit-error* nil)

(defun %audit-values ()
  (when *audit-error* (error *audit-error*))
  (values-list *audit-results*))

(defmethod clog:set-on-click ((heading audit-element) callback
                             &rest options &key one-time cancel-event)
  (declare (ignore one-time cancel-event))
  (push (list* :click heading callback options) *audit-calls*)
  (%audit-values))
(defmethod clog::set-event ((heading audit-element) event dispatcher
                          &rest options &key call-back-script pre-eval eval-script
                            post-eval cancel-event one-time)
  (declare (ignore call-back-script pre-eval eval-script post-eval cancel-event one-time))
  (push (list* :event heading event dispatcher options) *audit-calls*)
  (setf (gethash (format nil "~A:~A" (clog:html-id heading) event) (test-data heading)) dispatcher)
  (%audit-values))
(defmethod clog:create-child ((body audit-body) html
                             &rest options &key html-id auto-place clog-type)
  (declare (ignore html-id auto-place clog-type))
  (push (list* :create body html options) *audit-calls*)
  (%audit-values))

(defun %without-instrumentation (thunk)
  (let ((methods
          (loop for (name classes) in
                '((clog:set-on-click (clog:clog-element t))
                  (clog::set-event (clog:clog-obj t t))
                  (clog:create-child (clog:clog-obj t)))
                for gf = (fdefinition name)
                collect (cons gf (find-method gf '(:around) (mapcar #'find-class classes))))))
    (unwind-protect
         (progn (dolist (pair methods) (remove-method (car pair) (cdr pair)))
                (funcall thunk))
      (dolist (pair methods) (add-method (car pair) (cdr pair))))))

(defun %ordinary-behaviour ()
  (loop for number in '(1 2)
        for body = (%test-body number)
        collect
        (let* ((returned (%installed-window number body))
               (heading (first (test-created body)))
               (key (format nil "~A:click" (clog:html-id heading)))
               (dispatcher (gethash key (test-data body)))
               (returned-original (eq returned dispatcher)))
          (dotimes (i (if (= number 1) 2 3)) (funcall dispatcher "original data"))
          (list returned-original (test-color heading)
                (mapcar #'test-html (rest (test-created body)))
                (every (lambda (child) (eq (clog:parent child) body)) (test-created body))))))

(defun %closed-window-pointers ()
  ;; Return only weak pointers from a terminated thread, so its Lisp stack
  ;; cannot conservatively keep the otherwise unreachable connection cycle.
  (bordeaux-threads:join-thread
   (bordeaux-threads:make-thread
    (lambda ()
      (%developing
       (lambda ()
         (let ((body (%test-body 2)))
           (%installed-window 2 body)
           (let ((observation (first (r::%live-windows 2))))
             (assert (eq observation (trivial-garbage:weak-pointer-value (first r::*tutorial-02-windows*))))
             (list (first r::*tutorial-02-windows*)
                   (trivial-garbage:make-weak-pointer body)))))))
    :initial-bindings
    (list (cons 'r::*observe-tutorial-02* r::*observe-tutorial-02*)
          (cons 'r::*tutorial-02-windows* r::*tutorial-02-windows*)
          (cons 'clog::*clog-debug* clog::*clog-debug*))
    :name "closed tutorial observation GC witness")))

(defun check-instrumentation-audit ()
  (let ((r::*observe-tutorial-01* nil) (r::*observe-tutorial-02* nil)
        (r::*tutorial-01-windows* nil) (r::*tutorial-02-windows* nil)
        (r::*observation-hook* nil) (r::*previous-clog-debug* nil)
        (clog::*clog-debug* nil))
    (%developing
     (lambda ()
       (assert (equal (%without-instrumentation #'%ordinary-behaviour) (%ordinary-behaviour)))
       (assert (and (null r::*tutorial-01-windows*) (null r::*tutorial-02-windows*)
                    (null clog::*clog-debug*)))
       (let* ((body (%test-body 1))
              (audit-body (change-class body 'audit-body))
              (heading (make-instance 'audit-element :data (test-data body) :tag "h1"
                                     :connection-id (clog::connection-id body) :html-id "audit-heading"))
              (callback #'identity) (dispatcher #'identity)
              (observation (r::%retain-click 1 heading callback))
              (output (r::%retain-click 2 heading callback))
              (frame (r::%begin-dispatch output))
              (child (make-instance 'test-element :data (test-data body) :html-id "audit-child")))
         (setf (clog:parent child) body)
         (dolist (active '(nil t))
           (let ((r::*observe-tutorial-01* active)
                 (r::*initializing-tutorial* (when active (cons 1 body)))
                 (r::*registering-click* nil) (r::*observing-output* nil))
             (loop for operation in
                   (list (lambda () (clog:set-on-click heading callback))
                         (lambda () (clog:set-on-click heading nil))
                         (lambda () (clog:set-on-click heading callback :one-time nil :one-time t :cancel-event :sentinel))
                         (lambda () (clog::set-event heading "click" dispatcher :pre-eval "A" :pre-eval "B" :one-time :sentinel))
                         (lambda () (clog::set-event heading "click" nil))
                         (lambda () (clog:create-child audit-body "<p>default options</p>"))
                         (lambda () (clog:create-child audit-body "<p>audit</p>" :auto-place nil :auto-place :top :html-id "same")))
                   for kind in '(:click :unbind :click :event :unbind :create :create)
                   do (dolist (results (list nil (list child :secondary nil callback) :error))
                        (let* ((*audit-results* results) (*audit-calls* nil)
                               (*audit-error* (when (eq results :error)
                                               (make-condition 'simple-error :format-control "original primary error")))
                               (baseline (%without-instrumentation
                                          (lambda () (handler-case (multiple-value-list (funcall operation))
                                                       (error (condition) condition)))))
                               (arguments (copy-tree *audit-calls*)))
                          (setf *audit-calls* nil)
                          (let ((r::*registering-click* (when (and active (eq kind :event)) observation))
                                (r::*observing-output* (when (and active (eq kind :create)) (cons output frame))))
                            (assert (equal baseline (handler-case (multiple-value-list (funcall operation))
                                                      (error (condition) condition)))))
                          (assert (= 1 (length *audit-calls*)))
                          (assert (equal arguments *audit-calls*))
                          (when (and active (eq kind :event) (not *audit-error*))
                            (assert (eq (r::%object observation "CLOG dispatcher") dispatcher))
                            (assert (eq (r::%object observation "Registered observer")
                                        (gethash "audit-heading:click" (test-data heading)))))))))))
       ;; Preserve an existing debug hook's arguments, invocation count and
       ;; return values; unrelated handler/window paths establish no scope.
       (let ((calls 0) (previous
                        (lambda (event data) (funcall event data))))
         (setf clog::*clog-debug* previous)
         (r:observe-tutorial-01) (r:observe-tutorial-02)
         (assert (eq previous r::*previous-clog-debug*))
         (let* ((body1 (%test-body 1)) (body2 (%test-body 2))
                (other (%test-body 1)) (inspector (%test-body 2)))
           (setf (gethash "clog-path" (test-data inspector)) "/inspector")
           (%installed-window 1 body1) (%installed-window 2 body2)
           (assert (null r::*initializing-tutorial*))
           (let ((one (first (r::%live-windows 1))) (two (first (r::%live-windows 2))))
             (assert (equal '(first second)
                            (multiple-value-list
                             (funcall clog::*clog-debug*
                                      (lambda (data) (assert (eq data other)) (incf calls) (values 'first 'second)) other))))
             (assert (= 1 calls))
             ;; Even on the tutorial path, unrelated or direct handler calls
             ;; and registrations outside ON-NEW-WINDOW are not captured.
             (funcall (tut:tutorial-1-handler) other)
             (%installed-window 2 inspector)
             (clog:set-on-click (first (test-created other)) #'identity)
             (assert (= 1 (length (r::%live-windows 1))))
             (assert (= 1 (length (r::%live-windows 2))))
             (%click one) (%click two)
             (let ((paragraphs (copy-list (r:observed-paragraphs two))))
               (clog:create-child body2 "<p>outside dispatch</p>")
               (clog:create-child inspector "<p>Inspector activity</p>")
               (assert (equal paragraphs (r:observed-paragraphs two))))
             (%check-inspection-pure one body1) (%check-inspection-pure two body2)
             ;; Public mode ignores existing observer entries and refuses
             ;; opt-in/release. It creates no new record, contract or route.
             (assert (null (ap:find-example-contract 'r:release-tutorial-observations)))
             (%served
              (lambda ()
                (%must-detect #'r:observe-tutorial-01) (%must-detect #'r:observe-tutorial-02)
                (%must-detect #'r:release-tutorial-observations)
                (let ((records (copy-list (r:observed-dispatches one))))
                  (%click one)
                  (assert (equal records (r:observed-dispatches one))))))
             ;; Explicit release clears even objects held in Inspector views,
             ;; restores the original entry, and leaves visible state alone.
             (let ((observer (r::%object two "Registered observer"))
                   (dispatcher (r::%object two "CLOG dispatcher"))
                   (created (copy-list (test-created body2)))
                   (replacement (clog:set-on-click (first (test-created body1)) #'identity))
                   (registrations (list *click-registrations* *event-registrations* *color-writes*)))
               (r:release-tutorial-observations)
               (assert (eq clog::*clog-debug* previous))
               (assert (eq dispatcher (gethash (format nil "~A:click" (clog:html-id (first created))) (test-data body2))))
               (assert (eq replacement (gethash (format nil "~A:click" (clog:html-id (first (test-created body1)))) (test-data body1))))
               (assert (equal created (test-created body2)))
               (assert (equal registrations (list *click-registrations* *event-registrations* *color-writes*)))
               (dolist (observation (list one two))
                 (assert (not (r::observation-active-p observation)))
                 (assert (= 1 (hash-table-count (r:observation-objects observation))))
                 (assert (null (r:observed-dispatches observation)))
                 (assert (search "Observation released" (hv:view-html
                          (etypecase observation (r:tutorial-01-click-color (r:click-color observation))
                                                 (r:tutorial-02-counter-output (r:counter-output observation)))))))
               (assert (null (r:observed-paragraphs two)))
               (assert (null (r:observed-counter two)))
               (funcall observer "after release")
               (assert (null (r:observed-dispatches two)))
               (assert (= (+ 2 (length created)) (length (test-created body2)))))
             (%installed-window 1 (%test-body 1))
             (assert (null (r::%live-windows 1))))
           (r:observe-tutorial-02)
           (let ((pointers (%closed-window-pointers)))
             (push (first pointers) r::*tutorial-02-windows*)
             (dotimes (i 3) (trivial-garbage:gc :full t))
             (assert (every (lambda (pointer) (null (trivial-garbage:weak-pointer-value pointer))) pointers)))
           (r:release-tutorial-observations)
           ;; Stopping during an in-flight dispatch must not repopulate its
           ;; cleared records on return. The original operation still runs.
           (r:observe-tutorial-02)
           (let ((body (%test-body 2)))
             (%installed-window 2 body)
             (let ((observation (first (r::%live-windows 2))) (calls 0))
               (assert (equal '(:first :second)
                        (multiple-value-list
                         (r::%observe-dispatch observation
                          (lambda (data)
                            (assert (eq data body)) (incf calls)
                            (r:release-tutorial-observations)
                            (clog:create-child body "<p>after scope ended</p>")
                            (values :first :second)) body))))
               (assert (= 1 calls))
               (assert (= 2 (length (test-created body))))
               (assert (null (r::%begin-dispatch observation)))
               (assert (null (slot-value observation 'r::pending)))
               (assert (null (r:observed-dispatches observation)))
               (assert (null (r:observed-paragraphs observation)))
               (assert (null (r:observed-counter observation))))))))))
  (format t "~&Instrumentation audit passed: absent-method equivalence, exact next-method calls/arguments/all values, exact handler scope, unrelated activity excluded, passive views/public gates, explicit release and closed-window GC.~%")
  t)
