
(DEFPACKAGE :DREYECK/FEDWIKI-JOURNAL/TESTS
  (:USE :CL)
  (:IMPORT-FROM :DREYECK/FEDWIKI-JOURNAL
                #:FEDWIKI-JOURNAL-FINDING-ENTRY-OF
                #:FEDWIKI-JOURNAL-FINDING-KIND-OF
                #:JOURNAL-CHECK)
  (:EXPORT #:RUN-FEDWIKI-JOURNAL-TESTS))
