
(COMMON-LISP:DEFPACKAGE :DREYECK/HYPERDOC/BOUNDARY-TESTS
  (:USE :CL)
  (:EXPORT :RUN-TESTS))

(COMMON-LISP:IN-PACKAGE :DREYECK/HYPERDOC/BOUNDARY-TESTS)

(COMMON-LISP:DEFUN DREYECK/HYPERDOC/BOUNDARY-TESTS::PAGE-HTML
                   (DREYECK/HYPERDOC/BOUNDARY-TESTS::BOOK
                    DREYECK/HYPERDOC/BOUNDARY-TESTS::PATH)
  (HTML-INSPECTOR-VIEWS:VIEW-HTML
   (HTML-INSPECTOR-VIEWS:👀CONTENT
    (HYPERDOC::MAKE-TEXT-PAGE DREYECK/HYPERDOC/BOUNDARY-TESTS::BOOK
                              DREYECK/HYPERDOC/BOUNDARY-TESTS::PATH))))

(COMMON-LISP:DEFUN DREYECK/HYPERDOC/BOUNDARY-TESTS:RUN-TESTS NIL
                   (COMMON-LISP:ASSERT
                                       (COMMON-LISP:NOT
                                                        (ASDF/OPERATE:COMPONENT-LOADED-P
                                                                                         (ASDF/SYSTEM:FIND-SYSTEM
                                                                                                                  "dreyeck/hyperdoc"))))
                   (COMMON-LISP:ASSERT
                                       (COMMON-LISP:NOT
                                                        (COMMON-LISP:FIND-PACKAGE
                                                                                  :DREYECK/HYPERSPEC)))
                   (COMMON-LISP:ASSERT
                                       (COMMON-LISP:NOT
                                                        (COMMON-LISP:SEARCH
                                                                            "/hyperspec/"
                                                                            HTML-INSPECTOR-VIEWS/STANDARD::*HYPERSPEC-URL-TEMPLATE*)))
                   (COMMON-LISP:LET*
                                     ((DREYECK/HYPERDOC/BOUNDARY-TESTS::BASE
                                                                             (COMMON-LISP:MAKE-INSTANCE
                                                                                                        (QUOTE
                                                                                                               HYPERDOC:HYPERDOC)
                                                                                                        :ID
                                                                                                        "boundary"
                                                                                                        :TITLE
                                                                                                        "Boundary"
                                                                                                        :DIRECTORY
                                                                                                        #P"/tmp/"))
                                      (DREYECK/HYPERDOC/BOUNDARY-TESTS::LOADER
                                                                               (COMMON-LISP:FIND-METHOD
                                                                                                        (FUNCTION
                                                                                                                  HYPERDOC:LOAD-PAGE)
                                                                                                        NIL
                                                                                                        (COMMON-LISP:LIST
                                                                                                                          (COMMON-LISP:FIND-CLASS
                                                                                                                                                  (QUOTE
                                                                                                                                                         HYPERDOC:HTML-PAGE)))))
                                      (DREYECK/HYPERDOC/BOUNDARY-TESTS::RENDERER
                                                                                 (COMMON-LISP:FIND-METHOD
                                                                                                          (FUNCTION
                                                                                                                    HYPERBOOK:SERIALIZE-PAGE-DOM)
                                                                                                          NIL
                                                                                                          (COMMON-LISP:LIST
                                                                                                                            (COMMON-LISP:FIND-CLASS
                                                                                                                                                    (QUOTE
                                                                                                                                                           HYPERDOC:PAGE))))))
                                     (COMMON-LISP:ASSERT
                                                         (COMMON-LISP:EQ
                                                                         (HYPERDOC:PAGE-CLASS
                                                                                              DREYECK/HYPERDOC/BOUNDARY-TESTS::BASE
                                                                                              :HTML)
                                                                         (COMMON-LISP:FIND-CLASS
                                                                                                 (QUOTE
                                                                                                        HYPERDOC:HTML-PAGE))))
                                     (ASDF/OPERATE:LOAD-SYSTEM
                                                               "dreyeck/hyperdoc")
                                     (COMMON-LISP:ASSERT
                                                         (COMMON-LISP:EQ
                                                                         DREYECK/HYPERDOC/BOUNDARY-TESTS::LOADER
                                                                         (COMMON-LISP:FIND-METHOD
                                                                                                  (FUNCTION
                                                                                                            HYPERDOC:LOAD-PAGE)
                                                                                                  NIL
                                                                                                  (COMMON-LISP:LIST
                                                                                                                    (COMMON-LISP:FIND-CLASS
                                                                                                                                            (QUOTE
                                                                                                                                                   HYPERDOC:HTML-PAGE))))))
                                     (COMMON-LISP:ASSERT
                                                         (COMMON-LISP:EQ
                                                                         DREYECK/HYPERDOC/BOUNDARY-TESTS::RENDERER
                                                                         (COMMON-LISP:FIND-METHOD
                                                                                                  (FUNCTION
                                                                                                            HYPERBOOK:SERIALIZE-PAGE-DOM)
                                                                                                  NIL
                                                                                                  (COMMON-LISP:LIST
                                                                                                                    (COMMON-LISP:FIND-CLASS
                                                                                                                                            (QUOTE
                                                                                                                                                   HYPERDOC:PAGE))))))
                                     (COMMON-LISP:LET
                                                      ((DREYECK/HYPERDOC/BOUNDARY-TESTS::LOCAL
                                                                                               (COMMON-LISP:MAKE-INSTANCE
                                                                                                                          (COMMON-LISP:FIND-SYMBOL
                                                                                                                                                   "HYPERDOC"
                                                                                                                                                   :DREYECK/HYPERDOC)
                                                                                                                          :ID
                                                                                                                          "local-boundary"
                                                                                                                          :TITLE
                                                                                                                          "Local"
                                                                                                                          :DIRECTORY
                                                                                                                          #P"/tmp/")))
                                                      (COMMON-LISP:ASSERT
                                                                          (COMMON-LISP:EQ
                                                                                          (HYPERDOC:PAGE-CLASS
                                                                                                               DREYECK/HYPERDOC/BOUNDARY-TESTS::LOCAL
                                                                                                               :HTML)
                                                                                          (COMMON-LISP:FIND-CLASS
                                                                                                                  (COMMON-LISP:FIND-SYMBOL
                                                                                                                                           "HTML-PAGE"
                                                                                                                                           :DREYECK/HYPERDOC))))
                                                      (UIOP/STREAM:WITH-TEMPORARY-FILE
                                                                                       (:STREAM
                                                                                                COMMON-LISP:STREAM
                                                                                                :PATHNAME
                                                                                                DREYECK/HYPERDOC/BOUNDARY-TESTS::PATH
                                                                                                :TYPE
                                                                                                "html")
                                                                                       (COMMON-LISP:WRITE-STRING
                                                                                                                 "<h1>Boundary</h1><html-expr>(package-name *package*)</html-expr>"
                                                                                                                 COMMON-LISP:STREAM)
                                                                                       (COMMON-LISP:FINISH-OUTPUT
                                                                                                                  COMMON-LISP:STREAM)
                                                                                       (COMMON-LISP:ASSERT
                                                                                                           (COMMON-LISP:SEARCH
                                                                                                                               "COMMON-LISP<"
                                                                                                                               (DREYECK/HYPERDOC/BOUNDARY-TESTS::PAGE-HTML
                                                                                                                                                                           DREYECK/HYPERDOC/BOUNDARY-TESTS::BASE
                                                                                                                                                                           DREYECK/HYPERDOC/BOUNDARY-TESTS::PATH)))
                                                                                       (COMMON-LISP:ASSERT
                                                                                                           (COMMON-LISP:SEARCH
                                                                                                                               "COMMON-LISP-USER"
                                                                                                                               (DREYECK/HYPERDOC/BOUNDARY-TESTS::PAGE-HTML
                                                                                                                                                                           DREYECK/HYPERDOC/BOUNDARY-TESTS::LOCAL
                                                                                                                                                                           DREYECK/HYPERDOC/BOUNDARY-TESTS::PATH)))
                                                                                       (COMMON-LISP:LET
                                                                                                        ((DREYECK/HYPERDOC/BOUNDARY-TESTS::PAGE
                                                                                                                                                (HYPERDOC::MAKE-TEXT-PAGE
                                                                                                                                                                          DREYECK/HYPERDOC/BOUNDARY-TESTS::LOCAL
                                                                                                                                                                          DREYECK/HYPERDOC/BOUNDARY-TESTS::PATH)))
                                                                                                        (HYPERDOC:LOAD-PAGE
                                                                                                                            DREYECK/HYPERDOC/BOUNDARY-TESTS::PAGE)
                                                                                                        (COMMON-LISP:ASSERT
                                                                                                                            (COMMON-LISP:=
                                                                                                                                           1
                                                                                                                                           (COMMON-LISP:LENGTH
                                                                                                                                                               (PLUMP-DOM:GET-ELEMENTS-BY-TAG-NAME
                                                                                                                                                                                                   (HYPERBOOK:DOM-OF
                                                                                                                                                                                                                     DREYECK/HYPERDOC/BOUNDARY-TESTS::PAGE)
                                                                                                                                                                                                   "in-package")))))
                                                                                       (COMMON-LISP:WITH-OPEN-FILE
                                                                                                                   (DREYECK/HYPERDOC/BOUNDARY-TESTS::OUT
                                                                                                                                                         DREYECK/HYPERDOC/BOUNDARY-TESTS::PATH
                                                                                                                                                         :DIRECTION
                                                                                                                                                         :OUTPUT
                                                                                                                                                         :IF-EXISTS
                                                                                                                                                         :SUPERSEDE)
                                                                                                                   (COMMON-LISP:WRITE-STRING
                                                                                                                                             "<h1>Explicit</h1><in-package>KEYWORD</in-package><html-expr>(cl:package-name cl:*package*)</html-expr>"
                                                                                                                                             DREYECK/HYPERDOC/BOUNDARY-TESTS::OUT))
                                                                                       (COMMON-LISP:ASSERT
                                                                                                           (COMMON-LISP:SEARCH
                                                                                                                               "KEYWORD"
                                                                                                                               (DREYECK/HYPERDOC/BOUNDARY-TESTS::PAGE-HTML
                                                                                                                                                                           DREYECK/HYPERDOC/BOUNDARY-TESTS::LOCAL
                                                                                                                                                                           DREYECK/HYPERDOC/BOUNDARY-TESTS::PATH))))))
                   (ASDF/OPERATE:LOAD-SYSTEM "dreyeck/hyperspec")
                   (COMMON-LISP:ASSERT
                                       (COMMON-LISP:STRING= "/hyperspec/"
                                                            (UIOP/PACKAGE:SYMBOL-CALL
                                                                                      :DREYECK/HYPERSPEC
                                                                                      :HYPERSPEC-HTTP-ROOT)))
                   (COMMON-LISP:ASSERT
                                       (COMMON-LISP:NOT
                                                        (ASDF/OPERATE:COMPONENT-LOADED-P
                                                                                         (ASDF/SYSTEM:FIND-SYSTEM
                                                                                                                  "dreyeck/workflow/authoring"))))
                   (COMMON-LISP:FORMAT COMMON-LISP:T
                                       "Upstream-first page/loading and separate HyperSpec boundary passed.~%")
                   COMMON-LISP:T)
