(IN-PACKAGE #:DREYECK/PAGE-ATTACHED-SYSTEM-PROJECTION/TESTS)

(DEFUN RUN-PAGE-ATTACHED-SYSTEM-PROJECTION-TESTS ()
  (LET* ((SYSTEM-DESIGNATOR "dreyeck/topicmap")
         (SYSTEM (ASDF/SYSTEM:FIND-SYSTEM SYSTEM-DESIGNATOR))
         (ASD (ASDF/SYSTEM:SYSTEM-SOURCE-FILE SYSTEM))
         (PROJECTION
          (DREYECK/PAGE-ATTACHED-SYSTEM-PROJECTION:PAGE-ATTACHED-SYSTEM-PROJECTION
           SYSTEM-DESIGNATOR))
         (TOPICS (DREYECK/TOPICMAP:TOPICMAP-PROJECTION-TOPICS-OF PROJECTION))
         (ASSOCIATIONS
          (DREYECK/TOPICMAP:TOPICMAP-PROJECTION-ASSOCIATIONS-OF PROJECTION))
         (AUTHORITY-ID (FORMAT NIL "asd:~A" (NAMESTRING ASD)))
         (SYSTEM-ID "asdf-system:dreyeck/topicmap")
         (ASSOCIATION-ID
          (FORMAT NIL "association:~A:defines:~A" AUTHORITY-ID SYSTEM-ID))
         (AUTHORITY
          (FIND AUTHORITY-ID TOPICS :KEY
                #'DREYECK/TOPICMAP:TOPICMAP-TOPIC-ID-OF :TEST #'STRING=))
         (SYSTEM-TOPIC
          (FIND SYSTEM-ID TOPICS :KEY #'DREYECK/TOPICMAP:TOPICMAP-TOPIC-ID-OF
                :TEST #'STRING=))
         (ASSOCIATION
          (FIND ASSOCIATION-ID ASSOCIATIONS :KEY
                #'DREYECK/TOPICMAP:TOPICMAP-ASSOCIATION-ID-OF :TEST #'STRING=)))
    (ASSERT
     (EQUAL ASD (DREYECK/TOPICMAP:TOPICMAP-PROJECTION-SOURCE-OF PROJECTION)))
    (ASSERT AUTHORITY)
    (ASSERT SYSTEM-TOPIC)
    (ASSERT ASSOCIATION)
    (ASSERT
     (EQ :PAGE-ATTACHED-AUTHORITY
         (DREYECK/TOPICMAP:TOPICMAP-TOPIC-TYPE-OF AUTHORITY)))
    (ASSERT
     (EQ :ASDF-SYSTEM (DREYECK/TOPICMAP:TOPICMAP-TOPIC-TYPE-OF SYSTEM-TOPIC)))
    (ASSERT (NULL (DREYECK/TOPICMAP:TOPICMAP-TOPIC-OBJECT-OF AUTHORITY)))
    (ASSERT (NULL (DREYECK/TOPICMAP:TOPICMAP-TOPIC-OBJECT-OF SYSTEM-TOPIC)))
    T))
