(in-package #:dreyeck/topicmap/tests)

(defun run-dispatch-reading-tests ()
  (let* ((name 'dreyeck/inspector/topicmap/tala::👀tala-input)
         (gf (dreyeck/inspector/topicmap/tala::reading-view-generic-function))
         (method (find-method gf nil (list (find-class 'dreyeck/topicmap/tala:tala-input))))
         (workspace (dreyeck/inspector/topicmap/tala::reading-view-workspace))
         (projection (dreyeck/topicmap:topicmap-projection-of workspace))
         (topics (dreyeck/topicmap:topicmap-projection-topics-of projection))
         (associations (dreyeck/topicmap:topicmap-projection-associations-of projection)))
    (assert (eq gf (fdefinition name)))
    (assert (typep gf 'generic-function))
    (labels ((topic-for (object)
               (find object topics :key #'dreyeck/topicmap:topicmap-topic-object-of :test #'eq))
             (follow (topic relation)
               (let ((edge (find-if
                            (lambda (edge)
                              (and (eq relation (dreyeck/topicmap:topicmap-association-type-of edge))
                                   (string= (dreyeck/topicmap:topicmap-topic-id-of topic)
                                            (dreyeck/topicmap:topicmap-association-from-of edge))))
                            associations)))
                 (assert edge)
                 (or (find (dreyeck/topicmap:topicmap-association-to-of edge)
                           topics :key #'dreyeck/topicmap:topicmap-topic-id-of :test #'string=)
                     (error "Dangling source relation ~S" relation)))))
      (assert (string= (dreyeck/topicmap:topicmap-workspace-point-of workspace)
                       (dreyeck/topicmap:topicmap-topic-id-of (topic-for gf))))
      (assert (eq :lisp-method (dreyeck/topicmap:topicmap-topic-type-of (topic-for method))))
      (assert (find-if (lambda (edge)
                        (and (eq :has-method (dreyeck/topicmap:topicmap-association-type-of edge))
                             (string= (dreyeck/topicmap:topicmap-topic-id-of (topic-for gf))
                                      (dreyeck/topicmap:topicmap-association-from-of edge))
                             (string= (dreyeck/topicmap:topicmap-topic-id-of (topic-for method))
                                      (dreyeck/topicmap:topicmap-association-to-of edge))))
                      associations))
      (let* ((source (follow (topic-for method) :defined-by))
             (file (follow source :source-file)))
        (assert (eq :lisp-definition-source (dreyeck/topicmap:topicmap-topic-type-of source)))
        (assert (equal '(dreyeck/topicmap/tala:tala-input)
                       (dreyeck/lisp-image::definition-source-description-of
                        (dreyeck/topicmap:topicmap-topic-object-of source))))
        (assert (equal (truename (dreyeck/topicmap:topicmap-topic-object-of file))
                       (truename (asdf:system-relative-pathname
                                  "dreyeck" "dreyeck/src/topicmap-tala-inspector.lisp"))))))
    (let ((observations (dreyeck/inspector/topicmap/tala::reading-view-methods)))
      (assert (= (length observations) (length (sb-mop:generic-function-methods gf))))
      (dolist (entry observations)
        (assert (member (getf entry :method) (sb-mop:generic-function-methods gf)))
        (assert (equal (getf entry :qualifiers) (method-qualifiers (getf entry :method))))
        (assert (equal (getf entry :specializers) (sb-mop:method-specializers (getf entry :method))))))
    (let* ((projected (dreyeck/inspector/topicmap/tala::reading-view-projection))
           (owner (dreyeck/topicmap:topicmap-projection-source-of projected)))
      (assert (typep owner 'dreyeck/topicmap:topicmap-workspace))
      (assert (eq gf (dreyeck/topicmap:topicmap-projection-source-of
                     (dreyeck/topicmap:topicmap-workspace-projection-of owner)))))
    (let ((operations (dreyeck/inspector/topicmap/tala::reading-view-operations)))
      (assert (equal (mapcar (lambda (entry) (getf entry :kind)) operations)
                     '(:ordinary-function :generic-function :ordinary-function :generic-function)))
      (dolist (entry operations)
        (assert (eq (getf entry :function) (fdefinition (getf entry :name))))
        (assert (getf entry :definition-sources))
        (when (eq :generic-function (getf entry :kind))
          (assert (some (lambda (method)
                          (let ((source (getf method :definition-source)))
                            (and source (dreyeck/lisp-image::definition-source-pathname-of source))))
                        (getf entry :methods)))))))
  ;; Load and render the real page, then execute its five source widgets.
  (let ((book (hyperbook:find-hyperbook "dreyeck/topicmap/tala/reading" :signal-error? t)))
    (hyperdoc::ensure-pages-loaded book)
    (let* ((page (hyperbook:find-page book "From DEFVIEW to Generic Dispatch" :signal-error? t))
           (view (find "Content" (html-inspector-views:all-views page)
                       :key #'html-inspector-views:view-title :test #'string=))
           (html (html-inspector-views:view-html view))
           ;; The EXPR link at the top of the page retains the generic
           ;; function itself, so it is a reference but not a widget.
           (widgets (mapcar #'cdr (tala-reading-widget-references view))))
      (let* ((landing (hyperbook:find-page book "Reading TALA as a Layout Layer" :signal-error? t))
             (content (find "Content" (html-inspector-views:all-views landing)
                            :key #'html-inspector-views:view-title :test #'string=)))
        (assert (find page (html-inspector-views:view-references content) :key #'cdr :test #'eq)))
      (assert (search "gigamonkeys.com/book/object-reorientation-generic-functions" html))
      (assert (search "gigamonkeys.com/book/object-reorientation-classes" html))
      (assert (= 5 (length widgets)))
      (dolist (widget widgets)
        (html-inspector-views:view-html widget)
        (let ((actions (remove-if-not
                        (lambda (ref) (typep (cdr ref) 'html-inspector-views:thunk))
                        (html-inspector-views:view-references widget))))
          (assert (= 1 (length actions)))
          (assert (html-inspector-views:eval-thunk (cdar actions)))))))
  (format t "~&DISPATCH-READING-PASS: live function, methods, source chain and five page widgets.~%")
  t)
