(in-package #:dreyeck/work/trails-rendered-reading/tests)

(defun context-view (object title)
  (or (find title (views:all-views object) :key #'views:view-title :test #'equal)
      (error "Missing ~A view" title)))

(defun context-projection-signature (projection)
  ;; TALA's immutability witness includes allocated Topic/Association instances.
  ;; Successive projections allocate those wrappers afresh; retain all their
  ;; semantic fields and represented objects when comparing Before/At/After.
  (destructuring-bind (source properties topics associations)
      (dreyeck/topicmap/tala:projection-state projection)
    (list source properties (mapcar #'cdr topics) (mapcar #'cdr associations))))

(defun temporal-proof-values (context)
  "Seven actual Lisp values, independent of Topicmap rendering and its controls."
  (let* ((events (reading:context-events context))
         (ward-index (position "2026-10-01T17:18:24.009Z" events :key (lambda (e) (gethash "at" e)) :test #'equal))
         (jan-index (position "2026-10-01T18:03:05.302Z" events :key (lambda (e) (gethash "at" e)) :test #'equal))
         (ward (reading::context-event-object context ward-index))
         (jan (reading::context-event-object context jan-index))
         (delta (reading:context-delta context ward)))
    (reading::context-table
     "ordered events" (map 'vector #'identity events)
     "Ward event" ward "before state" (getf delta :before)
     "Ward delta" delta "after state" (getf delta :after)
     "Jan fork event" jan "resulting Jan state" (reading:context-state-at context (gethash "at" (reading::event-record jan))))))

(defun check-raw-temporal-derivation (context)
  (let* ((events (reading:context-events context))
         (jan (reading::context-page context "jan-think"))
         (thompson (reading::context-page context "thompson-think"))
         (jan-journal (gethash "journal" (gethash "raw" jan)))
         (source-journal (gethash "journal" (gethash "raw" thompson)))
         (ward (aref events 8)) (cursor (reading::context-cursor context))
         (proof (temporal-proof-values context))
         (delta (gethash "Ward delta" proof)))
    ;; The copied prefix really is Thompson's whole history, including the correction.
    (assert (dreyeck/work/reading::%json-equal source-journal (subseq jan-journal 0 (1- (length jan-journal)))))
    (assert (find 1790874834907 jan-journal :key (lambda (a) (gethash "date" a))))
    (assert (= 1 (length (reading::context-local-journal jan))))
    (assert (= 1 (count 1790874834907 events :key (lambda (e) (gethash "date" e)))))
    (assert (equal "thompson-think" (gethash "page" (find 1790874834907 events :key (lambda (e) (gethash "date" e))))))
    (assert (< 1790874834907 (gethash "date" ward) (gethash "date" (aref events 9))))
    ;; Each emitted record retains an actual action from its publishing raw journal.
    (loop for event across events
          do (assert (find (gethash "journal" event)
                           (gethash "journal" (gethash "raw" (reading::context-page context (gethash "page" event)))) :test #'eq))
             (dolist (key '("topics-added" "topics-removed" "relations-set" "relations-remove" "relations-removed"))
               (assert (not (nth-value 1 (gethash key event))))))
    (assert (not (gethash "baseline" (gethash "temporal" (reading::context-data context)))))
    (assert (= 4 (length (getf delta :relation-changes))))
    (assert (null (getf delta :added-topics))) (assert (null (getf delta :removed-topics)))
    (assert (null (getf delta :removed-relations)))
    (dolist (change (getf delta :relation-changes))
      (let ((before (getf change :before)) (after (getf change :after)))
        (dolist (key '("id" "from" "to" "item")) (assert (equal (gethash key before) (gethash key after))))
        (assert (equal "" (gethash "kind" before))) (assert (equal "Trail" (gethash "kind" after)))))
    (assert (= cursor (reading::context-cursor context)))
    (assert (equalp (reading:context-state-at context "2026-10-01T17:18:24.009Z")
                    (reading:context-state-at context 1790875104009)))
    (assert (equalp (gethash "before state" proof) (reading:context-state-at context 1790875104008)))
    (assert (equalp (gethash "after state" proof) (reading:context-state-at context 1790875104009)))
    (loop for value being the hash-values of proof do (check-inspector-child proof value))
    ;; Raw content and dates, rather than cached effects or the cursor, determine state.
    (let* ((fresh (reading:federated-context))
           (page (reading::context-page fresh "ward-trails"))
           (action (find 1790875104009 (gethash "journal" (gethash "raw" page)) :key (lambda (a) (gethash "date" a)))))
      (setf (gethash "text" (gethash "item" action))
            (cl-ppcre:regex-replace "\"Trail\"" (gethash "text" (gethash "item" action)) "\"EvidenceProbe\""))
      (let ((probe (reading:context-delta fresh (aref (reading:context-events fresh) 8))))
        (assert (every (lambda (r) (equal "EvidenceProbe" (gethash "kind" r))) (getf probe :changed-relations))))
      (setf (gethash "date" action) 1790875105009)
      (let ((derived (reading::context-derived-events fresh)))
        (assert (not (find 1790875104009 derived :key (lambda (e) (gethash "date" e)))))
        (assert (find 1790875105009 derived :key (lambda (e) (gethash "date" e)))))
      (assert (every (lambda (r) (equal "" (gethash "kind" r)))
                     (remove-if-not (lambda (r) (uiop:string-prefix-p "trail:" (gethash "id" r)))
                                    (getf (reading:context-state-at fresh 1790875104009) :relations)))))
    (format t "~&RAW-TEMPORAL-DERIVATION-PASS: byte-preserved journals, inherited prefix ownership, raw-driven dates and labels, direct State-at/Delta and seven Inspector values.~%")))

(defun context-native-fixture (context function)
  "Exercise production fedwiki HyperBook/page resolution without network access."
  (let* ((catalog hyperbook::*catalog*)
         (hyperbook::*catalog* (make-instance 'hyperbook::catalog)))
    (setf (hyperbook::factories-of hyperbook::*catalog*)
          (alexandria:copy-hash-table (hyperbook::factories-of catalog)))
    (loop for record across (reading::context-pages context)
          for id = (gethash "hyperbook" record)
          for wiki = (or (find id (hyperbook::hyperbooks-of hyperbook::*catalog*)
                              :key #'hyperbook:id-of :test #'equal)
                         (make-instance 'hyperbook/fedwiki::fedwiki :id id))
          do (setf (hyperbook/fedwiki::status-of wiki) t)
             (hyperbook:register wiki)
             (setf (gethash (gethash "slug" record) (hyperbook/fedwiki::pages-of wiki))
                   (hyperbook/fedwiki::make-fedwiki-page wiki (gethash "slug" record) (gethash "title" record))))
    (funcall function)))

(defun check-temporal-federation ()
  (let* ((context (reading:federated-context))
         (events (reading::context-events context))
         (data (reading::context-data context))
         (expected-times '("2026-10-01T17:10:57.791Z" "2026-10-01T17:10:57.792Z"
                           "2026-10-01T17:13:27.513Z" "2026-10-01T17:13:37.885Z"
                           "2026-10-01T17:13:39.907Z" "2026-10-01T17:13:54.907Z"
                           "2026-10-01T17:14:16.195Z" "2026-10-01T17:14:46.108Z"
                           "2026-10-01T17:18:24.009Z" "2026-10-01T18:03:05.302Z"
                           "2026-10-01T18:03:51.968Z"))
         (jan-id "fedwiki:jan.voices.ustawi.wiki/how-we-think")
         (thompson-id "fedwiki:thompson.voices.ustawi.wiki/how-we-think"))
    (check-raw-temporal-derivation context)
    (assert (= 11 (length events)))
    (assert (equal expected-times (map 'list (lambda (event) (gethash "at" event)) events)))
    (assert (apply #'< (map 'list (lambda (event) (gethash "date" event)) events)))
    ;; Every event is attached to its actual publishing page and journal action.
    (loop for event across events
          for journal = (gethash "journal" event)
          do (assert (= (gethash "date" event) (gethash "date" journal)))
             (assert (equal (gethash "operation" event) (gethash "type" journal)))
             (let ((page (reading::context-page context (gethash "page" event))))
               (assert (equal (gethash "site" event) (gethash "site" page)))
               (assert (equal (gethash "page-title" event) (gethash "title" page)))
               (assert (equal (gethash "hyperbook" event) (gethash "hyperbook" page)))))
    (assert (= 1 (count "jan-think" events :key (lambda (event) (gethash "page" event)) :test #'equal)))
    (assert (equal "inherited" (gethash "history" (gethash "after" (aref events 9)))))
    (assert (equal "[[How We May Think]]" (gethash "text" (gethash "before" (aref events 5)))))
    (assert (equal "[[As We May Think]]" (gethash "text" (gethash "after" (aref events 5)))))
    (assert (equal "[[Dorothy Sim" (gethash "text" (gethash "after" (aref events 2)))))
    (assert (equal "[[Dorothy Smith]]" (gethash "text" (gethash "after" (aref events 3)))))
    (assert (equal "[[How We Think]] via Thompson" (gethash "text" (gethash "after" (aref events 10)))))
    (loop for index from 0 below (length events)
          for expected-changes in '(4 1 0 1 2 1 0 1 4 5 1)
          do (reading::select-context-event context index)
             (let* ((state (reading::context-state context index))
                    (delta (reading::context-delta context)))
               (assert (equalp state (reading::context-state context index)))
               (assert (= expected-changes (length (getf delta :changed-relations))))
               (assert (null (getf delta :removed-relations)))
               (assert (equalp state (getf delta :after)))
               (assert (equalp (reading::context-state context (1- index)) (getf delta :before)))
               (assert (if (< index 9) (not (member jan-id (getf state :topics) :test #'equal))
                           (member jan-id (getf state :topics) :test #'equal)))
               (assert (member thompson-id (getf state :topics) :test #'equal))
               (let ((trail-relations (remove-if-not (lambda (relation) (uiop:string-prefix-p "trail:" (gethash "id" relation)))
                                                     (getf state :relations))))
                 (assert (= 4 (length trail-relations)))
                 (assert (every (lambda (relation) (equal (if (< index 8) "" "Trail") (gethash "kind" relation)))
                                trail-relations)))
               (setf (reading::context-mode context) :delta)
               (let ((projection (reading::context-projection context)))
                 (assert (= expected-changes (length (dreyeck/topicmap:topicmap-projection-associations-of projection))))
                 (assert (every (lambda (association)
                                  (member (getf (dreyeck/topicmap:topicmap-association-properties-of association) :evidence)
                                          (getf delta :changed-relations)
                                          :test #'dreyeck/work/reading::%json-equal))
                                (dreyeck/topicmap:topicmap-projection-associations-of projection))))
               (setf (reading::context-mode context) :state)
               (assert (notany (lambda (r) (member (gethash "kind" r) '("causes" "influences") :test #'equal))
                               (getf state :relations)))))
    ;; Fork imports all three related links, preserving separate source/target.
    (let* ((state (reading::context-state context 9))
           (imports (remove-if-not (lambda (r) (and (equal jan-id (gethash "from" r))
                                                    (equal "wiki-link" (gethash "kind" r))))
                                   (getf state :relations))))
      (assert (= 3 (length imports)))
      (assert (find-if (lambda (r) (and (equal "fork" (gethash "kind" r))
                                       (equal thompson-id (gethash "from" r))
                                       (equal jan-id (gethash "to" r)))) (getf state :relations))))
    (assert (dreyeck/work/reading::%json-equal data (reading::read-federated-context)))
    (reading::select-context-event context 9)
    (setf (reading::context-phase context) :before)
    (assert (not (dreyeck/topicmap:topicmap-projection-topic-by-id (reading::context-projection context) jan-id)))
    (setf (reading::context-phase context) :at)
    (assert (dreyeck/topicmap:topicmap-projection-topic-by-id (reading::context-projection context) jan-id))
    (let ((at-state (context-projection-signature (reading::context-projection context))))
      (setf (reading::context-phase context) :after)
      (assert (equalp at-state (context-projection-signature (reading::context-projection context)))))
    (setf (reading::context-phase context) :at)
    (context-native-fixture
     context
     (lambda ()
       (let ((jan (reading::native-context-page (reading::context-page context "jan-think")))
             (thompson (reading::native-context-page (reading::context-page context "thompson-think"))))
         (assert (not (eq jan thompson)))
         (assert (equal (hyperbook:title-of jan) (hyperbook:title-of thompson)))
         (assert (equal "fedwiki:jan.voices.ustawi.wiki" (hyperbook:id-of (hyperbook:hyperbook-of jan))))
         (assert (equal "fedwiki:thompson.voices.ustawi.wiki" (hyperbook:id-of (hyperbook:hyperbook-of thompson)))))
       ;; Evidence views resolve native source pages for every selected event.
       (loop for record across events
             for event = (make-instance 'reading::federated-event :record record :context context)
             for view = (context-view event "Evidence")
             do (views:view-html view)
                (assert (member (reading::native-context-page (reading::context-page context (gethash "page" record)))
                                (mapcar #'cdr (views:view-references view)) :test #'eq))
                (when (gethash "source-page" record)
                  (assert (member (reading::native-context-page (reading::context-page context (gethash "source-page" record)))
                                  (mapcar #'cdr (views:view-references view)) :test #'eq))))
       ;; TALA retains native page signs and event evidence while State/Delta
       ;; action buttons keep one context object and refresh its existing pane.
       (reading::select-context-event context 9)
       (let* ((view (context-view context "Topicmap"))
              (html (views:view-html view))
              (references (views:view-references view))
              (dom (plump:parse html))
              (jan-sign (find jan-id (plump:get-elements-by-tag-name dom "g")
                              :key (lambda (g) (plump:attribute g "data-topic-id")) :test #'equal)))
         (assert jan-sign)
         (assert (search "data-delta=\"changed\"" html))
         (assert (search "Previous event" html))
         (assert (search "Next event" html))
         (assert (search "State" html))
         (assert (search "Delta" html))
         (assert (find-if (lambda (reference) (typep (cdr reference) 'reading::federated-event)) references))
         (let ((sign-thunk (cdr (assoc (plump:attribute jan-sign "id") references :test #'equal))))
           (assert (eq (views:eval-thunk sign-thunk)
                       (reading::native-context-page (reading::context-page context "jan-think")))))
         (let* ((button (find "Previous event" (plump:get-elements-by-tag-name dom "button") :key #'plump:text :test #'equal))
                (action (cdr (assoc (plump:attribute button "id") references :test #'equal))))
           (assert (uiop:string-prefix-p "action-" (plump:attribute button "id")))
           (assert (views:eval-thunk action))
           (assert (= 8 (reading::context-cursor context))))
         (let* ((button (find "Delta" (plump:get-elements-by-tag-name dom "button") :key #'plump:text :test #'equal))
                (action (cdr (assoc (plump:attribute button "id") references :test #'equal))))
           (assert (views:eval-thunk action))
           (assert (eq :delta (reading::context-mode context)))
           (assert (= 4 (length (dreyeck/topicmap:topicmap-projection-associations-of
                                (reading::context-projection context))))))
         (reading::select-context-event context 5)
         (let* ((correction (views:view-html (context-view context "Topicmap")))
                (correction-dom (plump:parse correction))
                (removed (find "concept:How We May Think" (plump:get-elements-by-tag-name correction-dom "g")
                               :key (lambda (g) (plump:attribute g "data-topic-id")) :test #'equal)))
           (assert removed)
           (assert (equal "removed" (plump:attribute removed "data-delta"))))))))
  (format t "~&TEMPORAL-FEDERATION-PASS: 11 exact events, deterministic State/Delta, inherited fork history, separate site/page identities, native TALA page signs, event evidence and in-place cursor actions.~%"))
