
(IN-PACKAGE :DREYECK/WORKFLOW/TESTS)

(COMMON-LISP:DEFUN DREYECK/WORKFLOW/TESTS:RUN-AUTHORING-TESTS COMMON-LISP:NIL
                   (COMMON-LISP:LET*
                                     ((DREYECK/WORKFLOW/TESTS::ROOT
                                                                    (COMMON-LISP:MERGE-PATHNAMES
                                                                                                 (COMMON-LISP:FORMAT
                                                                                                                     COMMON-LISP:NIL
                                                                                                                     "workflow-proof-~A/"
                                                                                                                     (COMMON-LISP:GENSYM))
                                                                                                 (UIOP/STREAM:TEMPORARY-DIRECTORY)))
                                      (DREYECK/WORKFLOW/TESTS::ASD
                                                                   (COMMON-LISP:MERGE-PATHNAMES
                                                                                                "workflow-proof.asd"
                                                                                                DREYECK/WORKFLOW/TESTS::ROOT))
                                      (DREYECK/WORKFLOW/TESTS::SOURCE
                                                                      (COMMON-LISP:MERGE-PATHNAMES
                                                                                                   "answer.lisp"
                                                                                                   DREYECK/WORKFLOW/TESTS::ROOT))
                                      (DREYECK/WORKFLOW/TESTS::ENVIRONMENT
                                                                           (DREYECK/WORKFLOW/AUTHORING:MAKE-AUTHORING-ENVIRONMENT))
                                      (DREYECK/WORKFLOW/TESTS::SYSTEM
                                                                      "workflow-proof"))
                                     (COMMON-LISP:ENSURE-DIRECTORIES-EXIST
                                                                           DREYECK/WORKFLOW/TESTS::SOURCE)
                                     (COMMON-LISP:UNWIND-PROTECT
                                                                 (COMMON-LISP:PROGN
                                                                                    (HTML-INSPECTOR-VIEWS/STANDARD::MATERIALIZE-LISP-SOURCE
                                                                                                                                            DREYECK/WORKFLOW/TESTS::ASD
                                                                                                                                            (COMMON-LISP:QUOTE
                                                                                                                                                               ((ASDF/PARSE-DEFSYSTEM:DEFSYSTEM
                                                                                                                                                                                                "workflow-proof"
                                                                                                                                                                                                :COMPONENTS
                                                                                                                                                                                                ((:FILE
                                                                                                                                                                                                        "answer"))
                                                                                                                                                                                                :DEPENDS-ON
                                                                                                                                                                                                ("dreyeck/workflow")))))
                                                                                    (HTML-INSPECTOR-VIEWS/STANDARD::MATERIALIZE-LISP-SOURCE
                                                                                                                                            DREYECK/WORKFLOW/TESTS::SOURCE
                                                                                                                                            (COMMON-LISP:QUOTE
                                                                                                                                                               ((COMMON-LISP:IN-PACKAGE
                                                                                                                                                                                        :CL-USER)
                                                                                                                                                                (COMMON-LISP:DEFUN
                                                                                                                                                                                   COMMON-LISP-USER::WORKFLOW-PROOF-ANSWER
                                                                                                                                                                                   COMMON-LISP:NIL
                                                                                                                                                                                   42)
                                                                                                                                                                (COMMON-LISP:DEFUN
                                                                                                                                                                                   COMMON-LISP-USER::WORKFLOW-PROOF-NEIGHBOR
                                                                                                                                                                                   COMMON-LISP:NIL
                                                                                                                                                                                   :UNCHANGED))))
                                                                                    (ASDF/FIND-SYSTEM:LOAD-ASD
                                                                                                               DREYECK/WORKFLOW/TESTS::ASD)
                                                                                    (ASDF/OPERATE:LOAD-SYSTEM
                                                                                                              DREYECK/WORKFLOW/TESTS::SYSTEM)
                                                                                    (COMMON-LISP:FLET
                                                                                                      ((DREYECK/WORKFLOW/TESTS::PLAN
                                                                                                                                     (DREYECK/WORKFLOW/TESTS::VALUE
                                                                                                                                                                    DREYECK/WORKFLOW/TESTS::EXPECTED)
                                                                                                                                     (DREYECK/WORKFLOW:PLAN-DEFINITION
                                                                                                                                                                       DREYECK/WORKFLOW/TESTS::SYSTEM
                                                                                                                                                                       "answer"
                                                                                                                                                                       (COMMON-LISP:QUOTE
                                                                                                                                                                                          COMMON-LISP-USER::WORKFLOW-PROOF-ANSWER)
                                                                                                                                                                       (COMMON-LISP:LIST
                                                                                                                                                                                         (COMMON-LISP:QUOTE
                                                                                                                                                                                                            COMMON-LISP:DEFUN)
                                                                                                                                                                                         (COMMON-LISP:QUOTE
                                                                                                                                                                                                            COMMON-LISP-USER::WORKFLOW-PROOF-ANSWER)
                                                                                                                                                                                         COMMON-LISP:NIL
                                                                                                                                                                                         DREYECK/WORKFLOW/TESTS::VALUE)
                                                                                                                                                                       (COMMON-LISP:LIST
                                                                                                                                                                                         (COMMON-LISP:QUOTE
                                                                                                                                                                                                            COMMON-LISP:AND)
                                                                                                                                                                                         (COMMON-LISP:QUOTE
                                                                                                                                                                                                            (COMMON-LISP:NOT
                                                                                                                                                                                                                             (UIOP/OS:GETENV
                                                                                                                                                                                                                                             "HYPERDOC_WORKFLOW_EDITOR_SOURCE")))
                                                                                                                                                                                         (COMMON-LISP:QUOTE
                                                                                                                                                                                                            (COMMON-LISP:NOT
                                                                                                                                                                                                                             (COMMON-LISP:FBOUNDP
                                                                                                                                                                                                                                                  (COMMON-LISP:FIND-SYMBOL
                                                                                                                                                                                                                                                                           "REPLACE-CST-EXPRESSION-IN-FILE"
                                                                                                                                                                                                                                                                           :HTML-INSPECTOR-VIEWS/STANDARD))))
                                                                                                                                                                                         (COMMON-LISP:LIST
                                                                                                                                                                                                           (COMMON-LISP:QUOTE
                                                                                                                                                                                                                              COMMON-LISP:=)
                                                                                                                                                                                                           (COMMON-LISP:LIST
                                                                                                                                                                                                                             (COMMON-LISP:QUOTE
                                                                                                                                                                                                                                                COMMON-LISP-USER::WORKFLOW-PROOF-ANSWER))
                                                                                                                                                                                                           DREYECK/WORKFLOW/TESTS::EXPECTED)))))
                                                                                                      (COMMON-LISP:LET*
                                                                                                                        ((DREYECK/WORKFLOW/TESTS::CHANGE
                                                                                                                                                         (DREYECK/WORKFLOW/TESTS::PLAN
                                                                                                                                                                                       43
                                                                                                                                                                                       43))
                                                                                                                         (DREYECK/WORKFLOW/TESTS::NEIGHBOR
                                                                                                                                                           (COMMON-LISP:THIRD
                                                                                                                                                                              (DREYECK/WORKFLOW:SOURCE-FORMS
                                                                                                                                                                                                             DREYECK/WORKFLOW/TESTS::SOURCE)))
                                                                                                                         (DREYECK/WORKFLOW/TESTS::RESULT
                                                                                                                                                         (DREYECK/WORKFLOW:PERSIST-IN
                                                                                                                                                                                      DREYECK/WORKFLOW/TESTS::CHANGE
                                                                                                                                                                                      DREYECK/WORKFLOW/TESTS::ENVIRONMENT)))
                                                                                                                        (COMMON-LISP:ASSERT
                                                                                                                                            (COMMON-LISP:EQ
                                                                                                                                                            :VERIFIED
                                                                                                                                                            (COMMON-LISP:GETF
                                                                                                                                                                              DREYECK/WORKFLOW/TESTS::RESULT
                                                                                                                                                                              :STATUS)))
                                                                                                                        (COMMON-LISP:ASSERT
                                                                                                                                            (COMMON-LISP:SEARCH
                                                                                                                                                                "WORKFLOW-FRESH-EXPECTATION-PASSED"
                                                                                                                                                                (COMMON-LISP:GETF
                                                                                                                                                                                  DREYECK/WORKFLOW/TESTS::RESULT
                                                                                                                                                                                  :FRESH-PROOF)))
                                                                                                                        (COMMON-LISP:ASSERT
                                                                                                                                            (DREYECK/WORKFLOW:FORM-EQUAL
                                                                                                                                                                         DREYECK/WORKFLOW/TESTS::NEIGHBOR
                                                                                                                                                                         (COMMON-LISP:THIRD
                                                                                                                                                                                            (DREYECK/WORKFLOW:SOURCE-FORMS
                                                                                                                                                                                                                           DREYECK/WORKFLOW/TESTS::SOURCE))))
                                                                                                                        (DREYECK/WORKFLOW/TESTS::MUST-FAIL
                                                                                                                                                           (COMMON-LISP:LAMBDA
                                                                                                                                                                               COMMON-LISP:NIL
                                                                                                                                                                               (DREYECK/WORKFLOW:PERSIST-IN
                                                                                                                                                                                                            DREYECK/WORKFLOW/TESTS::CHANGE
                                                                                                                                                                                                            DREYECK/WORKFLOW/TESTS::ENVIRONMENT))))
                                                                                                      (DREYECK/WORKFLOW/TESTS::MUST-FAIL
                                                                                                                                         (COMMON-LISP:LAMBDA
                                                                                                                                                             COMMON-LISP:NIL
                                                                                                                                                             (DREYECK/WORKFLOW:PERSIST-IN
                                                                                                                                                                                          (DREYECK/WORKFLOW/TESTS::PLAN
                                                                                                                                                                                                                        44
                                                                                                                                                                                                                        999)
                                                                                                                                                                                          DREYECK/WORKFLOW/TESTS::ENVIRONMENT)))
                                                                                                      (COMMON-LISP:LET
                                                                                                                       ((DREYECK/WORKFLOW/TESTS::DEPENDENCY
                                                                                                                                                            (DREYECK/WORKFLOW:PLAN-DEPENDENCY
                                                                                                                                                                                              DREYECK/WORKFLOW/TESTS::SYSTEM
                                                                                                                                                                                              "workflow-deliberately-missing-dependency"
                                                                                                                                                                                              COMMON-LISP:T)))
                                                                                                                       (DREYECK/WORKFLOW/TESTS::MUST-FAIL
                                                                                                                                                          (COMMON-LISP:LAMBDA
                                                                                                                                                                              COMMON-LISP:NIL
                                                                                                                                                                              (DREYECK/WORKFLOW:PERSIST-IN
                                                                                                                                                                                                           DREYECK/WORKFLOW/TESTS::DEPENDENCY
                                                                                                                                                                                                           DREYECK/WORKFLOW/TESTS::ENVIRONMENT)))))
                                                                                    (COMMON-LISP:FORMAT
                                                                                                        COMMON-LISP:T
                                                                                                        "Workflow authoring tests passed: actual writer, fresh ordinary reconstruction, stale source, wrong behavior, missing dependency.~%")
                                                                                    COMMON-LISP:T)
                                                                 (ASDF/SYSTEM-REGISTRY:CLEAR-SYSTEM
                                                                                                    DREYECK/WORKFLOW/TESTS::SYSTEM)
                                                                 (UIOP/FILESYSTEM:DELETE-DIRECTORY-TREE
                                                                                                        DREYECK/WORKFLOW/TESTS::ROOT
                                                                                                        :VALIDATE
                                                                                                        COMMON-LISP:T
                                                                                                        :IF-DOES-NOT-EXIST
                                                                                                        :IGNORE))))
