;;;; Real reader/writer regressions; every source write is to the registered fixture.
(defpackage #:dreyeck/work/addresses/tests
  (:use #:cl)
  (:local-nicknames (#:work #:dreyeck/work/reading) (#:a #:dreyeck/work/authoring)
                    (#:tm #:dreyeck/topicmap) (#:tst #:dreyeck/work/authoring/tests)
                    (#:ed #:dreyeck/work/editor/tests) (#:ops #:dreyeck/work/operation-requests)
                    (#:w #:dreyeck/gesture-binding-witness) (#:views #:html-inspector-views))
  (:export #:run-tests #:run-live-addresses-witness))
(in-package #:dreyeck/work/addresses/tests)

(defun request (page &optional (source "fedwiki-item-authoring"))
  (let* ((projection (work:work-projection :page page))
         (from (tm:topicmap-projection-topic-by-id projection source))
         (foreign (hyperbook:find-page (hyperbook:hyperbook-of page) "Deriving HyperDoc Authoring Constraints" :signal-error? t))
         (target (tm:topicmap-projection-topic-by-id (work:work-projection :page foreign) "serialized-verified-effect")))
    (work:request-work-relationship-creation
     (ops:work-topic-operation-request (w:create-relationship-operation) from) target "work:relation/addresses")))
(defun create (page &optional (source "fedwiki-item-authoring"))
  (let* ((request (request page source))
         (outcome (a:execute-work-relationship-creation request (dreyeck/workflow/authoring:make-authoring-environment))))
    (assert (eq :applied (a:work-relationship-creation-outcome-status outcome)) () "~S" (a:work-relationship-creation-outcome-cause outcome))
    (values (car (last (work:qualified-bridges (work:work-projection :page page)))) request outcome)))
(defun assert-stale (bridge)
  (handler-case (progn (work:resolve-addresses-bridge bridge) (error "Expected stale bridge"))
    (work:stale-addresses-bridge (c) (assert (plusp (length (work:addresses-stale-reason c)))))))
(defun assert-current (bridge)
  (assert (typep (work:resolve-addresses-bridge bridge) 'tm:topicmap-association)))

(defun check-addresses (page path)
  (let* ((foreign (hyperbook:find-page (hyperbook:hyperbook-of page) "Deriving HyperDoc Authoring Constraints" :signal-error? t))
         (foreign-path (work::%page-path foreign))
         (original (tst::%read path)) (foreign-original (tst::%read foreign-path))
         (environment (dreyeck/workflow/authoring:make-authoring-environment)))
    (labels ((reset () (tst::%write path original) (tst::%write foreign-path foreign-original))
             (edit (file old new) (tst::%write file (tst::replace-once (tst::%read file) old new))))
      (unwind-protect
           (progn
             ;; Complete request keeps exact snapshot-bound occurrences and full read set.
             (let* ((r (request page)) (before (tst::%read path)) (p (a:plan-work-relationship-creation r)))
               (assert (typep r 'work:addresses-creation-request))
               (assert (= 2 (length (work:addresses-read-set r))))
               (assert (equal before (work:work-relationship-creation-authority-snapshot r)))
               (assert (search "work-addresses-warrant:v1:" (a:work-relationship-creation-plan-representation p)))
               (assert (equal before (tst::%read path)))
               (let ((view (tst::%view r "Addresses read set")))
                 (dolist (entry (work:addresses-read-set r))
                   (assert (member (cdr entry) (mapcar #'cdr (views:view-references view)) :test #'eq)))))
             (multiple-value-bind (bridge r outcome) (create page)
               (declare (ignore outcome))
               (let ((local (work:work-projection :page page)) (evidence (work:evidence-neighborhood :page page)))
                 (assert (= 23 (length (tm:topicmap-projection-topics-of local))))
                 (assert (= 22 (length (tm:topicmap-projection-associations-of local))))
                 (assert (null (tm:topicmap-projection-topic-by-id local "serialized-verified-effect")))
                 (assert (= 3 (length (tm:topicmap-projection-topics-of evidence))))
                 (assert (= 2 (length (tm:topicmap-projection-associations-of evidence))))
                 (let* ((milestone (tm:topicmap-projection-topic-by-id evidence "milestone/m0-page-edit"))
                        (commit (tm:topicmap-topic-object-of milestone)))
                   (assert (typep commit 'dreyeck/git:git-commit))
                   (assert (equal "bb8bf21f4a1a0cd998b12feafbe19ec5819fe037" (dreyeck/git:git-commit-hash-of commit))))
                 (assert (tst::%view bridge "Qualified addresses bridge"))
                 ;; Ordinary Work ingestion does not ask a foreign authority for source.
                 (let ((old (symbol-function 'work::%resolve-authority)))
                   (unwind-protect
                        (progn (setf (symbol-function 'work::%resolve-authority) (lambda (&rest _) (declare (ignore _)) (error "Unexpected foreign read")))
                               (assert (= 22 (length (tm:topicmap-projection-associations-of (work:work-projection :page page))))))
                     (setf (symbol-function 'work::%resolve-authority) old))))
               (assert-current bridge)
               (handler-case (progn (work:resolve-work-topic-occurrence (work:work-relationship-creation-from-occurrence r))
                                    (error "Old request occurrence falsely current"))
                 (work:stale-work-topic-occurrence () t))
               ;; Restart-equivalent reconstruction from current source only.
               (assert-current (first (work:qualified-bridges (work:work-projection :page page))))
               ;; Equal-width status edit via EXISTING status executor; unchanged guards stay current.
               (let* ((topic (tm:topicmap-projection-topic-by-id (work:work-projection :page page) "hyperdoc-page-authoring"))
                      (sr (work:request-work-status-change (ops:work-topic-operation-request (w:change-work-status-operation) topic) topic "done"))
                      (so (a:execute-work-status-change sr environment)))
                 (assert (eq :applied (a:work-status-change-outcome-status so))))
               (assert-current bridge)
               ;; Independent bridge B from a distinct Work item, same owner/foreign authorities.
               (let ((b (create page "hyperdoc-page-authoring")))
                 (assert-current bridge) (assert-current b)
                 (assert (= 2 (length (work:qualified-bridges (work:work-projection :page page)))))
                 (assert (= 3 (length (tm:topicmap-projection-associations-of (work:evidence-neighborhood :page page)))))
                 (format t "~&ADDRESSES-TWO-BRIDGES-PASS: A and independently appended B both current.~%")))
             ;; Each guarded semantic extent makes currentness fail independently.
             (dolist (mutation '(:source :facet :contract :statement :move :duplicate :remap))
               (reset)
               (let ((bridge (create page)))
                 (case mutation
                   (:source (edit path ">FedWiki Item Authoring</a>" ">FedWiki Item authoring</a>"))
                   (:facet (edit foreign-path "edits of one page are serialized under a page lock" "edits of one page are serialized without page lock"))
                   (:contract (edit path "investigation, implementation or change" "investigation, counteraction or change"))
                   (:statement (edit path "Serialized verified effect: addresses.</li>" "Serialized verified effect: addresses!</li>"))
                   (:move (tst::%write path (concatenate 'string "<p>Unrelated inserted prose.</p>" (tst::%read path))))
                   (:duplicate (let* ((range (work::%range (work::%field (work:bridge-warrant bridge) "source") "anchor"))
                                      (text (subseq original (car range) (cdr range))))
                                 (tst::%write path (concatenate 'string (tst::%read path) "<p>" text "</p>"))))
                   (:remap
                    (let* ((old (hyperdoc:file-of foreign)) (copy (merge-pathnames "remapped.html" foreign-path)))
                      (tst::%write copy (tst::%read foreign-path))
                      (unwind-protect (progn (setf (slot-value foreign 'hyperdoc::file) copy) (assert-stale bridge))
                        (setf (slot-value foreign 'hyperdoc::file) old) (delete-file copy)))))
                 (unless (eq mutation :remap) (assert-stale bridge))
                 (unless (member mutation '(:duplicate :remap))
                   (assert (= 22 (length (tm:topicmap-projection-associations-of (work:work-projection :page page)))))
                   (assert (null (tm:topicmap-projection-associations-of (work:evidence-neighborhood :page page)))))))
             ;; Unknown/broken qualification cannot be accepted as a local row.
             (dolist (bad '(:version :missing :orphan :base64 :duplicate-marker))
               (reset)
               (create page)
               (case bad
                 (:version (edit path "data-work-qualification=\"addresses-v1\"" "data-work-qualification=\"addresses-v9\""))
                 (:missing (let* ((text (tst::%read path)) (start (search work::+addresses-annotation+ text)) (end (+ 3 (search "-->" text :start2 start))))
                             (tst::%write path (concatenate 'string (subseq text 0 start) (subseq text end)))))
                 (:orphan (edit path " data-work-qualification=\"addresses-v1\"" ""))
                 (:duplicate-marker (edit path "data-work-qualification=\"addresses-v1\""
                                           "data-work-qualification=\"addresses-v1\" data-work-qualification=\"addresses-v1\""))
                 (:base64 (edit path work::+addresses-annotation+ (concatenate 'string work::+addresses-annotation+ "!"))))
               (handler-case (progn (work:work-projection :page page) (error "Malformed accepted"))
                 (work:addresses-qualification-error () t)))
             ;; Strict execution freshness rejects edits tolerated by persisted currentness.
             (dolist (which '(:owner :foreign))
               (reset)
               (let* ((r (request page)) (p (a:plan-work-relationship-creation r)))
                 (if (eq which :owner)
                     (edit path "data-topic=\"hyperdoc-page-authoring\" data-kind=\"work item\" data-status=\"open\""
                                "data-topic=\"hyperdoc-page-authoring\" data-kind=\"work item\" data-status=\"done\"")
                     (tst::%write foreign-path (concatenate 'string foreign-original "<p>Unrelated note.</p>")))
                 (let ((before (tst::%read path)))
                   (assert (eq :refused (a:work-relationship-creation-outcome-status (a:execute-work-relationship-creation r environment))))
                   (handler-case (progn (a:apply-work-relationship-creation p) (error "Stale plan applied"))
                     (a:work-relationship-creation-apply-refused () t))
                   (assert (equal before (tst::%read path))))))
             ;; Endpoint admission reads exact authored roles, not generic Topic type.
             (dolist (role '("source" "target"))
               (reset)
               (if (equal role "source")
                   (edit path "data-topic=\"fedwiki-item-authoring\" data-kind=\"work item\""
                              "data-topic=\"fedwiki-item-authoring\" data-kind=\"concept\"")
                   (edit foreign-path "data-topic=\"serialized-verified-effect\" data-kind=\"constraint\""
                                      "data-topic=\"serialized-verified-effect\" data-kind=\"concept\""))
               (handler-case (progn (request page) (error "Invalid endpoint role admitted"))
                 (work:work-relationship-creation-refused () t)))
             ;; The new contract cannot be used as an unchecked local relation
             ;; to a concept merely because its declaration now exists.
             (reset)
             (let* ((projection (work:work-projection :page page))
                    (from (tm:topicmap-projection-topic-by-id projection "fedwiki-item-authoring"))
                    (to (tm:topicmap-projection-topic-by-id projection "hyperdoc-authoring")))
               (handler-case
                   (progn (work:request-work-relationship-creation
                            (ops:work-topic-operation-request (w:create-relationship-operation) from)
                            to "work:relation/addresses") (error "Wrong local addresses role admitted"))
                 (work:work-relationship-creation-refused () t)))
             (tst::%write path (concatenate 'string original
               "<ul><li data-from=\"fedwiki-item-authoring\" data-to=\"hyperdoc-authoring\" data-relation=\"work:relation/addresses\">bad roles</li></ul>"))
             (handler-case (progn (work:work-projection :page page) (error "Bad local roles projected"))
               (work:addresses-qualification-error () t))
             ;; Capability absent: no plan/effect.
             (reset)
             (assert (eq :refused (a:work-relationship-creation-outcome-status (a:execute-work-relationship-creation (request page) nil))))
             (assert (equal original (tst::%read path)))
             ;; Inject drift at the FINAL preinstall hook and AFTER install.
             (dolist (timing '(:before :after))
               (reset)
               (let* ((r (request page)) (old (symbol-function 'a::%replace-source)))
                 (unwind-protect
                      (progn
                        (setf (symbol-function 'a::%replace-source)
                              (lambda (file expected candidate refuse &key before-install)
                                (if (eq timing :before)
                                    (funcall old file expected candidate refuse :before-install
                                      (lambda () (tst::%write foreign-path (concatenate 'string foreign-original "<p>Concurrent edit.</p>"))
                                                 (funcall before-install)))
                                    (progn (funcall old file expected candidate refuse :before-install before-install)
                                           (tst::%write foreign-path (concatenate 'string foreign-original "<p>Post-install edit.</p>"))))))
                        (let ((outcome (a:execute-work-relationship-creation r environment)))
                          (assert (eq (if (eq timing :before) :refused :unverified) (a:work-relationship-creation-outcome-status outcome)))
                          (assert (if (eq timing :before) (equal original (tst::%read path))
                                      (search "work-addresses-warrant:v1:" (tst::%read path))))))
                   (setf (symbol-function 'a::%replace-source) old))))
             ;; Existing local relationship appends AFTER the qualified record,
             ;; preserves its warrant, and still uses the original wire path.
             (reset)
             (let ((bridge-a (create page)))
             (let* ((p (work:work-projection :page page))
                    (from (tm:topicmap-projection-topic-by-id p "lisp-source-authoring"))
                    (to (tm:topicmap-projection-topic-by-id p "running-image-authoring"))
                    (r (work:request-work-relationship-creation (ops:work-topic-operation-request (w:create-relationship-operation) from) to "work:relation/informs"))
                    (plan (a:plan-work-relationship-creation r)))
               (assert (not (typep r 'work:addresses-creation-request)))
               (assert (equal (format nil "~%<li data-from=\"lisp-source-authoring\" data-to=\"running-image-authoring\" data-relation=\"work:relation/informs\">Structural Lisp Source Authoring → Running Lisp Image Authoring: informs.</li>")
                              (a:work-relationship-creation-plan-representation plan)))
               (assert (eq :applied (a:work-relationship-creation-outcome-status
                                     (a:execute-work-relationship-creation r environment))))
               (assert-current bridge-a)
               (assert (= 23 (length (tm:topicmap-projection-associations-of (work:work-projection :page page))))))))
        (reset)))))

(defun check-ui (page path)
  (let* ((ws (tm:make-topicmap-workspace (work:work-projection :page page) "fedwiki-item-authoring"))
         (context (a::select-work-operation (w:create-relationship-operation) (tm:topicmap-workspace-current-topic ws) ws))
         (target (ed::click context "Create relationship" "Inspect foreign Constraint: Serialized verified effect"))
         (choice (ed::click target "Inspected foreign target" "Use inspected target"))
         (r (views:eval-thunk (cdr (assoc "Use relation: addresses" (tst::%buttons choice) :test #'equal)))))
    (assert (typep r 'work:addresses-creation-request))
    (assert (eq (work:work-relationship-creation-to-occurrence r) (work:topic-source-occurrence (a::inspected-target-topic target))))
    (assert (eq target (a::editor-target-context (a::%editor-context r))))
    (assert (eq ws (a::editor-workspace (a::%editor-context r))))
    (assert (not (eq ws (a::inspected-target-workspace target))))
    (assert (equal "Work Breakdown" (hyperbook:title-of (work:work-relationship-creation-authority-page r))))
    (assert (equal (tst::%read path) (work:work-relationship-creation-authority-snapshot r)))
    (tst::%view r "Addresses read set")
    (let* ((plan (ed::click r "Work request" "Preview plan"))
           (fresh (ed::click plan "Work plan" "Execute request after revalidation")))
      (assert (typep fresh 'tm:topicmap-workspace) () "UI execution returned ~S" fresh)
      (assert (equal "fedwiki-item-authoring" (tm:topicmap-workspace-point-of fresh)))
      (assert (eq :applied (a:work-relationship-creation-outcome-status (ed::outcome fresh)))))))

(defun run-tests ()
  (let ((before (tst::work-page-sources)))
    (tst::call-with-work-breakdown-fixture #'check-addresses)
    (tst::call-with-work-breakdown-fixture #'check-ui)
    (assert (equal before (tst::work-page-sources))))
  (format t "~&ADDRESSES-REGRESSION-PASS: exact source/target/scope/contract/statement guards, fixed ranges, isolated authority, strict full read-set execution, post-install unverified, local Work and Evidence separation, explicit foreign UI context.~%") t)
