(in-package #:dreyeck/work/trails-rendered-reading/tests)

(defun context-view (object title)
  (or (find title (views:all-views object) :key #'views:view-title :test #'equal)
      (error "Missing ~A view" title)))

(defun temporal-proof-values (context)
  "Seven actual Lisp values, independent of Topicmap rendering and its controls."
  (let* ((events (reading:context-events context))
         (ward-index (position "2026-10-01T17:18:24.009Z" events :key (lambda (e) (gethash "at" e)) :test #'equal))
         (jan-index (position "2026-10-01T18:03:05.302Z" events :key (lambda (e) (gethash "at" e)) :test #'equal))
         (ward (reading::context-event-object context ward-index))
         (jan (reading::context-event-object context jan-index))
         (delta (reading:context-delta context ward)))
    (reading::context-table
     "ordered events" (map 'vector #'identity events)
     "Ward event" ward "before state" (getf delta :before)
     "Ward delta" delta "after state" (getf delta :after)
     "Jan fork event" jan "resulting Jan state" (reading:context-state-at context (gethash "at" (reading::event-record jan))))))

(defun check-raw-temporal-derivation (context)
  (let* ((events (reading:context-events context))
         (jan (reading::context-page context "jan-think"))
         (thompson (reading::context-page context "thompson-think"))
         (jan-journal (gethash "journal" (gethash "raw" jan)))
         (source-journal (gethash "journal" (gethash "raw" thompson)))
         (ward (aref events 8)) (cursor (reading::context-cursor context))
         (proof (temporal-proof-values context))
         (delta (gethash "Ward delta" proof)))
    ;; The copied prefix really is Thompson's whole history, including the correction.
    (assert (dreyeck/work/reading::%json-equal source-journal (subseq jan-journal 0 (1- (length jan-journal)))))
    (assert (find 1790874834907 jan-journal :key (lambda (a) (gethash "date" a))))
    (assert (= 1 (length (reading::context-local-journal jan))))
    (assert (= 1 (count 1790874834907 events :key (lambda (e) (gethash "date" e)))))
    (assert (equal "thompson-think" (gethash "page" (find 1790874834907 events :key (lambda (e) (gethash "date" e))))))
    (assert (< 1790874834907 (gethash "date" ward) (gethash "date" (aref events 9))))
    ;; Each emitted record retains an actual action from its publishing raw journal.
    (loop for event across events
          do (assert (find (gethash "journal" event)
                           (gethash "journal" (gethash "raw" (reading::context-page context (gethash "page" event)))) :test #'eq))
             (dolist (key '("topics-added" "topics-removed" "relations-set" "relations-remove" "relations-removed"))
               (assert (not (nth-value 1 (gethash key event))))))
    (assert (not (gethash "baseline" (gethash "temporal" (reading::context-data context)))))
    (assert (= 4 (length (getf delta :relation-changes))))
    (assert (null (getf delta :added-topics))) (assert (null (getf delta :removed-topics)))
    (assert (null (getf delta :removed-relations)))
    (dolist (change (getf delta :relation-changes))
      (let ((before (getf change :before)) (after (getf change :after)))
        (dolist (key '("id" "from" "to" "item")) (assert (equal (gethash key before) (gethash key after))))
        (assert (equal "" (gethash "kind" before))) (assert (equal "Trail" (gethash "kind" after)))))
    (assert (= cursor (reading::context-cursor context)))
    (assert (equalp (reading:context-state-at context "2026-10-01T17:18:24.009Z")
                    (reading:context-state-at context 1790875104009)))
    (assert (equalp (gethash "before state" proof) (reading:context-state-at context 1790875104008)))
    (assert (equalp (gethash "after state" proof) (reading:context-state-at context 1790875104009)))
    (loop for value being the hash-values of proof do (check-inspector-child proof value))
    ;; Raw content and dates, rather than cached effects or the cursor, determine state.
    (let* ((fresh (reading:federated-context))
           (page (reading::context-page fresh "ward-trails"))
           (action (find 1790875104009 (gethash "journal" (gethash "raw" page)) :key (lambda (a) (gethash "date" a)))))
      (setf (gethash "text" (gethash "item" action))
            (cl-ppcre:regex-replace "\"Trail\"" (gethash "text" (gethash "item" action)) "\"EvidenceProbe\""))
      (let ((probe (reading:context-delta fresh (aref (reading:context-events fresh) 8))))
        (assert (every (lambda (r) (equal "EvidenceProbe" (gethash "kind" r))) (getf probe :changed-relations))))
      (setf (gethash "date" action) 1790875105009)
      (let ((derived (reading::context-derived-events fresh)))
        (assert (not (find 1790875104009 derived :key (lambda (e) (gethash "date" e)))))
        (assert (find 1790875105009 derived :key (lambda (e) (gethash "date" e)))))
      (assert (every (lambda (r) (equal "" (gethash "kind" r)))
                     (remove-if-not (lambda (r) (uiop:string-prefix-p "trail:" (gethash "id" r)))
                                    (getf (reading:context-state-at fresh 1790875104009) :relations)))))
    (format t "~&RAW-TEMPORAL-DERIVATION-PASS: byte-preserved journals, inherited prefix ownership, raw-driven dates and labels, direct State-at/Delta and seven Inspector values.~%")))

(defun context-native-fixture (context function)
  "Exercise production fedwiki HyperBook/page resolution without network access."
  (let* ((catalog hyperbook::*catalog*)
         (hyperbook::*catalog* (make-instance 'hyperbook::catalog)))
    (setf (hyperbook::factories-of hyperbook::*catalog*)
          (alexandria:copy-hash-table (hyperbook::factories-of catalog)))
    (loop for record across (reading::context-pages context)
          for id = (gethash "hyperbook" record)
          for wiki = (or (find id (hyperbook::hyperbooks-of hyperbook::*catalog*)
                              :key #'hyperbook:id-of :test #'equal)
                         (make-instance 'hyperbook/fedwiki::fedwiki :id id))
          do (setf (hyperbook/fedwiki::status-of wiki) t)
             (hyperbook:register wiki)
             (setf (gethash (gethash "slug" record) (hyperbook/fedwiki::pages-of wiki))
                   (hyperbook/fedwiki::make-fedwiki-page wiki (gethash "slug" record) (gethash "title" record))))
    (funcall function)))

(defun check-temporal-federation ()
  (let* ((context (reading:federated-context))
         (events (reading::context-events context))
         (data (reading::context-data context))
         (expected-times '("2026-10-01T17:10:57.791Z" "2026-10-01T17:10:57.792Z"
                           "2026-10-01T17:13:27.513Z" "2026-10-01T17:13:37.885Z"
                           "2026-10-01T17:13:39.907Z" "2026-10-01T17:13:54.907Z"
                           "2026-10-01T17:14:16.195Z" "2026-10-01T17:14:46.108Z"
                           "2026-10-01T17:18:24.009Z" "2026-10-01T18:03:05.302Z"
                           "2026-10-01T18:03:51.968Z"))
         (jan-id "fedwiki:jan.voices.ustawi.wiki/how-we-think")
         (thompson-id "fedwiki:thompson.voices.ustawi.wiki/how-we-think"))
    (check-raw-temporal-derivation context)
    (assert (= 11 (length events)))
    (assert (equal expected-times (map 'list (lambda (event) (gethash "at" event)) events)))
    (assert (apply #'< (map 'list (lambda (event) (gethash "date" event)) events)))
    ;; Every event is attached to its actual publishing page and journal action.
    (loop for event across events
          for journal = (gethash "journal" event)
          do (assert (= (gethash "date" event) (gethash "date" journal)))
             (assert (equal (gethash "operation" event) (gethash "type" journal)))
             (let ((page (reading::context-page context (gethash "page" event))))
               (assert (equal (gethash "site" event) (gethash "site" page)))
               (assert (equal (gethash "page-title" event) (gethash "title" page)))
               (assert (equal (gethash "hyperbook" event) (gethash "hyperbook" page)))))
    (assert (= 1 (count "jan-think" events :key (lambda (event) (gethash "page" event)) :test #'equal)))
    (assert (equal "inherited" (gethash "history" (gethash "after" (aref events 9)))))
    (assert (equal "[[How We May Think]]" (gethash "text" (gethash "before" (aref events 5)))))
    (assert (equal "[[As We May Think]]" (gethash "text" (gethash "after" (aref events 5)))))
    (assert (equal "[[Dorothy Sim" (gethash "text" (gethash "after" (aref events 2)))))
    (assert (equal "[[Dorothy Smith]]" (gethash "text" (gethash "after" (aref events 3)))))
    (assert (equal "[[How We Think]] via Thompson" (gethash "text" (gethash "after" (aref events 10)))))
    (loop for index from 0 below (length events)
          for expected-changes in '(4 1 0 1 2 1 0 1 4 5 1)
          do (reading::select-context-event context index)
             (let* ((state (reading::context-state context index))
                    (delta (reading::context-delta context)))
               (assert (equalp state (reading::context-state context index)))
               (assert (= expected-changes (length (getf delta :changed-relations))))
               (assert (null (getf delta :removed-relations)))
               (assert (equalp state (getf delta :after)))
               (assert (equalp (reading::context-state context (1- index)) (getf delta :before)))
               (assert (if (< index 9) (not (member jan-id (getf state :topics) :test #'equal))
                           (member jan-id (getf state :topics) :test #'equal)))
               (assert (member thompson-id (getf state :topics) :test #'equal))
               (let ((trail-relations (remove-if-not (lambda (relation) (uiop:string-prefix-p "trail:" (gethash "id" relation)))
                                                     (getf state :relations))))
                 (assert (= 4 (length trail-relations)))
                 (assert (every (lambda (relation) (equal (if (< index 8) "" "Trail") (gethash "kind" relation)))
                                trail-relations)))
               (setf (reading::context-mode context) :delta)
               (let ((projection (reading::context-projection context)))
                 (assert (= expected-changes (length (dreyeck/topicmap:topicmap-projection-associations-of projection))))
                 (assert (every (lambda (association)
                                  (member (getf (dreyeck/topicmap:topicmap-association-properties-of association) :evidence)
                                          (getf delta :changed-relations)
                                          :test #'dreyeck/work/reading::%json-equal))
                                (dreyeck/topicmap:topicmap-projection-associations-of projection))))
               (setf (reading::context-mode context) :state)
               (assert (notany (lambda (r) (member (gethash "kind" r) '("causes" "influences") :test #'equal))
                               (getf state :relations)))))
    ;; Fork imports all three related links, preserving separate source/target.
    (let* ((state (reading::context-state context 9))
           (imports (remove-if-not (lambda (r) (and (equal jan-id (gethash "from" r))
                                                    (equal "wiki-link" (gethash "kind" r))))
                                   (getf state :relations))))
      (assert (= 3 (length imports)))
      (assert (find-if (lambda (r) (and (equal "fork" (gethash "kind" r))
                                       (equal thompson-id (gethash "from" r))
                                       (equal jan-id (gethash "to" r)))) (getf state :relations))))
    (assert (dreyeck/work/reading::%json-equal data (reading::read-federated-context)))
    (reading::select-context-event context 9)
    (context-native-fixture
     context
     (lambda ()
       (let ((jan (reading::native-context-page (reading::context-page context "jan-think")))
             (thompson (reading::native-context-page (reading::context-page context "thompson-think"))))
         (assert (not (eq jan thompson)))
         (assert (equal (hyperbook:title-of jan) (hyperbook:title-of thompson)))
         (assert (equal "fedwiki:jan.voices.ustawi.wiki" (hyperbook:id-of (hyperbook:hyperbook-of jan))))
         (assert (equal "fedwiki:thompson.voices.ustawi.wiki" (hyperbook:id-of (hyperbook:hyperbook-of thompson)))))
       ;; Evidence views resolve native source pages for every selected event.
       (loop for record across events
             for event = (make-instance 'reading::federated-event :record record :context context)
             for view = (context-view event "Evidence")
             do (views:view-html view)
                (assert (member (reading::native-context-page (reading::context-page context (gethash "page" record)))
                                (mapcar #'cdr (views:view-references view)) :test #'eq))
                (when (gethash "source-page" record)
                  (assert (member (reading::native-context-page (reading::context-page context (gethash "source-page" record)))
                                  (mapcar #'cdr (views:view-references view)) :test #'eq))))
       ;; TALA retains native page signs and event evidence while State/Delta
       ;; action buttons keep one context object and refresh its existing pane.
       (reading::select-context-event context 9)
       (let* ((view (context-view context "Topicmap"))
              (html (views:view-html view))
              (references (views:view-references view))
              (dom (plump:parse html))
              (jan-sign (find jan-id (plump:get-elements-by-tag-name dom "g")
                              :key (lambda (g) (plump:attribute g "data-topic-id")) :test #'equal)))
         (assert jan-sign)
         (assert (search "data-delta=\"changed\"" html))
         (assert (search "Previous event" html))
         (assert (search "Next event" html))
         (assert (search "State" html))
         (assert (search "Delta" html))
         (assert (find-if (lambda (reference) (typep (cdr reference) 'reading::federated-event)) references))
         (let ((sign-thunk (cdr (assoc (plump:attribute jan-sign "id") references :test #'equal))))
           (assert (views:eval-thunk sign-thunk))
           (assert (equal jan-id (dreyeck/topicmap:topicmap-workspace-point-of
                                 (reading::context-current-workspace context))))
           (assert (= 9 (reading::context-cursor context))))
         (let* ((button (find "Previous event" (plump:get-elements-by-tag-name dom "button") :key #'plump:text :test #'equal))
                (action (cdr (assoc (plump:attribute button "id") references :test #'equal))))
           (assert (uiop:string-prefix-p "action-" (plump:attribute button "id")))
           (assert (views:eval-thunk action))
           (assert (= 8 (reading::context-cursor context))))
         (let* ((button (find "Delta" (plump:get-elements-by-tag-name dom "button") :key #'plump:text :test #'equal))
                (action (cdr (assoc (plump:attribute button "id") references :test #'equal))))
           (assert (views:eval-thunk action))
           (assert (eq :delta (reading::context-mode context)))
           (assert (= 4 (length (dreyeck/topicmap:topicmap-projection-associations-of
                                (reading::context-projection context))))))
         (reading::select-context-event context 5)
         (let* ((correction (views:view-html (context-view context "Topicmap")))
                (correction-dom (plump:parse correction))
                (removed (find "concept:How We May Think" (plump:get-elements-by-tag-name correction-dom "g")
                               :key (lambda (g) (plump:attribute g "data-topic-id")) :test #'equal)))
           (assert removed)
           (assert (equal "removed" (plump:attribute removed "data-delta"))))))))
  (format t "~&TEMPORAL-FEDERATION-PASS: 11 exact events, deterministic State/Delta, inherited fork history, separate site/page identities, native TALA page signs, event evidence and in-place cursor actions.~%"))

(defun check-coordinated-context-workspace ()
  (let* ((context (reading:federated-context))
         (events (reading:context-events context))
         (jan-id "fedwiki:jan.voices.ustawi.wiki/how-we-think")
         (thompson-id "fedwiki:thompson.voices.ustawi.wiki/how-we-think")
         (temporal (reading::context-temporal-projection context))
         (topics (dreyeck/topicmap:topicmap-projection-topics-of temporal)))
    (assert (eq context (dreyeck/topicmap:topicmap-projection-source-of temporal)))
    (assert (equal (map 'list (lambda (e) (gethash "id" e)) events)
                   (mapcar #'dreyeck/topicmap:topicmap-topic-id-of topics)))
    (loop for association in (dreyeck/topicmap:topicmap-projection-associations-of temporal)
          for index from 1
          do (assert (equal (gethash "id" (aref events (1- index)))
                            (dreyeck/topicmap:topicmap-association-from-of association)))
             (assert (equal (gethash "id" (aref events index))
                            (dreyeck/topicmap:topicmap-association-to-of association))))
    ;; The presentation hook must coexist with the generic Association gesture
    ;; binding, rather than replace the existing HTML-view after method.
    (assert (find-method #'clog-moldable-inspector::create-view-element '(:after)
                         (list (find-class 't) (find-class 't) (find-class 'views:html-view))))
    (assert (find-method #'clog-moldable-inspector::create-view-element '(:after)
                         (list (find-class 'clog-moldable-inspector::pane) (find-class 't)
                               (find-class 'views:html-view))))
    (loop for topic in topics for record across events for index from 0
          do (assert (eq (reading::context-event-object context index)
                         (dreyeck/topicmap:topicmap-topic-object-of topic)))
             (assert (search (subseq (gethash "at" record) 11)
                             (dreyeck/topicmap:topicmap-topic-label-of topic)))
             (assert (search (reading::context-page-label (reading::context-page context (gethash "page" record)))
                             (dreyeck/topicmap:topicmap-topic-label-of topic)))
             (assert (search (gethash "operation" record) (dreyeck/topicmap:topicmap-topic-label-of topic))))
    ;; Repeated/clamped movement uses the same event objects, not a second clock.
    (reading::select-context-event context -1)
    (assert (= 0 (reading::context-cursor context)))
    (loop for index from 0 below (length events)
          do (assert (= index (reading::context-cursor context)))
             (let ((delta (reading::context-current-delta context)))
               (assert (eq delta (reading::context-current-delta context)))
               (assert (equalp delta (reading:context-delta context)))
               (assert (eq (getf delta :after) (reading::context-current-state context)))
               (assert (equalp (reading::context-current-state context)
                              (reading:context-state-at context (gethash "date" (aref events index)))))
               (dolist (mode '(:state :delta))
                 (setf (reading::context-mode context) mode)
                 (let ((projection (reading::context-projection context)))
                   (assert (eq context (dreyeck/topicmap:topicmap-projection-source-of projection)))
                   (assert (every (lambda (association)
                                    (member (getf (dreyeck/topicmap:topicmap-association-properties-of association) :evidence)
                                            (if (eq mode :state) (getf (reading::context-current-state context) :relations)
                                                (append (getf delta :changed-relations) (getf delta :removed-relations))) :test #'eq))
                                  (dreyeck/topicmap:topicmap-projection-associations-of projection))))))
             (reading::select-context-event context (1+ index)))
    (assert (= 10 (reading::context-cursor context)))
    (loop for index downfrom 10 to 0
          do (assert (= index (reading::context-cursor context)))
             (reading::select-context-event context (1- index)))
    (assert (= 0 (reading::context-cursor context)))
    (context-native-fixture
     context
     (lambda ()
       (labels ((render ()
                  (let* ((view (context-view context "Topicmap")) (html (views:view-html view)))
                    (values view (plump:parse html) html)))
                (action (view element)
                  (assert (uiop:string-prefix-p "action-" (plump:attribute element "id")))
                  (assert (views:eval-thunk (cdr (assoc (plump:attribute element "id")
                                                       (views:view-references view) :test #'equal)))))
                (button (dom label)
                  (or (find label (plump:get-elements-by-tag-name dom "button") :key #'plump:text :test #'equal)
                      (error "Missing button ~A" label)))
                (map-dom (dom kind)
                  (find kind (plump:get-elements-by-tag-name dom "div")
                        :key (lambda (e) (plump:attribute e "data-projection")) :test #'equal))
                (sign (dom id)
                  (find id (plump:get-elements-by-tag-name dom "g")
                        :key (lambda (e) (plump:attribute e "data-topic-id")) :test #'equal))
                (has-reference (view object)
                  (assert (member object (mapcar #'cdr (views:view-references view)) :test #'eq))))
         ;; Select Thompson directly in the temporal map, then walk the raw order.
         (multiple-value-bind (view dom) (render)
           (assert (map-dom dom "temporal")) (assert (map-dom dom "context"))
           ;; SVG paint order is the renderer's concern; the Lisp projection
           ;; and its ordered adjacency edges carry chronological order.
           (assert (equal (sort (map 'list (lambda (e) (gethash "id" e)) events) #'string<)
                          (sort (mapcar (lambda (e) (plump:attribute e "data-topic-id"))
                                        (remove-if-not (lambda (e) (plump:attribute e "data-topic-id"))
                                                       (plump:get-elements-by-tag-name (map-dom dom "temporal") "g"))) #'string<)))
           (action view (sign (map-dom dom "temporal") (gethash "id" (aref events 5)))))
         (assert (= 5 (reading::context-cursor context)))
         (dolist (index '(6 7 8))
           (multiple-value-bind (view dom) (render) (action view (button dom "Next event")))
           (assert (= index (reading::context-cursor context))))
         (let ((temporal-rendering (reading::context-rendering context :temporal)))
           (multiple-value-bind (view dom) (render) (action view (button dom "Delta")))
           (assert (= 8 (reading::context-cursor context)))
           (assert (eq temporal-rendering (reading::context-rendering context :temporal)))
           (multiple-value-bind (view dom) (render)
             (let* ((projection (reading::context-rendered-projection context :context))
                    (delta (reading::context-current-delta context))
                    (associations (dreyeck/topicmap:topicmap-projection-associations-of projection)))
               (assert (= 4 (length associations)))
               (assert (= 4 (length (getf delta :relation-changes))))
               (assert (null (getf delta :added-topics))) (assert (null (getf delta :removed-topics)))
               (let ((rows (remove-if-not (lambda (row) (plump:attribute row "data-relation-change"))
                                          (plump:get-elements-by-tag-name dom "tr"))))
                 (assert (= 4 (length rows)))
                 (assert (every (lambda (row) (search "\"\" → \"Trail\"" (plump:text row))) rows)))
               (has-reference view (reading::context-event-object context 8))
               (has-reference view (reading::context-current-state context))
               (has-reference view delta)
               (dolist (change (getf delta :relation-changes)) (has-reference view change))
               (dolist (association associations)
                 (has-reference view association)
                 (let* ((properties (dreyeck/topicmap:topicmap-association-properties-of association))
                        (change (getf properties :change))
                        (evidence (context-view association "Evidence")))
                   (views:view-html evidence)
                   (has-reference evidence (getf properties :evidence))
                   (has-reference evidence change)
                   (has-reference evidence (getf change :before))
                   (has-reference evidence (getf change :after))))
               (assert (= 1 (count "true" (plump:get-elements-by-tag-name (map-dom dom "temporal") "g")
                                   :key (lambda (e) (plump:attribute e "data-selected")) :test #'equal))))))
         (multiple-value-bind (view dom) (render) (action view (button dom "Next event")))
         (assert (= 9 (reading::context-cursor context)))
         (multiple-value-bind (view dom) (render) (action view (button dom "State")))
         ;; Same title, distinct Topics and native pages. Point selection stays local.
         (dolist (id (list jan-id thompson-id))
           (multiple-value-bind (view dom) (render)
             (action view (sign (map-dom dom "context") id)))
           (assert (= 9 (reading::context-cursor context)))
           (let* ((workspace (reading::context-current-workspace context))
                  (topic (dreyeck/topicmap:topicmap-workspace-current-topic workspace))
                  (page (dreyeck/topicmap:topicmap-topic-object-of topic)))
             (assert (equal id (dreyeck/topicmap:topicmap-topic-id-of topic)))
             (multiple-value-bind (view dom) (render)
               (declare (ignore dom))
               (has-reference view topic) (has-reference view page)
               (has-reference view (reading::native-context-page page)))))
         (multiple-value-bind (view dom) (render) (action view (button dom "Next event")))
         (assert (= 10 (reading::context-cursor context)))
         (multiple-value-bind (view dom) (render) (action view (button dom "Delta")))
         (let* ((projection (reading::context-rendered-projection context :context))
                (association (first (dreyeck/topicmap:topicmap-projection-associations-of projection)))
                (properties (dreyeck/topicmap:topicmap-association-properties-of association))
                (attribution (getf properties :attribution))
                (view (context-view association "Evidence")))
           (assert (= 1 (length (dreyeck/topicmap:topicmap-projection-associations-of projection))))
           (assert (equal "wiki-link" (dreyeck/topicmap:topicmap-association-type-of association)))
           (assert (equal "via Thompson" (gethash "attribution" attribution)))
           (assert (equal "thompson-think" (gethash "credited-page" attribution)))
           (views:view-html view)
           (has-reference view attribution)
           (has-reference view (gethash "after" (aref events 10)))
           (has-reference view (reading::native-context-page (reading::context-page context "thompson-think"))))))))
  (format t "~&COORDINATED-WORKSPACE-PASS: one cursor, two TALA maps, ordered event selection, deterministic Previous/Next, actual State/Delta/topic/relation Inspector references and separate native page navigation.~%"))

(defun check-context-represented-objects ()
  (let* ((context (reading:federated-context))
         (raw (dreyeck/work/reading::%copy-json (reading::context-data context)))
         (hyperbook/fedwiki::*neighborhood* (make-hash-table :test 'equal)))
    (context-native-fixture context (lambda ()
     (let ((catalog-pages (copy-list (hyperbook::hyperbooks-of hyperbook::*catalog*))))
      (labels ((topic (id)
               (dreyeck/topicmap::topicmap-projection-topic-by-id (reading::context-projection context) id))
             (object (id) (dreyeck/topicmap:topicmap-topic-object-of (topic id)))
             (references (object title)
               (let ((view (context-view object title)))
                 (views:view-html view)
                 (mapcar #'cdr (views:view-references view)))))
      ;; Native, historical, site-qualified page identity: not metadata or a sign.
      (let* ((evidence (reading::context-page context "jan-dewey"))
             (id (reading::context-page-id evidence))
             (page (object id)) (event (reading::context-event-object context 10)))
        (assert (typep page 'hyperbook/fedwiki::fedwiki-page))
        (assert (typep page 'reading::context-fedwiki-page))
        (assert (eq page (reading::context-page-object context evidence)))
        (assert (eq page (object id)))
        (assert (eq evidence (reading::page-evidence page)))
        (assert (eq event (reading::page-event page)))
        (assert (equal "fedwiki:jan.voices.ustawi.wiki" (hyperbook:id-of (hyperbook:hyperbook-of page))))
        (assert (equal "john-dewey" (hyperbook:id-of page)))
        (assert (some (lambda (item) (search "[[How We Think]] via Thompson" (hyperbook/fedwiki::text-of item)))
                      (hyperbook/fedwiki::story-of page)))
        (assert (not (search "Reload" (views:view-html (views:title-bar-action-buttons page)))))
        (let* ((view (context-view page "Story")) (html (views:view-html view))
               (refs (mapcar #'cdr (views:view-references view))))
          (assert (search "via Thompson" html))
          (assert (member (reading::context-page-object context (reading::context-page context "jan-think"))
                          refs :test #'eq))
          (assert (some (lambda (ref) (typep ref 'reading::federated-subject)) refs))
          (assert (eq (reading::context-subject-object context "Reflective Practice")
                      (reading::historical-wiki-link-target page "Reflective Practice"))))
        (let* ((link (find "How We Think" (hyperbook/fedwiki::wiki-links-of (hyperbook:links-of page))
                           :key #'hyperbook/fedwiki::target-title-of :test #'equal))
               (target (views:eval-thunk (hyperbook::thunk-of link))))
          (assert (eq target (reading::context-page-object context (reading::context-page context "jan-think")))))
        (let ((refs (references page "Source / Time")))
          (dolist (value (list event (reading::page-json page) (gethash "raw" evidence)))
            (assert (member value refs :test #'eq))))
        ;; Moving the cursor never mutates an already represented page snapshot.
        (reading::select-context-event context 9)
        (let ((earlier (object id)))
          (assert (not (eq page earlier)))
          (assert (notany (lambda (item) (search "via Thompson" (hyperbook/fedwiki::text-of item)))
                          (hyperbook/fedwiki::story-of earlier)))
          (assert (eq event (reading::page-event page))))
        (reading::select-context-event context 10))
      (let ((jan (object "fedwiki:jan.voices.ustawi.wiki/how-we-think"))
            (thompson (object "fedwiki:thompson.voices.ustawi.wiki/how-we-think")))
        (assert (not (eq jan thompson)))
        (assert (equal (hyperbook:title-of jan) (hyperbook:title-of thompson)))
        (assert (not (eq (hyperbook:hyperbook-of jan) (hyperbook:hyperbook-of thompson))))
        (assert (equal "thompson.voices.ustawi.wiki"
                       (hyperbook/fedwiki::site-of (aref (hyperbook/fedwiki::journal-of jan)
                                                        (1- (length (hyperbook/fedwiki::journal-of jan))))))))
      ;; A real unresolved subject preserves the reading, source event and links.
      (let ((subject (object "concept:Reflective Practice")))
        (assert (typep subject 'reading::federated-subject))
        (assert (eq subject (reading::context-subject-object context "Reflective Practice")))
        (assert (eq context (reading::subject-context subject)))
        (assert (eq (reading::context-event-object context 10) (reading::subject-event subject)))
        (assert (equal "Reflective Practice" (reading::subject-title subject)))
        (assert (reading::subject-links subject))
        (assert (every (lambda (link) (and (typep link 'hyperbook/fedwiki::wiki-link)
                                          (equal "Reflective Practice" (hyperbook/fedwiki::target-title-of link))))
                       (reading::subject-links subject)))
        ;; None of the saved pages is arbitrarily relabeled Reflective Practice.
        (assert (null (reading::subject-context-pages subject)))
        (assert (null (reading::subject-neighborhood-pages subject)))
        (let ((refs (references subject "Subject")))
          (dolist (value (append (list context (reading::subject-event subject)) (reading::subject-links subject)))
            (assert (member value refs :test #'eq))))
        ;; Cached neighborhood references stay distinct from historical evidence.
        (let* ((jan (make-instance 'hyperbook/fedwiki::fedwiki :id "fedwiki:jan.voices.ustawi.wiki"))
               (thompson (make-instance 'hyperbook/fedwiki::fedwiki :id "fedwiki:thompson.voices.ustawi.wiki"))
               (jp (hyperbook/fedwiki::make-fedwiki-page jan "reflective-practice" "Reflective Practice"))
               (tp (hyperbook/fedwiki::make-fedwiki-page thompson "reflective-practice" "Reflective Practice")))
          (setf (gethash "reflective-practice" (hyperbook/fedwiki::pages-of jan)) jp
                (gethash "reflective-practice" (hyperbook/fedwiki::pages-of thompson)) tp
                (gethash "jan.voices.ustawi.wiki" hyperbook/fedwiki::*neighborhood*) jan
                (gethash "thompson.voices.ustawi.wiki" hyperbook/fedwiki::*neighborhood*) thompson)
          (assert (equal (list jp tp) (reading::subject-neighborhood-pages subject)))
          (assert (null (reading::subject-context-pages subject)))
          (clrhash hyperbook/fedwiki::*neighborhood*)))
      (assert (equal '("fedwiki:jan.voices.ustawi.wiki" "fedwiki:thompson.fed.wiki" "fedwiki:thompson.voices.ustawi.wiki")
                     (sort (mapcar (lambda (page) (hyperbook:id-of (hyperbook:hyperbook-of page)))
                                   (reading::subject-context-pages (object "concept:How We Think"))) #'string<)))
      ;; Event signs and relation contract signs retain exact model references.
      (reading::select-context-event context 8)
      (let* ((event (reading::context-event-object context 8))
             (sign (dreyeck/topicmap::topicmap-projection-topic-by-id (reading::context-temporal-projection context)
                                                        (gethash "id" (reading::event-record event)))))
        (assert (eq event (dreyeck/topicmap:topicmap-topic-object-of sign))))
      (dolist (mode '(:state :delta))
        (setf (reading::context-mode context) mode)
        (let* ((delta (reading::context-current-delta context))
               (projection (reading::context-projection context)))
          (dolist (association (dreyeck/topicmap:topicmap-projection-associations-of projection))
            (let* ((properties (dreyeck/topicmap:topicmap-association-properties-of association))
                   (sign (getf properties :relation-contract))
                   (expected (if (eq mode :delta) (getf properties :change) (getf properties :evidence)))
                   (represented (dreyeck/topicmap:topicmap-topic-object-of sign)))
              (assert (typep sign 'dreyeck/topicmap:topicmap-topic))
              (assert (eq :relation (dreyeck/topicmap:topicmap-topic-type-of sign)))
              (assert (eq expected represented))
              (when (eq mode :delta) (assert (member represented (getf delta :relation-changes) :test #'eq)))
              (assert (member represented (references association "Evidence") :test #'eq))))))
      ;; Constructing projections never registers global sites or materializes pages.
      (assert (zerop (hash-table-count hyperbook/fedwiki::*neighborhood*)))
      (assert (equal catalog-pages (hyperbook::hyperbooks-of hyperbook::*catalog*)))
      (assert (dreyeck/work/reading::%json-equal raw (reading::context-data context))))))))
  (format t "~&REPRESENTED-OBJECTS-PASS: EQ page/subject/event/state/change objects, historical native pages, distinct same-title sites, unresolved native links, separate context/neighborhood and unchanged raw evidence/catalog.~%"))
