;;;; Fixture-only checks of the Inspector connections over existing Work objects.
(defpackage #:dreyeck/work/editor/tests
  (:use #:cl)
  (:local-nicknames (#:a #:dreyeck/work/authoring)
                    (#:tst #:dreyeck/work/authoring/tests)
                    (#:work #:dreyeck/work/reading)
                    (#:tm #:dreyeck/topicmap)
                    (#:m #:dreyeck/inspector/topicmap)
                    (#:ops #:dreyeck/work/operation-requests)
                    (#:r #:dreyeck/gesture/operation-request)
                    (#:w #:dreyeck/gesture-binding-witness)
                    (#:views #:html-inspector-views))
  (:export #:run-tests #:run-live-editor-witness))
(in-package #:dreyeck/work/editor/tests)

(defun button (object title label)
  (let ((view (tst::%view object title)))
    (assert view () "No ~S view for ~S." title object)
    (or (cdr (assoc label (tst::%buttons view) :test #'equal))
        (error "No ~S button in ~S." label title))))
(defun click (object title label) (views:eval-thunk (button object title label)))
(defun refs (object title)
  (labels ((contents (view)
             (loop for (_ . value) in (views:view-references view)
                   append (if (typep value 'views:view)
                              (cons value (contents value)) (list value)))))
    (contents (tst::%view object title))))
(defun outcome (workspace) (gethash workspace a::*work-editor-outcomes*))
(defun workspace (page)
  (tm:make-topicmap-workspace (work:work-projection :page page) "hyperdoc-page-authoring"))

(defun registered-selection (context) (a::editor-selection context))
(defun topic-context (ws)
  (or (find-if (lambda (object) (typep object 'a::work-editor-context))
               (mapcar #'cdr (views:view-references (tst::%view ws "Topicmap"))))
      (error "No concrete Work editor context.")))

(defun check-connections (page path)
  (let* ((source (tst::%read path))
         (ws (workspace page))
         (topic (tm:topicmap-workspace-current-topic ws))
         (occurrence (work:topic-source-occurrence topic))
         (native (tst::%view ws "Topicmap"))
         (objects (mapcar #'cdr (views:view-references native)))
         (sign (find topic objects :key (lambda (object)
                                         (when (typep object 'm::topic-action-reference)
                                           (m::action-topic object))) :test #'eq)))
    (assert sign)
    (assert (eq occurrence (work:topic-source-occurrence (m::action-topic sign))))
    (assert (member topic objects :test #'eq))
    (assert (member (tm:topicmap-topic-object-of topic) objects :test #'eq))
    (assert (search "Open Work Topic" (views:view-html native)))
    (assert (eq topic (tm:topicmap-projection-topic-by-id (tm:topicmap-projection-of ws)
                                                       (tm:topicmap-topic-id-of topic))))
    (assert (equal '("Change work status" "Create relationship")
                   (sort (mapcar #'car (tst::%buttons (tst::%view (topic-context ws) "Work Operations"))) #'string<)))
    ;; PRIMARY continues to navigate, using the existing sign thunk.
    (let* ((target (tm:topicmap-projection-topic-by-id (tm:topicmap-workspace-projection-of ws)
                                                     "lisp-source-authoring"))
           (reference (find target objects :key (lambda (object)
                                                  (when (typep object 'm::topic-action-reference)
                                                    (m::action-topic object))) :test #'eq)))
      (assert reference)
      (views:eval-thunk reference)
      (assert (equal "lisp-source-authoring" (tm:topicmap-workspace-point-of ws)))
      (tm:topicmap-workspace-go-to ws "hyperdoc-page-authoring"))
    (dolist (title '("Change work status" "Create relationship"))
      (let* ((operation (if (equal title "Change work status") (w:change-work-status-operation)
                           (w:create-relationship-operation)))
             (selection (click (topic-context ws) "Work Operations" title)))
        (assert (typep selection 'a::work-editor-context))
        (assert (eq (registered-selection selection) (ops:work-topic-operation-request operation topic)))
        (assert (eq occurrence (r:operation-request-occurrence (registered-selection selection))))))
    (assert (string= source (tst::%read path)))))

(defun check-status-loop (page path)
  (let* ((source (tst::%read path))
         (ws (workspace page))
         (old (tm:topicmap-workspace-current-topic ws))
         (ignored (tst::%view ws "Topicmap"))
         (selection (click (topic-context ws) "Work Operations" "Change work status"))
         (request (click selection "Change work status" "Change work status to \"in progress\""))
         (preview (click request "Work request" "Preview plan")))
    (declare (ignore ignored))
    (assert (typep request 'work:work-status-change-request))
    (assert (eq (registered-selection selection) (work:work-status-change-selection request)))
    (assert (member (registered-selection selection) (refs request "Work request") :test #'eq))
    (assert (member page (refs request "Work request") :test #'eq))
    (assert (typep preview 'a:work-status-change-plan))
    (assert (eq request (a:work-status-change-plan-request preview)))
    (assert (string= source (tst::%read path)))
    ;; Observe the actual UI callback's executor and reread; both must be used.
    ;; The executor must construct another plan, not apply the inspected one.
    (let ((executor (symbol-function 'a:execute-work-status-change))
          (reader (symbol-function 'work:work-projection))
          (executions 0) (reads 0) fresh)
      (unwind-protect
           (progn
             (setf (symbol-function 'a:execute-work-status-change)
                   (lambda (given environment)
                     (assert (eq request given))
                     (assert (typep environment 'dreyeck/workflow/authoring::authoring-environment))
                     (incf executions) (funcall executor given environment))
                   (symbol-function 'work:work-projection)
                   (lambda (&rest args) (incf reads) (apply reader args)))
             (setf fresh (click preview "Work plan" "Execute request after revalidation")))
        (setf (symbol-function 'a:execute-work-status-change) executor
              (symbol-function 'work:work-projection) reader))
      (assert (= 1 executions reads))
      (assert (typep fresh 'tm:topicmap-workspace))
      (assert (not (eq fresh ws)))
      (assert (not (eq (tm:topicmap-workspace-projection-of fresh) (tm:topicmap-workspace-projection-of ws))))
      (assert (equal (tm:topicmap-workspace-point-of ws) (tm:topicmap-workspace-point-of fresh)))
      (assert (eq :applied (a:work-status-change-outcome-status (outcome fresh))))
      (assert (not (eq preview (a:work-status-change-outcome-plan (outcome fresh)))))
      (let ((new (tm:topicmap-workspace-current-topic fresh)))
        (assert (not (eq new old)))
        (assert (not (eq (work:topic-source-occurrence new) (work:topic-source-occurrence old))))
        (assert (string= (tst::%read path) (work:topic-occurrence-snapshot (work:topic-source-occurrence new))))
        (assert (equal "in progress" (getf (tm:topicmap-topic-view-properties-of new) :status))))
      (assert (search "Applied" (views:view-html (tst::%view fresh "Work Breakdown"))))
      ;; Old selection and old complete request remain old authority.
      (let ((written (tst::%read path)))
        (assert (typep (a::complete-editor-status selection "in progress") 'work:work-status-change-refused))
        (assert (typep (click old "Work Operations" "Change work status") 'error))
        (let ((refused (a::execute-work-request request)))
          (assert (eq :refused (a:work-status-change-outcome-status refused)))
          (assert (search "refused" (views:view-html (tst::%view refused "Work status change outcome")))))
        (assert (string= written (tst::%read path)))))))

(defun relationship-request (ws)
  (let* ((projection (tm:topicmap-workspace-projection-of ws))
         (from (tm:topicmap-projection-topic-by-id projection "lisp-source-authoring"))
         (target (tm:topicmap-projection-topic-by-id projection "running-image-authoring")))
    (tm:topicmap-workspace-go-to ws "lisp-source-authoring")
    (tst::%view ws "Topicmap")
    (let* ((selection (click (topic-context ws) "Work Operations" "Create relationship"))
           (choice (click selection "Create relationship"
                          (format nil "Target: ~A" (tm:topicmap-topic-label-of target))))
           (request (views:eval-thunk (cdr (assoc "Use relation: informs" (tst::%buttons choice) :test #'equal)))))
      (assert (eq from (a::editor-topic selection)))
      (assert (member target (mapcar #'cdr (views:view-references choice)) :test #'eq))
      (assert (eq (registered-selection selection) (work:work-relationship-creation-selection request)))
      (assert (eq (work:topic-source-occurrence target) (work:work-relationship-creation-to-occurrence request)))
      (assert (equal "work:relation/informs" (work:work-relationship-creation-relation request)))
      request)))

(defun check-relationship-loop (page path)
  (let* ((source (tst::%read path)) (ws (workspace page))
         (request (relationship-request ws))
         (preview (click request "Work request" "Preview plan"))
         (executor (symbol-function 'a:execute-work-relationship-creation))
         (executions 0) fresh)
    (assert (typep request 'work:work-relationship-creation-request))
    (assert (typep preview 'a:work-relationship-creation-plan))
    (assert (member request (refs preview "Work plan") :test #'eq))
    (assert (string= source (tst::%read path)))
    (unwind-protect
         (progn
           (setf (symbol-function 'a:execute-work-relationship-creation)
                 (lambda (given env) (assert (eq request given)) (incf executions) (funcall executor given env)))
           (setf fresh (click preview "Work plan" "Execute request after revalidation")))
      (setf (symbol-function 'a:execute-work-relationship-creation) executor))
    (assert (= 1 executions))
    (assert (eq :applied (a:work-relationship-creation-outcome-status (outcome fresh))))
    (assert (not (eq preview (a:work-relationship-creation-outcome-plan (outcome fresh)))))
    (assert (equal "lisp-source-authoring" (tm:topicmap-workspace-point-of fresh)))
    (assert (= 23 (length (tm:topicmap-projection-associations-of (tm:topicmap-workspace-projection-of fresh)))))
    (let ((added (car (last (tm:topicmap-projection-associations-of (tm:topicmap-workspace-projection-of fresh))))))
      (assert (equal "work:relation/informs" (tm:topicmap-association-type-of added)))
      (assert (equal "running-image-authoring" (tm:topicmap-association-to-of added))))))

(defun check-stale-arguments (page path)
  (let* ((ws (workspace page)) (topic (tm:topicmap-workspace-current-topic ws))
         (selection (a::select-work-operation (w:create-relationship-operation) topic ws))
         (target (tm:topicmap-projection-topic-by-id (tm:topicmap-workspace-projection-of ws) "running-image-authoring"))
         (choice (a::%relationship-choices selection target))
         (concurrent (concatenate 'string (tst::%read path) "<!-- concurrent edit -->")))
    (tst::%write path concurrent)
    (assert (typep (views:eval-thunk (cdr (assoc "Use relation: informs" (tst::%buttons choice) :test #'equal)))
                  'work:work-relationship-creation-refused))
    (assert (string= concurrent (tst::%read path)))))

(defun check-unverified-and-point (page path)
  ;; Force post-install verification failure inside the existing executor.
  ;; This is still a real temporary-file write through the authorised path.
  (let* ((ws (workspace page)) (topic (tm:topicmap-workspace-current-topic ws))
         (selection (a::select-work-operation (w:change-work-status-operation) topic ws))
         (request (a::complete-editor-status selection "in progress"))
         (verifier (symbol-function 'a::%verify-installed)) fresh)
    ;; This navigable topic is unrelated to the edit. Remove it in the simulated
    ;; concurrent change after installation: Point must not survive by fiction.
    (tm:topicmap-workspace-go-to ws "corpus")
    (unwind-protect
         (progn
           (setf (symbol-function 'a::%verify-installed)
                 (lambda (plan candidate)
                   (declare (ignore candidate))
                   (tst::%write path (str:replace-all "\"corpus\"" "\"corpus-new\"" (tst::%read path)))
                   (error 'a:work-status-change-unverified :plan plan :reason "fixture verification failure")))
           (setf fresh (a::execute-work-request request)))
      (setf (symbol-function 'a::%verify-installed) verifier))
    (assert (typep fresh 'tm:topicmap-workspace))
    (assert (eq :unverified (a:work-status-change-outcome-status (outcome fresh))))
    (assert (not (equal "corpus" (tm:topicmap-workspace-point-of fresh))))
    (assert (tm:topicmap-workspace-current-topic fresh))
    (let ((html (views:view-html (tst::%view fresh "Work Breakdown"))))
      (assert (search "Unverified effect" html))
      (assert (search "not verified" html)))
    (assert (string= (tst::%read path)
                    (work:topic-occurrence-snapshot (work:topic-source-occurrence
                                                     (tm:topicmap-workspace-current-topic fresh)))))))

(defun check-two-workspaces (page path)
  "A -> B -> A, sharing even the exact Topic/occurrence and registered request.
B deliberately has a smaller observed projection, different relations and Point.
Returning to A must use A's targets, relation choices and post-effect Point."
  (let* ((source (tst::%read path))
         (wa (workspace page))
         (pa (tm:topicmap-workspace-projection-of wa))
         (from (tm:topicmap-projection-topic-by-id pa "lisp-source-authoring"))
         (target (tm:topicmap-projection-topic-by-id pa "running-image-authoring"))
         (pb (tm:make-topicmap-projection
              :source page
              :topics (remove target (tm:topicmap-projection-topics-of pa) :test #'eq)
              :associations (remove-if-not
                             (lambda (association)
                               (and (equal "develops" (tm:topicmap-association-type-of association))
                                    (not (equal (tm:topicmap-topic-id-of target) (tm:topicmap-association-from-of association)))
                                    (not (equal (tm:topicmap-topic-id-of target) (tm:topicmap-association-to-of association)))))
                             (tm:topicmap-projection-associations-of pa))))
         (wb (tm:make-topicmap-workspace pb "lisp-source-authoring")))
    (tm:topicmap-workspace-go-to wa "lisp-source-authoring")
    ;; Capture A's actual native Point affordance before opening B's.
    (let* ((open-a (topic-context wa))
           (sa (click open-a "Work Operations" "Create relationship"))
           (open-b (topic-context wb))
           (sb (click open-b "Work Operations" "Create relationship")))
      (assert (not (eq open-a open-b)))
      (assert (eq from (a::editor-topic open-a)))
      (assert (eq from (a::editor-topic open-b)))
      (assert (eq (registered-selection sa) (registered-selection sb)))
      (assert (eq (work:topic-source-occurrence from)
                  (r:operation-request-occurrence (registered-selection sa))))
      (assert (null (a::%editor-context (registered-selection sa))))
      (assert (eq pa (a::editor-projection sa)))
      (assert (eq pb (a::editor-projection sb)))
      (tm:topicmap-workspace-go-to wa "interaction")
      (tm:topicmap-workspace-go-to wb "corpus")
      (let* ((label (format nil "Target: ~A" (tm:topicmap-topic-label-of target)))
             (targets-a (tst::%buttons (tst::%view sa "Create relationship")))
             (targets-b (tst::%buttons (tst::%view sb "Create relationship")))
             (other (tm:topicmap-projection-topic-by-id pb "corpus"))
             (choice-b (click sb "Create relationship" (format nil "Target: ~A" (tm:topicmap-topic-label-of other)))))
        (assert (= (length targets-a) (length (tm:topicmap-projection-topics-of pa))))
        (assert (assoc label targets-a :test #'equal))
        (assert (not (assoc label targets-b :test #'equal)))
        (assert (equal '("Use relation: develops") (mapcar #'car (tst::%buttons choice-b))))
        ;; Return to A only after B's complete target/relation UI was inspected.
        (let* ((choice-a (click sa "Create relationship" label))
               (request (views:eval-thunk
                         (cdr (assoc "Use relation: informs" (tst::%buttons choice-a) :test #'equal))))
               (preview (click request "Work request" "Preview plan")))
          (assert (member target (mapcar #'cdr (views:view-references choice-a)) :test #'eq))
          (assert (equal
                   (sort (remove-duplicates
                          (mapcar (lambda (association)
                                    (format nil "Use relation: ~A"
                                            (or (tm:topicmap-association-relation-label association)
                                                (tm:topicmap-association-type-of association))))
                                  (tm:topicmap-projection-associations-of pa)) :test #'equal) #'string<)
                   (sort (mapcar #'car (tst::%buttons choice-a)) #'string<)))
          (assert (eq (registered-selection sa) (work:work-relationship-creation-selection request)))
          (assert (eq (work:topic-source-occurrence target) (work:work-relationship-creation-to-occurrence request)))
          (assert (eq wa (a::editor-workspace (a::%editor-context request))))
          (assert (string= source (tst::%read path)))
          (let ((fresh (click preview "Work plan" "Execute request after revalidation")))
            (assert (eq :applied (a:work-relationship-creation-outcome-status (outcome fresh))))
            (assert (equal "interaction" (tm:topicmap-workspace-point-of fresh)))
            (assert (equal "corpus" (tm:topicmap-workspace-point-of wb)))
            (assert (not (eq pa (tm:topicmap-workspace-projection-of fresh))))))))))

(defun check-source-ownership ()
  (dolist (entry '(("dreyeck/work/authoring" "dreyeck/src/work-topicmap-editor")
                   ("dreyeck/work/authoring/tests" "dreyeck/tests/work-topicmap-editor")
                   ("dreyeck/work/authoring/tests" "dreyeck/tests/work-topicmap-editor-browser")))
    (let ((component (asdf:find-component (first entry) (second entry))))
      (assert component)
      (assert (equal (truename (asdf:component-pathname component))
                     (truename (asdf:system-relative-pathname "dreyeck" (concatenate 'string (second entry) ".lisp")))))))
  (let ((source (uiop:read-file-string (asdf:system-relative-pathname "dreyeck" "dreyeck/src/work-topicmap-editor.lisp"))))
    (assert (not (search "apply-work-status-change" source)))
    (assert (not (search "apply-work-relationship-creation" source)))))

(defun run-tests ()
  (let ((pages (tst::work-page-sources)))
    (dolist (test (list #'check-connections #'check-status-loop #'check-relationship-loop
                       #'check-stale-arguments #'check-unverified-and-point #'check-two-workspaces))
      (tst::call-with-work-breakdown-fixture test))
    (check-source-ownership)
    (tst::check-authoring-boundary)
    (assert (equal pages (tst::work-page-sources))))
  (format t "~&WORK-TOPICMAP-EDITOR-PASS: exact Topic/occurrence, two-Workspace callback isolation, two operations, staged requests/plans, executor replanning, fresh objects, stale refusal, unverified reread, Point fallback, ASDF ownership and Catalog boundary.~%"))
