(defpackage #:dreyeck/work/tests
  (:use #:cl)
  (:local-nicknames (#:work #:dreyeck/work/reading)
                    (#:tm #:dreyeck/topicmap)
                    (#:views #:html-inspector-views)
                    (#:authored #:dreyeck/topicmap/tala/authored)
                    (#:tala #:dreyeck/topicmap/tala))
  (:export #:run-tests))
(in-package #:dreyeck/work/tests)

(defun content-view (page)
  (let ((view (find "Content" (views:all-views page)
                    :key #'views:view-title :test #'equal)))
    (assert view)
    (views:view-html view)
    view))

(defun check-pages-and-example ()
  (let ((book (hyperbook:find-hyperbook "dreyeck/work/reading" :signal-error? t)))
    (dolist (title '("Work Breakdown" "Interaction" "Operations and Change"
                     "Connect and Associations" "State and Persistence"
                     "HyperDoc Dogfooding" "D2 Corpus" "Planning with SHOP3"
                     "D2 Connections"))
      (content-view (hyperbook:find-page book title :signal-error? t)))
    (assert (typep (work:work-page "Working on HyperDoc") 'hyperdoc::code-page))
    ;; The definition must be a real executable Code Page widget, not only prose.
    (let* ((view (content-view (work:work-page "D2 Connections")))
           (widgets (remove-if-not (lambda (ref) (typep (cdr ref) 'views:view))
                                   (views:view-references view))))
      (assert (= 1 (length widgets)))
      (let* ((widget (cdar widgets))
             (html (views:view-html widget))
             (action (find-if (lambda (ref) (typep (cdr ref) 'views:thunk))
                              (views:view-references widget))))
        (assert (search "inspector-action" html))
        (assert action)
        (assert (typep (views:eval-thunk (cdr action)) 'authored:authored-d2)))))
  (let* ((source (work:connections-source))
         (render (work:connections-example))
         (svg (authored:authored-d2-svg render)))
    (assert (string= source (authored:authored-d2-source render)))
    (assert (not (search "&gt;" source)))
    (assert (string= "v0.9.0" (authored:authored-d2-version render)))
    (assert (search "<svg" svg))
    (assert (search "explains" svg))
    (assert (search "compare evidence" svg))
    (assert (find "Authored D2" (views:all-views render)
                  :key #'views:view-title :test #'equal))))

(defun check-native-work-navigation ()
  (let* ((workspace (work:work-workspace))
         (projection (tm:topicmap-projection-of workspace))
         (view (find "Topicmap" (views:all-views workspace)
                     :key #'views:view-title :test #'equal)))
    (views:view-html view)
    (dolist (id '("d2" "connection" "association" "connect" "topicmap"))
      (assert (find-if (lambda (a)
                        (and (equal "connections-example" (tm:topicmap-association-from-of a))
                             (equal id (tm:topicmap-association-to-of a))))
                      (tm:topicmap-projection-associations-of projection))))
    (dolist (topic (tm:topicmap-projection-topics-of projection))
      (let* ((old-point (tm:topicmap-workspace-point-of workspace))
             (action (find-if
                      (lambda (ref)
                        (and (typep (cdr ref) 'dreyeck/inspector/topicmap::topic-action-reference)
                             (eq topic (dreyeck/inspector/topicmap::action-topic (cdr ref)))))
                      (views:view-references view)))
             (page (tm:topicmap-topic-object-of topic)))
        (assert action)
        (assert (typep page 'hyperdoc:page))
        (assert (eq topic (views:eval-thunk (cdr action))))
        (assert (eq page (tm:topicmap-workspace-current-object workspace)))
        (let ((updated (find "Topicmap" (views:all-views workspace)
                             :key #'views:view-title :test #'equal)))
          (views:view-html updated)
          (assert (find page (views:view-references updated) :key #'cdr :test #'eq)))
        (assert (equal (tm:topicmap-topic-id-of topic)
                       (tm:topicmap-workspace-point-of workspace)))
        (unless (equal old-point (tm:topicmap-topic-id-of topic))
          (assert (equal old-point (first (tm:topicmap-workspace-history-of workspace)))))))))

(defun check-work-layout ()
  (let* ((projection (work:work-projection :areas-only t))
         (render (work:work-layout-example)))
    (assert (= 7 (length (tm:topicmap-projection-topics-of projection))))
    (assert (= 7 (length (tm:topicmap-projection-associations-of projection))))
    (assert (typep render 'tala:tala-rendering))
    (assert (search "<svg" (tala:tala-rendering-svg render)))))

(defun run-tests ()
  (check-pages-and-example)
  (check-native-work-navigation)
  (check-work-layout)
  (format t "~&WORK-READING-PASS: pages, executable widget, D2 SVG, native page navigation, seven-area derived layout.~%")
  t)
