(in-package #:dreyeck/work/trails-rendered-reading/tests)

(defun context-view (object title)
  (or (find title (views:all-views object) :key #'views:view-title :test #'equal)
      (error "Missing ~A view" title)))

(defun check-native-follow-reference (view evidence)
  "Resolve the actual lazy navigation reference, not an eager rendering lookup."
  (let* ((dom (plump:parse (views:view-html view)))
         (element (find (reading::context-page-label evidence)
                        (plump:get-elements-by-tag-name dom "span")
                        :key #'plump:text :test #'equal))
         (id (and element (plump:attribute element "id"))))
    (assert (and id (uiop:string-prefix-p "eval-" id)))
    (assert (eq (reading::native-context-page evidence)
                (views:eval-thunk (cdr (assoc id (views:view-references view) :test #'equal)))))))

(defun temporal-proof-values (context)
  "Seven actual Lisp values, independent of Topicmap rendering and its controls."
  (let* ((events (reading:context-events context))
         (ward-index (position "2026-10-01T17:18:24.009Z" events :key (lambda (e) (gethash "at" e)) :test #'equal))
         (jan-index (position "2026-10-01T18:03:05.302Z" events :key (lambda (e) (gethash "at" e)) :test #'equal))
         (ward (reading::context-event-object context ward-index))
         (jan (reading::context-event-object context jan-index))
         (delta (reading:context-delta context ward)))
    (reading::context-table
     "ordered events" (map 'vector #'identity events)
     "Ward event" ward "before state" (getf delta :before)
     "Ward delta" delta "after state" (getf delta :after)
     "Jan fork event" jan "resulting Jan state" (reading:context-state-at context (gethash "at" (reading::event-record jan))))))

(defun check-raw-temporal-derivation (context)
  (let* ((events (reading:context-events context))
         (jan (reading::context-page context "jan-think"))
         (thompson (reading::context-page context "thompson-think"))
         (jan-journal (gethash "journal" (gethash "raw" jan)))
         (source-journal (gethash "journal" (gethash "raw" thompson)))
         (ward (aref events 8)) (cursor (reading::context-cursor context))
         (proof (temporal-proof-values context))
         (delta (gethash "Ward delta" proof)))
    ;; The copied prefix really is Thompson's whole history, including the correction.
    (assert (dreyeck/work/reading::%json-equal source-journal (subseq jan-journal 0 (1- (length jan-journal)))))
    (assert (find 1790874834907 jan-journal :key (lambda (a) (gethash "date" a))))
    (assert (= 1 (length (reading::context-local-journal jan))))
    (assert (= 1 (count 1790874834907 events :key (lambda (e) (gethash "date" e)))))
    (assert (equal "thompson-think" (gethash "page" (find 1790874834907 events :key (lambda (e) (gethash "date" e))))))
    (assert (< 1790874834907 (gethash "date" ward) (gethash "date" (aref events 9))))
    ;; Each emitted record retains an actual action from its publishing raw journal.
    (loop for event across events
          do (assert (find (gethash "journal" event)
                           (gethash "journal" (gethash "raw" (reading::context-page context (gethash "page" event)))) :test #'eq))
             (dolist (key '("topics-added" "topics-removed" "relations-set" "relations-remove" "relations-removed" "summary"))
               (assert (not (nth-value 1 (gethash key event))))))
    (assert (not (gethash "baseline" (gethash "temporal" (reading::context-data context)))))
    (assert (= 4 (length (getf delta :relation-changes))))
    (assert (null (getf delta :added-topics))) (assert (null (getf delta :removed-topics)))
    (assert (null (getf delta :removed-relations)))
    (dolist (change (getf delta :relation-changes))
      (let ((before (getf change :before)) (after (getf change :after)))
        (dolist (key '("id" "from" "to" "item")) (assert (equal (gethash key before) (gethash key after))))
        (assert (equal "" (gethash "kind" before))) (assert (equal "Trail" (gethash "kind" after)))))
    (assert (= cursor (reading::context-cursor context)))
    (assert (equalp (reading:context-state-at context "2026-10-01T17:18:24.009Z")
                    (reading:context-state-at context 1790875104009)))
    (assert (equalp (gethash "before state" proof) (reading:context-state-at context 1790875104008)))
    (assert (equalp (gethash "after state" proof) (reading:context-state-at context 1790875104009)))
    (loop for value being the hash-values of proof do (check-inspector-child proof value))
    ;; Raw content and dates, rather than cached effects or the cursor, determine state.
    (let* ((fresh (reading:federated-context))
           (page (reading::context-page fresh "ward-trails"))
           (action (find 1790875104009 (gethash "journal" (gethash "raw" page)) :key (lambda (a) (gethash "date" a)))))
      (setf (gethash "text" (gethash "item" action))
            (cl-ppcre:regex-replace "\"Trail\"" (gethash "text" (gethash "item" action)) "\"EvidenceProbe\""))
      (let ((probe (reading:context-delta fresh (aref (reading:context-events fresh) 8))))
        (assert (every (lambda (r) (equal "EvidenceProbe" (gethash "kind" r))) (getf probe :changed-relations))))
      (setf (gethash "date" action) 1790875105009)
      (let ((derived (reading::context-derived-events fresh)))
        (assert (not (find 1790875104009 derived :key (lambda (e) (gethash "date" e)))))
        (assert (find 1790875105009 derived :key (lambda (e) (gethash "date" e)))))
      (assert (every (lambda (r) (equal "" (gethash "kind" r)))
                     (remove-if-not (lambda (r) (uiop:string-prefix-p "trail:" (gethash "id" r)))
                                    (getf (reading:context-state-at fresh 1790875104009) :relations)))))
    (format t "~&RAW-TEMPORAL-DERIVATION-PASS: byte-preserved journals, inherited prefix ownership, raw-driven dates and labels, direct State-at/Delta and seven Inspector values.~%")))

(defun context-native-fixture (context function)
  "Exercise production fedwiki HyperBook/page resolution without network access."
  (let* ((catalog hyperbook::*catalog*)
         (hyperbook::*catalog* (make-instance 'hyperbook::catalog)))
    (setf (hyperbook::factories-of hyperbook::*catalog*)
          (alexandria:copy-hash-table (hyperbook::factories-of catalog)))
    (loop for record across (reading::context-pages context)
          for id = (gethash "hyperbook" record)
          for wiki = (or (find id (hyperbook::hyperbooks-of hyperbook::*catalog*)
                              :key #'hyperbook:id-of :test #'equal)
                         (make-instance 'hyperbook/fedwiki::fedwiki :id id))
          do (setf (hyperbook/fedwiki::status-of wiki) t)
             (hyperbook:register wiki)
             (setf (gethash (gethash "slug" record) (hyperbook/fedwiki::pages-of wiki))
                   (hyperbook/fedwiki::make-fedwiki-page wiki (gethash "slug" record) (gethash "title" record))))
    (funcall function)))

(defun check-temporal-federation ()
  (let* ((context (reading:federated-context))
         (events (reading::context-events context))
         (data (reading::context-data context))
         (expected-times '("2026-10-01T17:10:57.791Z" "2026-10-01T17:10:57.792Z"
                           "2026-10-01T17:13:27.513Z" "2026-10-01T17:13:37.885Z"
                           "2026-10-01T17:13:39.907Z" "2026-10-01T17:13:54.907Z"
                           "2026-10-01T17:14:16.195Z" "2026-10-01T17:14:46.108Z"
                           "2026-10-01T17:18:24.009Z" "2026-10-01T18:03:05.302Z"
                           "2026-10-01T18:03:51.968Z"))
         (jan-id "fedwiki:jan.voices.ustawi.wiki/how-we-think")
         (thompson-id "fedwiki:thompson.voices.ustawi.wiki/how-we-think"))
    (check-raw-temporal-derivation context)
    (assert (= 11 (length events)))
    (assert (equal expected-times (map 'list (lambda (event) (gethash "at" event)) events)))
    (assert (apply #'< (map 'list (lambda (event) (gethash "date" event)) events)))
    ;; Every event is attached to its actual publishing page and journal action.
    (loop for event across events
          for journal = (gethash "journal" event)
          do (assert (= (gethash "date" event) (gethash "date" journal)))
             (assert (equal (gethash "operation" event) (gethash "type" journal)))
             (let ((page (reading::context-page context (gethash "page" event))))
               (assert (equal (gethash "site" event) (gethash "site" page)))
               (assert (equal (gethash "page-title" event) (gethash "title" page)))
               (assert (equal (gethash "hyperbook" event) (gethash "hyperbook" page)))))
    (assert (= 1 (count "jan-think" events :key (lambda (event) (gethash "page" event)) :test #'equal)))
    (assert (equal "inherited" (gethash "history" (gethash "after" (aref events 9)))))
    (assert (equal "[[How We May Think]]" (gethash "text" (gethash "before" (aref events 5)))))
    (assert (equal "[[As We May Think]]" (gethash "text" (gethash "after" (aref events 5)))))
    (assert (equal "[[Dorothy Sim" (gethash "text" (gethash "after" (aref events 2)))))
    (assert (equal "[[Dorothy Smith]]" (gethash "text" (gethash "after" (aref events 3)))))
    (assert (equal "[[How We Think]] via Thompson" (gethash "text" (gethash "after" (aref events 10)))))
    (loop for index from 0 below (length events)
          for expected-changes in '(4 1 0 1 2 1 0 1 4 5 1)
          do (reading::select-context-event context index)
             (let* ((state (reading::context-state context index))
                    (delta (reading::context-delta context)))
               (assert (equalp state (reading::context-state context index)))
               (assert (= expected-changes (length (getf delta :changed-relations))))
               (assert (null (getf delta :removed-relations)))
               (assert (equalp state (getf delta :after)))
               (assert (equalp (reading::context-state context (1- index)) (getf delta :before)))
               (assert (if (< index 9) (not (member jan-id (getf state :topics) :test #'equal))
                           (member jan-id (getf state :topics) :test #'equal)))
               (assert (member thompson-id (getf state :topics) :test #'equal))
               (let ((trail-relations (remove-if-not (lambda (relation) (uiop:string-prefix-p "trail:" (gethash "id" relation)))
                                                     (getf state :relations))))
                 (assert (= 4 (length trail-relations)))
                 (assert (every (lambda (relation) (equal (if (< index 8) "" "Trail") (gethash "kind" relation)))
                                trail-relations)))
               (setf (reading::context-mode context) :delta)
               (let ((projection (reading::context-projection context)))
                 (assert (= expected-changes (length (dreyeck/topicmap:topicmap-projection-associations-of projection))))
                 (assert (every (lambda (association)
                                  (member (getf (dreyeck/topicmap:topicmap-association-properties-of association) :evidence)
                                          (getf delta :changed-relations)
                                          :test #'dreyeck/work/reading::%json-equal))
                                (dreyeck/topicmap:topicmap-projection-associations-of projection))))
               (setf (reading::context-mode context) :state)
               (assert (notany (lambda (r) (member (gethash "kind" r) '("causes" "influences") :test #'equal))
                               (getf state :relations)))))
    ;; Fork imports all three related links, preserving separate source/target.
    (let* ((state (reading::context-state context 9))
           (imports (remove-if-not (lambda (r) (and (equal jan-id (gethash "from" r))
                                                    (equal "wiki-link" (gethash "kind" r))))
                                   (getf state :relations))))
      (assert (= 3 (length imports)))
      (assert (find-if (lambda (r) (and (equal "fork" (gethash "kind" r))
                                       (equal thompson-id (gethash "from" r))
                                       (equal jan-id (gethash "to" r)))) (getf state :relations))))
    (assert (dreyeck/work/reading::%json-equal data (reading::read-federated-context)))
    (reading::select-context-event context 9)
    (context-native-fixture
     context
     (lambda ()
       (let ((jan (reading::native-context-page (reading::context-page context "jan-think")))
             (thompson (reading::native-context-page (reading::context-page context "thompson-think"))))
         (assert (not (eq jan thompson)))
         (assert (equal (hyperbook:title-of jan) (hyperbook:title-of thompson)))
         (assert (equal "fedwiki:jan.voices.ustawi.wiki" (hyperbook:id-of (hyperbook:hyperbook-of jan))))
         (assert (equal "fedwiki:thompson.voices.ustawi.wiki" (hyperbook:id-of (hyperbook:hyperbook-of thompson)))))
       ;; Evidence views resolve native source pages only when followed.
       (loop for record across events
             for event = (make-instance 'reading::federated-event :record record :context context)
             for view = (context-view event "Evidence")
             do (views:view-html view)
                (check-native-follow-reference view (reading::context-page context (gethash "page" record)))
                (when (gethash "source-page" record)
                  (check-native-follow-reference view (reading::context-page context (gethash "source-page" record)))))
       ;; TALA retains native page signs and event evidence while State/Delta
       ;; action buttons keep one context object and refresh its existing pane.
       (reading::select-context-event context 9)
       (let* ((view (context-view context "Topicmap"))
              (html (views:view-html view))
              (references (views:view-references view))
              (dom (plump:parse html))
              (jan-sign (find jan-id (plump:get-elements-by-tag-name dom "g")
                              :key (lambda (g) (plump:attribute g "data-topic-id")) :test #'equal)))
         (assert jan-sign)
         (assert (search "data-delta=\"changed\"" html))
         (assert (search "Previous event" html))
         (assert (search "Next event" html))
         (assert (search "State" html))
         (assert (search "Delta" html))
         (assert (find-if (lambda (reference) (typep (cdr reference) 'reading::federated-event)) references))
         (let ((sign-thunk (cdr (assoc (plump:attribute jan-sign "id") references :test #'equal))))
           (assert (null (views:eval-thunk sign-thunk)))
           (assert (equal jan-id (dreyeck/topicmap:topicmap-workspace-point-of
                                 (reading::context-current-workspace context))))
           (assert (= 9 (reading::context-cursor context))))
         (let* ((button (find "Previous event" (plump:get-elements-by-tag-name dom "button") :key #'plump:text :test #'equal))
                (action (cdr (assoc (plump:attribute button "id") references :test #'equal))))
           (assert (uiop:string-prefix-p "action-" (plump:attribute button "id")))
           (assert (views:eval-thunk action))
           (assert (= 8 (reading::context-cursor context))))
         (let* ((button (find "Delta" (plump:get-elements-by-tag-name dom "button") :key #'plump:text :test #'equal))
                (action (cdr (assoc (plump:attribute button "id") references :test #'equal))))
           (assert (views:eval-thunk action))
           (assert (eq :delta (reading::context-mode context)))
           (assert (= 4 (length (dreyeck/topicmap:topicmap-projection-associations-of
                                (reading::context-projection context))))))
         (reading::select-context-event context 5)
         (let* ((correction (views:view-html (context-view context "Topicmap")))
                (correction-dom (plump:parse correction))
                (removed (find "concept:How We May Think" (plump:get-elements-by-tag-name correction-dom "g")
                               :key (lambda (g) (plump:attribute g "data-topic-id")) :test #'equal)))
           (assert removed)
           (assert (equal "removed" (plump:attribute removed "data-delta"))))))))
  (format t "~&TEMPORAL-FEDERATION-PASS: 11 exact events, deterministic State/Delta, inherited fork history, separate site/page identities, native TALA page signs, event evidence and in-place cursor actions.~%"))

(defun check-coordinated-context-workspace ()
  (let* ((context (reading:federated-context))
         (events (reading:context-events context))
         (jan-id "fedwiki:jan.voices.ustawi.wiki/how-we-think")
         (thompson-id "fedwiki:thompson.voices.ustawi.wiki/how-we-think")
         (temporal (reading::context-temporal-projection context))
         (topics (dreyeck/topicmap:topicmap-projection-topics-of temporal)))
    (assert (eq context (dreyeck/topicmap:topicmap-projection-source-of temporal)))
    (assert (equal (map 'list (lambda (e) (gethash "id" e)) events)
                   (mapcar #'dreyeck/topicmap:topicmap-topic-id-of topics)))
    (loop for association in (dreyeck/topicmap:topicmap-projection-associations-of temporal)
          for index from 1
          do (assert (equal (gethash "id" (aref events (1- index)))
                            (dreyeck/topicmap:topicmap-association-from-of association)))
             (assert (equal (gethash "id" (aref events index))
                            (dreyeck/topicmap:topicmap-association-to-of association))))
    ;; The presentation hook must coexist with the generic Association gesture
    ;; binding, rather than replace the existing HTML-view after method.
    (assert (find-method #'clog-moldable-inspector::create-view-element '(:after)
                         (list (find-class 't) (find-class 't) (find-class 'views:html-view))))
    (assert (find-method #'clog-moldable-inspector::create-view-element '(:after)
                         (list (find-class 'clog-moldable-inspector::pane) (find-class 't)
                               (find-class 'views:html-view))))
    (loop for topic in topics for record across events for index from 0
          do (assert (eq (reading::context-event-object context index)
                         (dreyeck/topicmap:topicmap-topic-object-of topic)))
             (assert (search (subseq (gethash "at" record) 11)
                             (dreyeck/topicmap:topicmap-topic-label-of topic)))
             (assert (search (reading::context-page-label (reading::context-page context (gethash "page" record)))
                             (dreyeck/topicmap:topicmap-topic-label-of topic)))
             (assert (search (gethash "operation" record) (dreyeck/topicmap:topicmap-topic-label-of topic))))
    ;; Repeated/clamped movement uses the same event objects, not a second clock.
    (reading::select-context-event context -1)
    (assert (= 0 (reading::context-cursor context)))
    (loop for index from 0 below (length events)
          do (assert (= index (reading::context-cursor context)))
             (let ((delta (reading::context-current-delta context)))
               (assert (eq delta (reading::context-current-delta context)))
               (assert (equalp delta (reading:context-delta context)))
               (assert (eq (getf delta :after) (reading::context-current-state context)))
               (assert (equalp (reading::context-current-state context)
                              (reading:context-state-at context (gethash "date" (aref events index)))))
               (dolist (mode '(:state :delta))
                 (setf (reading::context-mode context) mode)
                 (let ((projection (reading::context-projection context)))
                   (assert (eq context (dreyeck/topicmap:topicmap-projection-source-of projection)))
                   (assert (every (lambda (association)
                                    (member (getf (dreyeck/topicmap:topicmap-association-properties-of association) :evidence)
                                            (if (eq mode :state) (getf (reading::context-current-state context) :relations)
                                                (append (getf delta :changed-relations) (getf delta :removed-relations))) :test #'eq))
                                  (dreyeck/topicmap:topicmap-projection-associations-of projection))))))
             (reading::select-context-event context (1+ index)))
    (assert (= 10 (reading::context-cursor context)))
    (loop for index downfrom 10 to 0
          do (assert (= index (reading::context-cursor context)))
             (reading::select-context-event context (1- index)))
    (assert (= 0 (reading::context-cursor context)))
    (context-native-fixture
     context
     (lambda ()
       (labels ((render ()
                  (let* ((view (context-view context "Topicmap")) (html (views:view-html view)))
                    (values view (plump:parse html) html)))
                (action (view element)
                  (assert (uiop:string-prefix-p "action-" (plump:attribute element "id")))
                  (assert (views:eval-thunk (cdr (assoc (plump:attribute element "id")
                                                       (views:view-references view) :test #'equal)))))
                (button (dom label)
                  (or (find label (plump:get-elements-by-tag-name dom "button") :key #'plump:text :test #'equal)
                      (error "Missing button ~A" label)))
                (map-dom (dom kind)
                  (find kind (plump:get-elements-by-tag-name dom "div")
                        :key (lambda (e) (plump:attribute e "data-projection")) :test #'equal))
                (sign (dom id)
                  (find id (plump:get-elements-by-tag-name dom "g")
                        :key (lambda (e) (plump:attribute e "data-topic-id")) :test #'equal))
                (has-reference (view object)
                  (assert (member object (mapcar #'cdr (views:view-references view)) :test #'eq))))
         ;; Select Thompson directly in the temporal map, then walk the raw order.
         (multiple-value-bind (view dom) (render)
           (assert (map-dom dom "temporal")) (assert (map-dom dom "context"))
           ;; SVG paint order is the renderer's concern; the Lisp projection
           ;; and its ordered adjacency edges carry chronological order.
           (assert (equal (sort (map 'list (lambda (e) (gethash "id" e)) events) #'string<)
                          (sort (mapcar (lambda (e) (plump:attribute e "data-topic-id"))
                                        (remove-if-not (lambda (e) (plump:attribute e "data-topic-id"))
                                                       (plump:get-elements-by-tag-name (map-dom dom "temporal") "g"))) #'string<)))
           (action view (sign (map-dom dom "temporal") (gethash "id" (aref events 5)))))
         (assert (= 5 (reading::context-cursor context)))
         (dolist (index '(6 7 8))
           (multiple-value-bind (view dom) (render) (action view (button dom "Next event")))
           (assert (= index (reading::context-cursor context))))
         (let ((temporal-rendering (reading::context-rendering context :temporal)))
           (multiple-value-bind (view dom) (render) (action view (button dom "Delta")))
           (assert (= 8 (reading::context-cursor context)))
           (assert (eq temporal-rendering (reading::context-rendering context :temporal)))
           (multiple-value-bind (view dom) (render)
             (let* ((projection (reading::context-rendered-projection context :context))
                    (delta (reading::context-current-delta context))
                    (associations (dreyeck/topicmap:topicmap-projection-associations-of projection)))
               (assert (= 4 (length associations)))
               (assert (= 4 (length (getf delta :relation-changes))))
               (assert (null (getf delta :added-topics))) (assert (null (getf delta :removed-topics)))
               (let ((rows (remove-if-not (lambda (row) (plump:attribute row "data-relation-change"))
                                          (plump:get-elements-by-tag-name dom "tr"))))
                 (assert (= 4 (length rows)))
                 (assert (every (lambda (row) (search "\"\" → \"Trail\"" (plump:text row))) rows)))
               (has-reference view (reading::context-event-object context 8))
               (has-reference view (reading::context-current-state context))
               (has-reference view delta)
               (dolist (change (getf delta :relation-changes)) (has-reference view change))
               (dolist (association associations)
                 (has-reference view association)
                 (let* ((properties (dreyeck/topicmap:topicmap-association-properties-of association))
                        (change (getf properties :change))
                        (evidence (context-view association "Evidence")))
                   (views:view-html evidence)
                   (has-reference evidence (getf properties :evidence))
                   (has-reference evidence change)
                   (has-reference evidence (getf change :before))
                   (has-reference evidence (getf change :after))))
               (assert (= 1 (count "true" (plump:get-elements-by-tag-name (map-dom dom "temporal") "g")
                                   :key (lambda (e) (plump:attribute e "data-selected")) :test #'equal))))))
         (multiple-value-bind (view dom) (render) (action view (button dom "Next event")))
         (assert (= 9 (reading::context-cursor context)))
         (multiple-value-bind (view dom) (render) (action view (button dom "State")))
         ;; Same title, distinct Topics and native pages. Primary moves Point;
         ;; Follow is an explicit operation on the represented object at Point.
         (dolist (id (list jan-id thompson-id))
           (multiple-value-bind (view dom) (render)
             (let* ((element (sign (map-dom dom "context") id))
                    (reference (cdr (assoc (plump:attribute element "id")
                                           (views:view-references view) :test #'equal))))
               (assert (uiop:string-prefix-p "action-" (plump:attribute element "id")))
               (assert (null (views:eval-thunk reference)))))
           (assert (= 9 (reading::context-cursor context)))
           (let* ((workspace (reading::context-current-workspace context))
                  (topic (dreyeck/topicmap:topicmap-workspace-current-topic workspace))
                  (page (dreyeck/topicmap:topicmap-topic-object-of topic)))
             (assert (equal id (dreyeck/topicmap:topicmap-topic-id-of topic)))
             (multiple-value-bind (view dom) (render)
               (declare (ignore dom))
               (has-reference view topic) (has-reference view page))))
         (multiple-value-bind (view dom) (render) (action view (button dom "Next event")))
         (assert (= 10 (reading::context-cursor context)))
         (multiple-value-bind (view dom) (render) (action view (button dom "Delta")))
         (let* ((projection (reading::context-rendered-projection context :context))
                (association (first (dreyeck/topicmap:topicmap-projection-associations-of projection)))
                (properties (dreyeck/topicmap:topicmap-association-properties-of association))
                (attribution (getf properties :attribution))
                (view (context-view association "Evidence")))
           (assert (= 1 (length (dreyeck/topicmap:topicmap-projection-associations-of projection))))
           (assert (equal "wiki-link" (dreyeck/topicmap:topicmap-association-type-of association)))
           (assert (equal "via Thompson" (gethash "attribution" attribution)))
           (assert (equal "thompson-think" (gethash "credited-page" attribution)))
           (views:view-html view)
           (has-reference view attribution)
           (has-reference view (gethash "after" (aref events 10)))
           (check-native-follow-reference view (reading::context-page context "thompson-think")))))))
  (format t "~&COORDINATED-WORKSPACE-PASS: one cursor, two TALA maps, ordered event selection, deterministic Previous/Next, actual State/Delta/topic/relation Inspector references and native object following.~%"))

(defun check-context-represented-objects ()
  (let* ((context (reading:federated-context))
         (raw (dreyeck/work/reading::%copy-json (reading::context-data context)))
         (hyperbook/fedwiki::*neighborhood* (make-hash-table :test 'equal)))
    (context-native-fixture context (lambda ()
     (let ((catalog-pages (copy-list (hyperbook::hyperbooks-of hyperbook::*catalog*))))
      (labels ((topic (id)
               (dreyeck/topicmap::topicmap-projection-topic-by-id (reading::context-projection context) id))
             (object (id) (dreyeck/topicmap:topicmap-topic-object-of (topic id)))
             (references (object title)
               (let ((view (context-view object title)))
                 (views:view-html view)
                 (mapcar #'cdr (views:view-references view)))))
      ;; Native, historical, site-qualified page identity: not metadata or a sign.
      (let* ((evidence (reading::context-page context "jan-dewey"))
             (id (reading::context-page-id evidence))
             (page (object id)) (event (reading::context-event-object context 10)))
        (assert (typep page 'hyperbook/fedwiki::fedwiki-page))
        (assert (typep page 'reading::context-fedwiki-page))
        (assert (eq page (reading::context-page-object context evidence)))
        (assert (eq page (object id)))
        (assert (eq evidence (reading::page-evidence page)))
        (assert (eq event (reading::page-event page)))
        (assert (equal "fedwiki:jan.voices.ustawi.wiki" (hyperbook:id-of (hyperbook:hyperbook-of page))))
        (assert (equal "john-dewey" (hyperbook:id-of page)))
        (assert (some (lambda (item) (search "[[How We Think]] via Thompson" (hyperbook/fedwiki::text-of item)))
                      (hyperbook/fedwiki::story-of page)))
        (assert (not (search "Reload" (views:view-html (views:title-bar-action-buttons page)))))
        (let* ((view (context-view page "Story")) (html (views:view-html view))
               (refs (mapcar #'cdr (views:view-references view))))
          (assert (search "via Thompson" html))
          (assert (member (reading::context-page-object context (reading::context-page context "jan-think"))
                          refs :test #'eq))
          (assert (some (lambda (ref) (typep ref 'reading::federated-subject)) refs))
          (assert (eq (reading::context-subject-object context "Reflective Practice")
                      (reading::historical-wiki-link-target page "Reflective Practice"))))
        (let* ((link (find "How We Think" (hyperbook/fedwiki::wiki-links-of (hyperbook:links-of page))
                           :key #'hyperbook/fedwiki::target-title-of :test #'equal))
               (target (views:eval-thunk (hyperbook::thunk-of link))))
          (assert (eq target (reading::context-page-object context (reading::context-page context "jan-think")))))
        (let ((refs (references page "Source / Time")))
          (dolist (value (list event (reading::page-json page) (gethash "raw" evidence)))
            (assert (member value refs :test #'eq))))
        ;; Moving the cursor never mutates an already represented page snapshot.
        (reading::select-context-event context 9)
        (let ((earlier (object id)))
          (assert (not (eq page earlier)))
          (assert (notany (lambda (item) (search "via Thompson" (hyperbook/fedwiki::text-of item)))
                          (hyperbook/fedwiki::story-of earlier)))
          (assert (eq event (reading::page-event page))))
        (reading::select-context-event context 10))
      (let ((jan (object "fedwiki:jan.voices.ustawi.wiki/how-we-think"))
            (thompson (object "fedwiki:thompson.voices.ustawi.wiki/how-we-think")))
        (assert (not (eq jan thompson)))
        (assert (equal (hyperbook:title-of jan) (hyperbook:title-of thompson)))
        (assert (not (eq (hyperbook:hyperbook-of jan) (hyperbook:hyperbook-of thompson))))
        (assert (equal "thompson.voices.ustawi.wiki"
                       (hyperbook/fedwiki::site-of (aref (hyperbook/fedwiki::journal-of jan)
                                                        (1- (length (hyperbook/fedwiki::journal-of jan))))))))
      ;; A real unresolved subject preserves the reading, source event and links.
      (let ((subject (object "concept:Reflective Practice")))
        (assert (typep subject 'reading::federated-subject))
        (assert (eq subject (reading::context-subject-object context "Reflective Practice")))
        (assert (eq context (reading::subject-context subject)))
        (assert (eq (reading::context-event-object context 10) (reading::subject-event subject)))
        (assert (equal "Reflective Practice" (reading::subject-title subject)))
        (assert (reading::subject-links subject))
        (assert (every (lambda (link) (and (typep link 'hyperbook/fedwiki::wiki-link)
                                          (equal "Reflective Practice" (hyperbook/fedwiki::target-title-of link))))
                       (reading::subject-links subject)))
        ;; None of the saved pages is arbitrarily relabeled Reflective Practice.
        (assert (null (reading::subject-context-pages subject)))
        (assert (null (reading::subject-neighborhood-pages subject)))
        (let ((refs (references subject "Subject")))
          (dolist (value (append (list context (reading::subject-event subject)) (reading::subject-links subject)))
            (assert (member value refs :test #'eq))))
        ;; Cached neighborhood references stay distinct from historical evidence.
        (let* ((jan (make-instance 'hyperbook/fedwiki::fedwiki :id "fedwiki:jan.voices.ustawi.wiki"))
               (thompson (make-instance 'hyperbook/fedwiki::fedwiki :id "fedwiki:thompson.voices.ustawi.wiki"))
               (jp (hyperbook/fedwiki::make-fedwiki-page jan "reflective-practice" "Reflective Practice"))
               (tp (hyperbook/fedwiki::make-fedwiki-page thompson "reflective-practice" "Reflective Practice")))
          (setf (gethash "reflective-practice" (hyperbook/fedwiki::pages-of jan)) jp
                (gethash "reflective-practice" (hyperbook/fedwiki::pages-of thompson)) tp
                (gethash "jan.voices.ustawi.wiki" hyperbook/fedwiki::*neighborhood*) jan
                (gethash "thompson.voices.ustawi.wiki" hyperbook/fedwiki::*neighborhood*) thompson)
          (assert (equal (list jp tp) (reading::subject-neighborhood-pages subject)))
          (assert (null (reading::subject-context-pages subject)))
          (clrhash hyperbook/fedwiki::*neighborhood*)))
      (assert (equal '("fedwiki:jan.voices.ustawi.wiki" "fedwiki:thompson.fed.wiki" "fedwiki:thompson.voices.ustawi.wiki")
                     (sort (mapcar (lambda (page) (hyperbook:id-of (hyperbook:hyperbook-of page)))
                                   (reading::subject-context-pages (object "concept:How We Think"))) #'string<)))
      ;; Event signs and relation contract signs retain exact model references.
      (reading::select-context-event context 8)
      (let* ((event (reading::context-event-object context 8))
             (sign (dreyeck/topicmap::topicmap-projection-topic-by-id (reading::context-temporal-projection context)
                                                        (gethash "id" (reading::event-record event)))))
        (assert (eq event (dreyeck/topicmap:topicmap-topic-object-of sign))))
      (dolist (mode '(:state :delta))
        (setf (reading::context-mode context) mode)
        (let* ((delta (reading::context-current-delta context))
               (projection (reading::context-projection context)))
          (dolist (association (dreyeck/topicmap:topicmap-projection-associations-of projection))
            (let* ((properties (dreyeck/topicmap:topicmap-association-properties-of association))
                   (sign (getf properties :relation-contract))
                   (expected (if (eq mode :delta) (getf properties :change) (getf properties :evidence)))
                   (represented (dreyeck/topicmap:topicmap-topic-object-of sign)))
              (assert (typep sign 'dreyeck/topicmap:topicmap-topic))
              (assert (eq :relation (dreyeck/topicmap:topicmap-topic-type-of sign)))
              (assert (eq expected represented))
              (when (eq mode :delta) (assert (member represented (getf delta :relation-changes) :test #'eq)))
              (assert (member represented (references association "Evidence") :test #'eq))))))
      ;; Constructing projections never registers global sites or materializes pages.
      (assert (zerop (hash-table-count hyperbook/fedwiki::*neighborhood*)))
      (assert (equal catalog-pages (hyperbook::hyperbooks-of hyperbook::*catalog*)))
      (assert (dreyeck/work/reading::%json-equal raw (reading::context-data context))))))))
  (format t "~&REPRESENTED-OBJECTS-PASS: EQ page/subject/event/state/change objects, historical native pages, distinct same-title sites, unresolved native links, separate context/neighborhood and unchanged raw evidence/catalog.~%"))

(defun context-native-follow-fixture (context function)
  "Only the HTTP boundary is replaced: absent plugin pages return the native
server's non-JSON miss response. Collaborative/context resolution stays real."
  (let ((fetch (symbol-function 'hyperbook/fedwiki::fetch-page-json)))
    (unwind-protect
         (progn
           (setf (symbol-function 'hyperbook/fedwiki::fetch-page-json)
                 (lambda (&rest arguments)
                   (declare (ignore arguments))
                   (shasht:read-json "Page not found")))
           (context-native-fixture context function))
      (setf (symbol-function 'hyperbook/fedwiki::fetch-page-json) fetch))))

(defun check-context-interaction-semantics ()
  (let* ((context (reading:federated-context))
         (raw (dreyeck/work/reading::%copy-json (reading::context-data context)))
         (hyperbook/fedwiki::*neighborhood* (make-hash-table :test 'equal)))
    (context-native-follow-fixture
     context
     (lambda ()
       ;; Native page resolution must be exercised offline, with loaded source
       ;; pages, rather than replaced by another title/context resolver.
       (dolist (wiki (hyperbook::hyperbooks-of hyperbook::*catalog*))
         (maphash (lambda (id page) (declare (ignore id))
                    (setf (slot-value page 'hyperbook/fedwiki::story) #()))
                  (hyperbook/fedwiki::pages-of wiki)))
       (let* ((projection (reading::context-rendered-projection context :context))
              (jan-id "fedwiki:jan.voices.ustawi.wiki/john-dewey")
              (subject-id "concept:Reflective Practice")
              (jan-topic (dreyeck/topicmap::topicmap-projection-topic-by-id projection jan-id))
              (subject-topic (dreyeck/topicmap::topicmap-projection-topic-by-id projection subject-id))
              (jan (dreyeck/topicmap:topicmap-topic-object-of jan-topic))
              (subject (dreyeck/topicmap:topicmap-topic-object-of subject-topic))
              (workspace (reading::context-current-workspace context)))
         (labels ((reference (view element)
                    (cdr (assoc (plump:attribute element "id") (views:view-references view) :test #'equal)))
                  (primary (id &optional (kind "context"))
                    (let* ((view (context-view context "Topicmap"))
                           (dom (plump:parse (views:view-html view)))
                           (map (find kind (plump:get-elements-by-tag-name dom "div")
                                      :key (lambda (e) (plump:attribute e "data-projection")) :test #'equal))
                           (sign (find id (plump:get-elements-by-tag-name map "g")
                                       :key (lambda (e) (plump:attribute e "data-topic-id")) :test #'equal)))
                      (assert (uiop:string-prefix-p "action-" (plump:attribute sign "id")))
                      (views:eval-thunk (reference view sign))))
                  (follow-at-point (id)
                    (assert (null (primary id)))
                    (let* ((view (reading::context-point-view context))
                           (dom (plump:parse (views:view-html view)))
                           (button (find "Follow" (plump:get-elements-by-tag-name dom "button")
                                         :key #'plump:text :test #'equal)))
                      (assert (uiop:string-prefix-p "eval-" (plump:attribute button "id")))
                      (views:eval-thunk (reference view button))))
                  (inspection (id expected)
                    (let* ((view (context-view context "Topicmap"))
                           (dom (plump:parse (views:view-html view)))
                           (row (find id (plump:get-elements-by-tag-name dom "tr")
                                      :key (lambda (e) (plump:attribute e "data-inspection-topic")) :test #'equal)))
                      (dolist (label '("Inspect represented object" "Inspect Topicmap sign"))
                        (let ((element (find label (remove-if-not
                                                   (lambda (e) (plump:attribute e "id"))
                                                   (plump:get-elements-by-tag-name row "span"))
                                             :key #'plump:text :test #'equal)))
                          (assert (uiop:string-prefix-p "inspect-" (plump:attribute element "id")))
                          (assert (eq (if (equal label "Inspect represented object") expected
                                          (dreyeck/topicmap::topicmap-projection-topic-by-id projection id))
                                      (reference view element)))))))
                  (add-candidate (site)
                    (let* ((wiki (hyperbook:find-hyperbook (format nil "fedwiki:~A" site) :signal-error? t))
                           (page (hyperbook/fedwiki::make-fedwiki-page wiki "reflective-practice" "Reflective Practice")))
                      (setf (slot-value page 'hyperbook/fedwiki::story) #()
                            (gethash "reflective-practice" (hyperbook/fedwiki::pages-of wiki)) page
                            (gethash site hyperbook/fedwiki::*neighborhood*) wiki)
                      page)))
           ;; Rendering has no follow or subject resolution effect.
           (let ((lookup (symbol-function 'hyperbook/fedwiki::lookup-slug-in-page-context)) (calls 0))
             (unwind-protect
                  (progn
                    (setf (symbol-function 'hyperbook/fedwiki::lookup-slug-in-page-context)
                          (lambda (&rest args) (incf calls) (apply lookup args)))
                    (views:view-html (context-view context "Topicmap"))
                    (views:view-html (context-view subject "Subject"))
                    (assert (zerop calls))
                    (assert (null (reading::subject-resolution subject)))
                    (assert (null (primary jan-id)))
                    (assert (zerop calls))
                    (assert (eq jan (follow-at-point jan-id)))
                    (assert (= 10 (reading::context-cursor context)))
                    (assert (equal jan-id (dreyeck/topicmap:topicmap-workspace-point-of workspace)))
                    (assert (null (primary subject-id)))
                    (assert (zerop calls))
                    (assert (eq subject (follow-at-point subject-id)))
                    (assert (plusp calls))
                    (assert (null (getf (reading::subject-resolution subject) :pages)))
                    (assert (null (getf (reading::subject-resolution subject) :failures))))
               (setf (symbol-function 'hyperbook/fedwiki::lookup-slug-in-page-context) lookup)))
           (assert (typep subject 'reading::federated-subject))
           (assert (typep jan 'reading::context-fedwiki-page))
           (inspection subject-id subject)
           (inspection jan-id jan)
           ;; A unique candidate is followed. Two sites require an explicit
           ;; choice; source ordering and site spelling never decide for us.
           (let* ((tp (add-candidate "thompson.voices.ustawi.wiki"))
                  (jp nil))
             (assert (eq tp (follow-at-point subject-id)))
             (assert (equal (list tp) (getf (reading::subject-resolution subject) :pages)))
             (let ((lookup (symbol-function 'hyperbook/fedwiki::lookup-slug-in-page-context)))
               (unwind-protect
                    (progn
                      (setf (symbol-function 'hyperbook/fedwiki::lookup-slug-in-page-context)
                            (lambda (slug source &rest arguments)
                              (if (equal "fedwiki:jan.voices.ustawi.wiki"
                                         (hyperbook:id-of (hyperbook:hyperbook-of source)))
                                  (error "Fixture transport unavailable")
                                  (apply lookup slug source arguments))))
                      (assert (eq subject (follow-at-point subject-id)))
                      (assert (equal (list tp) (getf (reading::subject-resolution subject) :pages)))
                      (assert (getf (reading::subject-resolution subject) :failures)))
                 (setf (symbol-function 'hyperbook/fedwiki::lookup-slug-in-page-context) lookup)))
             (setf jp (add-candidate "jan.voices.ustawi.wiki"))
             (assert (eq subject (follow-at-point subject-id)))
             (let* ((pages (getf (reading::subject-resolution subject) :pages))
                    (view (context-view subject "Subject"))
                    (html (views:view-html view)))
               (assert (= 2 (length pages)))
               (assert (member tp pages :test #'eq)) (assert (member jp pages :test #'eq))
               (assert (search "Choose wiki working material" html))
               (dolist (page pages)
                 (assert (member page (mapcar #'cdr (views:view-references view)) :test #'eq))))
             ;; The native context resolver may return a remote reference. It
             ;; is deduplicated by origin, and never called a persistent fork.
             (let* ((source (hyperbook:find-page (hyperbook:find-hyperbook "fedwiki:ward.voices.ustawi.wiki")
                                               "trails-rendered"))
                    (wiki (hyperbook:hyperbook-of tp)))
               (setf (slot-value source 'hyperbook/fedwiki::context) (list wiki))
               (assert (eq subject (follow-at-point subject-id)))
               (assert (= 2 (length (getf (reading::subject-resolution subject) :pages)))))
             (format t "~&SUBJECT-FOLLOW-PASS: unique Thompson / Reflective Practice follows; Jan + Thompson require explicit choice; native collaborative/context resolution and origin deduplication.~%"))
           (assert (= 10 (reading::context-cursor context)))
           (assert (equal subject-id (dreyeck/topicmap:topicmap-workspace-point-of workspace)))
           ;; A temporal click uses its represented event, recomputes the
           ;; existing State/Delta, and cannot call the wiki follow operation.
           (let ((follow (symbol-function 'reading::follow-context-object))
                 (before (reading::context-current-state context)))
             (unwind-protect
                  (progn
                    (setf (symbol-function 'reading::follow-context-object)
                          (lambda (object) (error "Temporal click followed ~S" object)))
                    (primary (gethash "id" (aref (reading::context-events context) 8)) "temporal")
                    (assert (= 8 (reading::context-cursor context)))
                    (assert (not (equalp before (reading::context-current-state context))))
                    (assert (= 4 (length (getf (reading::context-current-delta context) :relation-changes)))))
               (setf (symbol-function 'reading::follow-context-object) follow)))
           (assert (dreyeck/work/reading::%json-equal raw (reading::context-data context))))))))
  ;; With empty global registries, even repeated render/rebuild at every event
  ;; must leave them empty. Live page references are lazy until navigation.
  (let* ((context (reading:federated-context))
         (hyperbook/fedwiki::*neighborhood* (make-hash-table :test 'equal))
         (hyperbook::*catalog* (make-instance 'hyperbook::catalog)))
    (loop for index below (length (reading::context-events context))
          do (reading::select-context-event context index)
             (dolist (mode '(:state :delta))
               (setf (reading::context-mode context) mode)
               (reading::context-projection context)
               (views:view-html (context-view context "Topicmap"))))
    (assert (zerop (hash-table-count hyperbook/fedwiki::*neighborhood*)))
    (assert (null (hyperbook::hyperbooks-of hyperbook::*catalog*))))
  (format t "~&INTERACTION-SEMANTICS-PASS: temporal-only event selection, context Point navigation, exact historical Follow at Point, unchanged subject resolution/choice, exact Inspector targets, NIL movement transport and side-effect-free projection/rendering.~%"))

(defun check-context-orthogonal-operations ()
  (let* ((context (reading:federated-context))
         (workspace (reading::context-current-workspace context))
         (a "fedwiki:jan.voices.ustawi.wiki/john-dewey")
         (b "fedwiki:thompson.voices.ustawi.wiki/how-we-think")
         (c "concept:How We Think")
         (projection (dreyeck/topicmap:topicmap-workspace-projection-of workspace))
         (topic-b (dreyeck/topicmap::topicmap-projection-topic-by-id projection b))
         (page-b (dreyeck/topicmap:topicmap-topic-object-of topic-b))
         (follow (symbol-function 'reading::follow-context-object))
         (follows nil) (updates 0))
    (assert (equal a (dreyeck/topicmap:topicmap-workspace-point-of workspace)))
    (unwind-protect
         (progn
           (setf (symbol-function 'reading::follow-context-object)
                 (lambda (object) (push object follows) (funcall follow object)))
           (let* ((view (context-view context "Topicmap"))
                  (dom (plump:parse (views:view-html view))))
             (labels ((reference (view element)
                        (cdr (assoc (plump:attribute element "id") (views:view-references view) :test #'equal)))
                      (sign (id)
                        (find id (plump:get-elements-by-tag-name dom "g")
                              :key (lambda (e) (plump:attribute e "data-topic-id")) :test #'equal))
                      (point-view ()
                        (reading::bind-context-point-actions
                         (reading::context-point-view context) (lambda () (incf updates))))
                      (button (dom label)
                        (or (find label (plump:get-elements-by-tag-name dom "button") :key #'plump:text :test #'equal)
                            (error "Missing Point operation ~A" label))))
               (assert (not (search "Set Workspace Point" (views:view-html view))))
               ;; Primary B moves Point, with the existing NIL transport and no Follow.
               (let* ((element (sign b)) (action (reference view element)))
                 (assert (uiop:string-prefix-p "action-" (plump:attribute element "id")))
                 (assert (typep action 'dreyeck/inspector/topicmap::topic-action-reference))
                 (assert (eq topic-b (dreyeck/inspector/topicmap::action-topic action)))
                 (assert (eq workspace (dreyeck/inspector/topicmap::action-workspace action)))
                 (setf (reading::point-action-update-view action) (lambda () (incf updates)))
                 (assert (null (views:eval-thunk action)))
                 (assert (equal b (dreyeck/topicmap:topicmap-workspace-point-of workspace)))
                 (assert (= 1 updates))
                 (assert (null (views:eval-thunk action)))
                 (assert (= 1 updates))
                 (assert (null follows))
                 (assert (= 10 (reading::context-cursor context))))
               ;; Follow and both inspections act on the exact object/sign at Point B.
               (let* ((point-view (point-view))
                      (html (views:view-html point-view)) (point-dom (plump:parse html))
                      (follow-button (button point-dom "Follow")))
                 (assert (search (dreyeck/topicmap:topicmap-topic-label-of topic-b) html))
                 (assert (not (search "Open wiki page" html)))
                 (assert (uiop:string-prefix-p "eval-" (plump:attribute follow-button "id")))
                 (assert (eq page-b (views:eval-thunk (reference point-view follow-button))))
                 (assert (equal (list page-b) follows))
                 (dolist (label '("Inspect represented object" "Inspect Topicmap sign"))
                   (let ((element (find label (remove-if-not (lambda (e) (plump:attribute e "id"))
                                                            (plump:get-elements-by-tag-name point-dom "span"))
                                        :key #'plump:text :test #'equal)))
                     (assert (uiop:string-prefix-p "inspect-" (plump:attribute element "id")))
                     (assert (eq (if (equal label "Inspect represented object") page-b topic-b)
                                 (reference point-view element)))))
                 (assert (equal b (dreyeck/topicmap:topicmap-workspace-point-of workspace)))
                 (assert (= 10 (reading::context-cursor context)))
                 ;; Every relation endpoint is graph navigation through the same action.
                 (dolist (row (plump:get-elements-by-tag-name point-dom "tr"))
                   (let* ((association (find (plump:attribute row "data-point-relation")
                                            (dreyeck/topicmap::topicmap-associations-of-point workspace)
                                            :key #'dreyeck/topicmap:topicmap-association-id-of :test #'equal))
                          (element (first (plump:get-elements-by-tag-name row "button")))
                          (action (reference point-view element)))
                     (assert association)
                     (assert (typep action 'reading::context-point-action))
                     (assert (equal (dreyeck/topicmap::topicmap-association-other-topic-id workspace association)
                                    (dreyeck/topicmap:topicmap-topic-id-of
                                     (dreyeck/inspector/topicmap::action-topic action))))))
                 (let* ((topic-c (dreyeck/topicmap::topicmap-projection-topic-by-id projection c))
                        (element (button point-dom (dreyeck/topicmap:topicmap-topic-label-of topic-c))))
                   (assert (null (views:eval-thunk (reference point-view element))))
                   (assert (= 2 updates))
                   (assert (equal c (dreyeck/topicmap:topicmap-workspace-point-of workspace)))
                   (assert (equal (list b a) (dreyeck/topicmap:topicmap-workspace-history-of workspace)))
                   (assert (equal (list page-b) follows))
                   (assert (= 10 (reading::context-cursor context)))))
               (let* ((updated (plump:parse (views:view-html (context-view context "Topicmap"))))
                      (sign-c (find c (plump:get-elements-by-tag-name updated "g")
                                    :key (lambda (e) (plump:attribute e "data-topic-id")) :test #'equal))
                      (point (find "true" (plump:get-elements-by-tag-name updated "div")
                                   :key (lambda (e) (plump:attribute e "data-workspace-point")) :test #'equal)))
                 (assert (equal "true" (plump:attribute sign-c "data-selected")))
                 (assert (search "How We Think" (plump:text point)))
                 (assert (= (length (dreyeck/topicmap::topicmap-associations-of-point workspace))
                            (length (plump:get-elements-by-tag-name point "tr")))))
               ;; Temporal selection re-projects the same editing session.
               (let ((event-sign (sign (gethash "id" (aref (reading::context-events context) 8)))))
                 (assert (views:eval-thunk (reference view event-sign))))
               (assert (= 8 (reading::context-cursor context)))
               (let ((current (reading::context-current-workspace context)))
                 (assert (equal c (dreyeck/topicmap:topicmap-workspace-point-of current)))
                 (assert (eq current workspace))
                 (assert (equal (list b a) (dreyeck/topicmap:topicmap-workspace-history-of current))))
               (assert (equal (list page-b) follows)))))
      (setf (symbol-function 'reading::follow-context-object) follow)))
  (format t "~&ORTHOGONAL-CONTEXT-OPERATIONS-PASS: primary B moves Point/no follow/NIL; Follow and inspections at B preserve Point/time; relation to C uses the same movement; temporal selection retains Workspace/Point/history.~%"))

(defun check-context-topic-operations ()
  (let* ((context (reading:federated-context))
         (workspace (reading::context-current-workspace context))
         (projection (tm:topicmap-workspace-projection-of workspace))
         (a (tm:topicmap-workspace-point-of workspace))
         (history (tm:topicmap-workspace-history-of workspace))
         (cursor (reading::context-cursor context))
         (b (tm:topicmap-projection-topic-by-id projection "fedwiki:thompson.voices.ustawi.wiki/how-we-think"))
         (object (tm:topicmap-topic-object-of b))
         (follow (symbol-function 'reading::follow-context-object))
         (follows nil))
    (assert (not (equal a (tm:topicmap-topic-id-of b))))
    (unwind-protect
         (progn
           (setf (symbol-function 'reading::follow-context-object)
                 (lambda (target) (push target follows) (funcall follow target)))
           (dolist (case (list (list (w:follow-operation) 90 object)
                               (list (w:inspect-represented-object-operation) 180 object)
                               (list (w:inspect-topicmap-sign-operation) 270 b)))
             (destructuring-bind (operation angle expected) case
               (dolist (kind '(:radial-menu :learned-mark))
                 (let ((occurrence (gt::%production-occurrence workspace b)))
                   (assert (= 6 (length (m:workspace-action-sign-bindings occurrence))))
                   (gt::check-topic-binding-sectors occurrence)
                   (gt::check-topic-binding-pair occurrence operation angle)
                   (gt::%feed occurrence (gt::%sector-trace angle kind))
                   (assert (eq :completed (getf (gt::%result occurrence) :state)))
                   (assert (eq operation (w:gesture-binding-operation
                                         (dreyeck/gesture/clog:gesture-window-selection
                                          (m:occurrence-gesture-window occurrence)))))
                   (assert (eq expected (m:workspace-action-sign-selected-object occurrence)))
                   (assert (equal a (tm:topicmap-workspace-point-of workspace)))
                   (assert (eq history (tm:topicmap-workspace-history-of workspace)))
                   (assert (= cursor (reading::context-cursor context)))))))
           (assert (equal (list object object) follows))
           ;; A Subject offers the same Follow identities; resolution remains the existing function.
           (let ((subject (tm:topicmap-projection-topic-by-id projection "concept:How We Think")))
             (gt::check-topic-binding-pair (gt::%production-occurrence workspace subject) (w:follow-operation) 90))
           ;; Unsupported objects leave Follow's sector vacant and refuse direct execution.
           (let* ((plain (tm:make-topicmap-topic :id "unsupported" :label "Unsupported" :object :unsupported))
                  (ws (tm:make-topicmap-workspace (tm:make-topicmap-projection :topics (list plain)) "unsupported"))
                  (occurrence (gt::%production-occurrence ws plain)))
             (assert (= 4 (length (m:workspace-action-sign-bindings occurrence))))
             (gt::check-topic-binding-sectors occurrence)
             (gt::check-topic-binding-pair occurrence (w:inspect-represented-object-operation) 180)
             (gt::check-topic-binding-pair occurrence (w:inspect-topicmap-sign-operation) 270)
             (assert (handler-case
                         (progn (m:operation-inspectable-object
                                 (w:follow-operation)
                                 (list :type :workspace-action-sign-occurrence :occurrence occurrence)) nil)
                       (m:operation-not-applicable () t))))
           ;; Actual PRIMARY reference retains the ordinary non-refreshing Point operation.
           (let* ((view (context-view context "Topicmap"))
                  (dom (plump:parse (views:view-html view)))
                  (sign (find (tm:topicmap-topic-id-of b) (plump:get-elements-by-tag-name dom "g")
                              :key (lambda (e) (plump:attribute e "data-topic-id")) :test #'equal))
                  (reference (cdr (assoc (plump:attribute sign "id") (views:view-references view) :test #'equal))))
             (assert (null (views:eval-thunk reference)))
             (assert (equal (tm:topicmap-topic-id-of b) (tm:topicmap-workspace-point-of workspace)))
             (assert (equal (list a) (tm:topicmap-workspace-history-of workspace)))
             (assert (= cursor (reading::context-cursor context)))
             (assert (equal (list object object) follows))))
      (setf (symbol-function 'reading::follow-context-object) follow)))
  (format t "~&FEDERATED-TOPIC-OPERATIONS-PASS: same menu/mark identities and sectors, exact B Follow/object/sign, unchanged A/history/time, applicability/refusal, unchanged PRIMARY.~%"))

(defun check-context-persistent-workspace ()
  (let* ((context (reading:federated-context))
         (workspace (reading::context-current-workspace context))
         (a "fedwiki:jan.voices.ustawi.wiki/john-dewey")
         (b "fedwiki:thompson.voices.ustawi.wiki/how-we-think")
         (c "concept:How We Think")
         (d "concept:Reflective Practice")
         (go-to (symbol-function 'dreyeck/topicmap:topicmap-workspace-go-to))
         (follow (symbol-function 'reading::follow-context-object))
         (moves 0))
    (assert (equal a (dreyeck/topicmap:topicmap-workspace-point-of workspace)))
    (unwind-protect
         (progn
           (setf (symbol-function 'dreyeck/topicmap:topicmap-workspace-go-to)
                 (lambda (session id) (incf moves) (funcall go-to session id))
                 (symbol-function 'reading::follow-context-object)
                 (lambda (object) (error "Re-projection followed ~S" object)))
           (labels ((move (id)
                      (let* ((view (context-view context "Topicmap"))
                             (dom (plump:parse (views:view-html view)))
                             (sign (find id (plump:get-elements-by-tag-name dom "g")
                                         :key (lambda (e) (plump:attribute e "data-topic-id")) :test #'equal))
                             (reference (cdr (assoc (plump:attribute sign "id")
                                                    (views:view-references view) :test #'equal))))
                        (assert (uiop:string-prefix-p "action-" (plump:attribute sign "id")))
                        (assert (null (views:eval-thunk reference)))))
                    (render (projected history)
                      (let* ((current (reading::context-current-workspace context))
                             (view (context-view context "Topicmap"))
                             (dom (plump:parse (views:view-html view)))
                             (map (find "context" (plump:get-elements-by-tag-name dom "div")
                                        :key (lambda (e) (plump:attribute e "data-projection")) :test #'equal))
                             (marks (remove-if-not (lambda (e) (equal "true" (plump:attribute e "data-selected")))
                                                   (plump:get-elements-by-tag-name map "g")))
                             (point-view (reading::context-point-view context))
                             (panel (views:view-html point-view)))
                        (assert (eq workspace current))
                        (assert (eq workspace (reading::context-workspace context)))
                        (assert (equal c (dreyeck/topicmap:topicmap-workspace-point-of current)))
                        (assert (eq history (dreyeck/topicmap:topicmap-workspace-history-of current)))
                        (assert (eq projected (dreyeck/topicmap:topicmap-workspace-point-projected-p current)))
                        (assert (= (if projected 1 0) (length marks)))
                        (if projected
                            (progn
                              (assert (equal c (plump:attribute (first marks) "data-topic-id")))
                              (assert (search "Follow" panel))
                              (assert (member (dreyeck/topicmap:topicmap-workspace-current-object current)
                                              (mapcar #'cdr (views:view-references point-view)) :test #'eq)))
                            (progn
                              (assert (search c panel))
                              (assert (search "Not present in current projection" panel))
                              (dolist (operation '("Follow" "Inspect represented object" "Inspect Topicmap sign" "Relations at Point"))
                                (assert (not (search operation panel))))
                              (assert (null (views:view-references point-view)))))
                        (assert (= 2 moves)))))
             (move b) (move c)
             (let ((history (dreyeck/topicmap:topicmap-workspace-history-of workspace)))
               (assert (equal (list b a) history))
               (reading::select-context-event context 8)
               (render t history)
               (setf (reading::context-mode context) :delta)
               (render nil history)
               (assert (plusp (length (dreyeck/topicmap:topicmap-projection-topics-of
                                      (dreyeck/topicmap:topicmap-workspace-projection-of workspace)))))
               ;; Both real empty Deltas preserve the editing session and Point.
               (dolist (index '(6 2))
                 (reading::select-context-event context index)
                 (render nil history)
                 (assert (null (dreyeck/topicmap:topicmap-projection-topics-of
                                (dreyeck/topicmap:topicmap-workspace-projection-of workspace)))))
               (setf (reading::context-mode context) :state)
               (render t history)
               (setf (reading::context-mode context) :delta)
               (render nil history)
               (setf (reading::context-mode context) :state)
               (reading::select-context-event context 10)
               (render t history)
               (setf (reading::context-mode context) :delta)
               (render nil history)
               ;; The event page is present here, but must not replace absent C.
               (assert (dreyeck/topicmap:topicmap-projection-topic-by-id
                        (dreyeck/topicmap:topicmap-workspace-projection-of workspace) a))
               (setf (reading::context-mode context) :state)
               (render t history)
               (move d)
               (assert (= 3 moves))
               (assert (eq workspace (reading::context-current-workspace context)))
               (assert (equal d (dreyeck/topicmap:topicmap-workspace-point-of workspace)))
               (assert (eq history (cdr (dreyeck/topicmap:topicmap-workspace-history-of workspace))))
               (assert (equal (cons c history) (dreyeck/topicmap:topicmap-workspace-history-of workspace)))
               (let ((panel (views:view-html (reading::context-point-view context))))
                 (assert (search "Follow" panel))
                 (assert (search "Inspect represented object" panel))
                 (assert (not (search "Not present in current projection" panel)))))))
      (setf (symbol-function 'dreyeck/topicmap:topicmap-workspace-go-to) go-to
            (symbol-function 'reading::follow-context-object) follow)))
  (format t "~&PERSISTENT-WORKSPACE-PASS: same session, Point/history retained through time/mode, absent and empty projections, zero/one Cursor, fresh projected objects, no Follow or fallback, explicit D records C only.~%"))

(defun check-attribution-negative-control ()
  (let ((context (reading:federated-context)))
    (context-native-fixture
     context
     (lambda ()
       (loop for cursor from 0 to 9
             do (reading::select-context-event context cursor)
                (dolist (mode '(:state :delta))
                  (setf (reading::context-mode context) mode)
                  (let ((projection (reading::context-projection context)))
                    (dolist (association (dreyeck/topicmap:topicmap-projection-associations-of projection))
                      (assert (null (getf (dreyeck/topicmap:topicmap-association-properties-of association) :attribution)))
                      (assert (not (search "Textual attribution"
                                           (views:view-html (context-view association "Evidence")))))))
                  (assert (not (search "Textual attribution"
                                       (views:view-html (context-view context "Topicmap"))))))))))
  (format t "~&ATTRIBUTION-NEGATIVE-CONTROL-PASS: cursors 0–9, State/Delta associations and Topicmap/Evidence views have no attribution.~%"))

(defun check-attribution-mutation-control ()
  ;; Trace the one interpreter as well as checking the result. A duplicated
  ;; textual test could also hide the mutated attribution, but must fail this
  ;; control because it bypasses the shared operation.
  (let* ((name 'reading::context-item-attribution)
         (interpreter (symbol-function name)) (calls nil))
    (unwind-protect
         (progn
           (setf (symbol-function name)
                 (lambda (item) (push item calls) (funcall interpreter item)))
           (let* ((context (reading:federated-context))
                  (page (reading::context-page context "jan-dewey"))
                  (action (find 1790877831968 (gethash "journal" (gethash "raw" page))
                                :key (lambda (entry) (gethash "date" entry))))
                  (item (gethash "item" action)))
             ;; DERIVE-FEDERATED-DATA must use the same interpreter. Its saved
             ;; observed link deliberately remains attributed after the mutation.
             (assert (member item calls :test #'eq))
             (assert (some (lambda (link) (gethash "attribution" link))
                           (gethash "links" (gethash "observed" (reading::context-data context)))))
             (assert (search " via Thompson" (gethash "text" item)))
             (setf (gethash "text" item)
                   (cl-ppcre:regex-replace " via Thompson" (gethash "text" item) ""))
             (assert (null (funcall interpreter item)))
             (context-native-fixture
              context
              (lambda ()
                (dolist (mode '(:state :delta))
                  (setf (reading::context-mode context) mode calls nil)
                  (let ((projection (reading::context-projection context)))
                    ;; Use the actual, already page-scoped item, not its bare ID.
                    (assert (find item (dreyeck/topicmap:topicmap-projection-associations-of projection)
                                  :key (lambda (association)
                                         (getf (dreyeck/topicmap:topicmap-association-properties-of association) :item))
                                  :test #'eq))
                    (assert (member item calls :test #'eq))
                    (dolist (association (dreyeck/topicmap:topicmap-projection-associations-of projection))
                      (assert (null (getf (dreyeck/topicmap:topicmap-association-properties-of association) :attribution)))
                      (assert (not (search "Textual attribution"
                                           (views:view-html (context-view association "Evidence")))))))
                  ;; Warm the map caches so calls from association construction
                  ;; cannot conceal an independent interpreter in the view.
                  (reading::context-rendering context :context)
                  (reading::context-rendering context :temporal)
                  (setf calls nil)
                  (assert (not (search "Textual attribution"
                                       (views:view-html (context-view context "Topicmap")))))
                  (assert (member item calls :test #'eq)))))))
      (setf (symbol-function name) interpreter)))
  (format t "~&ATTRIBUTION-MUTATION-CONTROL-PASS: removing the raw attribution suppresses association/Topicmap/Evidence attribution despite stale observed metadata; derivation, association and view decisions use the single interpreter.~%"))
