(defpackage #:dreyeck/work/trails-rendered-reading/tests
  (:use #:cl)
  (:local-nicknames (#:reading #:dreyeck/work/trails-rendered-reading)
                    (#:views #:html-inspector-views))
  (:export #:run-tests))
(in-package #:dreyeck/work/trails-rendered-reading/tests)

(defparameter *categories* '(:observed :derived :inferred :hypothesized))

(defun render-page (book title)
  (let* ((page (hyperbook:find-page book title :signal-error? t))
         (view (find "Content" (views:all-views page)
                     :key #'views:view-title :test #'equal)))
    (assert view)
    (views:view-html view)
    (assert (notany (lambda (reference) (typep (cdr reference) 'condition))
                    (views:view-references view)))
    (values page view)))

(defun record-by-id (evidence category id)
  (let ((matches (remove-if-not (lambda (record) (equal id (getf record :id)))
                                (getf evidence category))))
    (assert (= 1 (length matches)) () "~A ~S occurs ~D times" category id (length matches))
    (first matches)))

(defun all-ids (evidence)
  (loop for category in *categories*
        append (mapcar (lambda (record) (getf record :id)) (getf evidence category))))

(defun check-structure (evidence)
  "Ids are unique across categories, and every basis names a record that exists."
  (let ((ids (all-ids evidence)))
    (assert (every #'stringp ids))
    (assert (= (length ids) (length (remove-duplicates ids :test #'equal))))
    (dolist (category '(:derived :inferred :hypothesized))
      (dolist (record (getf evidence category))
        (assert (getf record :basis) () "~S has no basis" (getf record :id))
        (dolist (id (getf record :basis))
          (if (stringp id)
              (assert (member id ids :test #'equal) ()
                      "~S names missing basis ~S" (getf record :id) id)
              (resolve id)))))
    (dolist (record (getf evidence :inferred))
      (assert (member (getf record :verification)
                      '(:not-directly-observed :pending-runtime-check))))
    (dolist (record (getf evidence :hypothesized))
      (assert (eq :unverified (getf record :status))))))

(defun check-provenance (evidence)
  (check-structure evidence)
  (assert (eq :agent-observed (getf (getf evidence :provenance) :kind)))
  ;; The snippet was searched for and not found; nothing observed may claim it.
  (dolist (id '("mech-snippet-search" "solo-snippet-search" "phrase-search"))
    (assert (eql 0 (getf (record-by-id evidence :observed id) :hits))))
  (dolist (record (getf evidence :observed))
    (assert (not (eq :implementation-location (getf record :relation)))))
  (let ((location (record-by-id evidence :inferred "snippet-location")))
    (assert (eq :not-directly-observed (getf location :verification)))
    (assert (member "ward-statement" (getf location :basis) :test #'equal)))
  (let ((unresolved (getf evidence :unresolved)))
    (assert (find :not-public unresolved :key (lambda (r) (getf r :status))))))

(defun check-initial-state (evidence)
  (check-structure evidence)
  (let ((provenance (getf evidence :provenance)))
    (assert (eq :source-state (getf provenance :scope)))
    (assert (null (getf provenance :runtime-observed))))
  (let ((checkout (record-by-id evidence :observed "wiki-checkout"))
        (pin (record-by-id evidence :observed "pinned-mech-revision")))
    (assert (equal "47a9ca6b97597eedebe602bd80b8657978b813e3" (getf checkout :head)))
    (assert (eq t (getf checkout :clean)))
    (assert (null (getf pin :code-block-present))))
  (assert (eq :left-untouched
              (getf (record-by-id evidence :observed "dirty-mech-checkout") :disposition))))

(defun check-decision (decision)
  (let ((chosen (remove :chosen (getf decision :alternatives)
                        :key (lambda (a) (getf a :choice)) :test-not #'eq)))
    (assert (= 1 (length chosen)))
    (assert (equal "impure-environment-override" (getf (first chosen) :id))))
  (assert (find-if (lambda (b) (search "getBBox" (or (getf b :not-added) "")))
                   (getf decision :boundaries))))

(defun resolve (reference)
  "A cross-reading reference (READING CATEGORY ID) names exactly one record."
  (destructuring-bind (function category id) reference
    (record-by-id (funcall function) category id)))

(defun check-runtime (evidence)
  (check-structure evidence)
  (assert (eq :runtime-state (getf (getf evidence :provenance) :scope)))
  (let ((process (record-by-id evidence :observed "process")))
    ;; Runtime records do not claim a source revision for the process.
    (assert (null (getf process :commit)))
    (assert (null (getf process :head)))
    (assert (equal "127.0.0.1:3477" (getf process :listener)))
    (assert (null (getf process :personal-config-keys-present))))
  (let ((hashes (list (getf (record-by-id evidence :observed "local-mech-build") :sha256)
                      (getf (record-by-id evidence :observed "artifact") :mech-bundle-sha256)
                      (getf (record-by-id evidence :observed "served-assets") :mech-sha256)
                      (getf (record-by-id evidence :observed "browser-run") :browser-mech-sha256))))
    (assert (= 64 (length (first hashes))))
    (assert (every (lambda (h) (equal h (first hashes))) hashes)))
  (let ((render (record-by-id evidence :observed "render-two-aspects")))
    (assert (= 5 (length (getf render :nodes))))
    (assert (= 4 (length (getf render :edges))))
    (assert (every (lambda (edge) (equal "Trail" (second edge))) (getf render :edges))))
  (assert (eq :failed-attempt (getf (record-by-id evidence :observed "pane-popup-attempt") :kind)))
  (let ((confirmation (record-by-id evidence :derived "lock-governs-build-confirmed")))
    (resolve (getf confirmation :confirms))
    ;; The earlier inference is confirmed here, not rewritten there.
    (assert (eq :pending-runtime-check (getf (resolve (getf confirmation :confirms)) :verification)))))

(defun check-chain (chain)
  (let* ((stages (getf chain :stages))
         (boundary (remove :not-reproducible stages
                           :key (lambda (s) (getf s :status)) :test-not #'eq)))
    (assert (equal '(1 2 3 4 5 6) (mapcar (lambda (s) (getf s :stage)) stages)))
    (assert (equal '(:page-item :plugin-version :intermediate-representation
                     :runtime-transformation :rendered-result :interpretation-layer)
                   (mapcar (lambda (s) (getf s :name)) stages)))
    (assert (= 1 (length boundary)))
    (assert (eq (first boundary) (car (last stages))))
    (assert (= 5 (getf (getf chain :boundary) :after-stage)))
    (assert (equal "PUBLIC REPRODUCTION ENDS HERE" (getf (getf chain :boundary) :label)))
    (dolist (stage stages)
      (assert (getf stage :evidence))
      (mapc #'resolve (getf stage :evidence)))
    (dolist (stage (butlast stages))
      (assert (eq :reproduced (getf stage :status))))
    (let ((last (first boundary)))
      (assert (getf last :first-unreproducible-operation))
      (assert (member '(reading:provenance-evidence :observed "ward-statement")
                      (getf last :evidence) :test #'equal)))))

(defun check-operations (record)
  (assert (member "flake.lock" (getf record :not-changed) :test #'equal))
  (assert (member "getBBox lookup" (getf record :not-added) :test #'equal))
  (dolist (entry (getf record :files-modified))
    (assert (commit-id-p (getf entry :commit)))
    (assert (commit-id-p (getf entry :parent)))
    (assert (null (getf entry :pushed))))
  (assert (search "89c6d582" (getf record :record-history))))

(defun commit-id-p (string)
  (and (stringp string) (= 40 (length string))
       (every (lambda (c) (digit-char-p c 16)) string)))

(defun check-commit-record (evidence operations runtime)
  (check-structure evidence)
  (assert (eq :committed-source (getf (getf evidence :provenance) :scope)))
  (assert (null (getf (getf evidence :provenance) :rebuild-performed)))
  (let ((hyperdoc (record-by-id evidence :observed "hyperdoc-commit"))
        (wiki (record-by-id evidence :observed "wiki-commit"))
        (default (record-by-id evidence :observed "default-eval"))
        (override (record-by-id evidence :observed "override-eval"))
        (artifact (record-by-id runtime :observed "artifact")))
    (assert (commit-id-p (getf hyperdoc :commit)))
    (assert (commit-id-p (getf wiki :commit)))
    (assert (equal '("flake.nix") (getf wiki :files)))
    (assert (null (getf wiki :flake-lock-changed)))
    ;; The operations record points at the same commits.
    (let ((commits (mapcar (lambda (e) (getf e :commit)) (getf operations :files-modified))))
      (assert (member (getf hyperdoc :commit) commits :test #'equal))
      (assert (member (getf wiki :commit) commits :test #'equal)))
    ;; Runtime and committed source meet only through output-path identity.
    (assert (equal (getf override :out-path) (getf artifact :path)))
    (assert (equal (getf override :mech-source) (getf artifact :mech-input)))
    (assert (not (equal (getf default :out-path) (getf override :out-path))))
    (assert (search "wiki-plugin-mech-local" (getf override :mech-source)))
    (dolist (id '("original-commit-eval" "pure-eval-with-env" "impure-eval-without-env"))
      (assert (equal (getf default :mech-source)
                     (getf (record-by-id evidence :observed id) :mech-source))))
    (assert (equal "/nix/store/ib56gml232vfswinxwqw65cin4z98xsc-wiki-0.39.2"
                   (getf (record-by-id evidence :observed "result-link") :target)))))

(defun check-fresh (function)
  "Each call returns fresh data: mutating one result leaves the next intact."
  (let ((a (funcall function)) (b (funcall function)))
    (assert (equal a b))
    (setf (getf (first (getf a :observed)) :id) "mutated")
    (assert (equal b (funcall function)))))

(defun run-tests ()
  (check-provenance (reading:provenance-evidence))
  (check-initial-state (reading:initial-state))
  (check-decision (reading:integration-decision))
  (check-runtime (reading:runtime-verification))
  (check-chain (reading:provenance-chain))
  (check-operations (reading:operations-record))
  (check-commit-record (reading:commit-record) (reading:operations-record)
                       (reading:runtime-verification))
  (check-fresh #'reading:commit-record)
  (check-fresh #'reading:provenance-evidence)
  (check-fresh #'reading:initial-state)
  (check-fresh #'reading:runtime-verification)
  (let ((book (hyperbook:find-hyperbook "dreyeck/work/reading" :signal-error? t)))
    (multiple-value-bind (landing view) (render-page book "Work Breakdown")
      (declare (ignore landing))
      (let ((page (render-page book "Trails Rendered public reproduction")))
        (assert (member page (mapcar #'cdr (views:view-references view)) :test #'eq))))
    (multiple-value-bind (page view) (render-page book "Trails Rendered public reproduction")
      (declare (ignore page))
      (let ((references (mapcar #'cdr (views:view-references view))))
        (dolist (evidence (list (reading:provenance-evidence)
                                (reading:initial-state)
                                (reading:integration-decision)
                                (reading:runtime-verification)
                                (reading:provenance-chain)
                                (reading:operations-record)
                                (reading:commit-record)))
          (assert (member evidence references :test #'equal))))))
  t)
