(defpackage #:dreyeck/work/trails-rendered-reading/tests
  (:use #:cl)
  (:local-nicknames (#:reading #:dreyeck/work/trails-rendered-reading)
                    (#:views #:html-inspector-views))
  (:export #:run-tests))
(in-package #:dreyeck/work/trails-rendered-reading/tests)

(defparameter *categories* '(:observed :derived :inferred :hypothesized))

(defun render-page (book title)
  (let* ((page (hyperbook:find-page book title :signal-error? t))
         (view (find "Content" (views:all-views page)
                     :key #'views:view-title :test #'equal)))
    (assert view)
    (views:view-html view)
    (assert (notany (lambda (reference) (typep (cdr reference) 'condition))
                    (views:view-references view)))
    (values page view)))

(defun record-by-id (evidence category id)
  (let ((matches (remove-if-not (lambda (record) (equal id (getf record :id)))
                                (getf evidence category))))
    (assert (= 1 (length matches)) () "~A ~S occurs ~D times" category id (length matches))
    (first matches)))

(defun all-ids (evidence)
  (loop for category in *categories*
        append (mapcar (lambda (record) (getf record :id)) (getf evidence category))))

(defun check-structure (evidence)
  "Ids are unique across categories, and every basis names a record that exists."
  (let ((ids (all-ids evidence)))
    (assert (every #'stringp ids))
    (assert (= (length ids) (length (remove-duplicates ids :test #'equal))))
    (dolist (category '(:derived :inferred :hypothesized))
      (dolist (record (getf evidence category))
        (assert (getf record :basis) () "~S has no basis" (getf record :id))
        (dolist (id (getf record :basis))
          (if (stringp id)
              (assert (member id ids :test #'equal) ()
                      "~S names missing basis ~S" (getf record :id) id)
              (resolve id)))))
    (dolist (record (getf evidence :inferred))
      (assert (member (getf record :verification)
                      '(:not-directly-observed :pending-runtime-check))))
    (dolist (record (getf evidence :hypothesized))
      (assert (eq :unverified (getf record :status))))))

(defun check-provenance (evidence)
  (check-structure evidence)
  (assert (eq :agent-observed (getf (getf evidence :provenance) :kind)))
  ;; The snippet was searched for and not found; nothing observed may claim it.
  (dolist (id '("mech-snippet-search" "solo-snippet-search" "phrase-search"))
    (assert (eql 0 (getf (record-by-id evidence :observed id) :hits))))
  (dolist (record (getf evidence :observed))
    (assert (not (eq :implementation-location (getf record :relation)))))
  (let ((location (record-by-id evidence :inferred "snippet-location")))
    (assert (eq :not-directly-observed (getf location :verification)))
    (assert (member "ward-statement" (getf location :basis) :test #'equal)))
  (let ((unresolved (getf evidence :unresolved)))
    (assert (find :not-public unresolved :key (lambda (r) (getf r :status))))))

(defun check-initial-state (evidence)
  (check-structure evidence)
  (let ((provenance (getf evidence :provenance)))
    (assert (eq :source-state (getf provenance :scope)))
    (assert (null (getf provenance :runtime-observed))))
  (let ((checkout (record-by-id evidence :observed "wiki-checkout"))
        (pin (record-by-id evidence :observed "pinned-mech-revision")))
    (assert (equal "47a9ca6b97597eedebe602bd80b8657978b813e3" (getf checkout :head)))
    (assert (eq t (getf checkout :clean)))
    (assert (null (getf pin :code-block-present))))
  (assert (eq :left-untouched
              (getf (record-by-id evidence :observed "dirty-mech-checkout") :disposition))))

(defun check-decision (decision)
  (let ((chosen (remove :chosen (getf decision :alternatives)
                        :key (lambda (a) (getf a :choice)) :test-not #'eq)))
    (assert (= 1 (length chosen)))
    (assert (equal "impure-environment-override" (getf (first chosen) :id))))
  (assert (find-if (lambda (b) (search "getBBox" (or (getf b :not-added) "")))
                   (getf decision :boundaries))))

(defun resolve (reference)
  "A cross-reading reference (READING CATEGORY ID) names exactly one record."
  (destructuring-bind (function category id) reference
    (record-by-id (funcall function) category id)))

(defun check-runtime (evidence)
  (check-structure evidence)
  (assert (eq :runtime-state (getf (getf evidence :provenance) :scope)))
  (let ((process (record-by-id evidence :observed "process")))
    ;; Runtime records do not claim a source revision for the process.
    (assert (null (getf process :commit)))
    (assert (null (getf process :head)))
    (assert (equal "127.0.0.1:3477" (getf process :listener)))
    (assert (null (getf process :personal-config-keys-present))))
  (let ((hashes (list (getf (record-by-id evidence :observed "local-mech-build") :sha256)
                      (getf (record-by-id evidence :observed "artifact") :mech-bundle-sha256)
                      (getf (record-by-id evidence :observed "served-assets") :mech-sha256)
                      (getf (record-by-id evidence :observed "browser-run") :browser-mech-sha256))))
    (assert (= 64 (length (first hashes))))
    (assert (every (lambda (h) (equal h (first hashes))) hashes)))
  (let ((render (record-by-id evidence :observed "render-two-aspects")))
    (assert (= 5 (length (getf render :nodes))))
    (assert (= 4 (length (getf render :edges))))
    (assert (every (lambda (edge) (equal "Trail" (second edge))) (getf render :edges))))
  (assert (eq :failed-attempt (getf (record-by-id evidence :observed "pane-popup-attempt") :kind)))
  (let ((confirmation (record-by-id evidence :derived "lock-governs-build-confirmed")))
    (resolve (getf confirmation :confirms))
    ;; The earlier inference is confirmed here, not rewritten there.
    (assert (eq :pending-runtime-check (getf (resolve (getf confirmation :confirms)) :verification)))))

(defun check-chain (chain)
  (let* ((stages (getf chain :stages))
         (boundary (remove :not-reproducible stages
                           :key (lambda (s) (getf s :status)) :test-not #'eq)))
    (assert (equal '(1 2 3 4 5 6) (mapcar (lambda (s) (getf s :stage)) stages)))
    (assert (equal '(:page-item :plugin-version :intermediate-representation
                     :runtime-transformation :rendered-result :interpretation-layer)
                   (mapcar (lambda (s) (getf s :name)) stages)))
    (assert (= 1 (length boundary)))
    (assert (eq (first boundary) (car (last stages))))
    (assert (= 5 (getf (getf chain :boundary) :after-stage)))
    (assert (equal "PUBLIC REPRODUCTION ENDS HERE" (getf (getf chain :boundary) :label)))
    (dolist (stage stages)
      (assert (getf stage :evidence))
      (mapc #'resolve (getf stage :evidence)))
    (dolist (stage (butlast stages))
      (assert (eq :reproduced (getf stage :status))))
    (let ((last (first boundary)))
      (assert (getf last :first-unreproducible-operation))
      (assert (member '(reading:provenance-evidence :observed "ward-statement")
                      (getf last :evidence) :test #'equal)))))

(defun check-operations (record)
  (assert (member "flake.lock" (getf record :not-changed) :test #'equal))
  (assert (member "getBBox lookup" (getf record :not-added) :test #'equal))
  (dolist (entry (getf record :files-modified))
    (assert (commit-id-p (getf entry :commit)))
    (assert (commit-id-p (getf entry :parent)))
    (assert (null (getf entry :pushed))))
  (assert (search "89c6d582" (getf record :record-history))))

(defun commit-id-p (string)
  (and (stringp string) (= 40 (length string))
       (every (lambda (c) (digit-char-p c 16)) string)))

(defun check-commit-record (evidence operations runtime)
  (check-structure evidence)
  (assert (eq :committed-source (getf (getf evidence :provenance) :scope)))
  (assert (null (getf (getf evidence :provenance) :rebuild-performed)))
  (let ((hyperdoc (record-by-id evidence :observed "hyperdoc-commit"))
        (wiki (record-by-id evidence :observed "wiki-commit"))
        (default (record-by-id evidence :observed "default-eval"))
        (override (record-by-id evidence :observed "override-eval"))
        (artifact (record-by-id runtime :observed "artifact")))
    (assert (commit-id-p (getf hyperdoc :commit)))
    (assert (commit-id-p (getf wiki :commit)))
    (assert (equal '("flake.nix") (getf wiki :files)))
    (assert (null (getf wiki :flake-lock-changed)))
    ;; The operations record points at the same commits.
    (let ((commits (mapcar (lambda (e) (getf e :commit)) (getf operations :files-modified))))
      (assert (member (getf hyperdoc :commit) commits :test #'equal))
      (assert (member (getf wiki :commit) commits :test #'equal)))
    ;; Runtime and committed source meet only through output-path identity.
    (assert (equal (getf override :out-path) (getf artifact :path)))
    (assert (equal (getf override :mech-source) (getf artifact :mech-input)))
    (assert (not (equal (getf default :out-path) (getf override :out-path))))
    (assert (search "wiki-plugin-mech-local" (getf override :mech-source)))
    (dolist (id '("original-commit-eval" "pure-eval-with-env" "impure-eval-without-env"))
      (assert (equal (getf default :mech-source)
                     (getf (record-by-id evidence :observed id) :mech-source))))
    (assert (equal "/nix/store/ib56gml232vfswinxwqw65cin4z98xsc-wiki-0.39.2"
                   (getf (record-by-id evidence :observed "result-link") :target)))))

(defun check-integration (evidence)
  (check-structure evidence)
  (assert (eq :integration (getf (getf evidence :provenance) :scope)))
  (flet ((field (id key) (getf (record-by-id evidence :observed id) key)))
    (let ((trails "3b9d053ad25b19a7566eab87ade29f2cbb935d70")
          (merge (field "authoritative-merge" :commit)))
      ;; Tested integration is not authoritative integration.
      (assert (commit-id-p merge))
      (assert (not (equal merge (field "rehearsal-1" :commit))))
      (assert (not (equal merge (field "rehearsal-2" :commit))))
      (dolist (id '("rehearsal-1" "rehearsal-2" "authoritative-merge"))
        (assert (equal trails (second (field id :parents)))))
      ;; Rehearsal 1 sat on the tip that later moved; rehearsal 2 and the merge on the new tip.
      (assert (equal (first (field "rehearsal-1" :parents)) (field "recon-authoritative-tip" :commit)))
      (assert (equal (field "authoritative-movement" :from) (field "recon-authoritative-tip" :commit)))
      (assert (equal (first (field "rehearsal-2" :parents)) (field "authoritative-movement" :to)))
      (assert (equal (first (field "authoritative-merge" :parents)) (field "pre-merge-check" :head)))
      (assert (equal (field "authoritative-merge" :tree) (field "rehearsal-2" :tree)))
      (assert (not (equal (field "authoritative-merge" :tree) (field "rehearsal-1" :tree))))
      (assert (eq :historical-evidence-only
                  (getf (record-by-id evidence :derived "rehearsal-1-not-executed") :status)))
      ;; The rejected alternative stays rejected and removed.
      (assert (equal '(:worktree t :branch t) (field "rebase-alternative" :removed)))
      ;; Publication is a verified fast-forward from the pre-merge tip to the merge.
      (assert (equal (field "merge-publication" :before) (field "pre-merge-check" :github)))
      (assert (equal (field "merge-publication" :after) merge))
      (assert (eq t (field "merge-publication" :fast-forward)))
      ;; Every suite passed after the final merge.
      (assert (every (lambda (r) (eq :pass (second r))) (field "final-merge-tests" :results)))
      (assert (= 3 (length (field "final-merge-tests" :results))))
      ;; The witnesses the record cites still agree with the earlier readings.
      (assert (member trails (getf (record-by-id evidence :derived "provenance-references-valid") :contains)
                      :test #'equal))
      (assert (equal (field "override-witness-recheck" :out-path)
                     (getf (record-by-id (reading:runtime-verification) :observed "artifact") :path)))
      (assert (equal (field "wiki-publication" :after)
                     (getf (record-by-id (reading:commit-record) :observed "wiki-commit") :commit)))))
  ;; The reproduction boundary is unchanged by integration.
  (assert (equal "PUBLIC REPRODUCTION ENDS HERE"
                 (getf (getf (reading:provenance-chain) :boundary) :label))))

(defun check-evidence-refs (evidence integration)
  (check-structure evidence)
  (dolist (pair '(("rehearsal-1-tag" "rehearsal-1") ("rehearsal-2-tag" "rehearsal-2")))
    (destructuring-bind (tag-id rehearsal-id) pair
      (let ((tag (record-by-id evidence :observed tag-id))
            (rehearsal (record-by-id integration :observed rehearsal-id)))
        ;; Each tag points at exactly the rehearsal commit the integration record names.
        (assert (equal (getf tag :commit) (getf rehearsal :commit)))
        (assert (equal (getf tag :cites)
                       (list 'reading:integration-record :observed rehearsal-id)))
        (assert (search "NOT an authoritative" (getf tag :message-says)))
        (assert (search "evidence/trails-rendered-merge-rehearsal-" (getf tag :tag)))
        ;; A rehearsal tag never names the authoritative merge.
        (assert (not (equal (getf tag :commit)
                            (getf (record-by-id integration :observed "authoritative-merge") :commit)))))))
  (let ((home (record-by-id evidence :observed "trails-commits-home")))
    (assert (equal (getf (record-by-id integration :observed "trails-branch") :commits)
                   (getf home :commits)))))

(defun check-codeberg-follow-up (evidence integration)
  (check-structure evidence)
  (let ((earlier (record-by-id evidence :observed "earlier-codeberg-observation"))
        (now (record-by-id evidence :observed "codeberg-tip"))
        (github (record-by-id evidence :observed "github-tip"))
        (parent (record-by-id evidence :observed "github-tip-parent"))
        (behind (record-by-id evidence :derived "codeberg-one-commit-behind"))
        (publication (record-by-id evidence :observed "b75b2560-publication")))
    ;; The earlier observation is cited, not rewritten.
    (assert (equal (getf earlier :commit)
                   (getf (record-by-id integration :observed "codeberg-state") :commit)))
    (assert (equal (getf earlier :recorded-as)
                   (list 'reading:integration-record :observed "codeberg-state")))
    (assert (not (equal (getf earlier :commit) (getf now :commit))))
    ;; One commit behind: the GitHub tip's parent is the Codeberg tip.
    (assert (equal (getf parent :commit) (getf github :commit)))
    (assert (equal (getf parent :parent) (getf now :commit)))
    (assert (equal (getf behind :missing) (list (getf github :commit))))
    (assert (eql 0 (getf (record-by-id evidence :observed "session-codeberg-pushes") :codeberg-pushes)))
    ;; The actor is inferred at most, and left unresolved.
    (assert (eq :not-directly-observed
                (getf (record-by-id evidence :inferred "external-codeberg-publication") :verification)))
    (assert (find :actor-and-mechanism (getf evidence :unresolved)
                  :key (lambda (r) (getf r :relation))))
    ;; The failed first push keeps an unestablished cause; no guessed cause is recorded.
    (let ((attempt-1 (first (getf publication :attempts))))
      (assert (eq :failed (getf attempt-1 :result)))
      (assert (eq :not-established (getf attempt-1 :cause))))
    (assert (not (search "transient" (string-downcase (prin1-to-string evidence)))))))

(defun check-fresh (function)
  "Each call returns fresh data: mutating one result leaves the next intact."
  (let ((a (funcall function)) (b (funcall function)))
    (assert (equal a b))
    (setf (getf (first (getf a :observed)) :id) "mutated")
    (assert (equal b (funcall function)))))

(defun items-view (object)
  (let ((view (find "Items" (views:all-views object)
                    :key #'views:view-title :test #'equal)))
    (assert view () "No navigable Items view for ~S" object)
    (views:view-html view)
    view))

(defun check-inspector-child (parent child)
  "Rendering the parent's Items view must expose the actual child object."
  (assert (member child (mapcar #'cdr (views:view-references (items-view parent)))
                  :test #'eq)))

(defun check-solo-batch ()
  (let* ((batch (reading:solo-batch))
         (sources (gethash "sources" batch))
         (source (aref sources 0))
         (aspects (gethash "aspects" source))
         (provenance (reading:solo-batch-provenance))
         (capture (getf provenance :capture)))
    ;; Pin the observed bytes, rather than regenerating a source-derived fixture.
    (assert (equal (getf capture :payload-sha256)
                   (ironclad:byte-array-to-hex-string
                    (ironclad:digest-file
                     :sha256 (asdf:system-relative-pathname
                              "dreyeck/work/reading" (getf capture :payload-file))))))
    (assert (= 3 (hash-table-count batch)))
    (assert (equal "batch" (gethash "type" batch)))
    (assert (equal (getf capture :page-key) (gethash "pageKey" batch)))
    (assert (and (vectorp sources) (= 1 (length sources))))
    (assert (equal "Trails Rendered" (gethash "source" source)))
    (assert (and (vectorp aspects) (= 2 (length aspects))))
    (assert (equal '("trail 1" "trail 2")
                   (map 'list (lambda (aspect) (gethash "name" aspect)) aspects)))
    (check-inspector-child batch sources)
    (check-inspector-child sources source)
    (check-inspector-child source aspects)
    (loop for aspect across aspects
          for names in '(("Susan" "John" "Reflective") ("Jean" "Dorothy" "Reflective"))
          do (assert (= 2 (hash-table-count aspect)))
             ;; Solo adds label after receiving the message; it must be absent here.
             (assert (not (nth-value 1 (gethash "label" aspect))))
             (check-inspector-child aspects aspect)
             (check-inspector-child aspect (gethash "name" aspect))
             (let* ((graph (gethash "graph" aspect))
                    (nodes (gethash "nodes" graph))
                    (rels (gethash "rels" graph)))
               (assert (and (vectorp nodes) (= 3 (length nodes))))
               (assert (and (vectorp rels) (= 2 (length rels))))
               (check-inspector-child aspect graph)
               (check-inspector-child graph nodes)
               (check-inspector-child graph rels)
               (loop for node across nodes for name in names
                     do (assert (search name (gethash "name" (gethash "props" node))))
                        (assert (find #\Newline (gethash "name" (gethash "props" node))))
                        (assert (vectorp (gethash "in" node)))
                        (assert (vectorp (gethash "out" node)))
                        (check-inspector-child nodes node)
                        (check-inspector-child node (gethash "props" node)))
               (assert (equalp #() (gethash "in" (aref nodes 0))))
               (assert (equalp #(0) (gethash "out" (aref nodes 0))))
               (assert (equalp #(0) (gethash "in" (aref nodes 1))))
               (assert (equalp #(1) (gethash "out" (aref nodes 1))))
               (assert (equalp #(1) (gethash "in" (aref nodes 2))))
               (assert (equalp #() (gethash "out" (aref nodes 2))))
               (loop for rel across rels for from from 0
                     do (assert (equal "Trail" (gethash "type" rel)))
                        (assert (= from (gethash "from" rel)))
                        (assert (= (1+ from) (gethash "to" rel)))
                        (assert (hash-table-p (gethash "props" rel)))
                        (assert (zerop (hash-table-count (gethash "props" rel))))
                        (check-inspector-child rels rel))))
    (assert (eq :observed-runtime-value (getf provenance :kind)))
    (assert (eq :debugger-breakpoint-before-first-mutation (getf capture :method)))
    (assert (getf capture :event-source-is-opener))
    (assert (= 47 (getf capture :line)))
    (assert (null (getf capture :plugin-source-changes)))
    (assert (getf capture :breakpoint-removed))
    (assert (equal "6405b752d1739af0" (getf (getf provenance :source-page) :mech-item-id)))
    (assert (equal "0.1.48-3" (getf (getf provenance :environment) :mech-version)))
    (assert (equal "0.1.30-1" (getf (getf provenance :environment) :solo-version)))
    ;; Each inspection is independent, even at nested mutable fields.
    (let ((fresh (reading:solo-batch)))
      (assert (equalp batch fresh))
      (setf (gethash "name" (aref aspects 0)) "mutated")
      (setf (gethash "props" (aref (gethash "rels" (gethash "graph" (aref aspects 1))) 0)) nil)
      (assert (equalp fresh (reading:solo-batch))))
    ;; The captured representation cannot depend on the caller's JSON defaults.
    (let ((shasht:*read-default-object-format* :plist)
          (shasht:*read-default-array-format* :list))
      (assert (hash-table-p (reading:solo-batch)))
      (assert (vectorp (gethash "sources" (reading:solo-batch)))))))

(defun run-tests ()
  (check-solo-batch)
  (check-provenance (reading:provenance-evidence))
  (check-initial-state (reading:initial-state))
  (check-decision (reading:integration-decision))
  (check-runtime (reading:runtime-verification))
  (check-chain (reading:provenance-chain))
  (check-operations (reading:operations-record))
  (check-commit-record (reading:commit-record) (reading:operations-record)
                       (reading:runtime-verification))
  (check-fresh #'reading:commit-record)
  (check-integration (reading:integration-record))
  (check-fresh #'reading:integration-record)
  (check-evidence-refs (reading:evidence-refs) (reading:integration-record))
  (check-fresh #'reading:evidence-refs)
  (check-codeberg-follow-up (reading:codeberg-follow-up) (reading:integration-record))
  (check-fresh #'reading:codeberg-follow-up)
  (check-fresh #'reading:provenance-evidence)
  (check-fresh #'reading:initial-state)
  (check-fresh #'reading:runtime-verification)
  (let ((book (hyperbook:find-hyperbook "dreyeck/work/reading" :signal-error? t)))
    (multiple-value-bind (landing view) (render-page book "Work Breakdown")
      (declare (ignore landing))
      (let ((page (render-page book "Trails Rendered public reproduction")))
        (assert (member page (mapcar #'cdr (views:view-references view)) :test #'eq))))
    (multiple-value-bind (page view) (render-page book "Trails Rendered public reproduction")
      (declare (ignore page))
      (let ((references (mapcar #'cdr (views:view-references view))))
        (dolist (evidence (list (reading:provenance-evidence)
                                (reading:initial-state)
                                (reading:integration-decision)
                                (reading:runtime-verification)
                                (reading:provenance-chain)
                                (reading:operations-record)
                                (reading:commit-record)
                                (reading:integration-record)
                                (reading:evidence-refs)
                                (reading:codeberg-follow-up)
                                (reading:solo-batch)
                                (reading:solo-batch-provenance)))
          (assert (member evidence references :test #'equalp)))
        (assert (search "Inspect the SOLO batch" (views:view-html view)))
        (assert (search "Inspect the batch provenance" (views:view-html view))))))
  (format t "~&TRAILS-RENDERED-SOLO-BATCH-PASS: captured bytes, nested arrays/objects, pre-mutation payload, fresh values, provenance and native inspector references through both graphs; page links resolve.~%")
  t)
