;;;; One qualified Work -> Constraint relation. Durable warrants are data,
;;;; separately validated from snapshot-bound operation requests.
(in-package #:dreyeck/work/reading)

(export '(addresses-creation-request addresses-read-set addresses-warrant
          qualified-addresses-bridge bridge-warrant bridge-occurrence bridge-annotation-end
          qualified-bridges resolve-addresses-bridge evidence-neighborhood
          addresses-qualification-error stale-addresses-bridge addresses-stale-reason
          relationship-insertion-position addresses-authority-descriptor))

(defparameter +addresses-version+ "addresses-v1")
(defparameter +addresses-annotation+ "<!--work-addresses-warrant:v1:")

(define-condition addresses-qualification-error (error)
  ((reason :initarg :reason :reader addresses-stale-reason))
  (:report (lambda (c s) (format s "Malformed addresses qualification: ~A" (addresses-stale-reason c)))))
(define-condition stale-addresses-bridge (error)
  ((reason :initarg :reason :reader addresses-stale-reason))
  (:report (lambda (c s) (format s "Stale addresses bridge: ~A" (addresses-stale-reason c)))))
(defun %bad-addresses (format-control &rest args)
  (error 'addresses-qualification-error :reason (apply #'format nil format-control args)))
(defun %stale-addresses (format-control &rest args)
  (error 'stale-addresses-bridge :reason (apply #'format nil format-control args)))

(defun %object (&rest fields)
  (let ((object (make-hash-table :test 'equal)))
    (loop for (key value) on fields by #'cddr do (setf (gethash key object) value)) object))
(defun %field (object key)
  (unless (hash-table-p object) (%bad-addresses "Expected object for ~A" key))
  (multiple-value-bind (value present) (gethash key object)
    (unless present (%bad-addresses "Missing field ~A" key)) value))
(defun %keys (object keys)
  (unless (and (hash-table-p object) (= (hash-table-count object) (length keys))
               (every (lambda (key) (nth-value 1 (gethash key object))) keys))
    (%bad-addresses "Unexpected object fields; required ~S" keys)))
(defun %string-field (object key)
  (let ((value (%field object key)))
    (unless (and (stringp value) (plusp (length value))) (%bad-addresses "Invalid ~A" key)) value))
(defun %range (object key)
  (let ((range (%field object key)))
    (unless (and (vectorp range) (= 2 (length range))
                 (every (lambda (n) (and (integerp n) (not (minusp n)))) range)
                 (< (aref range 0) (aref range 1)))
      (%bad-addresses "Invalid ~A range" key))
    (cons (aref range 0) (aref range 1))))
(defun %validate-fragment (object range-key text-key)
  (let ((range (%range object range-key)) (text (%string-field object text-key)))
    (unless (= (- (cdr range) (car range)) (length text))
      (%bad-addresses "Range/text length disagreement for ~A" range-key))))

(defun %page-path (page)
  (let ((file (hyperdoc:file-of page)))
    (truename (if (pathnamep file) file (asdf:component-pathname file)))))
(defun addresses-authority-descriptor (page)
  (%object "book" (hyperbook:id-of (hyperbook:hyperbook-of page))
           "page" (hyperbook:id-of page) "file" (namestring (%page-path page))))
(defun %validate-authority (descriptor)
  (%keys descriptor '("book" "page" "file"))
  (dolist (key '("book" "page" "file")) (%string-field descriptor key)))
(defun %same-authority (a b)
  (every (lambda (key) (equal (%field a key) (%field b key))) '("book" "page" "file")))
(defun %resolve-authority (descriptor)
  (handler-case
      (let ((page (work-page (%field descriptor "page") (%field descriptor "book"))))
        (unless (%same-authority descriptor (addresses-authority-descriptor page))
          (%stale-addresses "Authority mapping changed for ~A" (%field descriptor "page"))) page)
    (stale-addresses-bridge (c) (error c))
    (error (c) (%stale-addresses "Authority unavailable: ~A" c))))

(defun %dom (snapshot)
  (let ((plump:*tag-dispatchers* plump:*html-tags*)) (plump:parse snapshot)))
(defun %entry-range (snapshot occurrence)
  "Find the structurally enclosing LI, using the physical scanner address."
  (let ((start (car (topic-occurrence-element-range occurrence)))
        (stack nil) (answer nil))
    (%scan-tags snapshot
      (lambda (position name attributes end)
        (declare (ignore attributes end))
        (when (string= name "li") (push position stack)))
      (lambda (position end)
        (when (%end-tag-p snapshot position end "li")
          (let ((open (pop stack)))
            (when (and open (<= open start) (< start end) (null answer))
              (setf answer (cons open (1+ end))))))))
    (unless answer (%stale-addresses "Topic has no complete declaration LI")) answer))
(defun %node-at-occurrence (snapshot page occurrence)
  (let* ((nodes (remove-if-not (lambda (node) (plump:attribute node "data-topic"))
                                (plump:get-elements-by-tag-name (%dom snapshot) "a")))
         (occurrences (scan-work-topics snapshot page)))
    (%align-topics occurrences nodes snapshot)
    (or (loop for node in nodes for o in occurrences
              when (equal (topic-occurrence-element-range o) (topic-occurrence-element-range occurrence))
                return node)
        (%stale-addresses "No structural Topic at recorded range"))))
(defun %exact-kind-p (snapshot occurrence kind)
  (multiple-value-bind (name attributes end)
      (%start-tag snapshot (car (topic-occurrence-element-range occurrence)))
    (declare (ignore name end))
    (let ((entries (remove "data-kind" attributes :key #'first :test-not #'string-equal)))
      (and (= 1 (length entries)) (equal "data-kind" (first (first entries)))
           (eql #\" (fifth (first entries))) (equal kind (second (first entries)))))))
(defun %observe-addresses-topic (occurrence kind)
  (let* ((snapshot (topic-occurrence-snapshot occurrence))
         (page (topic-occurrence-page occurrence))
         (anchor (topic-occurrence-element-range occurrence))
         (scope (%entry-range snapshot occurrence))
         (node (%node-at-occurrence snapshot page occurrence)))
    (unless (and (%exact-kind-p snapshot occurrence kind)
                 (equal kind (plump:attribute node "data-kind"))
                 (equal "li" (plump:tag-name (plump:parent node)))
                 (or (not (equal kind "relation"))
                     (and (equal "work:relation/addresses" (plump:attribute node "data-topic"))
                          (equal "Work Breakdown" (plump:attribute node "page"))
                          (or (null (plump:attribute node "hyperbook"))
                              (equal (hyperbook:id-of (hyperbook:hyperbook-of page))
                                     (plump:attribute node "hyperbook"))))))
      (%stale-addresses "Expected exact endpoint kind ~A in its own LI" kind))
    (%object "authority" (addresses-authority-descriptor page)
             "anchor" (vector (car anchor) (cdr anchor)) "anchorText" (subseq snapshot (car anchor) (cdr anchor))
             "scope" (vector (car scope) (cdr scope)) "scopeText" (subseq snapshot (car scope) (cdr scope))
             "topic" (topic-occurrence-topic occurrence) "kind" kind)))
(defun %validate-observation (observation kind)
  (%keys observation '("authority" "anchor" "anchorText" "scope" "scopeText" "topic" "kind"))
  (%validate-authority (%field observation "authority"))
  (%validate-fragment observation "anchor" "anchorText")
  (%validate-fragment observation "scope" "scopeText")
  (%string-field observation "topic")
  (unless (equal kind (%field observation "kind")) (%bad-addresses "Invalid recorded role ~A" kind))
  (let ((anchor (%range observation "anchor")) (scope (%range observation "scope")))
    (unless (<= (car scope) (car anchor) (cdr anchor) (cdr scope)) (%bad-addresses "Anchor outside definition"))
    (unless (equal (%field observation "anchorText")
                   (subseq (%field observation "scopeText") (- (car anchor) (car scope)) (- (cdr anchor) (car scope))))
      (%bad-addresses "Anchor text disagrees with definition text"))
    (let* ((text (%field observation "anchorText")) (occurrences (scan-work-topics text nil))
           (o (first occurrences)))
      (unless (and (= 1 (length occurrences))
                   (equal (topic-occurrence-element-range o) (cons 0 (length text)))
                   (equal (topic-occurrence-topic o) (%field observation "topic"))
                   (%exact-kind-p text o kind))
        (%bad-addresses "Recorded Topic/role disagrees with anchor text")))))

(defun validate-local-addresses-roles (topics from to)
  "The new contract's two roles, without altering any pre-existing relation."
  (flet ((kind (id)
           (let ((topic (find id topics :key #'tm:topicmap-topic-id-of :test #'equal)))
             (and topic (getf (tm:topicmap-topic-view-properties-of topic) :kind)))))
    (unless (and (equal "work item" (kind from)) (equal "constraint" (kind to)))
      (%bad-addresses "addresses requires source Work item and target Constraint"))))

(defclass qualified-addresses-bridge ()
  ((warrant :initarg :warrant :reader bridge-warrant)
   (occurrence :initarg :occurrence :reader bridge-occurrence)
   (annotation-end :initarg :annotation-end :reader bridge-annotation-end)))
(defclass addresses-creation-request (work-relationship-creation-request)
  ((read-set :initarg :read-set :reader addresses-read-set)
   (warrant :initarg :warrant :reader addresses-warrant)))
(defun qualified-bridges (projection)
  (getf (tm:topicmap-projection-view-properties-of projection) :qualified-bridges))

(defun %validate-warrant (warrant)
  (%keys warrant '("version" "coordinates" "owner" "source" "target" "contract" "statement" "from" "to" "relation"))
  (unless (and (equal +addresses-version+ (%field warrant "version"))
               (equal "utf-8/decoded-character/half-open/v1" (%field warrant "coordinates")))
    (%bad-addresses "Unsupported representation/coordinates"))
  (%validate-authority (%field warrant "owner"))
  (unless (and (equal "Work Breakdown" (%field (%field warrant "owner") "page"))
               (equal "Deriving HyperDoc Authoring Constraints" (%field (%field (%field warrant "target") "authority") "page"))
               (equal (%field (%field warrant "owner") "book")
                      (%field (%field (%field warrant "target") "authority") "book"))
               (equal "serialized-verified-effect" (%field warrant "to")))
    (%bad-addresses "Outside the bounded authority/Constraint case"))
  (loop for name in '("source" "target" "contract") for kind in '("work item" "constraint" "relation")
        do (%validate-observation (%field warrant name) kind))
  (let ((statement (%field warrant "statement")))
    (%keys statement '("range" "text"))
    (%validate-fragment statement "range" "text")
    (let* ((text (%field statement "text")) (occurrences (scan-work-relationships text nil))
           (nodes (plump:get-elements-by-tag-name (%dom text) "li")) (o (first occurrences)))
      (unless (and (= 1 (length occurrences)) (= 1 (length nodes))
                   (equal (relationship-occurrence-element-range o) (cons 0 (length text)))
                   (equal +addresses-version+ (plump:attribute (first nodes) "data-work-qualification"))
                   (equal (%field warrant "from") (relationship-occurrence-from o))
                   (equal (%field warrant "to") (relationship-occurrence-to o))
                   (equal (%field warrant "relation") (relationship-occurrence-relation o)))
        (%bad-addresses "Statement observation disagrees with fields"))))
  (unless (and (equal (%field warrant "from") (%field (%field warrant "source") "topic"))
               (equal (%field warrant "to") (%field (%field warrant "target") "topic"))
               (equal "work:relation/addresses" (%field warrant "relation"))
               (equal "work:relation/addresses" (%field (%field warrant "contract") "topic"))
               (%same-authority (%field warrant "owner") (%field (%field warrant "source") "authority"))
               (%same-authority (%field warrant "owner") (%field (%field warrant "contract") "authority")))
    (%bad-addresses "Inconsistent owner/endpoints/contract")) warrant)

(defun encode-addresses-warrant (warrant)
  (cl-base64:usb8-array-to-base64-string
   (sb-ext:string-to-octets (shasht:write-json warrant nil) :external-format :utf-8)))
(defun %decode-addresses-warrant (encoded)
  (handler-case
      (let* ((octets (cl-base64:base64-string-to-usb8-array encoded))
             (text (sb-ext:octets-to-string octets :external-format :utf-8))
             (warrant (shasht:read-json text)))
        (unless (equal encoded (encode-addresses-warrant warrant))
          (%bad-addresses "Warrant is not canonical Base64/JSON"))
        (%validate-warrant warrant))
    (addresses-qualification-error (c) (error c))
    (error (c) (%bad-addresses "Invalid data-only warrant: ~A" c))))

(defun ingest-addresses-bridges (snapshot page nodes occurrences)
  "Classify qualified rows before local endpoint validation. No foreign I/O.
The annotation belongs physically to its preceding row; its recorded ranges
are validated only by the durable resolver, so moved valid records stay inspectable."
  (declare (ignore page))
  (let ((records nil) (annotations nil))
    (loop for node in nodes for o in occurrences
          for version = (plump:attribute node "data-work-qualification")
          when version do
            (unless (equal version +addresses-version+) (%bad-addresses "Unknown qualification ~S" version))
            (multiple-value-bind (tag attributes end)
                (%start-tag snapshot (car (relationship-occurrence-element-range o)))
              (declare (ignore tag end))
              (let ((markers (remove "data-work-qualification" attributes :key #'first :test-not #'string-equal)))
                (unless (and (= 1 (length markers))
                             (equal "data-work-qualification" (first (first markers)))
                             (eql #\" (fifth (first markers))))
                  (%bad-addresses "Ambiguous/malformed qualification attribute"))))
            (let* ((end (cdr (relationship-occurrence-element-range o)))
                   (begin (position-if-not #'%space-p snapshot :start end)))
              (unless (and begin (eql begin (search +addresses-annotation+ snapshot :start2 begin)))
                (%bad-addresses "Qualified row lacks its separate warrant"))
              (let ((close (search "-->" snapshot :start2 (+ begin (length +addresses-annotation+)))))
                (unless close (%bad-addresses "Unterminated warrant annotation"))
                (push begin annotations)
                (push (make-instance 'qualified-addresses-bridge :occurrence o :annotation-end (+ close 3)
                         :warrant (%decode-addresses-warrant
                                   (subseq snapshot (+ begin (length +addresses-annotation+)) close))) records))))
    ;; Even unknown versions/orphan annotations must be an explicit diagnostic.
    (loop with prefix = "<!--work-addresses-warrant:" for start = 0 then (1+ here)
          for here = (search prefix snapshot :start2 start) while here
          unless (member here annotations) do (%bad-addresses "Orphan or unknown-version annotation"))
    (nreverse records)))

(defun relationship-insertion-position (snapshot page)
  (let* ((projection (project-work-breakdown snapshot :source page))
         (last (car (last (scan-work-relationships snapshot page))))
         (end (and last (cdr (relationship-occurrence-element-range last)))))
    (unless end (error "No relationship insertion anchor"))
    (loop for record in (qualified-bridges projection)
          when (equal (relationship-occurrence-element-range (bridge-occurrence record))
                      (relationship-occurrence-element-range last))
            do (setf end (bridge-annotation-end record))) end))

(defun %fresh-observed-topic (observation page snapshot projection)
  (let* ((anchor (%range observation "anchor")) (scope (%range observation "scope")))
    (dolist (pair '(("anchor" "anchorText") ("scope" "scopeText")))
      (let ((range (%range observation (first pair))))
        (unless (and (<= (cdr range) (length snapshot))
                     (equal (%field observation (second pair)) (subseq snapshot (car range) (cdr range))))
          (%stale-addresses "Changed or moved ~A observation for ~A" (first pair) (%field observation "topic")))))
    (let* ((o (find anchor (scan-work-topics snapshot page) :key #'topic-occurrence-element-range :test #'equal))
           (topic (and o (find anchor (tm:topicmap-projection-topics-of projection)
                             :key (lambda (topic) (topic-occurrence-element-range (topic-source-occurrence topic)))
                             :test #'equal))))
      (unless (and topic (%exact-kind-p snapshot o (%field observation "kind"))
                   (equal (%field observation "topic") (topic-occurrence-topic o))
                   (equal (%field observation "kind") (getf (tm:topicmap-topic-view-properties-of topic) :kind))
                   (equal scope (%entry-range snapshot o))
                   (equal "li" (plump:tag-name (plump:parent (%node-at-occurrence snapshot page o)))))
        (%stale-addresses "Structural/role mismatch at recorded Topic address")) topic)))

(defun %resolve-addresses-bridge (bridge &key sources)
  "Shared exact-address validation. SOURCES is only for private pre-effect
candidate verification; the public currentness resolver always reads files."
  (handler-case
      (let* ((w (%validate-warrant (bridge-warrant bridge)))
             (owner (%resolve-authority (%field w "owner")))
             (cache nil))
        (unless (eq owner (relationship-occurrence-page (bridge-occurrence bridge)))
          (%stale-addresses "Statement owner is remapped"))
        (labels ((read-authority (descriptor)
                   (let* ((page (%resolve-authority descriptor)) (entry (assoc page cache)))
                     (unless entry
                       (let* ((source (or (cdr (assoc page sources))
                                          (uiop:read-file-string (%page-path page) :external-format :utf-8)))
                              (projection (project-work-breakdown source :source page)))
                         (setf entry (list page source projection)) (push entry cache))) entry))
                 (topic (name)
                   (let* ((observation (%field w name)) (entry (read-authority (%field observation "authority"))))
                     (%fresh-observed-topic observation (first entry) (second entry) (third entry)))))
          (let* ((owner-entry (read-authority (%field w "owner"))) (snapshot (second owner-entry))
                 (range (%range (%field w "statement") "range"))
                 (statement (find range (scan-work-relationships snapshot owner)
                                  :key #'relationship-occurrence-element-range :test #'equal))
                 (current (find range (qualified-bridges (third owner-entry))
                                :key (lambda (b) (relationship-occurrence-element-range (bridge-occurrence b))) :test #'equal)))
            (unless (and statement current (<= (cdr range) (length snapshot))
                         (equal (%field (%field w "statement") "text") (subseq snapshot (car range) (cdr range)))
                         (equal (encode-addresses-warrant w) (encode-addresses-warrant (bridge-warrant current))))
              (%stale-addresses "Changed or moved relationship statement/warrant"))
            (let* ((from (topic "source")) (to (topic "target")) (contract (topic "contract"))
                   (association (tm:make-topicmap-association
                                 :id (format nil "work:~A:~A:~A" (%field w "from") (%field w "relation") (%field w "to"))
                                 :type (%field w "relation") :from (%field w "from") :to (%field w "to")
                                 :properties (list :source-occurrence statement :relation-contract contract :qualified-bridge current))))
              (values association from to cache)))))
    (stale-addresses-bridge (c) (error c))
    (error (c) (%stale-addresses "Source structure/authority invalid: ~A" c))))

(defun resolve-addresses-bridge (bridge)
  "Resolve the persisted warrant against its CURRENT registered source files.
Return the Association, exact fresh endpoint Topics and observed source set."
  (%resolve-addresses-bridge bridge))

(defun %addresses-read-set-current (request)
  (dolist (name '("owner" "source" "target" "contract"))
    (let ((observation (%field (addresses-warrant request) name)))
      (%resolve-authority (if (equal name "owner") observation (%field observation "authority")))))
  (dolist (entry (addresses-read-set request))
    (unless (and (eq (car entry) (%resolve-authority (addresses-authority-descriptor (car entry))))
                 (equal (cdr entry) (uiop:read-file-string (%page-path (car entry)) :external-format :utf-8)))
      (%stale-addresses "Complete request read set changed"))) t)
(defun request-addresses-bridge (selection to-topic)
  (handler-case
      (progn
        (unless (and (typep selection 'r:operation-request)
                     (eq (r:operation-request-operation selection) (w:create-relationship-operation))
                     (typep (r:operation-request-occurrence selection) 'work-topic-source-occurrence)
                     (typep to-topic 'work-topic) (topic-source-occurrence to-topic))
          (%stale-addresses "Not Create relationship selected on exact HTML occurrences"))
      (let* ((from (r:operation-request-occurrence selection)) (to (topic-source-occurrence to-topic))
             (owner (topic-occurrence-page from)) (foreign (topic-occurrence-page to))
             (snapshot (topic-occurrence-snapshot from)) (target-snapshot (topic-occurrence-snapshot to)))
        (unless (and (typep owner 'hyperdoc:html-page) (typep foreign 'hyperdoc:html-page)
                     (equal "Work Breakdown" (hyperbook:title-of owner))
                     (equal "Deriving HyperDoc Authoring Constraints" (hyperbook:title-of foreign))
                     (eq (hyperbook:hyperbook-of owner) (hyperbook:hyperbook-of foreign)))
          (%stale-addresses "Only the bounded Work/architecture authority pair is supported"))
        (unless (equal "serialized-verified-effect" (topic-occurrence-topic to))
          (%stale-addresses "Only Serialized verified effect is admitted by this bounded slice"))
        (resolve-work-topic-occurrence from) (resolve-work-topic-occurrence to)
        (let* ((projection (project-work-breakdown snapshot :source owner))
               (contract (resolve-relation-contract "work:relation/addresses" (tm:topicmap-projection-topics-of projection) "addresses"))
               (w (%object "version" +addresses-version+ "coordinates" "utf-8/decoded-character/half-open/v1"
                           "owner" (addresses-authority-descriptor owner)
                           "source" (%observe-addresses-topic from "work item")
                           "target" (%observe-addresses-topic to "constraint")
                           "contract" (%observe-addresses-topic (topic-source-occurrence contract) "relation")
                           "from" (topic-occurrence-topic from) "to" (topic-occurrence-topic to)
                           "relation" "work:relation/addresses")))
          ;; Foreign source also has to be structurally valid/unique.
          (project-work-breakdown target-snapshot :source foreign)
          (dolist (record (qualified-bridges projection))
            (when (and (equal (topic-occurrence-topic from) (%field (bridge-warrant record) "from"))
                       (equal (topic-occurrence-topic to) (%field (bridge-warrant record) "to")))
              (%stale-addresses "Qualified relationship already stated")))
          (make-instance 'addresses-creation-request :operation (w:create-relationship-operation)
                         :selection selection :from-occurrence from :to-occurrence to
                         :relation "work:relation/addresses" :authority-page owner :authority-snapshot snapshot
                         :read-set (list (cons owner snapshot) (cons foreign target-snapshot)) :warrant w))))
    (error (c) (error 'work-relationship-creation-refused :reason "addresses request refused" :cause c))))

(defun %neighborhood-occurrence (topic)
  (if (typep topic 'work-topic) (topic-source-occurrence topic)
      (getf (tm:topicmap-topic-view-properties-of topic) :source-occurrence)))
(defun %same-neighborhood-topic (a b)
  (let ((oa (%neighborhood-occurrence a)) (ob (%neighborhood-occurrence b)))
    (and oa ob (eq (topic-occurrence-page oa) (topic-occurrence-page ob))
         (equal (topic-occurrence-element-range oa) (topic-occurrence-element-range ob))
         (equal (getf (tm:topicmap-topic-view-properties-of a) :kind)
                (getf (tm:topicmap-topic-view-properties-of b) :kind))
         (let ((ra (topic-occurrence-element-range oa)) (rb (topic-occurrence-element-range ob)))
           (equal (subseq (topic-occurrence-snapshot oa) (car ra) (cdr ra))
                  (subseq (topic-occurrence-snapshot ob) (car rb) (cdr rb)))))))
(defun evidence-neighborhood (&key (page (work-page "Work Breakdown")))
  "Only warranted bridges contribute cross-edges; stale records stay inspectable.
Duplicate semantic IDs never merge different observed source declarations."
  (let* ((local (work-projection :page page)) (topics nil) (associations nil) (results nil))
    (dolist (bridge (qualified-bridges local))
      (handler-case
          (multiple-value-bind (edge from to sources) (resolve-addresses-bridge bridge)
            (let* ((foreign (topic-occurrence-page (topic-source-occurrence to)))
                   (entry (assoc foreign sources)) (projection (third entry))
                   (candidates (list from to)) (edges (list edge)))
              (dolist (evidence (tm:topicmap-projection-associations-of projection))
                (when (and (equal (tm:topicmap-topic-id-of to) (tm:topicmap-association-from-of evidence))
                           (equal "work:relation/evidenced-by" (tm:topicmap-association-type-of evidence)))
                  (let* ((milestone (tm:topicmap-projection-topic-by-id projection (tm:topicmap-association-to-of evidence)))
                         (node (%node-at-occurrence (second entry) foreign (topic-source-occurrence milestone)))
                         (hash (plump:attribute node "data-commit")))
                    (when hash
                      (let ((topic (dreyeck/work/authoring-architecture::%standing-for
                                     milestone (dreyeck/work/authoring-architecture::%commit hash))))
                        (setf (slot-value topic 'tm::view-properties)
                              (list* :source-occurrence (topic-source-occurrence milestone)
                                     (tm:topicmap-topic-view-properties-of topic)))
                        (push topic candidates) (push evidence edges))))))
              ;; Validate this complete contribution BEFORE publishing any edge.
              (tm::validate-topicmap-projection candidates edges)
              (dolist (topic candidates)
                (let ((old (find (tm:topicmap-topic-id-of topic) topics :key #'tm:topicmap-topic-id-of :test #'equal)))
                  (when (and old (not (%same-neighborhood-topic old topic)))
                    (%stale-addresses "Conflicting observed authorities for Topic ID ~A" (tm:topicmap-topic-id-of topic)))))
              (dolist (topic candidates) (pushnew topic topics :key #'tm:topicmap-topic-id-of :test #'equal))
              (dolist (association edges) (pushnew association associations :key #'tm:topicmap-association-id-of :test #'equal))
              (push (list :bridge bridge :status :current) results)))
        (error (c) (push (list :bridge bridge :status :stale :reason c) results))))
    (tm:make-topicmap-projection :source page :topics (nreverse topics) :associations (nreverse associations)
                                :view-properties (list :qualified-bridges (qualified-bridges local) :bridge-results (nreverse results)))))

(views:defview qualified-addresses-overview (bridge qualified-addresses-bridge)
  (views:html-view :title "Qualified addresses bridge" :priority 0
    (let ((result (handler-case (progn (resolve-addresses-bridge bridge) (list :status :current))
                    (error (c) (list :status :stale :reason c)))))
      (views:html
        (:p "Durable currentness checks exact addressed text. Old request occurrences remain bound to their full snapshots.")
        (loop for name in '("owner" "source" "target" "contract" "statement")
              for label in '("Statement authority" "Source observation" "Target observation" "Contract observation" "Statement observation")
              do (views:html (:p (views:esc label) ": " (views:object-ref (%field (bridge-warrant bridge) name)))))
        (:p "Currentness result: " (views:esc (string-downcase (symbol-name (getf result :status)))) " "
            (views:object-ref result :display "Inspect currentness result"))
        (when (getf result :reason)
          (views:html (:p "Stale reason: " (views:object-ref (getf result :reason)))))
        (:p "No whole-source provenance digests retained; full snapshots exist only in requests/plans.")))))
(views:defview qualified-work-records (projection tm:topicmap-projection)
  (when (qualified-bridges projection)
    (views:html-view :title "Qualified bridges" :priority 0
      (views:html (dolist (bridge (qualified-bridges projection))
                    (views:html (:p (views:object-ref bridge :display "Inspect qualified addresses bridge"))))))))
(views:defview addresses-request-read-set (request addresses-creation-request)
  (views:html-view :title "Addresses read set" :priority 0
    (views:html (dolist (entry (addresses-read-set request))
                  (views:html (:p (views:object-ref (car entry))
                                 (views:esc (format nil " — full observed snapshot: ~D characters" (length (cdr entry))))
                                 " " (views:object-ref (cdr entry) :display "Inspect full observed snapshot"))))
                (:p (views:object-ref (addresses-warrant request) :display "Inspect endpoint and contract observations")))))
