;;;; Live SHOP3 domain for selecting the ASDF owner of the DMX SQLite system.

(in-package #:dreyeck.dmx.workspace-selection)

;; Keep SHOP3 operator order: (:operator task preconditions delete-list add-list).
(defdomain dreyeck-dmx-workspace-selection
  ((:operator (!select-hyperdoc-dreyeck-owner)
    ((repo hyperdoc)
     (hyperdoc-owns-primary-dreyeck-asd)
     (desired-final-system dreyeck/dmx/sqlite)
     (asdf-slash-system-requires-primary-owner)
     (avoid-shadowing-dreyeck-asd)
     (keep-hyperdoc-core-virtually-unchanged)
     (extensions-belong-in-dreyeck))
    ()
    ((selected-workspace hyperdoc-dreyeck-owner)))

   (:operator (!select-hauptsache-local-owner)
    ((allow-hauptsache-local-owner))
    ()
    ((selected-workspace hauptsache-local-owner)))

   (:operator (!select-shared-dreyeck-source-tree)
    ((allow-shared-dreyeck-source-tree))
    ()
    ((selected-workspace shared-dreyeck-source-tree)))

   (:operator (!defer-for-more-evidence)
    ((more-evidence-required))
    ()
   ((selected-workspace deferred-for-more-evidence)))

   (:operator (!select-property-journal-sync)
    ((repo hyperdoc)
     (repo hauptsache)
     (hyperdoc-owns-primary-dreyeck-asd)
     (dreyeck-owns-dmx-sqlite)
     (hauptsache-depends-on-dreyeck-dmx-sqlite)
     (hauptsache-local-dmx-sqlite-removed)
     (property-journal-sync-gap-open)
     (recorder-wip-isolated)
     (old-hauptsache-property-journal-branch-historical)
     (avoid-recorder-replay-before-store-parity)
     (keep-hyperdoc-core-virtually-unchanged)
     (extensions-belong-in-dreyeck))
    ()
    ((selected-next-task property-journal-sync)))

   (:operator (!select-build-graph-recorder-replay)
    ((allow-build-graph-recorder-replay))
    ()
    ((selected-next-task build-graph-recorder-replay)))

   (:operator (!select-fedwiki-artifact-materialization)
    ((fedwiki-artifact-materialization-required))
    ()
    ((selected-next-task fedwiki-artifact-materialization)))

   (:operator (!defer-next-task-for-more-evidence)
    ((more-next-task-evidence-required))
    ()
    ((selected-next-task deferred-for-more-evidence)))

   (:method (select-dmx-sqlite-workspace)
    ((repo hyperdoc)
     (repo hauptsache)
     (hyperdoc-owns-primary-dreyeck-asd)
     (hauptsache-has-local-system hauptsache-dmx-sqlite)
     (desired-final-system dreyeck/dmx/sqlite)
     (asdf-slash-system-requires-primary-owner)
     (avoid-shadowing-dreyeck-asd)
     (keep-hyperdoc-core-virtually-unchanged)
     (extensions-belong-in-dreyeck)
     (main-has-working-kioskbeerli-baseline)
     (recorder-wip-isolated)
     (property-journal-sync-plan-exists))
    ((!select-hyperdoc-dreyeck-owner)))

   (:method (select-dmx-sqlite-workspace)
    ((allow-hauptsache-local-owner))
    ((!select-hauptsache-local-owner)))

   (:method (select-dmx-sqlite-workspace)
    ((allow-shared-dreyeck-source-tree))
    ((!select-shared-dreyeck-source-tree)))

   (:method (select-dmx-sqlite-workspace)
    ((more-evidence-required))
    ((!defer-for-more-evidence)))

   (:method (select-dmx-sqlite-next-task)
    ((repo hyperdoc)
     (repo hauptsache)
     (hyperdoc-owns-primary-dreyeck-asd)
     (dreyeck-owns-dmx-sqlite)
     (hauptsache-depends-on-dreyeck-dmx-sqlite)
     (hauptsache-local-dmx-sqlite-removed)
     (property-journal-sync-gap-open)
     (recorder-wip-isolated)
     (old-hauptsache-property-journal-branch-historical)
     (avoid-recorder-replay-before-store-parity)
     (keep-hyperdoc-core-virtually-unchanged)
     (extensions-belong-in-dreyeck))
    ((!select-property-journal-sync)))

   (:method (select-dmx-sqlite-next-task)
    ((allow-build-graph-recorder-replay))
    ((!select-build-graph-recorder-replay)))

   (:method (select-dmx-sqlite-next-task)
    ((fedwiki-artifact-materialization-required))
    ((!select-fedwiki-artifact-materialization)))

   (:method (select-dmx-sqlite-next-task)
    ((more-next-task-evidence-required))
    ((!defer-next-task-for-more-evidence)))))
