(:REFACTOR-HYPERDOC-SEVENTH-EXTRACTION-HTN-ASSIMILATION
 (:OPERATION (!ASSIMILATE-SEVENTH-EXTRACTION-INTO-REUSABLE-HTN) :BASE #1="628aa5f0"
  :REUSABLE-TASK-LIBRARY "hyperdoc/refactor-hyperdoc-reusable-extraction-htn.sexp" :INPUT-EPISODE
  (:ARCHITECTURE-DECISION
   #2="hyperdoc/evidence/refactor-hyperdoc-live-lisp-executor-architecture-decision.sexp"
   :OWNER-REDECISION
   #3="hyperdoc/evidence/refactor-hyperdoc-seventh-build-referee-subgraph-owner-redecision.sexp"
   :SELECTION #4="hyperdoc/evidence/refactor-hyperdoc-seventh-dreyeck-extraction-selection.sexp"
   :REVIEW #5="hyperdoc/evidence/refactor-hyperdoc-seventh-dreyeck-extraction-review.sexp"
   :EXECUTION #6="hyperdoc/evidence/refactor-hyperdoc-seventh-dreyeck-extraction-result.sexp"
   :POST-REVIEW
   #7="hyperdoc/evidence/refactor-hyperdoc-seventh-dreyeck-extraction-post-review.sexp")
  :REUSED-ABSTRACT-TASKS
  (!LOCATE-REUSABLE-HTN-TASKS-BEFORE-SPECIALIZATION !CLASSIFY-REFACTORING-CANDIDATE-OWNERSHIP
   !SELECT-LOW-RISK-DOWNSTREAM-EXTRACTION-SLICE !REVIEW-SELECTED-EXTRACTION-SLICE-BEFORE-EXECUTION
   !ADAPT-CURRENT-PLAN-WITH-REUSED-OR-GENERALIZED-TASKS !EXECUTE-REVIEWED-EXTRACTION-SLICE
   !REVIEW-EXECUTED-EXTRACTION-SLICE !ASSIMILATE-REFACTORING-EPISODE-INTO-HTN)
  :NEW-ABSTRACT-TASKS NIL :NEW-ABSTRACT-TASK-CANDIDATES
  (!RECORD-EXECUTOR-ARCHITECTURE-DECISION-BEFORE-OWNER-SELECTION) :NEW-SPECIALIZATIONS
  ((:TASK !RECORD-LIVE-LISP-EXECUTOR-ARCHITECTURE-DECISION :SPECIALIZES
    !ADAPT-CURRENT-PLAN-WITH-REUSED-OR-GENERALIZED-TASKS :EVIDENCE #2# :ROLE
    :ARCHITECTURE-CORRECTION-BEFORE-OWNER-SELECTION)
   (:TASK !REDECIDE-BUILD-REFEREE-SUBGRAPH-OWNER-UNDER-LIVE-LISP-EXECUTOR-MODEL :SPECIALIZES
    !CLASSIFY-REFACTORING-CANDIDATE-OWNERSHIP :EVIDENCE #3# :ROLE
    :OWNER-REDECISION-UNDER-CORRECTED-EXECUTOR-MODEL)
   (:TASK !SELECT-SEVENTH-LOW-RISK-DREYECK-EXTRACTION-SLICE :SPECIALIZES
    !SELECT-LOW-RISK-DOWNSTREAM-EXTRACTION-SLICE :EVIDENCE #4#)
   (:TASK !REVIEW-SEVENTH-SLICE-SELECTION-BEFORE-EXECUTION :SPECIALIZES
    !REVIEW-SELECTED-EXTRACTION-SLICE-BEFORE-EXECUTION :EVIDENCE #5#)
   (:TASK !EXECUTE-SEVENTH-LOW-RISK-DREYECK-EXTRACTION-SLICE :SPECIALIZES
    !EXECUTE-REVIEWED-EXTRACTION-SLICE :EVIDENCE #6#)
   (:TASK !RECORD-SEVENTH-EXTRACTION-POST-REVIEW-WITH-DEFERRED-HYPERDOC-LOAD-BOUNDARY-REPAIR
    :SPECIALIZES !REVIEW-EXECUTED-EXTRACTION-SLICE :EVIDENCE #7#)
   (:TASK !ASSIMILATE-SEVENTH-EXTRACTION-INTO-REUSABLE-HTN :SPECIALIZES
    !ASSIMILATE-REFACTORING-EPISODE-INTO-HTN :EVIDENCE
    "hyperdoc/evidence/refactor-hyperdoc-seventh-extraction-htn-assimilation.sexp"))
  :EPISODE-RESULT
  (:EPISODE :SEVENTH-DREYECK-EXTRACTION :BASE #1# :MOVED-FILE
   ("hyperdoc/add-build-referee-subgraph-inspector-view-plan.sexp"
    "dreyeck/build/add-build-referee-subgraph-inspector-view-plan.sexp")
   :TARGET-SYSTEM :DREYECK/BUILD :EXECUTOR-ROLE :COHERENT-LIVE-LISP-IMAGE :CODEX-ROLE
   :LEGACY-COMPATIBILITY-OR-READER-DISPLAY-SURFACE :POST-REVIEW-VERDICT :ACCEPTED
   :LIVE-OLD-PATH-REFERENCES NIL :ASDF-UPDATE-REQUIRED-P NIL :NEW-ASDF-SUBSYSTEM-NEEDED-P NIL
   :NEW-ABSTRACT-TASK-CANDIDATES (!RECORD-EXECUTOR-ARCHITECTURE-DECISION-BEFORE-OWNER-SELECTION))
  :LESSON
  "The executor must be modeled as a coherent live Lisp image; SLY mREPL, SBCL Bridge, and scripted SBCL are transport/session realizations, while Codex-named systems are legacy collaboration or reader-display surfaces, not execution authority."
  :VALIDATIONS
  ((:TASK-LIBRARY-READ-BEFORE :PASSED) (:ASSIMILATION-ARTIFACT-READ :PENDING-UNTIL-WRITE)
   (:GIT-DIFF-CHECK-BEFORE :PASSED) (:POST-REVIEW-VERDICT :ACCEPTED))
  :NEXT (!SELECT-EIGHTH-LOW-RISK-DREYECK-EXTRACTION-SLICE)))
