(:REFACTOR-HYPERDOC-EIGHTH-EXTRACTION-COMMIT-3-SHOP3-PROBLEM-MATERIALIZATION
 (:TASK
  (!MATERIALIZE-EIGHTH-EXTRACTION-COMMIT-3-SHOP3-PROBLEM
   :REPOSITORY "/Users/rgb/workspace/hyperdoc/"
   :TARGET-BRANCH "hauptsache"
   :BASIS-COMMIT "bfa06ee9c0307327346d8705800bfcd4fa3b08c3"
   :WORKTREE-MODE :TEMPORARY-CLEAN-WORKTREE
   :MODE :PLANNER-MATERIALIZATION-ONLY))

 (:BASIS
  ((:LOCALIZATION
    "hyperdoc/evidence/refactor-hyperdoc-eighth-extraction-commit-3-localization.sexp")
   (:REUSABLE-HTN
    "hyperdoc/refactor-hyperdoc-reusable-extraction-htn.sexp")
   (:CANONICAL-SHOP3-SYSTEM :DREYECK/SHOP3)
   (:FORM-REVIEW
    :OUTCOME :B
    :EXISTING-DOMAIN-SUFFICIENT-P NIL
    :LIVE-FIND-PLANS-DEMONSTRATED-P T)))

 (:ASDF-MATERIALIZATION
  (:DIRECT-SYSTEM
   (:NAME :DREYECK/SHOP3/EXTRACTION-PLANNING)
   (:DEPENDS-ON (:DREYECK/SHOP3))
   (:SERIAL T)
   (:COMPONENTS
    ("extraction-planning/domain"
     "extraction-planning/problem"
     "extraction-planning/runner")))
  (:TEST-SYSTEM
   (:NAME :DREYECK/SHOP3/EXTRACTION-PLANNING/TESTS)
   (:DEPENDS-ON
    (:DREYECK/SHOP3/EXTRACTION-PLANNING :FIVEAM-ASDF))
   (:PERFORM-TESTS T))
  (:DREYECK/SHOP3-DIRECT-COMPONENTS-BEFORE 6)
  (:DREYECK/SHOP3-DIRECT-COMPONENTS-AFTER 6)
  (:PATH-CONTRACT-DEVIATION NIL))

 (:SHOP3-BOUNDARY
  (:DOMAIN
   DREYECK/SHOP3::EIGHTH-DREYECK-EXTRACTION-COMMIT-3-LOCALIZATION-DOMAIN)
  (:PROBLEM
   DREYECK/SHOP3::EIGHTH-DREYECK-EXTRACTION-COMMIT-3-LOCALIZATION)
  (:TOP-LEVEL-TASK
   (DREYECK/SHOP3::LOCALIZE-EIGHTH-DREYECK-EXTRACTION-COMMIT-3
    "/Users/rgb/workspace/hyperdoc/"
    DREYECK/SHOP3::HAUPTSACHE
    "59639866a1bb4aa9f27ddc43c383bd2907d196b3"))
  (:TOP-LEVEL-TASK-KIND :COMPOUND)
  (:METHOD-COUNT 1)
  (:PRIMITIVE-OPERATOR-COUNT 5)
  (:OPERATOR-SYNTAX :MODERN-OP-WITH-NAMED-OPTIONS)
  (:EXECUTOR-VISIBLE-PRIMITIVE-ACTIONS T)
  (:HEURISTIC-FALLBACK NIL))

 (:LIVE-RUNTIME-RESULT
  (:PLANNER :SHOP3)
  (:PLANNER-CALL :LIVE)
  (:FIND-PLANS-SYMBOL "SHOP3:FIND-PLANS")
  (:HEURISTIC-FALLBACK NIL)
  (:DOMAIN
   DREYECK/SHOP3::EIGHTH-DREYECK-EXTRACTION-COMMIT-3-LOCALIZATION-DOMAIN)
  (:PROBLEM
   DREYECK/SHOP3::EIGHTH-DREYECK-EXTRACTION-COMMIT-3-LOCALIZATION)
  (:PROBLEM-SYMBOL
   DREYECK/SHOP3::EIGHTH-DREYECK-EXTRACTION-COMMIT-3-LOCALIZATION)
  (:PLANS
   (((DREYECK/SHOP3::!RECORD-NO-SPECIALIZED-PLAN-FOUND
      "/Users/rgb/workspace/hyperdoc/"
      DREYECK/SHOP3::HAUPTSACHE
      "59639866a1bb4aa9f27ddc43c383bd2907d196b3")
     1.0
     (DREYECK/SHOP3::!CLASSIFY-LEGACY-IMPLEMENTATION-COPY-SET
      "/Users/rgb/workspace/hyperdoc/"
      DREYECK/SHOP3::HAUPTSACHE
      "59639866a1bb4aa9f27ddc43c383bd2907d196b3")
     1.0
     (DREYECK/SHOP3::!CLASSIFY-LIVE-AND-HISTORICAL-REFERENCES
      "/Users/rgb/workspace/hyperdoc/"
      DREYECK/SHOP3::HAUPTSACHE
      "59639866a1bb4aa9f27ddc43c383bd2907d196b3")
     1.0
     (DREYECK/SHOP3::!SELECT-COMMIT-3-PREPARATION-BOUNDARY
      "/Users/rgb/workspace/hyperdoc/"
      DREYECK/SHOP3::HAUPTSACHE
      "59639866a1bb4aa9f27ddc43c383bd2907d196b3")
     1.0
     (DREYECK/SHOP3::!RECORD-LOCALIZATION-RESULT
      "/Users/rgb/workspace/hyperdoc/"
      DREYECK/SHOP3::HAUPTSACHE
      "59639866a1bb4aa9f27ddc43c383bd2907d196b3")
     1.0)))
  (:RAW-PLANS
   (((DREYECK/SHOP3::!RECORD-NO-SPECIALIZED-PLAN-FOUND
      "/Users/rgb/workspace/hyperdoc/"
      DREYECK/SHOP3::HAUPTSACHE
      "59639866a1bb4aa9f27ddc43c383bd2907d196b3")
     1.0
     (DREYECK/SHOP3::!CLASSIFY-LEGACY-IMPLEMENTATION-COPY-SET
      "/Users/rgb/workspace/hyperdoc/"
      DREYECK/SHOP3::HAUPTSACHE
      "59639866a1bb4aa9f27ddc43c383bd2907d196b3")
     1.0
     (DREYECK/SHOP3::!CLASSIFY-LIVE-AND-HISTORICAL-REFERENCES
      "/Users/rgb/workspace/hyperdoc/"
      DREYECK/SHOP3::HAUPTSACHE
      "59639866a1bb4aa9f27ddc43c383bd2907d196b3")
     1.0
     (DREYECK/SHOP3::!SELECT-COMMIT-3-PREPARATION-BOUNDARY
      "/Users/rgb/workspace/hyperdoc/"
      DREYECK/SHOP3::HAUPTSACHE
      "59639866a1bb4aa9f27ddc43c383bd2907d196b3")
     1.0
     (DREYECK/SHOP3::!RECORD-LOCALIZATION-RESULT
      "/Users/rgb/workspace/hyperdoc/"
      DREYECK/SHOP3::HAUPTSACHE
      "59639866a1bb4aa9f27ddc43c383bd2907d196b3")
     1.0)))
  (:SHORTER-PLANS
   (((DREYECK/SHOP3::!RECORD-NO-SPECIALIZED-PLAN-FOUND
      "/Users/rgb/workspace/hyperdoc/"
      DREYECK/SHOP3::HAUPTSACHE
      "59639866a1bb4aa9f27ddc43c383bd2907d196b3")
     (DREYECK/SHOP3::!CLASSIFY-LEGACY-IMPLEMENTATION-COPY-SET
      "/Users/rgb/workspace/hyperdoc/"
      DREYECK/SHOP3::HAUPTSACHE
      "59639866a1bb4aa9f27ddc43c383bd2907d196b3")
     (DREYECK/SHOP3::!CLASSIFY-LIVE-AND-HISTORICAL-REFERENCES
      "/Users/rgb/workspace/hyperdoc/"
      DREYECK/SHOP3::HAUPTSACHE
      "59639866a1bb4aa9f27ddc43c383bd2907d196b3")
     (DREYECK/SHOP3::!SELECT-COMMIT-3-PREPARATION-BOUNDARY
      "/Users/rgb/workspace/hyperdoc/"
      DREYECK/SHOP3::HAUPTSACHE
      "59639866a1bb4aa9f27ddc43c383bd2907d196b3")
     (DREYECK/SHOP3::!RECORD-LOCALIZATION-RESULT
      "/Users/rgb/workspace/hyperdoc/"
      DREYECK/SHOP3::HAUPTSACHE
      "59639866a1bb4aa9f27ddc43c383bd2907d196b3"))))
  (:RUN-TIME 0.020287)
  (:PLAN-TREES
   ((((DREYECK/SHOP3::LOCALIZE-EIGHTH-DREYECK-EXTRACTION-COMMIT-3
       "/Users/rgb/workspace/hyperdoc/"
       DREYECK/SHOP3::HAUPTSACHE
       "59639866a1bb4aa9f27ddc43c383bd2907d196b3")
      #:METH-LOCALIZE-EIGHTH-DREYECK-EXTRACTION-COMMIT-32210--222
      ((1.0
        (DREYECK/SHOP3::!RECORD-NO-SPECIALIZED-PLAN-FOUND
         "/Users/rgb/workspace/hyperdoc/"
         DREYECK/SHOP3::HAUPTSACHE
         "59639866a1bb4aa9f27ddc43c383bd2907d196b3")
        0)
       (1.0
        (DREYECK/SHOP3::!CLASSIFY-LEGACY-IMPLEMENTATION-COPY-SET
         "/Users/rgb/workspace/hyperdoc/"
         DREYECK/SHOP3::HAUPTSACHE
         "59639866a1bb4aa9f27ddc43c383bd2907d196b3")
        1)
       (1.0
        (DREYECK/SHOP3::!CLASSIFY-LIVE-AND-HISTORICAL-REFERENCES
         "/Users/rgb/workspace/hyperdoc/"
         DREYECK/SHOP3::HAUPTSACHE
         "59639866a1bb4aa9f27ddc43c383bd2907d196b3")
        2)
       (1.0
        (DREYECK/SHOP3::!SELECT-COMMIT-3-PREPARATION-BOUNDARY
         "/Users/rgb/workspace/hyperdoc/"
         DREYECK/SHOP3::HAUPTSACHE
         "59639866a1bb4aa9f27ddc43c383bd2907d196b3")
        3)
       (1.0
        (DREYECK/SHOP3::!RECORD-LOCALIZATION-RESULT
         "/Users/rgb/workspace/hyperdoc/"
         DREYECK/SHOP3::HAUPTSACHE
         "59639866a1bb4aa9f27ddc43c383bd2907d196b3")
        4)))))
  (:PLAN-TREE-PROJECTION :RAW-SHOP3-PLAN-TREES)
  (:FINAL-STATES
   (((DREYECK/SHOP3::COMMIT-3-LOCALIZATION-RECORDED
      "/Users/rgb/workspace/hyperdoc/"
      DREYECK/SHOP3::HAUPTSACHE
      "59639866a1bb4aa9f27ddc43c383bd2907d196b3")
     (DREYECK/SHOP3::NEXT-TASK
      DREYECK/SHOP3::PREPARE-EIGHTH-DREYECK-EXTRACTION-COMMIT-3)
     (DREYECK/SHOP3::COMMIT-3-PREPARATION-BOUNDARY-SELECTED
      "/Users/rgb/workspace/hyperdoc/"
      DREYECK/SHOP3::HAUPTSACHE
      "59639866a1bb4aa9f27ddc43c383bd2907d196b3")
     (DREYECK/SHOP3::SHOP3-REFERENCE-BOUNDARY-CLASSIFIED
      "/Users/rgb/workspace/hyperdoc/"
      DREYECK/SHOP3::HAUPTSACHE
      "59639866a1bb4aa9f27ddc43c383bd2907d196b3")
     (DREYECK/SHOP3::LEGACY-IMPLEMENTATION-COPY-SET-CLASSIFIED
      "/Users/rgb/workspace/hyperdoc/"
      DREYECK/SHOP3::HAUPTSACHE
      "59639866a1bb4aa9f27ddc43c383bd2907d196b3")
     (DREYECK/SHOP3::NO-SPECIALIZED-REMOVAL-LINT-PLAN-RECORDED
      "/Users/rgb/workspace/hyperdoc/"
      DREYECK/SHOP3::HAUPTSACHE
      "59639866a1bb4aa9f27ddc43c383bd2907d196b3")
     (DREYECK/SHOP3::SPECIALIZED-REMOVAL-LINT-PLAN-FOUND
      DREYECK/SHOP3::FALSE)
     (DREYECK/SHOP3::PROJECTION-REPAIR-DEFERRED)
     (DREYECK/SHOP3::DOCUMENTATION-WORKFLOW-MOVE-DEFERRED)
     (DREYECK/SHOP3::PROVIDER-BOUNDARY-MOVE-DEFERRED)
     (DREYECK/SHOP3::COMPATIBILITY-REFERENCE-POLICY-PRESERVED)
     (DREYECK/SHOP3::NEW-CODE-CONTRADICTORY-REFERENCE-COUNT 0)
     (DREYECK/SHOP3::TRACKED-SHOP3-REFERENCE-PATH-COUNT 45)
     (DREYECK/SHOP3::LEGACY-IMPLEMENTATION-COPIES-LIVE-ASDF-COMPONENTS
      DREYECK/SHOP3::FALSE)
     (DREYECK/SHOP3::LEGACY-IMPLEMENTATION-COPY-COUNT 6)
     (DREYECK/SHOP3::LEGACY-IMPLEMENTATION-COPY
      "hyperdoc-shop3/views.lisp")
     (DREYECK/SHOP3::LEGACY-IMPLEMENTATION-COPY
      "hyperdoc-shop3/examples.lisp")
     (DREYECK/SHOP3::LEGACY-IMPLEMENTATION-COPY
      "hyperdoc-shop3/hyperdoc-maintenance-domain.lisp")
     (DREYECK/SHOP3::LEGACY-IMPLEMENTATION-COPY
      "hyperdoc-shop3/plan-objects.lisp")
     (DREYECK/SHOP3::LEGACY-IMPLEMENTATION-COPY
      "hyperdoc-shop3/manual-topics.lisp")
     (DREYECK/SHOP3::LEGACY-IMPLEMENTATION-COPY
      "hyperdoc-shop3/package.lisp")
     (DREYECK/SHOP3::COMPATIBILITY-SYSTEM DREYECK/SHOP3::HYPERDOC/SHOP3)
     (DREYECK/SHOP3::CANONICAL-SHOP3-OWNER DREYECK/SHOP3::DREYECK/SHOP3)
     (DREYECK/SHOP3::BASIS-COMMIT
      "59639866a1bb4aa9f27ddc43c383bd2907d196b3")
     (DREYECK/SHOP3::TARGET-BRANCH DREYECK/SHOP3::HAUPTSACHE)
     (DREYECK/SHOP3::REPOSITORY "/Users/rgb/workspace/hyperdoc/"))))
  (:FINAL-STATE-PROJECTION :STATE-ATOMS)))

 (:LIVE-ASSERTIONS
  (:DOMAIN-REGISTERED T)
  (:PROBLEM-REGISTERED T)
  (:PACKAGE-AWARE-PROBLEM-SYMBOL T)
  (:PLAN-COUNT 1)
  (:PLAN-LENGTH 5)
  (:PLAN-TREE-PRESENT T)
  (:FINAL-STATE-PRESENT T)
  (:FINAL-STATE-LOCALIZATION-COMPLETE T)
  (:RELEVANT-FINAL-STATE-ATOMS
   ((DREYECK/SHOP3::COMMIT-3-LOCALIZATION-RECORDED
     "/Users/rgb/workspace/hyperdoc/"
     DREYECK/SHOP3::HAUPTSACHE
     "59639866a1bb4aa9f27ddc43c383bd2907d196b3")
    (DREYECK/SHOP3::NEXT-TASK
     DREYECK/SHOP3::PREPARE-EIGHTH-DREYECK-EXTRACTION-COMMIT-3))))

 (:HTN-ADVANCE
  (:FROM :LOCALIZED-NO-SPECIALIZED-PLAN-FOUND)
  (:TO :COMMIT-3-SHOP3-PROBLEM-MATERIALIZED)
  (:NEXT
   (!PREPARE-EIGHTH-DREYECK-EXTRACTION-COMMIT-3
    :FROM-LIVE-SHOP3-PROBLEM T)))

 (:CHANGED-PATH-CONTRACT
  ("dreyeck.asd"
   "dreyeck/shop3/extraction-planning/domain.lisp"
   "dreyeck/shop3/extraction-planning/problem.lisp"
   "dreyeck/shop3/extraction-planning/runner.lisp"
   "dreyeck/shop3/extraction-planning/tests/package.lisp"
   "dreyeck/shop3/extraction-planning/tests/smoke.lisp"
   "hyperdoc/refactor-hyperdoc-reusable-extraction-htn.sexp"
   "hyperdoc/evidence/refactor-hyperdoc-eighth-extraction-commit-3-shop3-problem-materialization.sexp"))

 (:VALIDATION
  ((:CHECK :SHOP3-SYNTAX-CHECKS :STATUS :PASSED)
   (:CHECK :ASDF-LOAD
    :SYSTEM :DREYECK/SHOP3/EXTRACTION-PLANNING
    :MARKER "EXTRACTION_PLANNING_LOAD_OK"
    :STATUS :PASSED)
   (:CHECK :ASDF-TEST
    :SYSTEM :DREYECK/SHOP3/EXTRACTION-PLANNING/TESTS
    :MARKER "EXTRACTION_PLANNING_TEST_OK"
    :STATUS :PASSED)
   (:CHECK :LIVE-FIND-PLANS :STATUS :PASSED)
   (:CHECK :HEURISTIC-FALLBACK :EXPECTED NIL :ACTUAL NIL :STATUS :PASSED)
   (:CHECK :EXACT-PLAN-LENGTH :EXPECTED 5 :ACTUAL 5 :STATUS :PASSED)
   (:CHECK :FINAL-STATE-LOCALIZATION-COMPLETE :STATUS :PASSED)
   (:CHECK :EVIDENCE-SAFE-SINGLE-FORM :READ-EVAL NIL :STATUS :PASSED)
   (:CHECK :REUSABLE-HTN-SAFE-SINGLE-FORM :READ-EVAL NIL :STATUS :PASSED)
   (:CHECK :ONLY-SELECTED-PATHS-CHANGED :EXPECTED 8 :ACTUAL 8 :STATUS :PASSED)
   (:CHECK :GIT-DIFF-CHECK :COMMAND "git diff --check" :STATUS :PASSED)
   (:CHECK :REPOSITORY-LOAD-GATE
    :COMMAND "tools/check-lisp-load-gate.sh :hyperbook/server"
    :ENVIRONMENT :NIX-DEVELOP
    :MARKER "LOAD_GATE_OK"
    :STATUS :PASSED)
   (:CHECK :ORIGINAL-WORKTREE-STAGED-FILES-PRESERVED
    :INDEX-BLOB-IDS
    ("fec17cb44b315313f256f5fd1e647ecee049af95"
     "13289505c477d0bf84d66ed28d97f629683de3bd"
     "c7746ca7cee24ce18a0f1d819e8ede402b602ea5")
    :STATUS :PASSED)
   (:CHECK :TEMPORARY-WORKTREE-REMOVED
    :STATUS :PERFORMED-AFTER-COMMIT-VERIFICATION)))

 (:NON-ACTIONS
  (:LEGACY-FILES-DELETED 0)
  (:LINT-IMPLEMENTATION-CHANGES NIL)
  (:LINT-FIXTURES-ADDED NIL)
  (:PREVIOUS-PREPARATION-CONTRACT-RUN NIL)
  (:PROVIDER-BOUNDARY-MOVE NIL)
  (:DOCUMENTATION-OR-SCXML-MIGRATION NIL)
  (:PLAN-TREE-PROJECTION-REPAIR NIL)
  (:HAUPTSACHE-RUNTIME-PI-OR-SECRETS-MUTATION NIL)
  (:PUSHED NIL))

 (:ANSWER-RECONSTRUCTION
  (:SURFACE
   (:PROCESS-TRACE
    (:INSPECTED :LOCALIZATION-BASIS-AND-WORKSPACE-SELECTION-PRECEDENT)
    (:DECIDED :SEPARATE-ASDF-SYSTEM-PRESERVING-SIX-DIRECT-COMPONENTS)
    (:EXECUTED :LIVE-SHOP3-LOAD-TEST-AND-RUNNER)
    (:OBSERVED :ONE-FIVE-ACTION-PLAN-AND-COMPLETE-FINAL-STATE))
   (:RESULT :EIGHTH-EXTRACTION-COMMIT-3-SHOP3-PROBLEM-MATERIALIZED))
  (:ARTIFACT
   (:HYPERDOC-PAGE-DELTA NIL)
   (:LISP-DOMAIN-PROBLEM-RUNNER-AND-SMOKE-DELTA T)
   (:FEDWIKI-TWIN-DELTA NIL)
   (:DAILY-ANCHOR-DELTA NIL)
   (:REPLAY-CHECKS
    (:ASDF-LOAD :ASDF-TEST :LIVE-FIND-PLANS :SAFE-SINGLE-FORM
     :EXACT-CHANGED-PATHS :GIT-DIFF-CHECK :REPOSITORY-LOAD-GATE))))

 (:CLASSIFICATION
  :EIGHTH-EXTRACTION-COMMIT-3-SHOP3-PROBLEM-MATERIALIZED)
 (:NEXT
  (!PREPARE-EIGHTH-DREYECK-EXTRACTION-COMMIT-3
   :FROM-LIVE-SHOP3-PROBLEM T)))
