(:REFACTOR-HYPERDOC-EIGHTH-EXTRACTION-COMMIT-3-PREPARATION
 (:ARTIFACT-KIND
  :EXECUTION-CONTRACT-PROJECTION-OF-LIVE-SHOP3-PLAN)

 (:TASK
  (!PREPARE-EIGHTH-DREYECK-EXTRACTION-COMMIT-3
   :REPOSITORY "/Users/rgb/workspace/hyperdoc/"
   :TARGET-BRANCH "hauptsache"
   :BASIS-COMMIT "ab1926eb807e5e8721b888a34736ada458209a40"
   :MODE :PREPARATION-ONLY
   :FROM-LIVE-SHOP3-PROBLEM T))

 (:REPOSITORY-OBSERVATIONS
  (:LOCALIZATION-MATERIALIZATION-COMMIT
   "ab1926eb807e5e8721b888a34736ada458209a40")
  (:LIVE-LOCALIZATION-PLAN-LENGTH 5)
  (:LIVE-LOCALIZATION-FINAL-STATE-CONFIRMED T)
  (:TRACKED-SHOP3-REFERENCE-PATHS 50)
  (:DURABLE-GATE "tools/pre-commit-gate.sh")
  (:DURABLE-SHOP3-REFERENCE-CHECKER-PRESENT NIL)
  (:GIT-HOOK-USED-AS-PERSISTENT-ARTIFACT NIL)
  (:CANONICAL-SYSTEM :DREYECK/SHOP3)
  (:CANONICAL-PACKAGE :DREYECK/SHOP3)
  (:COMPATIBILITY-SYSTEM :HYPERDOC/SHOP3)
  (:COMPATIBILITY-DIRECT-COMPONENTS 0)
  (:COMPATIBILITY-DEPENDS-ON (:DREYECK/SHOP3))
  (:LEGACY-PACKAGE-NICKNAME :HYPERDOC/SHOP3))

 (:SHOP3-PROVENANCE
  (:DOMAIN
   DREYECK/SHOP3::EIGHTH-DREYECK-EXTRACTION-COMMIT-3-PREPARATION-DOMAIN)
  (:PROBLEM
   DREYECK/SHOP3::EIGHTH-DREYECK-EXTRACTION-COMMIT-3-PREPARATION)
  (:TOP-LEVEL-TASK
   (DREYECK/SHOP3::PREPARE-EIGHTH-DREYECK-EXTRACTION-COMMIT-3
    "/Users/rgb/workspace/hyperdoc/"
    DREYECK/SHOP3::HAUPTSACHE
    "ab1926eb807e5e8721b888a34736ada458209a40"))
  (:TOP-LEVEL-TASK-KIND :COMPOUND)
  (:METHOD-COUNT 1)
  (:PRIMITIVE-OPERATOR-COUNT 6)
  (:PLANNER SHOP3:FIND-PLANS)
  (:PLANNER-CALL :LIVE)
  (:HEURISTIC-FALLBACK NIL)
  (:RAW-PLAN
   ((DREYECK/SHOP3::!CONFIRM-LIVE-LOCALIZATION-BASIS
     "/Users/rgb/workspace/hyperdoc/"
     DREYECK/SHOP3::HAUPTSACHE
     "ab1926eb807e5e8721b888a34736ada458209a40")
    1.0
    (DREYECK/SHOP3::!SELECT-LEGACY-COPY-DELETION-SET
     "/Users/rgb/workspace/hyperdoc/"
     DREYECK/SHOP3::HAUPTSACHE
     "ab1926eb807e5e8721b888a34736ada458209a40")
    1.0
    (DREYECK/SHOP3::!SELECT-REFERENCE-LINT-DESIGN
     "/Users/rgb/workspace/hyperdoc/"
     DREYECK/SHOP3::HAUPTSACHE
     "ab1926eb807e5e8721b888a34736ada458209a40")
    1.0
    (DREYECK/SHOP3::!CLASSIFY-REFERENCE-POLICY
     "/Users/rgb/workspace/hyperdoc/"
     DREYECK/SHOP3::HAUPTSACHE
     "ab1926eb807e5e8721b888a34736ada458209a40")
    1.0
    (DREYECK/SHOP3::!DEFINE-COMMIT-3-EXECUTION-CONTRACT
     "/Users/rgb/workspace/hyperdoc/"
     DREYECK/SHOP3::HAUPTSACHE
     "ab1926eb807e5e8721b888a34736ada458209a40")
    1.0
    (DREYECK/SHOP3::!RECORD-COMMIT-3-PREPARATION
     "/Users/rgb/workspace/hyperdoc/"
     DREYECK/SHOP3::HAUPTSACHE
     "ab1926eb807e5e8721b888a34736ada458209a40")
    1.0))
  (:SHORTER-PLAN
   ((DREYECK/SHOP3::!CONFIRM-LIVE-LOCALIZATION-BASIS
     "/Users/rgb/workspace/hyperdoc/"
     DREYECK/SHOP3::HAUPTSACHE
     "ab1926eb807e5e8721b888a34736ada458209a40")
    (DREYECK/SHOP3::!SELECT-LEGACY-COPY-DELETION-SET
     "/Users/rgb/workspace/hyperdoc/"
     DREYECK/SHOP3::HAUPTSACHE
     "ab1926eb807e5e8721b888a34736ada458209a40")
    (DREYECK/SHOP3::!SELECT-REFERENCE-LINT-DESIGN
     "/Users/rgb/workspace/hyperdoc/"
     DREYECK/SHOP3::HAUPTSACHE
     "ab1926eb807e5e8721b888a34736ada458209a40")
    (DREYECK/SHOP3::!CLASSIFY-REFERENCE-POLICY
     "/Users/rgb/workspace/hyperdoc/"
     DREYECK/SHOP3::HAUPTSACHE
     "ab1926eb807e5e8721b888a34736ada458209a40")
    (DREYECK/SHOP3::!DEFINE-COMMIT-3-EXECUTION-CONTRACT
     "/Users/rgb/workspace/hyperdoc/"
     DREYECK/SHOP3::HAUPTSACHE
     "ab1926eb807e5e8721b888a34736ada458209a40")
    (DREYECK/SHOP3::!RECORD-COMMIT-3-PREPARATION
     "/Users/rgb/workspace/hyperdoc/"
     DREYECK/SHOP3::HAUPTSACHE
     "ab1926eb807e5e8721b888a34736ada458209a40")))
  (:RUN-TIME 0.099249)
  (:PLAN-TREE
   (((DREYECK/SHOP3::PREPARE-EIGHTH-DREYECK-EXTRACTION-COMMIT-3
      "/Users/rgb/workspace/hyperdoc/"
      DREYECK/SHOP3::HAUPTSACHE
      "ab1926eb807e5e8721b888a34736ada458209a40")
     #:METH-PREPARE-EIGHTH-DREYECK-EXTRACTION-COMMIT-32230--224
     ((1.0
       (DREYECK/SHOP3::!CONFIRM-LIVE-LOCALIZATION-BASIS
        "/Users/rgb/workspace/hyperdoc/"
        DREYECK/SHOP3::HAUPTSACHE
        "ab1926eb807e5e8721b888a34736ada458209a40")
       0)
      (1.0
       (DREYECK/SHOP3::!SELECT-LEGACY-COPY-DELETION-SET
        "/Users/rgb/workspace/hyperdoc/"
        DREYECK/SHOP3::HAUPTSACHE
        "ab1926eb807e5e8721b888a34736ada458209a40")
       1)
      (1.0
       (DREYECK/SHOP3::!SELECT-REFERENCE-LINT-DESIGN
        "/Users/rgb/workspace/hyperdoc/"
        DREYECK/SHOP3::HAUPTSACHE
        "ab1926eb807e5e8721b888a34736ada458209a40")
       2)
      (1.0
       (DREYECK/SHOP3::!CLASSIFY-REFERENCE-POLICY
        "/Users/rgb/workspace/hyperdoc/"
        DREYECK/SHOP3::HAUPTSACHE
        "ab1926eb807e5e8721b888a34736ada458209a40")
       3)
      (1.0
       (DREYECK/SHOP3::!DEFINE-COMMIT-3-EXECUTION-CONTRACT
        "/Users/rgb/workspace/hyperdoc/"
        DREYECK/SHOP3::HAUPTSACHE
        "ab1926eb807e5e8721b888a34736ada458209a40")
       4)
      (1.0
       (DREYECK/SHOP3::!RECORD-COMMIT-3-PREPARATION
        "/Users/rgb/workspace/hyperdoc/"
        DREYECK/SHOP3::HAUPTSACHE
        "ab1926eb807e5e8721b888a34736ada458209a40")
       5)))))
  (:PLAN-TREE-PROJECTION :RAW-SHOP3-PLAN-TREE)
  (:FINAL-STATE
   (:PROJECTION :LOSSLESS-STATE-TRANSITION-DELTA)
   (:ADDED-ATOMS
    ((DREYECK/SHOP3::COMMIT-3-PREPARED
      "/Users/rgb/workspace/hyperdoc/"
      DREYECK/SHOP3::HAUPTSACHE
      "ab1926eb807e5e8721b888a34736ada458209a40")
     (DREYECK/SHOP3::NEXT-TASK
      DREYECK/SHOP3::EXECUTE-EIGHTH-DREYECK-EXTRACTION-COMMIT-3)))
   (:DELETED-TRANSITION-ATOMS
    ((DREYECK/SHOP3::COMMIT-3-LOCALIZATION-PROBLEM-MATERIALIZED
      DREYECK/SHOP3::EIGHTH-DREYECK-EXTRACTION-COMMIT-3-LOCALIZATION)
     (DREYECK/SHOP3::LIVE-LOCALIZATION-BASIS-CONFIRMED
      "/Users/rgb/workspace/hyperdoc/"
      DREYECK/SHOP3::HAUPTSACHE
      "ab1926eb807e5e8721b888a34736ada458209a40")
     (DREYECK/SHOP3::LEGACY-COPY-DELETION-SET-SELECTED
      "/Users/rgb/workspace/hyperdoc/"
      DREYECK/SHOP3::HAUPTSACHE
      "ab1926eb807e5e8721b888a34736ada458209a40")
     (DREYECK/SHOP3::REFERENCE-LINT-DESIGN-SELECTED
      "/Users/rgb/workspace/hyperdoc/"
      DREYECK/SHOP3::HAUPTSACHE
      "ab1926eb807e5e8721b888a34736ada458209a40")
     (DREYECK/SHOP3::REFERENCE-POLICY-CLASSIFIED
      "/Users/rgb/workspace/hyperdoc/"
      DREYECK/SHOP3::HAUPTSACHE
      "ab1926eb807e5e8721b888a34736ada458209a40")
     (DREYECK/SHOP3::COMMIT-3-EXECUTION-CONTRACT-DEFINED
      "/Users/rgb/workspace/hyperdoc/"
      DREYECK/SHOP3::HAUPTSACHE
      "ab1926eb807e5e8721b888a34736ada458209a40")))
   (:PRESERVED-GROUND-ATOMS
    (:SOURCE
     "dreyeck/shop3/extraction-planning/preparation-problem.lisp")
    (:SEMANTICS
     :ALL-GROUND-INITIAL-STATE-ATOMS-EXCEPT-THE-DELETED-TRANSITION-ATOM)))
  (:FINAL-STATE-RELEVANT-ATOMS
   ((DREYECK/SHOP3::COMMIT-3-PREPARED
     "/Users/rgb/workspace/hyperdoc/"
     DREYECK/SHOP3::HAUPTSACHE
     "ab1926eb807e5e8721b888a34736ada458209a40")
    (DREYECK/SHOP3::NEXT-TASK
     DREYECK/SHOP3::EXECUTE-EIGHTH-DREYECK-EXTRACTION-COMMIT-3))))

 (:DELETION-SET
  (:COUNT 6)
  (:PATHS
   ("hyperdoc-shop3/package.lisp"
    "hyperdoc-shop3/manual-topics.lisp"
    "hyperdoc-shop3/plan-objects.lisp"
    "hyperdoc-shop3/hyperdoc-maintenance-domain.lisp"
    "hyperdoc-shop3/examples.lisp"
    "hyperdoc-shop3/views.lisp"))
  (:LIVE-ASDF-COMPONENTS NIL)
  (:CANONICAL-EQUIVALENTS-PRESENT T)
  (:CONTENT-EQUIVALENT-MODULO-RECORDED-BOUNDARY-EDITS T)
  (:RECORDED-BOUNDARY-EDITS
   (:DEFPACKAGE-PRIMARY-NAME
    :LEGACY-PACKAGE-NICKNAME
    :IN-PACKAGE-OWNER
    :FIXTURE-READER-PACKAGE)))

 (:REFERENCE-LINT-IMPLEMENTATION
  (:CHECKER-PATH "tools/check-shop3-reference-boundary.lisp")
  (:CHECKER-LANGUAGE :COMMON-LISP)
  (:GATE-PATH "tools/pre-commit-gate.sh")
  (:GATE-ADAPTER-LANGUAGE :SHELL)
  (:TEST-PATHS
   ("tools/testdata/shop3-reference-boundary/allowed-added-lines.diff"
    "tools/testdata/shop3-reference-boundary/rejected-added-lines.diff"))
  (:INPUT :STAGED-ADDED-LINES)
  (:IMPLEMENTED-IN-PREPARATION NIL))

 (:FORBIDDEN-NEW-LIVE-REFERENCES
  (:POLICY :ADDED-LINES-ONLY)
  (:CLASSIFY-BY (:PATH :REFERENCE-KIND))
  (:NEW-ASDF-DEPENDENCY
   (":HYPERDOC/SHOP3" "#:HYPERDOC/SHOP3"))
  (:NEW-PACKAGE-QUALIFIER
   ("HYPERDOC/SHOP3:" "HYPERDOC/SHOP3::"))
  (:NEW-IN-PACKAGE
   (":HYPERDOC/SHOP3" "#:HYPERDOC/SHOP3" "\"HYPERDOC/SHOP3\""))
  (:NEW-ASDF-COMPONENT-ROOT "hyperdoc-shop3/")
  (:NEW-PRIMARY-OWNER-CLAIM "(DEFPACKAGE #:HYPERDOC/SHOP3"))

 (:ALLOWED-REFERENCE-CLASSES
  (:COMPATIBILITY-SYSTEM-DEFINITION
   ((:PATH "hyperdoc.asd" :KIND :COMPATIBILITY-DEFSYSTEM)))
  (:LEGACY-PACKAGE-NICKNAME-DEFINITION
   ((:PATH "dreyeck/shop3/package.lisp" :KIND :PACKAGE-NICKNAME)))
  (:PROVIDER-BOUNDARY-FILES-PENDING-LATER-EXTRACTION
   ((:PATH "hyperdoc-shop3/provider-boundary-package.lisp"
     :KIND :PROVIDER-PACKAGE-DEFINITION)
    (:PATH "hyperdoc-shop3/provider-boundary.lisp"
     :KIND :PROVIDER-DEPENDENCY-AND-REGISTRY)))
  (:COMPATIBILITY-TESTS
   ((:PATH "tests/projection-pipeline-dmx-annotation-smoke.lisp"
     :KIND :COMPATIBILITY-LOAD-AND-PACKAGE-LOOKUP)
    (:PATH "tests/runtime-coherence-smoke.lisp"
     :KIND :FORBIDDEN-CORE-DEPENDENCY-ASSERTION)
    (:PATH "tests/shop3-provider-boundary-smoke.lisp"
     :KIND :PROVIDER-BOUNDARY-CONTRACT)
    (:PATH "tests/refactor-hyperdoc-upstream-core-plan-smoke.lisp"
     :KIND :PROVIDER-BOUNDARY-INVENTORY)
    (:PATH "tests/executable-dita-tasks-smoke.lisp"
     :KIND :EXISTING-FORBIDDEN-SYSTEM-SET-ONLY
     :REUSE-FOR-LINT-TESTS NIL)))
  (:HISTORICAL-EVIDENCE
   ((:PATH-CLASS "hyperdoc/evidence/refactor-hyperdoc-*.sexp"
     :KIND :RECONSTRUCTIVE-EXTRACTION-EVIDENCE)))
  (:DEFERRED-DOCUMENTATION
   ((:PATH "hyperdoc/Debug SHOP3 find-plans.html")
    (:PATH "hyperdoc/Kioskbeerli Pi simulation.html")
    (:PATH "hyperdoc/Kioskbeerli sops-nix secrets.html")
    (:PATH "hyperdoc/Parsing SHOP3 Introduction into Topics.html")
    (:PATH "hyperdoc/Projection Pipeline Operator Plan.html")
    (:PATH "hyperdoc/SHOP3 ASDF Refactor Plan Example.html")
    (:PATH "hyperdoc/SHOP3 Parser Documentation Plan and SCXML.html")
    (:PATH "hyperdoc/SHOP3 Planning API Reference.html")
    (:PATH "hyperdoc/SHOP3 Planning Layer for HyperDoc.html")
    (:PATH "hyperdoc/Using SHOP3 Planning in HyperDoc.html")
    (:PATH "hyperdoc/kernighan-plauger-critical-reading-style-plan.sexp")
    (:PATH "hyperdoc/projection-pipeline-operator.lisp")))
  (:DEFERRED-PLAN-AND-SCXML-ARTIFACTS
   ((:PATH "hyperdoc-shop3/shop3-parser-documentation-plan.sexp"
     :KIND :DEFERRED-PLAN)
    (:PATH "hyperdoc-shop3/shop3-parser-documentation-workflow.scxml"
     :KIND :DEFERRED-SCXML)))
  (:TEST-FIXTURES-WHOSE-PURPOSE-IS-TO-EXERCISE-THE-LINT
   ((:PATH
     "tools/testdata/shop3-reference-boundary/allowed-added-lines.diff"
     :KIND :POSITIVE-FIXTURE)
    (:PATH
     "tools/testdata/shop3-reference-boundary/rejected-added-lines.diff"
     :KIND :NEGATIVE-FIXTURE))))

 (:EXECUTION-CHANGED-PATH-CONTRACT
  (:DELETIONS
   ("hyperdoc-shop3/package.lisp"
    "hyperdoc-shop3/manual-topics.lisp"
    "hyperdoc-shop3/plan-objects.lisp"
    "hyperdoc-shop3/hyperdoc-maintenance-domain.lisp"
    "hyperdoc-shop3/examples.lisp"
    "hyperdoc-shop3/views.lisp"))
  (:MODIFICATIONS
   ("tools/pre-commit-gate.sh"))
  (:ADDITIONS
   ("tools/check-shop3-reference-boundary.lisp"
    "tools/testdata/shop3-reference-boundary/allowed-added-lines.diff"
    "tools/testdata/shop3-reference-boundary/rejected-added-lines.diff"
    "hyperdoc/evidence/refactor-hyperdoc-eighth-extraction-commit-3-execution.sexp"))
  (:EXCLUDED
   ((:PATH "dreyeck.asd" :REASON :ASDF-DEFINITION-UNCHANGED)
    (:PATH "hyperdoc.asd" :REASON :COMPATIBILITY-SYSTEM-UNCHANGED)
    (:PATH "hyperdoc-shop3/provider-boundary-package.lisp"
     :REASON :PROVIDER-BOUNDARY-MOVE-DEFERRED)
    (:PATH "hyperdoc-shop3/provider-boundary.lisp"
     :REASON :PROVIDER-BOUNDARY-MOVE-DEFERRED)
    (:PATH "hyperdoc-shop3/shop3-parser-documentation-plan.sexp"
     :REASON :DOCUMENTATION-WORKFLOW-MOVE-DEFERRED)
    (:PATH "hyperdoc-shop3/shop3-parser-documentation-workflow.scxml"
     :REASON :DOCUMENTATION-WORKFLOW-MOVE-DEFERRED)
    (:PATH "dreyeck/shop3/plan-objects.lisp"
     :REASON :PROJECTION-REPAIR-DEFERRED)
    (:PATH "dreyeck/shop3/hyperdoc-maintenance-domain.lisp"
     :REASON :PROJECTION-REPAIR-DEFERRED)
    (:PATH "dreyeck/shop3/extraction-planning/runner.lisp"
     :REASON :PROJECTION-REPAIR-DEFERRED)
    (:PATH "dreyeck/shop3/extraction-planning/tests/smoke.lisp"
     :REASON :PROJECTION-REPAIR-DEFERRED))))

 (:EXECUTION-ACCEPTANCE
  ((:SIX-LEGACY-IMPLEMENTATION-COPIES-ABSENT T)
   (:CANONICAL-SIX-COPIES-PRESENT T)
   (:DREYECK/SHOP3-DIRECT-COMPONENTS 6)
   (:HYPERDOC/SHOP3-DIRECT-COMPONENTS 0)
   (:HYPERDOC/SHOP3-DEPENDS-ON (:DREYECK/SHOP3))
   (:PRIMARY-PACKAGE :DREYECK/SHOP3)
   (:LEGACY-PACKAGE-NICKNAME :HYPERDOC/SHOP3)
   (:DIRECT-ASDF-LOAD :PASSED)
   (:COMPATIBILITY-ASDF-LOAD :PASSED)
   (:DIRECT-GAP-CANARY :PASSED)
   (:COMPATIBILITY-GAP-CANARY :PASSED)
   (:DUAL-LOAD-CANARY :PASSED)
   (:REFERENCE-LINT-REJECTION-FIXTURES :PASSED)
   (:REFERENCE-LINT-ALLOWANCE-FIXTURES :PASSED)
   (:PROVIDER-BOUNDARY-TESTS :PASSED)
   (:PROVIDER-BOUNDARY-FILES :UNCHANGED)
   (:DOCUMENTATION-WORKFLOWS :UNCHANGED)
   (:PROJECTION-REPAIR :NOT-PERFORMED)
   (:REPOSITORY-LOAD-GATE :PASSED)))

 (:DEFERRED-TASKS
  ((:TASK :MOVE-PROVIDER-BOUNDARY :STATUS :DEFERRED)
   (:TASK :MOVE-OR-REWRITE-DOCUMENTATION-WORKFLOWS :STATUS :DEFERRED)
   (:TASK :REPAIR-PLAN-TREE-PROJECTION :STATUS :DEFERRED)))

 (:PREPARATION-CHANGED-PATH-CONTRACT
  ("dreyeck.asd"
   "dreyeck/shop3/extraction-planning/preparation-domain.lisp"
   "dreyeck/shop3/extraction-planning/preparation-problem.lisp"
   "dreyeck/shop3/extraction-planning/runner.lisp"
   "dreyeck/shop3/extraction-planning/tests/smoke.lisp"
   "hyperdoc/refactor-hyperdoc-reusable-extraction-htn.sexp"
   "hyperdoc/evidence/refactor-hyperdoc-eighth-extraction-commit-3-preparation.sexp"))
 (:PATH-CONTRACT-DEVIATION NIL)

 (:VALIDATION
  ((:CHECK :PREPARATION-DOMAIN-REGISTERED :STATUS :PASSED)
   (:CHECK :PREPARATION-PROBLEM-REGISTERED :STATUS :PASSED)
   (:CHECK :LIVE-FIND-PLANS :STATUS :PASSED)
   (:CHECK :HEURISTIC-FALLBACK :EXPECTED NIL :ACTUAL NIL :STATUS :PASSED)
   (:CHECK :EXACT-PLAN-LENGTH :EXPECTED 6 :ACTUAL 6 :STATUS :PASSED)
   (:CHECK :PLAN-TREE-PRESENT :STATUS :PASSED)
   (:CHECK :FINAL-STATE-PRESENT :STATUS :PASSED)
   (:CHECK :FINAL-STATE-COMMIT-3-PREPARED :STATUS :PASSED)
   (:CHECK :ASDF-LOAD
    :SYSTEM :DREYECK/SHOP3/EXTRACTION-PLANNING
    :MARKER "PREPARATION_LOAD_OK"
    :STATUS :PASSED)
   (:CHECK :ASDF-TEST
    :SYSTEM :DREYECK/SHOP3/EXTRACTION-PLANNING/TESTS
    :MARKER "PREPARATION_TEST_OK"
    :STATUS :PASSED)
   (:CHECK :PREPARATION-ARTIFACT-SAFE-SINGLE-FORM :STATUS :PASSED)
   (:CHECK :REUSABLE-HTN-SAFE-SINGLE-FORM :STATUS :PASSED)
   (:CHECK :SIX-LEGACY-COPIES-STILL-PRESENT :STATUS :PASSED)
   (:CHECK :NO-LINT-IMPLEMENTATION-ADDED :STATUS :PASSED)
   (:CHECK :NO-LINT-TESTS-ADDED :STATUS :PASSED)
   (:CHECK :NO-EXECUTION-EVIDENCE-ADDED :STATUS :PASSED)
   (:CHECK :ONLY-CONTRACTED-PREPARATION-PATHS-CHANGED
    :EXPECTED 7 :ACTUAL 7 :STATUS :PASSED)
   (:CHECK :GIT-DIFF-CHECK :STATUS :PASSED)
   (:CHECK :REPOSITORY-LOAD-GATE
    :SYSTEM :HYPERBOOK/SERVER :MARKER "LOAD_GATE_OK" :STATUS :PASSED)
   (:CHECK :ORIGINAL-WORKTREE-STAGED-FILES-PRESERVED
    :INDEX-BLOB-IDS
    ("fec17cb44b315313f256f5fd1e647ecee049af95"
     "13289505c477d0bf84d66ed28d97f629683de3bd"
     "c7746ca7cee24ce18a0f1d819e8ede402b602ea5")
    :STATUS :PASSED)
   (:CHECK :TEMPORARY-WORKTREE-REMOVED :STATUS :AFTER-COMMIT)))

 (:NON-ACTIONS
  (:LEGACY-FILES-DELETED 0)
  (:LINT-IMPLEMENTATION-CHANGES NIL)
  (:LINT-TESTS-ADDED NIL)
  (:EXECUTION-EVIDENCE-ADDED NIL)
  (:COMMIT-3-EXECUTED NIL)
  (:PROVIDER-BOUNDARY-MOVE NIL)
  (:DOCUMENTATION-OR-SCXML-MIGRATION NIL)
  (:PLAN-TREE-PROJECTION-REPAIR NIL)
  (:HYPERDOC-PAGE-TOPIC-OR-FEDWIKI-CHANGES NIL)
  (:HAUPTSACHE-RUNTIME-PI-OR-SECRETS-MUTATION NIL)
  (:PUSHED NIL))

 (:ANSWER-RECONSTRUCTION
  (:SURFACE
   (:PROCESS-TRACE
    (:INSPECTED :TRACKED-GATE-REFERENCES-COPIES-AND-ASDF-BOUNDARIES)
    (:INFERRED :NEW-COMMON-LISP-ADDED-LINE-CHECKER-AT-TRACKED-GATE)
    (:DECIDED :SIX-DELETIONS-PLUS-NARROW-PATH-AND-KIND-ALLOWLIST)
    (:EXECUTED :LIVE-SHOP3-PREPARATION-PLAN)
    (:OBSERVED :ONE-SIX-ACTION-PLAN-AND-COMMIT-3-PREPARED-FINAL-STATE)))
  (:ARTIFACT
   (:HYPERDOC-PAGE-DELTA NIL)
   (:LISP-DOMAIN-PROBLEM-RUNNER-AND-SMOKE-DELTA T)
   (:FEDWIKI-TWIN-DELTA NIL)
   (:DAILY-ANCHOR-DELTA NIL)
   (:REPLAY-CHECKS
    (:ASDF-LOAD :ASDF-TEST :LIVE-FIND-PLANS :SAFE-SINGLE-FORM
     :EXACT-CHANGED-PATHS :GIT-DIFF-CHECK :REPOSITORY-LOAD-GATE))))

 (:CLASSIFICATION :EIGHTH-DREYECK-EXTRACTION-COMMIT-3-PREPARED)
 (:NEXT
  (!EXECUTE-EIGHTH-DREYECK-EXTRACTION-COMMIT-3
   :FROM-LIVE-SHOP3-PREPARATION-PLAN T)))
