(defpackage :hyperbook/fedwiki/tests
  (:use :cl)
  (:local-nicknames (:fw :hyperbook/fedwiki) (:v :html-inspector-views))
  (:export :run-tests :serve-browser-witness))
(in-package :hyperbook/fedwiki/tests)

(defun original-page ()
  "Use the existing retained original; do not manufacture a Wiki fixture."
  (let* ((json (with-open-file
                  (in (asdf:system-relative-pathname :hyperbook
                        "dreyeck/work/trails-rendered-evidence/ward.voices.ustawi.wiki--trails-rendered.json"))
                (shasht:read-json in)))
         (fw::*neighborhood* (make-hash-table :test #'equal)))
    ;; No network/sitemap initialization in acceptance. Seed the exact sites
    ;; referenced by the original journal before constructing the page.
    (labels ((site (name)
               (when name
                 (or (gethash name fw::*neighborhood*)
                     (setf (gethash name fw::*neighborhood*)
                           (make-instance 'fw::fedwiki :id (concatenate 'string "fedwiki:" name)))))))
      (loop for entry across (gethash "journal" json)
            do (site (gethash "site" entry))
               (let ((attribution (gethash "attribution" entry)))
                 (when (hash-table-p attribution) (site (gethash "site" attribution)))))
      (let* ((wiki (site "ward.voices.ustawi.wiki"))
             (page (fw::make-fedwiki-page wiki "trails-rendered" "Trails Rendered")))
        (setf (slot-value wiki 'fw::protocol) "http")
        (let ((before (shasht:write-json json nil)))
          (fw::set-page-data page json)
          (assert (equal before (shasht:write-json json nil)) () "Loading mutated the original page JSON."))
        ;; Reference skeletons prevent unrelated link lookups from fetching
        ;; plugin pages during this offline Story test. No target content is
        ;; claimed or executed; only original link titles/slugs are represented.
        (setf (gethash "trails-rendered" (fw::pages-of wiki)) page)
        (dolist (link (fw::wiki-links-of (hyperbook:links-of page)))
          (let ((slug (fw::target-slug-of link)))
            (unless (gethash slug (fw::pages-of wiki))
              (setf (gethash slug (fw::pages-of wiki))
                    (fw::make-fedwiki-page wiki slug (or (fw::target-title-of link) slug))))))
        page))))

(defun story-view (page)
  (or (find "Story" (v:all-views page) :key #'v:view-title :test #'equal)
      (error "Missing Story view")))

(defun run-tests ()
  (let* ((page (original-page))
         (item (find :mech (fw::story-of page) :key #'fw::item-type-of))
         (raw (fw::raw-json-of page))
         (source (find "6405b752d1739af0" (gethash "story" raw)
                       :key (lambda (x) (gethash "id" x)) :test #'equal))
         (before (shasht:write-json raw nil)))
    (assert (equal "6405b752d1739af0" (fw::id-of item)))
    (assert (equal (gethash "text" source) (fw::text-of item)))
    (assert (= 3 (count "code" (gethash "story" raw)
                        :key (lambda (x) (gethash "type" x)) :test #'equal)))
    (assert (every (lambda (x) (and (gethash "id" x) (gethash "type" x))) (gethash "story" raw)))
    (let ((fw::*mech-plugin-host-url* nil))
      (let ((html (v:view-html (story-view page))))
        (assert (search "Wiki plugin host is not configured" html))
        (assert (search "fedwiki-mech-host" html))
        (assert (search "6405b752d1739af0" html))
        (assert (search "data-page-json" html))
        (assert (not (search "<script" html)))))
    (let ((fw::*mech-plugin-host-url* "http://127.0.0.1:8099/"))
      (let* ((view (story-view page)) (html (v:view-html view)))
        (assert (search "http://127.0.0.1:8099/" html))
        (assert (search "No Code item has run" html))
        (assert (member item (mapcar #'cdr (v:view-references view)) :test #'eq))
        (assert (notany (lambda (ref) (typep (cdr ref) 'condition)) (v:view-references view)))))
    (assert (eq item (find :mech (fw::story-of page) :key #'fw::item-type-of)))
    (assert (equal before (shasht:write-json raw nil)))
    (let* ((fw::*neighborhood* (make-hash-table :test #'equal))
           (registered (setf (gethash "ward.voices.ustawi.wiki" fw::*neighborhood*) (fw::origin-of page)))
           (other (make-instance 'fw::fedwiki :id "fedwiki:reader.fixture.test"))
           (remote (fw::make-remote other page)))
      (declare (ignore registered))
      (assert (equalp raw (fw::raw-json-of remote)))
      (assert (not (eq raw (fw::raw-json-of remote))))
      (assert (equal "trails-rendered" (fw::origin-id-of remote)))
      (assert (eq (fw::origin-of page) (fw::origin-of remote))))
    (format t "~&FEDWIKI-MECH-STORY-PASS: original page/IDs/Code preserved, pure actual Story view, host bridge contract.~%"))
  t)

(defun serve-browser-witness (port host-url stop-file)
  "Explicit fresh Inspector witness. Never starts during ASDF TEST-OP."
  (setf fw::*mech-plugin-host-url* host-url)
  (let ((page (original-page)))
    (clog:initialize
     (lambda (body)
       (setf (clog:text (clog:create-style-block body)) clog-moldable-inspector::*css*)
       (let ((inspector (clog-moldable-inspector::create-inspector body
                         :pane-width "700px" :playground? nil)))
         (clog-moldable-inspector::create-pane inspector page :select "Story")))
     :port port :host "127.0.0.1")
    (format t "~&MECH-STORY-BROWSER-READY ~D~%" port)
    (finish-output)
    (unwind-protect
         (loop repeat 2400 until (probe-file stop-file) do (sleep 0.1))
      (clog:shutdown))))
