(defpackage :hyperdoc/tests
  (:use :cl)
  (:export
   :run-hyperdoc-tests

   :run-compile-order-smoke-tests
   :run-forced-compile-order-smoke-tests
   :run-fresh-inspector-compile-smoke-test

   :run-dmx-topic-proxy-smoke-tests
   :run-code-path-graphs-smoke-tests
   :run-whyline-output-questions-smoke-tests
   :run-state-machine-smoke-tests
   :run-snippet-playground-artifact-smoke-tests
   :run-authored-relation-artifact-pattern-smoke-tests
   :run-surface-smoke-tests
   :run-boundary-smoke-tests
   :run-relation-topic-proposals-smoke-tests
   :run-lisp-critic-review-plan-smoke-tests
   :run-lisp-critic-contract-smoke-tests
   :run-dock-presentation-smoke-tests
   :run-dock-annotation-smoke-tests
   :run-mobile-progressive-chrome-smoke-tests
   :run-page-system-smoke-tests
   :run-shop3-page-system-smoke-tests
   :run-dmx-annotations-smoke-tests
   :run-dmx-workspace-annotation-live-smoke-tests
   :run-dmx-workspace-journal-sink-smoke-tests
   :run-dmx-auth-session-boundary-smoke-tests
   :run-dmx-annotation-936040-regression-smoke-tests
   :run-sly-evidence-bounds-smoke-tests
   :run-dmx-workspace-assignment-auth-diagnosis-smoke-tests
   :run-dmx-platform-workspace-assignment-semantics-smoke-tests
   :run-zotero-optional-smoke-tests
   :run-article-allegation-slice-smoke-tests
   :run-fedwiki-materialization-smoke-tests
   :run-authored-html-render-safety-smoke-tests
   :run-lookup-issue-docs-render-smoke-tests
   :run-page-lookup-issues-smoke-tests
   :run-page-lookup-disconnection-smoke-tests
   :run-function-lookup-issues-smoke-tests
   :run-class-lookup-issues-smoke-tests
   :run-collective-knowledge-slice-smoke-tests
   :run-reproducible-devenv-as-knowledge-artifact-slice-smoke-tests
   :run-localhost-fedwiki-page-pipeline-smoke-tests
   :run-localhost-fedwiki-page-promotion-page-and-topic-smoke-test
   :run-localhost-fedwiki-page-promotion-missing-source-fail-soft-smoke-test
   :run-localhost-fedwiki-page-promotion-output-sync-smoke-test
   :run-localhost-fedwiki-page-promotion-workflow-scxml-smoke-tests
   :run-dmx-topicmap-919822-repair-runbook-smoke-test
   :run-localhost-fedwiki-page-promotion-plans-smoke-tests
   :run-topic-factory-snippet-dmx-smoke-tests
   :run-hyperdoc-test-system-runbook-smoke-tests
   :run-dmx-annotation-acceptance-scxml-runbook-smoke-tests
   :run-dmx-mcp-smoke-tests
   :run-dmx-incident-guarded-write-boundary-smoke-test
   :run-dmx-incident-arc-smoke-tests
   :run-dmx-query-layer-smoke-tests
   :run-dm6-page-topicmap-smoke-tests
   :run-topicmap-view-smoke-tests
   :run-dmx-shared-workspace-docs-smoke-tests
   :run-neo4j-duplicate-username-repair-smoke-tests
   :run-hyperdoc-neo4j-topic-delete-tool-operation-ir-smoke-tests
   :run-fedwiki-site-dmx-import-tests
   :run-check-runner-smoke-tests
   :run-fedwiki-story-items-smoke-tests
   :run-view-contract-smoke-tests
   :run-inspector-performance-smoke-tests
   :run-merged-doc-slices-smoke-tests
   :run-iconic-retrieval-smoke-tests
   :run-git-commit-assimilation-smoke-tests
   :run-skillization-smoke-tests
   :run-mech-deployment-provenance-smoke-tests
   :run-kioskberrli-dashboard-smoke-tests
   :run-py4dmx-cluster-smoke-tests
   :run-scxml-compiler-smoke-tests
   :run-interaction-net-smoke-tests
   :run-closure-nor-demo-smoke-tests
   :run-nor-graph-matcher-smoke-tests
   :run-continuation-route-trace-smoke-tests
   :run-shared-projection-ir-smoke-tests
   :run-localhost-first-fedwiki-live-publication-smoke-test
   :run-localhost-first-fedwiki-publication-plan-smoke-test
   :run-missing-local-fedwiki-twin-lookup-issue-smoke-test
   :run-page-lookup-topic-repair-scxml-smoke-tests))
