
(DEFPACKAGE #:DREYECK/CATALOG
  (:USE #:CL)
  (:EXPORT #:CATALOG-PRESENTATION-STATE))

(IN-PACKAGE #:DREYECK/CATALOG)

(DEFUN DREYECK/CATALOG:CATALOG-PRESENTATION-STATE (CATALOG WORKSPACE-TOPICS)
  (LIST :HYPERBOOKS
        (MAPCAR
         (LAMBDA (HYPERBOOK)
           (LIST :ID (HYPERBOOK:ID-OF HYPERBOOK) :LABEL
                 (HYPERBOOK:TITLE-OF HYPERBOOK) :STATE :MATERIALIZED))
         (SORT (COPY-LIST (HYPERBOOK:HYPERBOOKS-OF CATALOG)) #'STRING< :KEY
               #'HYPERBOOK:TITLE-OF))
        :WORKSPACES
        (MAPCAR
         (LAMBDA (TOPIC)
           (LIST :ID (DREYECK/TOPICMAP:TOPICMAP-TOPIC-ID-OF TOPIC) :LABEL
                 (DREYECK/TOPICMAP:TOPICMAP-TOPIC-LABEL-OF TOPIC) :STATE
                 :DISCOVERED))
         WORKSPACE-TOPICS)))



(DEFUN ADMIT (COMMON-LISP-USER::TARGET COMMON-LISP-USER::SYSTEM-DESIGNATOR)
  (ECASE COMMON-LISP-USER::TARGET
    (:CATALOG
     (LET* ((COMMON-LISP-USER::CATALOG HYPERBOOK:*CATALOG*)
            (COMMON-LISP-USER::ID
             (FORMAT NIL "workspace:~A" COMMON-LISP-USER::SYSTEM-DESIGNATOR))
            (COMMON-LISP-USER::EXISTING
             (FIND COMMON-LISP-USER::ID
                   (HYPERBOOK:HYPERBOOKS-OF COMMON-LISP-USER::CATALOG) :KEY
                   #'HYPERBOOK:ID-OF :TEST #'STRING=)))
       (OR COMMON-LISP-USER::EXISTING
           (LET ((COMMON-LISP-USER::OFFER
                  (MAKE-INSTANCE
                   'DREYECK/PAGE-ATTACHED-WORKSPACE-OFFER:PAGE-ATTACHED-WORKSPACE-OFFER
                   :ID COMMON-LISP-USER::ID :TITLE
                   COMMON-LISP-USER::SYSTEM-DESIGNATOR)))
             (SETF (HYPERBOOK:HYPERBOOKS-OF COMMON-LISP-USER::CATALOG)
                     (APPEND
                      (HYPERBOOK:HYPERBOOKS-OF COMMON-LISP-USER::CATALOG)
                      (LIST COMMON-LISP-USER::OFFER)))
             COMMON-LISP-USER::OFFER))))))
