
(DEFPACKAGE #:DREYECK/CATALOG
  (:USE #:CL)
  (:EXPORT #:CATALOG-PRESENTATION-STATE))

(IN-PACKAGE #:DREYECK/CATALOG)

(DEFUN DREYECK/CATALOG:CATALOG-PRESENTATION-STATE (CATALOG WORKSPACE-TOPICS)
  (LIST :HYPERBOOKS
        (MAPCAR
         (LAMBDA (HYPERBOOK)
           (LIST :ID (HYPERBOOK:ID-OF HYPERBOOK) :LABEL
                 (HYPERBOOK:TITLE-OF HYPERBOOK) :STATE :MATERIALIZED))
         (SORT (COPY-LIST (HYPERBOOK:HYPERBOOKS-OF CATALOG)) #'STRING< :KEY
               #'HYPERBOOK:TITLE-OF))
        :WORKSPACES
        (MAPCAR
         (LAMBDA (TOPIC)
           (LIST :ID (DREYECK/TOPICMAP:TOPICMAP-TOPIC-ID-OF TOPIC) :LABEL
                 (DREYECK/TOPICMAP:TOPICMAP-TOPIC-LABEL-OF TOPIC) :STATE
                 :DISCOVERED))
         WORKSPACE-TOPICS)))
