;;;; Package for source-backed FedWiki relation observations.

(defpackage #:dreyeck/fedwiki-source-relations
  (:use #:cl)
  (:export
   #:+fedwiki-source-relations-baseline+
   #:source-fragment-evidence
   #:source-fragment-file-of
   #:source-fragment-definition-of
   #:source-fragment-kind-of
   #:source-fragment-start-line-of
   #:source-fragment-end-line-of
   #:source-fragment-text-of
   #:definition-evidence
   #:definition-evidence-id-of
   #:definition-evidence-name-of
   #:definition-evidence-kind-of
   #:definition-evidence-role-of
   #:definition-evidence-file-of
   #:definition-evidence-fragment-of
   #:typed-source-relation
   #:typed-source-relation-id-of
   #:typed-source-relation-type-of
   #:typed-source-relation-source-of
   #:typed-source-relation-target-of
   #:typed-source-relation-role-of
   #:typed-source-relation-fragment-of
   #:typed-source-relation-derived-from-of
   #:refactoring-hypothesis
   #:refactoring-hypothesis-id-of
   #:refactoring-hypothesis-title-of
   #:refactoring-hypothesis-status-of
   #:refactoring-hypothesis-moved-definitions-of
   #:refactoring-hypothesis-removed-relations-of
   #:refactoring-hypothesis-required-tests-of
   #:refactoring-hypothesis-falsifier-of
   #:refactoring-hypothesis-notes-of
   #:fedwiki-source-relations-observation
   #:fedwiki-source-relations-commit-of
   #:fedwiki-source-relations-system-name-of
   #:fedwiki-source-relations-files-of
   #:fedwiki-source-relations-component-order-of
   #:fedwiki-source-relations-component-fragment-of
   #:fedwiki-source-relations-definitions-of
   #:fedwiki-source-relations-relations-of
   #:fedwiki-source-relations-hypotheses-of
   #:fedwiki-source-relations-task-of
   #:fedwiki-source-relations-task-location-of
   #:fedwiki-source-relations-existing-routine-of
   #:fedwiki-source-relations-routine-effects-of
   #:fedwiki-source-relations-problem-status-of
   #:fedwiki-source-relations-problem-statement-of
   #:fedwiki-source-relations-file
   #:fedwiki-source-relations-definition
   #:make-fedwiki-source-relations-observation
   #:fedwiki-source-relations-example
   #:*fedwiki-source-relations-hyperdoc*))
