
(DEFPACKAGE :DREYECK/FEDWIKI-JOURNAL
  (:USE :CL)
  (:EXPORT #:FEDWIKI-JOURNAL-FINDING
           #:FEDWIKI-JOURNAL-FINDING-PAGE-OF
           #:FEDWIKI-JOURNAL-FINDING-ENTRY-OF
           #:FEDWIKI-JOURNAL-FINDING-KIND-OF
           #:FEDWIKI-JOURNAL-FINDING-OBSERVED-OF
           #:FEDWIKI-JOURNAL-FINDING-EXPECTED-OF
           #:FEDWIKI-JOURNAL-FINDING-DETAILS-OF
           #:JOURNAL-CHECK
           #:FEDWIKI-JOURNAL-COPY-COMPARISON
           #:MAKE-FEDWIKI-JOURNAL-COPY-COMPARISON
           #:JOURNAL-COMPARISON-LEFT-NAME-OF
           #:JOURNAL-COMPARISON-LEFT-PAGE-OF
           #:JOURNAL-COMPARISON-RIGHT-NAME-OF
           #:JOURNAL-COMPARISON-RIGHT-PAGE-OF
           #:JOURNAL-COMPARISON-MISMATCHES-OF
           #:JOURNAL-DATE-MISMATCHES))
