
(IN-PACKAGE :DREYECK/FEDWIKI-JOURNAL)

(DEFCLASS FEDWIKI-JOURNAL-FINDING NIL
          ((PAGE :INITARG :PAGE :READER FEDWIKI-JOURNAL-FINDING-PAGE-OF)
           (ENTRY :INITARG :ENTRY :READER FEDWIKI-JOURNAL-FINDING-ENTRY-OF)
           (KIND :INITARG :KIND :READER FEDWIKI-JOURNAL-FINDING-KIND-OF)
           (OBSERVED :INITARG :OBSERVED :READER
            FEDWIKI-JOURNAL-FINDING-OBSERVED-OF)
           (EXPECTED :INITARG :EXPECTED :READER
            FEDWIKI-JOURNAL-FINDING-EXPECTED-OF)
           (DETAILS :INITARG :DETAILS :INITFORM NIL :READER
            FEDWIKI-JOURNAL-FINDING-DETAILS-OF)))

(DEFMETHOD PRINT-OBJECT ((FINDING FEDWIKI-JOURNAL-FINDING) STREAM)
  (PRINT-UNREADABLE-OBJECT (FINDING STREAM :TYPE T :IDENTITY T)
    (FORMAT STREAM "~S ~A" (FEDWIKI-JOURNAL-FINDING-KIND-OF FINDING)
            (FEDWIKI-JOURNAL-FINDING-OBSERVED-OF FINDING))))

(DEFGENERIC JOURNAL-CHECK
    (PAGE &KEY NOW FUTURE-TOLERANCE-SECONDS))

(DEFCLASS FEDWIKI-JOURNAL-REPAIR-CANDIDATE NIL ((PAGE :READER REPAIR-PAGE-OF :INITARG :PAGE) (SOURCE-JSON :READER REPAIR-SOURCE-JSON-OF :INITARG :SOURCE-JSON) (REPAIRED-JSON :READER REPAIRED-PAGE-JSON-OF :INITARG :REPAIRED-JSON) (REPAIRS :READER REPAIRS-OF :INITARG :REPAIRS)))

(DEFUN COPY-JSON-VALUE (VALUE) (COND ((HASH-TABLE-P VALUE) (LET ((COPY (MAKE-HASH-TABLE :TEST (FUNCTION EQUAL)))) (MAPHASH (LAMBDA (KEY CHILD) (SETF (GETHASH KEY COPY) (COPY-JSON-VALUE CHILD))) VALUE) COPY)) ((STRINGP VALUE) VALUE) ((VECTORP VALUE) (MAP (QUOTE VECTOR) (FUNCTION COPY-JSON-VALUE) VALUE)) ((CONSP VALUE) (MAPCAR (FUNCTION COPY-JSON-VALUE) VALUE)) (T VALUE)))

(DEFUN REPAIR-JOURNAL-DATE-DOMAIN (PAGE PAGE-JSON &KEY (NOW (GET-UNIVERSAL-TIME)) (FUTURE-TOLERANCE-SECONDS 86400)) (LET* ((FINDINGS (JOURNAL-CHECK PAGE :NOW NOW :FUTURE-TOLERANCE-SECONDS FUTURE-TOLERANCE-SECONDS)) (PAGE-JOURNAL (HYPERBOOK/FEDWIKI::JOURNAL-OF PAGE)) (REPAIRED-JSON (COPY-JSON-VALUE PAGE-JSON)) (RAW-JOURNAL (GETHASH "journal" REPAIRED-JSON)) (OFFSET-MS 2208988800000) (REPAIRS (QUOTE NIL))) (UNLESS (= (LENGTH PAGE-JOURNAL) (LENGTH RAW-JOURNAL)) (ERROR "Page journal and raw JSON journal differ in length.")) (DOLIST (FINDING FINDINGS) (WHEN (EQ :DATE-DOMAIN (FEDWIKI-JOURNAL-FINDING-KIND-OF FINDING)) (LET* ((ENTRY (FEDWIKI-JOURNAL-FINDING-ENTRY-OF FINDING)) (INDEX (POSITION ENTRY PAGE-JOURNAL :TEST (FUNCTION EQ)))) (UNLESS INDEX (ERROR "Finding entry is absent from the page journal.")) (LET* ((RAW-ENTRY (ELT RAW-JOURNAL INDEX)) (OBSERVED (GETHASH "date" RAW-ENTRY)) (PROPOSED (- OBSERVED OFFSET-MS))) (PUSH (LIST :ENTRY-INDEX INDEX :ENTRY-TYPE (GETHASH "type" RAW-ENTRY) :FROM OBSERVED :TO PROPOSED) REPAIRS) (SETF (GETHASH "date" RAW-ENTRY) PROPOSED))))) (MAKE-INSTANCE (QUOTE FEDWIKI-JOURNAL-REPAIR-CANDIDATE) :PAGE PAGE :SOURCE-JSON PAGE-JSON :REPAIRED-JSON REPAIRED-JSON :REPAIRS (NREVERSE REPAIRS))))

(DEFMETHOD JOURNAL-CHECK
           ((PAGE HYPERBOOK/FEDWIKI::FEDWIKI-PAGE)
            &KEY (NOW (GET-UNIVERSAL-TIME)) (FUTURE-TOLERANCE-SECONDS 86400))
  (LET ((LATEST-PLAUSIBLE (+ NOW FUTURE-TOLERANCE-SECONDS)))
    (REMOVE NIL
            (MAP 'LIST
                 (LAMBDA (ENTRY)
                   (LET ((DATE (HYPERBOOK/FEDWIKI::DATE-OF ENTRY)))
                     (WHEN DATE
                       (LET ((OBSERVED
                              (LOCAL-TIME:TIMESTAMP-TO-UNIVERSAL DATE)))
                         (WHEN (> OBSERVED LATEST-PLAUSIBLE)
                           (MAKE-INSTANCE 'FEDWIKI-JOURNAL-FINDING :PAGE PAGE
                                          :ENTRY ENTRY :KIND :DATE-DOMAIN
                                          :OBSERVED DATE :EXPECTED
                                          (LIST :NOT-AFTER-UNIVERSAL-TIME
                                                LATEST-PLAUSIBLE)
                                          :DETAILS
                                          (LIST :ENTRY-TYPE
                                                (HYPERBOOK/FEDWIKI::ENTRY-TYPE-OF
                                                 ENTRY)
                                                :OBSERVED-UNIVERSAL-TIME
                                                OBSERVED :NOW NOW
                                                :FUTURE-TOLERANCE-SECONDS
                                                FUTURE-TOLERANCE-SECONDS)))))))
                 (HYPERBOOK/FEDWIKI::JOURNAL-OF PAGE)))))
