
(IN-PACKAGE :DREYECK/FEDWIKI-JOURNAL)

(DEFCLASS FEDWIKI-JOURNAL-FINDING NIL
          ((PAGE :INITARG :PAGE :READER FEDWIKI-JOURNAL-FINDING-PAGE-OF)
           (ENTRY :INITARG :ENTRY :READER FEDWIKI-JOURNAL-FINDING-ENTRY-OF)
           (KIND :INITARG :KIND :READER FEDWIKI-JOURNAL-FINDING-KIND-OF)
           (OBSERVED :INITARG :OBSERVED :READER
            FEDWIKI-JOURNAL-FINDING-OBSERVED-OF)
           (EXPECTED :INITARG :EXPECTED :READER
            FEDWIKI-JOURNAL-FINDING-EXPECTED-OF)
           (DETAILS :INITARG :DETAILS :INITFORM NIL :READER
            FEDWIKI-JOURNAL-FINDING-DETAILS-OF)))

(DEFMETHOD PRINT-OBJECT ((FINDING FEDWIKI-JOURNAL-FINDING) STREAM)
  (PRINT-UNREADABLE-OBJECT (FINDING STREAM :TYPE T :IDENTITY T)
    (FORMAT STREAM "~S ~A" (FEDWIKI-JOURNAL-FINDING-KIND-OF FINDING)
            (FEDWIKI-JOURNAL-FINDING-OBSERVED-OF FINDING))))

(DEFGENERIC JOURNAL-CHECK
    (PAGE &KEY NOW FUTURE-TOLERANCE-SECONDS))

(DEFUN JOURNAL-ENTRY-TIME-OBSERVATION (ENTRY INDEX)
  (LET ((DATE (AND ENTRY (HYPERBOOK/FEDWIKI::DATE-OF ENTRY))))
    (LIST :INDEX INDEX :TYPE
          (AND ENTRY (HYPERBOOK/FEDWIKI::ENTRY-TYPE-OF ENTRY)) :DATE DATE
          :UNIVERSAL-TIME (AND DATE (LOCAL-TIME:TIMESTAMP-TO-UNIVERSAL DATE)))))

(DEFUN JOURNAL-DATE-MISMATCHES (LEFT-PAGE RIGHT-PAGE)
  (LET ((LEFT (HYPERBOOK/FEDWIKI::JOURNAL-OF LEFT-PAGE))
        (RIGHT (HYPERBOOK/FEDWIKI::JOURNAL-OF RIGHT-PAGE)))
    (LOOP FOR INDEX BELOW (MAX (LENGTH LEFT) (LENGTH RIGHT))
          FOR L = (JOURNAL-ENTRY-TIME-OBSERVATION
                   (AND (< INDEX (LENGTH LEFT)) (ELT LEFT INDEX)) INDEX)
          FOR R = (JOURNAL-ENTRY-TIME-OBSERVATION
                   (AND (< INDEX (LENGTH RIGHT)) (ELT RIGHT INDEX)) INDEX)
          UNLESS (AND (EQL (GETF L :TYPE) (GETF R :TYPE))
                      (EQL (GETF L :UNIVERSAL-TIME) (GETF R :UNIVERSAL-TIME)))
          COLLECT (LIST :INDEX INDEX :LEFT L :RIGHT R :DELTA-SECONDS
                        (LET ((LT (GETF L :UNIVERSAL-TIME))
                              (RT (GETF R :UNIVERSAL-TIME)))
                          (AND LT RT (- RT LT)))))))

(DEFCLASS FEDWIKI-JOURNAL-COPY-COMPARISON NIL
          ((LEFT-NAME :INITARG :LEFT-NAME :READER
            JOURNAL-COMPARISON-LEFT-NAME-OF)
           (LEFT-PAGE :INITARG :LEFT-PAGE :READER
            JOURNAL-COMPARISON-LEFT-PAGE-OF)
           (RIGHT-NAME :INITARG :RIGHT-NAME :READER
            JOURNAL-COMPARISON-RIGHT-NAME-OF)
           (RIGHT-PAGE :INITARG :RIGHT-PAGE :READER
            JOURNAL-COMPARISON-RIGHT-PAGE-OF)
           (MISMATCHES :INITARG :MISMATCHES :READER
            JOURNAL-COMPARISON-MISMATCHES-OF)))

(DEFUN MAKE-FEDWIKI-JOURNAL-COPY-COMPARISON
       (LEFT-NAME LEFT-PAGE RIGHT-NAME RIGHT-PAGE)
  (MAKE-INSTANCE 'FEDWIKI-JOURNAL-COPY-COMPARISON :LEFT-NAME LEFT-NAME
                 :LEFT-PAGE LEFT-PAGE :RIGHT-NAME RIGHT-NAME :RIGHT-PAGE
                 RIGHT-PAGE :MISMATCHES
                 (JOURNAL-DATE-MISMATCHES LEFT-PAGE RIGHT-PAGE)))

(DEFCLASS FEDWIKI-JOURNAL-REPAIR-CANDIDATE NIL ((PAGE :READER REPAIR-PAGE-OF :INITARG :PAGE) (SOURCE-JSON :READER REPAIR-SOURCE-JSON-OF :INITARG :SOURCE-JSON) (REPAIRED-JSON :READER REPAIRED-PAGE-JSON-OF :INITARG :REPAIRED-JSON) (REPAIRS :READER REPAIRS-OF :INITARG :REPAIRS)))

(DEFUN COPY-JSON-VALUE (VALUE) (COND ((HASH-TABLE-P VALUE) (LET ((COPY (MAKE-HASH-TABLE :TEST (FUNCTION EQUAL)))) (MAPHASH (LAMBDA (KEY CHILD) (SETF (GETHASH KEY COPY) (COPY-JSON-VALUE CHILD))) VALUE) COPY)) ((STRINGP VALUE) VALUE) ((VECTORP VALUE) (MAP (QUOTE VECTOR) (FUNCTION COPY-JSON-VALUE) VALUE)) ((CONSP VALUE) (MAPCAR (FUNCTION COPY-JSON-VALUE) VALUE)) (T VALUE)))

(DEFUN REPAIR-JOURNAL-DATE-DOMAIN (PAGE PAGE-JSON &KEY (NOW (GET-UNIVERSAL-TIME)) (FUTURE-TOLERANCE-SECONDS 86400)) (LET* ((FINDINGS (JOURNAL-CHECK PAGE :NOW NOW :FUTURE-TOLERANCE-SECONDS FUTURE-TOLERANCE-SECONDS)) (PAGE-JOURNAL (HYPERBOOK/FEDWIKI::JOURNAL-OF PAGE)) (REPAIRED-JSON (COPY-JSON-VALUE PAGE-JSON)) (RAW-JOURNAL (GETHASH "journal" REPAIRED-JSON)) (OFFSET-MS 2208988800000) (REPAIRS (QUOTE NIL))) (UNLESS (= (LENGTH PAGE-JOURNAL) (LENGTH RAW-JOURNAL)) (ERROR "Page journal and raw JSON journal differ in length.")) (DOLIST (FINDING FINDINGS) (WHEN (EQ :DATE-DOMAIN (FEDWIKI-JOURNAL-FINDING-KIND-OF FINDING)) (LET* ((ENTRY (FEDWIKI-JOURNAL-FINDING-ENTRY-OF FINDING)) (INDEX (POSITION ENTRY PAGE-JOURNAL :TEST (FUNCTION EQ)))) (UNLESS INDEX (ERROR "Finding entry is absent from the page journal.")) (LET* ((RAW-ENTRY (ELT RAW-JOURNAL INDEX)) (OBSERVED (GETHASH "date" RAW-ENTRY)) (PROPOSED (- OBSERVED OFFSET-MS))) (PUSH (LIST :ENTRY-INDEX INDEX :ENTRY-TYPE (GETHASH "type" RAW-ENTRY) :FROM OBSERVED :TO PROPOSED) REPAIRS) (SETF (GETHASH "date" RAW-ENTRY) PROPOSED))))) (MAKE-INSTANCE (QUOTE FEDWIKI-JOURNAL-REPAIR-CANDIDATE) :PAGE PAGE :SOURCE-JSON PAGE-JSON :REPAIRED-JSON REPAIRED-JSON :REPAIRS (NREVERSE REPAIRS))))

(DEFMETHOD JOURNAL-CHECK
           ((PAGE HYPERBOOK/FEDWIKI::FEDWIKI-PAGE)
            &KEY (NOW (GET-UNIVERSAL-TIME)) (FUTURE-TOLERANCE-SECONDS 86400))
  (LET ((LATEST-PLAUSIBLE (+ NOW FUTURE-TOLERANCE-SECONDS)))
    (REMOVE NIL
            (MAP 'LIST
                 (LAMBDA (ENTRY)
                   (LET ((DATE (HYPERBOOK/FEDWIKI::DATE-OF ENTRY)))
                     (WHEN DATE
                       (LET ((OBSERVED
                              (LOCAL-TIME:TIMESTAMP-TO-UNIVERSAL DATE)))
                         (WHEN (> OBSERVED LATEST-PLAUSIBLE)
                           (MAKE-INSTANCE 'FEDWIKI-JOURNAL-FINDING :PAGE PAGE
                                          :ENTRY ENTRY :KIND :DATE-DOMAIN
                                          :OBSERVED DATE :EXPECTED
                                          (LIST :NOT-AFTER-UNIVERSAL-TIME
                                                LATEST-PLAUSIBLE)
                                          :DETAILS
                                          (LIST :ENTRY-TYPE
                                                (HYPERBOOK/FEDWIKI::ENTRY-TYPE-OF
                                                 ENTRY)
                                                :OBSERVED-UNIVERSAL-TIME
                                                OBSERVED :NOW NOW
                                                :FUTURE-TOLERANCE-SECONDS
                                                FUTURE-TOLERANCE-SECONDS)))))))
                 (HYPERBOOK/FEDWIKI::JOURNAL-OF PAGE)))))
