;;;; Repository and Revision as Evidence Identity

(IN-PACKAGE #:DREYECK/GIT)

(DEFCLASS GIT-REVISION-REFERENCE (GIT-COMMIT)
          ((AUTHORITY :INITARG :AUTHORITY :READER GIT-REVISION-AUTHORITY-OF)
           (DISPLAY-ID :INITARG :DISPLAY-ID :READER GIT-REVISION-DISPLAY-ID-OF)
           (ROLE :INITARG :ROLE :READER GIT-REVISION-ROLE-OF)
           (WEB-URL :INITARG :WEB-URL :READER GIT-REVISION-WEB-URL-OF :INITFORM
            NIL)
           (FILES :ACCESSOR GIT-REVISION-FILES-OF :INITFORM NIL))
          (:DOCUMENTATION
           "An explicit evidence identity: repository authority plus full OID. Display id is presentation only; inherited Git readers use the full hash and local checkout."))

(DEFCLASS GIT-EVIDENCE-FILE (GIT-FILE-AT-COMMIT)
          ((LOCATIONS :ACCESSOR GIT-EVIDENCE-FILE-LOCATIONS-OF :INITFORM NIL))
          (:DOCUMENTATION
           "Existing file-at-commit identity with reader-facing evidence locations attached. Locations are Inspector objects, not a new source parser."))

(DEFUN MAKE-GIT-REVISION-REFERENCE
       (
        &KEY REPOSITORY AUTHORITY OID
        (DISPLAY-ID (AND OID (SUBSEQ OID 0 (MIN 7 (LENGTH OID))))) ROLE
        WEB-URL)
  (CHECK-TYPE REPOSITORY GIT-REPOSITORY-CHECKOUT)
  (UNLESS
      (AND (STRINGP AUTHORITY)
           (PLUSP (LENGTH (STRING-TRIM '(#\Space #\Tab #\Newline) AUTHORITY))))
    (ERROR "An evidence revision needs an explicit repository authority."))
  (UNLESS
      (AND (STRINGP OID) (MEMBER (LENGTH OID) '(40 64))
           (EVERY (LAMBDA (C) (DIGIT-CHAR-P C 16)) OID))
    (ERROR "An evidence revision needs a full object id, not a short SHA: ~S"
           OID))
  (UNLESS
      (AND (STRINGP DISPLAY-ID) (PLUSP (LENGTH DISPLAY-ID))
           (<= (LENGTH DISPLAY-ID) (LENGTH OID))
           (STRING-EQUAL DISPLAY-ID OID :END2 (LENGTH DISPLAY-ID)))
    (ERROR "Display id must abbreviate the supplied full OID: ~S" DISPLAY-ID))
  (MAKE-INSTANCE 'GIT-REVISION-REFERENCE :REPOSITORY REPOSITORY :COMMIT-ISH
                 (STRING-DOWNCASE OID) :HASH (STRING-DOWNCASE OID) :AUTHORITY
                 AUTHORITY :DISPLAY-ID DISPLAY-ID :ROLE ROLE :WEB-URL WEB-URL))

(DEFUN GIT-REVISION-IDENTITY (REVISION)
  (LIST (GIT-REVISION-AUTHORITY-OF REVISION) (GIT-COMMIT-HASH-OF REVISION)))

(DEFUN GIT-REVISION-LOCAL-STATUS (REVISION)
  (LET ((REPOSITORY (GIT-COMMIT-REPOSITORY-OF REVISION)))
    (COND
     ((NOT (PROBE-FILE (GIT-REPOSITORY-ROOT-OF REPOSITORY)))
      :CHECKOUT-UNAVAILABLE)
     ((GIT-COMMIT-OBJECT-PRESENT-P REPOSITORY (GIT-COMMIT-HASH-OF REVISION))
      :COMMIT-PRESENT)
     (T :COMMIT-UNAVAILABLE))))

(DEFUN ENSURE-GIT-EVIDENCE-FILE (REVISION PATH)
  (OR
   (FIND PATH (GIT-REVISION-FILES-OF REVISION) :KEY #'GIT-FILE-PATH-OF :TEST
         #'EQUAL)
   (LET ((FILE (MAKE-INSTANCE 'GIT-EVIDENCE-FILE :COMMIT REVISION :PATH PATH)))
     (SETF (GIT-REVISION-FILES-OF REVISION)
             (APPEND (GIT-REVISION-FILES-OF REVISION) (LIST FILE)))
     FILE)))

(DEFUN ADD-GIT-EVIDENCE-LOCATION (FILE LOCATION)
  (PUSHNEW LOCATION (GIT-EVIDENCE-FILE-LOCATIONS-OF FILE) :TEST #'EQ)
  LOCATION)
