
(COMMON-LISP:DEFPACKAGE :DREYECK/HYPERDOC
  (:USE :CL)
  (:EXPORT :HYPERDOC :HTML-PAGE :MAKE-HYPERDOC :DEFHYPERDOC))

(COMMON-LISP:IN-PACKAGE :DREYECK/HYPERDOC)

(COMMON-LISP:DEFCLASS DREYECK/HYPERDOC:HYPERDOC (HYPERDOC:HYPERDOC)
                      COMMON-LISP:NIL
                      (:DOCUMENTATION
                       "Dreyeck page policy, selected without redefining upstream methods."))

(COMMON-LISP:DEFCLASS DREYECK/HYPERDOC:HTML-PAGE (HYPERDOC:HTML-PAGE)
                      COMMON-LISP:NIL)

(COMMON-LISP:DEFUN DREYECK/HYPERDOC:MAKE-HYPERDOC
                   (COMMON-LISP:&REST DREYECK/HYPERDOC::ARGUMENTS)
  "Construct through the library, then select Dreyeck policy before deferred text loading."
  (COMMON-LISP:CHANGE-CLASS
   (COMMON-LISP:APPLY #'HYPERDOC:MAKE-HYPERDOC DREYECK/HYPERDOC::ARGUMENTS)
   'DREYECK/HYPERDOC:HYPERDOC))

(COMMON-LISP:DEFMACRO DREYECK/HYPERDOC:DEFHYPERDOC
                      (NAME COMMON-LISP:&REST ARGUMENTS)
                      (LIST (QUOTE COMMON-LISP:PROGN)
                            (LIST (QUOTE COMMON-LISP:DEFVAR) NAME
                                  (CONS (QUOTE DREYECK/HYPERDOC:MAKE-HYPERDOC)
                                        ARGUMENTS))
                            (LIST (QUOTE COMMON-LISP:EVAL-WHEN)
                                  (QUOTE (:LOAD-TOPLEVEL))
                                  (LIST (QUOTE HYPERBOOK:REGISTER) NAME))))

(COMMON-LISP:DEFMETHOD HYPERDOC:PAGE-CLASS
                       ((DREYECK/HYPERDOC::BOOK DREYECK/HYPERDOC:HYPERDOC)
                        (COMMON-LISP:TYPE (COMMON-LISP:EQL :HTML)))
  (COMMON-LISP:DECLARE
   (COMMON-LISP:IGNORE DREYECK/HYPERDOC::BOOK COMMON-LISP:TYPE))
  (COMMON-LISP:FIND-CLASS 'DREYECK/HYPERDOC:HTML-PAGE))

(COMMON-LISP:DEFMETHOD HYPERDOC:LOAD-PAGE :AFTER
                       ((DREYECK/HYPERDOC::PAGE DREYECK/HYPERDOC:HTML-PAGE))
  "Use the upstream loading seam to retain Dreyeck default reader context in memory only."
  (COMMON-LISP:LET* ((DREYECK/HYPERDOC::ROOT
                      (PLUMP-PARSER:PARSE "<in-package>CL-USER</in-package>"))
                     (DREYECK/HYPERDOC::CONTEXT
                      (COMMON-LISP:AREF
                       (PLUMP-DOM:CHILDREN DREYECK/HYPERDOC::ROOT) 0)))
    (PLUMP-DOM:REMOVE-CHILD DREYECK/HYPERDOC::CONTEXT)
    (PLUMP-DOM:PREPEND-CHILD
     (COMMON-LISP:SLOT-VALUE DREYECK/HYPERDOC::PAGE 'HYPERDOC::PARSE-TREE)
     DREYECK/HYPERDOC::CONTEXT)))
