(DEFPACKAGE #:DREYECK/PAGE-ATTACHED-WORKSPACE-OFFER
  (:USE #:CL)
  (:EXPORT #:PAGE-ATTACHED-WORKSPACE-OFFER #:PAGE-ATTACHED-WORKSPACE-OF))

(IN-PACKAGE #:DREYECK/PAGE-ATTACHED-WORKSPACE-OFFER)



(DEFCLASS PAGE-ATTACHED-WORKSPACE-OFFER (HYPERBOOK:HYPERBOOK)
          ((TITLE :INITARG :TITLE :READER HYPERBOOK:TITLE-OF)
           (WORKSPACE :INITARG :WORKSPACE :READER PAGE-ATTACHED-WORKSPACE-OF)))

(DEFUN PAGE-SLUG-OF (OFFER)
  (LET* ((ID (HYPERBOOK:ID-OF OFFER))
         (PREFIX "workspace:")
         (PREFIX-LENGTH (LENGTH PREFIX)))
    (UNLESS
        (AND (STRINGP ID) (<= PREFIX-LENGTH (LENGTH ID))
             (STRING= PREFIX ID :END2 PREFIX-LENGTH))
      (ERROR "Not a page-attached workspace subject ID: ~S" ID))
    (LET ((SLUG (SUBSEQ ID PREFIX-LENGTH)))
      (WHEN (ZEROP (LENGTH SLUG))
        (ERROR "Empty page slug in workspace subject ID: ~S" ID))
      SLUG)))

(DEFMETHOD HYPERBOOK:LOOKUP-PATH ((OFFER PAGE-ATTACHED-WORKSPACE-OFFER) PATH)
  (UNLESS (NULL PATH)
    (ERROR "Only root lookup is defined for ~S; got path ~S." OFFER PATH))
  (IF (SLOT-BOUNDP OFFER 'WORKSPACE)
      (PAGE-ATTACHED-WORKSPACE-OF OFFER)
      (LET* ((SLUG (PAGE-SLUG-OF OFFER))
             (WITNESS
              (DREYECK/PAGE-ATTACHED-SYSTEM-PROJECTION::RECONSTRUCT-PAGE-ATTACHED-WORKSPACE
               SLUG))
             (WORKSPACE (GETF WITNESS :WORKSPACE)))
        (UNLESS WORKSPACE
          (ERROR "Workspace reconstruction returned no workspace for ~S."
                 SLUG))
        (SETF (SLOT-VALUE OFFER 'WORKSPACE) WORKSPACE)
        WORKSPACE)))
