(IN-PACKAGE #:DREYECK/PAGE-ATTACHED-SYSTEM-PROJECTION)

(DEFUN RECONSTRUCT-PAGE-ATTACHED-WORKSPACE (SYSTEM-DESIGNATOR)
  (LET* ((SYSTEM (ASDF/SYSTEM:FIND-SYSTEM SYSTEM-DESIGNATOR))
         (SYSTEM-NAME (ASDF/COMPONENT:COMPONENT-NAME SYSTEM))
         (ASD (ASDF/SYSTEM:SYSTEM-SOURCE-FILE SYSTEM))
         (BASE-PROJECTION (PAGE-ATTACHED-SYSTEM-PROJECTION SYSTEM-DESIGNATOR))
         (WORKSPACE-PROJECTION
          (DREYECK/TOPICMAP::PROJECT-PAGE-ATTACHED-WORKSPACE BASE-PROJECTION
                                                             SYSTEM-NAME))
         (WORKSPACE
          (DREYECK/TOPICMAP::MAKE-TOPICMAP-WORKSPACE-FOR-OBJECT
           WORKSPACE-PROJECTION))
         (MATERIALIZED-PROJECTION
          (DREYECK/TOPICMAP:TOPICMAP-PROJECTION-OF WORKSPACE))
         (CURRENT-TOPIC
          (DREYECK/TOPICMAP:TOPICMAP-WORKSPACE-CURRENT-TOPIC WORKSPACE))
         (AUTHORITY-ID (FORMAT NIL "asd:~A" (NAMESTRING ASD))))
    (ASSERT
     (= 3
        (LENGTH
         (DREYECK/TOPICMAP:TOPICMAP-PROJECTION-TOPICS-OF BASE-PROJECTION))))
    (ASSERT
     (= 2
        (LENGTH
         (DREYECK/TOPICMAP:TOPICMAP-PROJECTION-ASSOCIATIONS-OF
          BASE-PROJECTION))))
    (ASSERT
     (= 4
        (LENGTH
         (DREYECK/TOPICMAP:TOPICMAP-PROJECTION-TOPICS-OF
          WORKSPACE-PROJECTION))))
    (ASSERT
     (= 3
        (LENGTH
         (DREYECK/TOPICMAP:TOPICMAP-PROJECTION-ASSOCIATIONS-OF
          WORKSPACE-PROJECTION))))
    (ASSERT WORKSPACE)
    (ASSERT MATERIALIZED-PROJECTION)
    (ASSERT (NOT (EQ WORKSPACE-PROJECTION MATERIALIZED-PROJECTION)))
    (ASSERT CURRENT-TOPIC)
    (ASSERT
     (STRING= AUTHORITY-ID
              (DREYECK/TOPICMAP:TOPICMAP-TOPIC-ID-OF CURRENT-TOPIC)))
    (LIST :SYSTEM-DESIGNATOR SYSTEM-DESIGNATOR :ASD ASD :BASE-PROJECTION
          BASE-PROJECTION :WORKSPACE-PROJECTION WORKSPACE-PROJECTION :WORKSPACE
          WORKSPACE :MATERIALIZED-PROJECTION MATERIALIZED-PROJECTION
          :FRESH-PROJECTION-P T :CURRENT-TOPIC CURRENT-TOPIC :CURRENT-TOPIC-ID
          (DREYECK/TOPICMAP:TOPICMAP-TOPIC-ID-OF CURRENT-TOPIC) :READY-FOR
          :FRESH-IMAGE-RUNNER)))
