(IN-PACKAGE #:DREYECK/PAGE-ATTACHED-SYSTEM-PROJECTION)

(DEFUN PAGE-ATTACHED-SYSTEM-PROJECTION (SYSTEM-DESIGNATOR)
  (LET* ((SYSTEM (ASDF/SYSTEM:FIND-SYSTEM SYSTEM-DESIGNATOR))
         (ASD (ASDF/SYSTEM:SYSTEM-SOURCE-FILE SYSTEM))
         (DEFINED-SYSTEM-NAMES
          (DREYECK/PAGE-ATTACHED-ASDF:SYSTEMS-DEFINED-BY-ASD ASD)))
    (DREYECK/TOPICMAP::PAGE-ATTACHED-ASDF-PROJECTION ASD DEFINED-SYSTEM-NAMES)))
