(defpackage #:dreyeck/state-machine
  (:use #:cl)
  (:export #:id-of
           #:make-state-machine-definition
           #:make-state-machine-run
           #:make-state-machine-state
           #:make-state-machine-transition
           #:state-machine-definition
           #:state-machine-definition-acyclic-p-of
           #:state-machine-definition-allow-terminal-outgoing-p-of
           #:state-machine-definition-events-of
           #:state-machine-definition-failure-states-of
           #:state-machine-definition-findings
           #:state-machine-definition-guards-of
           #:state-machine-definition-initial-state-of
           #:state-machine-definition-invariants-of
           #:state-machine-definition-multi-current-p-of
           #:state-machine-definition-multi-initial-p-of
           #:state-machine-definition-notes-of
           #:state-machine-definition-source-evidence-of
           #:state-machine-definition-states-of
           #:state-machine-definition-terminal-states-of
           #:state-machine-definition-transitions-of
           #:state-machine-run
           #:state-machine-run-current-state-of
           #:state-machine-run-end-time-of
           #:state-machine-run-evidence-trace-of
           #:state-machine-run-failure-classification-of
           #:state-machine-run-findings
           #:state-machine-run-input-of
           #:state-machine-run-machine-of
           #:state-machine-run-notes-of
           #:state-machine-run-start-time-of
           #:state-machine-run-status-of
           #:state-machine-run-transition-trace-of
           #:state-machine-run-visited-states-of
           #:state-machine-state
           #:state-machine-state-entry-condition-of
           #:state-machine-state-exit-condition-of
           #:state-machine-state-notes-of
           #:state-machine-state-role-of
           #:state-machine-transition
           #:state-machine-transition-emitted-evidence-of
           #:state-machine-transition-from-state-of
           #:state-machine-transition-guard-of
           #:state-machine-transition-notes-of
           #:state-machine-transition-reversible-p-of
           #:state-machine-transition-side-effects-of
           #:state-machine-transition-to-state-of
           #:state-machine-transition-trigger-of
           #:summary-of
           #:title-of))
