;;;; Qualified mode of the existing relationship request/planner/executor.
(in-package #:dreyeck/work/authoring)

(defclass addresses-creation-plan (work-relationship-creation-plan) ())
(defun %addresses-representation (request position)
  (let* ((statement (subseq (%relationship-representation
                            (work:topic-occurrence-topic (work:work-relationship-creation-from-occurrence request))
                            (work:topic-occurrence-topic (work:work-relationship-creation-to-occurrence request))
                            "work:relation/addresses"
                            (tm:topicmap-topic-label-of (ops:declared-work-topic (work:work-relationship-creation-from-occurrence request)))
                            (tm:topicmap-topic-label-of (ops:declared-work-topic (work:work-relationship-creation-to-occurrence request)))
                            "addresses") 1))
         (close (position #\> statement))
         (qualified (concatenate 'string (subseq statement 0 close)
                                 " data-work-qualification=\"addresses-v1\"" (subseq statement close)))
         (warrant (alexandria:copy-hash-table (work:addresses-warrant request))))
    (setf (gethash "statement" warrant)
          (work::%object "range" (vector (1+ position) (+ position 1 (length qualified))) "text" qualified))
    (work::%validate-warrant warrant)
    (format nil "~%~A~%~A~A-->" qualified work::+addresses-annotation+ (work::encode-addresses-warrant warrant))))

(defun %revalidate-addresses-request (request)
  (unless (and (eq (work:work-relationship-creation-from-occurrence request)
                   (r:operation-request-occurrence (work:work-relationship-creation-selection request)))
               (eq (work:work-relationship-creation-operation request) (w:create-relationship-operation))
               (eq (work:work-relationship-creation-authority-page request)
                   (work:topic-occurrence-page (work:work-relationship-creation-from-occurrence request)))
               (equal (work:work-relationship-creation-authority-snapshot request)
                      (work:topic-occurrence-snapshot (work:work-relationship-creation-from-occurrence request))))
    (error "Complete request does not retain its exact registered source selection"))
  (work::%addresses-read-set-current request)
  (let ((fresh (work::request-addresses-bridge
                (work:work-relationship-creation-selection request)
                (ops:declared-work-topic (work:work-relationship-creation-to-occurrence request)))))
    (unless (equal (work::encode-addresses-warrant (work:addresses-warrant request))
                   (work::encode-addresses-warrant (work:addresses-warrant fresh)))
      (error "Request observations differ from exact full read set"))))
(defun %verify-addresses-plan (plan)
  (let* ((request (work-relationship-creation-plan-request plan))
         (snapshot (work-relationship-creation-plan-snapshot plan))
         (page (work:work-relationship-creation-authority-page request))
         (position (work-relationship-creation-plan-position plan)))
    (%revalidate-addresses-request request)
    (unless (and (equal snapshot (work:work-relationship-creation-authority-snapshot request))
                 (= position (work:relationship-insertion-position snapshot page))
                 (equal (work-relationship-creation-plan-representation plan) (%addresses-representation request position)))
      (error "Forged/inconsistent qualified plan"))
    (dolist (name '("source" "contract"))
      (unless (<= (cdr (work::%range (work::%field (work:addresses-warrant request) name) "scope")) position)
        (error "Insertion before a guarded owner declaration is outside this slice")))
    (let* ((before (work:project-work-breakdown snapshot :source page))
           (candidate (%relationship-candidate plan))
           (after (work:project-work-breakdown candidate :source page))
           (bridge (car (last (work:qualified-bridges after)))))
      (unless (and (= (1+ (length (work:qualified-bridges before))) (length (work:qualified-bridges after)))
                   (equal (mapcar #'%topic-row (tm:topicmap-projection-topics-of before))
                          (mapcar #'%topic-row (tm:topicmap-projection-topics-of after)))
                   (equal (mapcar #'%association-row (tm:topicmap-projection-associations-of before))
                          (mapcar #'%association-row (tm:topicmap-projection-associations-of after))))
        (error "Qualified splice changed local Work graph"))
      (work::%resolve-addresses-bridge bridge :sources
         (acons page candidate (remove page (work:addresses-read-set request) :key #'car)))
      bridge)))

(defun plan-addresses-creation (request)
  (handler-case
      (let* ((page (work:work-relationship-creation-authority-page request))
             (snapshot (work:work-relationship-creation-authority-snapshot request))
             (position (work:relationship-insertion-position snapshot page))
             (plan (make-instance 'addresses-creation-plan :request request :snapshot snapshot :position position
                                  :representation (%addresses-representation request position))))
        (%verify-addresses-plan plan) plan)
    (error (c) (error 'work-relationship-creation-plan-refused :request request
                     :reason "qualified addresses plan refused" :cause c))))

(defun apply-addresses-creation (plan)
  (let* ((request (work-relationship-creation-plan-request plan))
         (page (work:work-relationship-creation-authority-page request))
         (snapshot (work-relationship-creation-plan-snapshot plan))
         (candidate (%relationship-candidate plan)))
    (flet ((refuse (reason &optional cause)
             (error 'work-relationship-creation-apply-refused :plan plan :reason reason :cause cause))
           (unverified (cause)
             (error 'work-relationship-creation-unverified :plan plan :reason (format nil "~A" cause))))
      (handler-case (%verify-addresses-plan plan)
        (error (c) (refuse "qualified plan/read set no longer holds" c)))
      (%replace-source (work::%page-path page) snapshot candidate #'refuse
         :before-install (lambda ()
                           (handler-case (%revalidate-addresses-request request)
                             (error (c) (refuse "complete read set changed before installation" c)))))
      ;; The effect exists now: every later failure is unverified, never rollback.
      (handler-case
          (progn
            (unless (equal candidate (%read-source (work::%page-path page))) (error "Owner differs from installed candidate"))
            (dolist (entry (work:addresses-read-set request))
              (unless (eq page (car entry))
                (unless (equal (cdr entry) (%read-source (work::%page-path (car entry))))
                  (error "Foreign full snapshot changed after installation"))))
            (hyperdoc:load-page page)
            (let* ((projection (work:work-projection :page page))
                   (bridge (car (last (work:qualified-bridges projection)))))
              (multiple-value-bind (association) (work:resolve-addresses-bridge bridge)
                (values association (getf (tm:topicmap-association-properties-of association) :source-occurrence)))))
        (error (c) (unverified c))))))
