;; This file has been generated automatically.
;; Do not edit.

(in-package :hyperbook/wikipedia)

(defparameter *editions*
  #(("trv" "Wikipidiya" "Ruwahan_patas") ("shi" "Wikipidya" "Tasna_Tamzwarut")
    ("guc" "Wikipeetia Wayuunaikiru'u" "Ee'iyalaaya_a'laülaasü")
    ("syl" "ꠍꠤꠟꠐꠤ ꠃꠁꠇꠤꠙꠤꠒꠤꠀ" "ꠝꠥꠟ_ꠚꠣꠔꠣ") ("tly" "Tolyšə Vikipedijə" "Sərlovhə")
    ("zgh" "ⵡⵉⴽⵉⴱⵉⴷⵢⴰ" "ⵜⴰⵙⵏⴰ_ⵏ_ⵓⵙⵏⵓⴱⴳ")
    ("rsk" "Википедия на панонским руским язику" "Главни_бок")
    ("wa" "Wikipedia walon" "Mwaisse_pådje")
    ("lbe" "Лакку мазрал википедия" "Агьаммур_лажин")
    ("or" "ଓଡ଼ିଆ ଉଇକିପିଡ଼ିଆ" "ପ୍ରଧାନ_ପୃଷ୍ଠା")
    ("fo" "Føroysk Wikipedia" "Forsíða")
    ("ang" "Engliscan Ƿikipǣdia" "Heafodtramet")
    ("as" "অসমীয়া ৱিকিপিডিয়া" "বেটুপাত")
    ("ne" "नेपाली विकिपिडिया" "मुख्य_पृष्ठ")
    ("bh" "भोजपुरी विकिपीडिया" "मुख्य_पन्ना")
    ("bxr" "Буряад Википеэди" "Нюур_хуудаһан")
    ("ny" "Chi-Chewa Wikipedia" "Tsamba_Lalikulu")
    ("ny" "Wikipedia mu ChiChewa" "Tsamba_Lalikulu")
    ("bcl" "Wikipedyang Bikol Sentral" "Panginot_na_Pahina")
    ("frp" "Vouiquipèdia en arpetan" "Vouiquipèdia:Reçua_principâla")
    ("ha" "Wikipedia a harshen Hausa" "Babban_shafi")
    ("ks" "کٲشُر وِکیٖپیٖڈیا" "اَہَم_صَفہٕ")
    ("mwl" "Biquipédia" "Biquipédia:Páigina_percipal")
    ("sd" "سنڌي وڪيپيڊيا" "مُک_صفحو") ("so" "Soomaali Wikipedia" "Bogga_Hore")
    ("kbd" "Адыгэбзэ Википедиэ" "НапэкӀуэцӀ_нэхъыщхьэ")
    ("tyv" "Тыва Википедия" "Кол_арын")
    ("mai" "मैथिली विकिपिडिया" "सम्मुख_पन्ना")
    ("azb" "تورکجه ویکیپدیا" "آنا_صفحه")
    ("ady" "Адыгэ Википедие" "НэкӀубгъо_шъхьаӀ")
    ("jam" "Jumiekan Patwa Wikipidia" "Mien_Piej")
    ("olo" "Livvinkarjalan Wikipedii" "Piäsivu")
    ("kbp" "Kabɩyɛ Wikipediya" "Talɩ_ɖeu")
    ("dty" "डोटेली विकिपिडिया" "मुख्य_पन्ना")
    ("atj" "Wikipetcia Atikamekw Nehiromowin" "Otitikowin")
    ("no" "Wikipedia på bokmål og riksmål" "Forside")
    ("no" "Wikipedia på bokmål og riksmål" "Forside")
    ("inh" "ГIалгIай Википеди" "Керттера_оагӀув")
    ("lfn" "Vicipedia en lingua franca nova" "Paje_xef")
    ("sat" "ᱥᱟᱱᱛᱟᱲᱤ ᱣᱤᱠᱤᱯᱤᱰᱤᱭᱟ" "ᱢᱩᱬᱩᱛ_ᱥᱟᱦᱴᱟ")
    ("shn" "ဝီႇၶီႇၽီးတီးယႃးတႆး" "ၼႃႈႁူဝ်ႁႅၵ်ႈ")
    ("hyw" "Արեւմտահայերէն Ուիքիփետիա" "Գլխաւոր_Էջ")
    ("mnw" "ဝဳကဳပဳဒဳယာမန်" "မုက်လိက်တမ်")
    ("gcr" "Wikipédja an kriyòl gwiyannen" "Paj_Prensipal")
    ("szy" "Wikipitiya nu Sakizaya" "saayaway_a_belih")
    ("an" "Wikipedia en aragonés" "Portalada")
    ("yo" "Wikipẹ́díà l'édè Yorùbá" "Ojúewé_Àkọ́kọ́")
    ("io" "Wikipedio en Ido" "Frontispico") ("zh-yue" "粵文維基百科" "頭版")
    ("als" "Alemannischi Wikipedia" "Wikipedia:Houptsyte")
    ("krc" "Къарачай-Малкъар Википедия" "Баш_бет")
    ("new" "नेपालभाषा विकिपिडियाया देवनागरी इन्पुट व्यवस्था" "मू_पौ")
    ("qu" "Qhichwa Wikipidiya" "Qhapaq_p'anqa")
    ("zh-classical" "文言維基大典" "維基大典:卷首") ("sco" "Scots Wikipaedia" "Main_Page")
    ("pl" "Polskojęzyczna Wikipedia" "Wikipedia:Strona_główna")
    ("nds-nl" "Nedersaksiese Wikipedie" "Vöärblad")
    ("war" "Waray Wikipedia" "Syahan_nga_Pakli")
    ("pa" "ਪੰਜਾਬੀ ਵਿਕੀਪੀਡੀਆ" "ਮੁੱਖ_ਸਫ਼ਾ")
    ("bar" "Boarische Wikipedia" "Wikipedia:Hoamseitn")
    ("yi" "יידיש-װיקיפעדיע" "הויפט_זייט")
    ("hy" "Հայերեն Վիքիպեդիա" "Գլխավոր_էջ")
    ("xmf" "მარგალური ვიკიპედია" "დუდხასჷლა")
    ("uz" "Oʻzbekcha Vikipediya" "Bosh_Sahifa")
    ("bo" "བོད་ཡིག་གི་ཝེ་ཁེ་རིག་མཛོད་" "གཙོ་ངོས།")
    ("zea" "Zeêuwstaelihe Wikipedia" "Vòblad")
    ("li" "Limburgse Wikipedia" "Veurblaad")
    ("nn" "Nynorsk Wikipedia" "Hovudside")
    ("arz" "ويكيبيديا مصرى" "الصفحه_الرئيسيه")
    ("sa" "संस्कृतविकिपीडिया" "मुख्यपृष्ठम्")
    ("fy" "Frysktalige Wikipedy" "Haadside")
    ("nah" "Huiquipedia nahuatlahtolcopa" "Calīxatl")
    ("ltg" "Vikipedeja latgaļu volūdā" "Suoku_puslopa")
    ("bjn" "Wikipedia basa Banjar" "Laman_Tatambaian")
    ("mn" "Монгол Википедиа" "Нүүр_хуудас") ("co" "Corsipedia" "Pagina_maestra")
    ("co" "Wikipedia in corsu" "Pagina_maestra")
    ("mg" "Wikipedia amin'ny teny malagasy" "Wikipedia:Fandraisana")
    ("gu" "ગુજરાતી વિકિપીડિયા" "મુખપૃષ્ઠ") ("kn" "ಕನ್ನಡ ವಿಶ್ವಕೋಶ" "ಮುಖ್ಯ_ಪುಟ")
    ("ext" "Wikipedia en estremeñu" "Güiquipedia:Portá")
    ("zh-min-nan" "Wikipedia Bân-lâm-gú" "Thâu-ia̍h")
    ("ss" "Wikipedia siSwati" "Likhasi_Lelikhulu")
    ("jv" "Wikipédia Jawa" "Wikipédia:Pendhapa")
    ("mr" "मराठी विकिपीडिया" "मुखपृष्ठ")
    ("stq" "seelterfräiske Wikipedia" "Haudsiede")
    ("haw" "Hawai‘i Wikipikia" "Ka_papa_kinohi")
    ("km" "វិគីភីឌាភាសាខ្មែរ" "ទំព័រដើម")
    ("lij" "Wikipedia in lìgure" "Pagina_prinçipâ")
    ("mzn" "مازرونی ویکیپدیا" "گت_صفحه") ("ps" "پښتو ويکيپېډيا" "لومړی_مخ")
    ("pap" "Wikipedia na Papiamentu" "Página_Prinsipal")
    ("srn" "Sranan Wikipedia" "Fesipapira")
    ("bat-smg" "Žemaitėška Vikipedėjė" "Pėrms_poslapis")
    ("pnb" "پنجابی وکیپیڈیا" "پہلا_صفہ")
    ("lad" "Vikipedya en lingua Judeo-Espanyola" "La_Primera_Hoja")
    ("ia" "Wikipedia in interlingua" "Pagina_principal")
    ("gn" "Vikipetã avañe'ẽme" "Kuatia_Ñepyrũha")
    ("ay" "Aymar Wikipidiya" "Nayriri_uñstawi")
    ("lmo" "Wikipedia in lumbard" "Pagina_principala")
    ("ace" "Wikipèdia bahsa Acèh" "Ôn_Keue")
    ("map-bms" "Wikipédia basa Banyumasan" "Kaca_Utama")
    ("bug" "Wikipedia basa Ugi" "Watangpola")
    ("vep" "Vepsän Vikipedii" "Pälehtpol’")
    ("se" "davvisámegiel Wikipedia" "Portála:Ovdasiidu")
    ("ckb" "ویکیپیدیای کوردیی ناوەندی" "دەستپێک")
    ("min" "Wikipedia bahaso Minangkabau" "Laman_Utamo")
    ("my" "မြန်မာဝီကီပီးဒီးယား" "ဗဟိုစာမျက်နှာ")
    ("ce" "Нохчийн Википеди" "Коьрта_агӀо")
    ("nds" "Platduutse Wikipedia" "Wikipedia:Hööftsiet")
    ("av" "Авар Википедия" "БетӀераб_гьумер")
    ("hak" "Hak-kâ-ngî Wikipedia" "Thèu-Ya̍p") ("gan" "贛語維基百科" "封面")
    ("en" "English Wikipedia" "Main_Page")
    ("fr" "Wikipédia en français" "Wikipédia:Accueil_principal")
    ("es" "Wikipedia en español" "Wikipedia:Portada")
    ("nl" "Nederlandstalige Wikipedia" "Hoofdpagina")
    ("bg" "Уикипедия на български език" "Начална_страница")
    ("el" "Ελληνική Βικιπαίδεια" "Πύλη:Κύρια")
    ("it" "Wikipedia in italiano" "Pagina_principale")
    ("pt" "Wikipédia em português" "Wikipédia:Página_principal")
    ("la" "Vicipaedia Latina" "Vicipaedia:Pagina_prima")
    ("sl" "Slovenska Wikipedija" "Glavna_stran") ("ko" "한국어 위키백과" "위키백과:대문")
    ("zh" "中文维基百科" "Wikipedia:首页") ("zh" "中文維基百科" "Wikipedia:首页")
    ("diq" "Wikipediyay Zazaki" "Pela_Seri")
    ("lez" "Лезги Википедия" "Кьилин_ччин")
    ("de" "deutschsprachige Wikipedia" "Wikipedia:Hauptseite")
    ("fa" "ویکیپدیای فارسی" "صفحهٔ_اصلی") ("hu" "magyar Wikipédia" "Kezdőlap")
    ("kk" "Қазақша Уикипедия" "Басты_бет")
    ("ba" "Башҡорт Википедияһы" "Баш_бит")
    ("cv" "Чăваш Википедийĕ" "Тĕп_страница")
    ("az" "Azərbaycanca Vikipediya" "Ana_səhifə")
    ("tr" "Türkçe Vikipedi" "Anasayfa")
    ("sh" "Wikipedia na srpskohrvatskom jeziku" "Glavna_stranica")
    ("sh" "Wikipedia na srpskohrvatskom jeziku" "Glavna_stranica")
    ("sh" "Википедија на српскохрватском језику" "Glavna_stranica")
    ("sh" "Википедија на српскохрватском језику" "Glavna_stranica")
    ("rue" "Русиньска Вікіпедія" "Головна_сторінка")
    ("crh" "Qırımtatarca Vikipediya" "Baş_Saife")
    ("ky" "Кыргыз Википедиясы" "Башкы_барак")
    ("tt" "Татар Википедиясе" "Баш_бит") ("ug" "ئۇيغۇرچە ۋىكىپېدىيە" "باش_بەت")
    ("gag" "Gagauzca Vikipediya" "Baş_yaprak")
    ("kaa" "Qaraqalpaqsha Wikipedia" "Bas_bet")
    ("id" "Wikipedia bahasa Indonesia" "Halaman_Utama")
    ("sv" "Svenskspråkiga Wikipedia" "Portal:Huvudsida")
    ("fi" "Suomenkielinen Wikipedia" "Wikipedia:Etusivu")
    ("ja" "ウィキペディア日本語版" "メインページ") ("da" "Dansk Wikipedia" "Forside")
    ("eo" "Vikipedio en Esperanto" "Vikipedio:Ĉefpaĝo")
    ("cs" "Česká Wikipedie" "Hlavní_strana")
    ("sk" "Slovenská Wikipédia" "Hlavná_stránka")
    ("ca" "Viquipèdia en català" "Portada")
    ("uk" "Українська Вікіпедія" "Головна_сторінка")
    ("ar" "ويكيبيديا العربية" "الصفحة_الرئيسة")
    ("ro" "Wikipedia în limba română" "Pagina_principală")
    ("he" "ויקיפדיה העברית" "עמוד_ראשי")
    ("et" "Eestikeelne Vikipeedia" "Vikipeedia:Esileht")
    ("vi" "Wikipedia tiếng Việt" "Trang_Chính")
    ("simple" "Simple English Wikipedia" "Main_Page")
    ("sr" "Википедија на српском језику" "Главна_страна")
    ("lt" "Lietuviškoji Vikipedija" "Pagrindinis_puslapis")
    ("hr" "Wikipedija na hrvatskome jeziku" "Glavna_stranica")
    ("ru" "Русская Википедия" "Заглавная_страница")
    ("eu" "Euskarazko Wikipedia" "Azala")
    ("sq" "Wikipedia Shqip" "Faqja_kryesore")
    ("udm" "Удмурт Википедия" "Кутскон_бам")
    ("sah" "Сахалыы Бикипиэдьийэ" "Сүрүн_сирэй")
    ("os" "Ирон Википеди" "Сæйраг_фарс")
    ("bn" "বাংলা উইকিপিডিয়া" "প্রধান_পাতা")
    ("tk" "Türkmençe Wikipediýa" "Baş_Sahypa")
    ("cu" "Словѣньска Википєдїꙗ" "Главьна_страница")
    ("th" "วิกิพีเดียภาษาไทย" "หน้าหลัก") ("oc" "wikipèdia en occitan" "Acuèlh")
    ("vo" "Vükiped Volapükik" "Cifapad") ("is" "Íslenska Wikipedia" "Forsíða")
    ("hi" "हिन्दी विकिपीडिया" "मुखपृष्ठ")
    ("sw" "Wikipedia ya Kiswahili" "Mwanzo")
    ("lv" "Vikipēdija latviešu valodā" "Sākumlapa")
    ("af" "Afrikaanse Wikipedia" "Tuisblad")
    ("mhr" "Олык Марий Википедий" "Тӱҥ_лаштык")
    ("ceb" "Wikipedya sa Sinugboanon" "Unang_Panid")
    ("gl" "Wikipedia en galego" "Portada")
    ("mk" "Википедија на македонски" "Главна_страница")
    ("ta" "தமிழ் விக்கிப்பீடியா" "முதற்_பக்கம்")
    ("ms" "Wikipedia Bahasa Melayu" "Laman_Utama")
    ("cdo" "Mìng-dĕ̤ng-ngṳ̄ Wikipedia" "Tàu_Hiĕk")
    ("br" "Wikipedia e brezhoneg" "Degemer")
    ("te" "తెలుగు వికీపీడియా" "మొదటి_పేజీ") ("cy" "Wicipedia Cymraeg" "Hafan")
    ("ka" "ქართული ვიკიპედია" "მთავარი_გვერდი")
    ("myv" "Эрзянь Википедия" "Прявтлопа")
    ("ml" "മലയാളം വിക്കിപീഡിയ" "പ്രധാന_താൾ")
    ("ga" "Vicipéid na Gaeilge" "Príomhleathanach")
    ("be" "Беларуская Вікіпедыя" "Галоўная_старонка")
    ("tl" "Wikipediang Tagalog" "Unang_Pahina")
    ("kv" "Коми Википедиа" "Медшӧр_лист_бок")
    ("szl" "Ślōnskŏ Wikipedyjŏ" "Przodniŏ_zajta")
    ("lb" "Lëtzebuergesch Wikipedia" "Haaptsäit")
    ("lb" "Wikipedia op Lëtzebuergesch" "Haaptsäit")
    ("su" "Wikipedia basa Sunda" "Tepas")
    ("mrj" "Кырык мары Википеди" "Тӹнг_ӹлӹштӓш")
    ("bs" "Wikipedia na bosanskom jeziku" "Početna_strana")
    ("scn" "Wikipedia ’n sicilianu" "Pàggina_principali")
    ("ht" "Wikipedya kreyòl ayisyen" "Paj_Prensipal")
    ("ur" "اردو ویکیپیڈیا" "صفحۂ_اول") ("ast" "Wikipedia n'asturianu" "Portada")
    ("wuu" "吴语维基百科" "封面") ("koi" "Перем коми Википедия" "Пондӧтчан_листбок")))
