;;;; Data model for the Goldberg Programmer-as-Reader HyperDoc slice.

(in-package #:hyperdoc-goldberg-programmer-as-reader)

(defclass goldberg-topic ()
  ((id :initarg :id :reader id-of)
   (title :initarg :title :reader title-of)
   (summary :initarg :summary :reader summary-of)
   (references :initarg :references :initform nil :reader references-of)
   (page :initarg :page :initform nil :reader page-of)
   (layer :initarg :layer :initform nil :reader layer-of)))

(defclass goldberg-reader-question ()
  ((id :initarg :id :reader id-of)
   (number :initarg :number :reader question-number-of)
   (layer :initarg :layer :reader layer-of)
   (question-text :initarg :question-text :reader question-text-of)
   (prompt :initarg :prompt :reader prompt-of)
   (summary :initarg :summary :reader summary-of)
   (operation-id :initarg :operation-id :reader operation-id-of)))

(defclass goldberg-reader-operation ()
  ((id :initarg :id :reader id-of)
   (title :initarg :title :reader title-of)
   (question-id :initarg :question-id :reader question-id-of)
   (summary :initarg :summary :reader summary-of)
   (preconditions :initarg :preconditions :initform nil :reader preconditions-of)
   (steps :initarg :steps :initform nil :reader steps-of)
   (result :initarg :result :reader result-of)
   (clickable-expression :initarg :clickable-expression :reader clickable-expression-of)))

(defmethod print-object ((topic goldberg-topic) stream)
  (print-unreadable-object (topic stream :type t)
    (format stream "~A" (title-of topic))))

(defmethod print-object ((question goldberg-reader-question) stream)
  (print-unreadable-object (question stream :type t)
    (format stream "Q~D ~A" (question-number-of question) (question-text-of question))))

(defmethod print-object ((operation goldberg-reader-operation) stream)
  (print-unreadable-object (operation stream :type t)
    (format stream "~A" (title-of operation))))

(defun plist-for-topic (topic)
  (list :id (id-of topic)
        :title (title-of topic)
        :summary (summary-of topic)
        :page (page-of topic)
        :layer (layer-of topic)
        :references (references-of topic)))

(defun plist-for-reader-question (question)
  (list :id (id-of question)
        :number (question-number-of question)
        :layer (layer-of question)
        :question (question-text-of question)
        :prompt (prompt-of question)
        :summary (summary-of question)
        :operation (operation-id-of question)))

(defun plist-for-reader-operation (operation)
  (list :id (id-of operation)
        :title (title-of operation)
        :question (question-id-of operation)
        :summary (summary-of operation)
        :preconditions (preconditions-of operation)
        :steps (steps-of operation)
        :result (result-of operation)
        :clickable-expression (clickable-expression-of operation)))
