(defpackage :interaction-net
  (:use :cl)
  (:export
   #:make-runtime
   #:define-agent
   #:define-symbol
   #:define-rule
   #:define-lafont-rule
   #:parse-net
   #:reduce-net
   #:read-nat
   #:read-list
   #:well-typed-net-p
   #:check-port-compatible
   #:matching-symbols-p
   #:complete-rule-table-p
   #:demo-plus
   #:demo-append-figure9
   #:*demo-runtime*
   #:*figure9-runtime*
   #:net-trace
   #:net-trace-object
   #:reduction-trace
   #:reduction-step
   #:reduction-trace-p
   #:reduction-trace-status
   #:reduction-trace-steps
   #:reduction-trace-total-steps
   #:reduction-trace-final-normal-form
   #:reduction-trace-failure-reason
   #:reduction-step-p
   #:reduction-step-step
   #:reduction-step-active-pair-kinds
   #:reduction-step-active-pair-cell-ids
   #:reduction-step-rule-name
   #:reduction-step-rule-key
   #:reduction-step-new-active-pairs
   #:reduction-limit-reached
   #:duplicate-rule-error
   #:same-symbol-rule-error
   #:unknown-agent-kind
   #:typing-error))
