;;;; Page-local ASDF system for the FedWiki reading artifact
;;;; the-1998-ai-planning-systems-competition.

(asdf:defsystem #:the-1998-ai-planning-systems-competition
  :description "FedWiki-attached DMX SQLite reading artifact for McDermott 2000, The 1998 AI Planning Systems Competition."
  :author "Generated by HyperDoc for a local FedWiki/SHOP3 reading slice"
  :license "Local project documentation artifact."
  :version "0.1.0"
  :serial t
  :depends-on (#:hyperdoc)
  :components
  ((:module "src"
    :serial t
    :components
    ((:file "package")
     (:file "model")
     (:file "topics")
     (:file "dmx-sqlite")
     (:file "fedwiki-page")
     (:file "materialize")
     (:file "inspect")))
   (:module "assets"
    :components
    ((:static-file "the-1998-ai-planning-systems-competition.dmx.sqlite")))
   (:module "pages"
    :components
    ((:static-file "the-1998-ai-planning-systems-competition.json")))
   (:module "examples"
    :components
    ((:static-file "mrepl-session.lisp")))
   (:module "tests"
    :components
    ((:static-file "smoke.lisp")))))

(asdf:defsystem #:the-1998-ai-planning-systems-competition/test
  :description "Smoke tests for the McDermott 2000 FedWiki ASDF reading artifact."
  :depends-on (#:the-1998-ai-planning-systems-competition)
  :serial t
  :components
  ((:module "tests"
    :serial t
    :components
    ((:file "smoke"))))
  :perform (asdf:test-op (op system)
             (declare (ignore op system))
             (uiop:symbol-call
              :the-1998-ai-planning-systems-competition/tests
              :run-smoke-tests)))
