;;;; HyperDoc authored topic family
;;;; Generated by splitting the former hyperdoc/topics.lisp monolith.

(in-package :hyperdoc)

;; ASDF workflow topics for runtime loading and undefined-function triage.
(defun asdf-topic ()
  (make-topic
   :id "asdf"
   :title "ASDF"
   :summary "ASDF is the Common Lisp system definition and build facility for loading, compiling, testing, and operating on software systems."
   :references '("Understanding ASDF Systems in HyperDoc"
                 "ASDF Components Workflow"
                 "Creating a HyperDoc")))

(defun asdf-quick-start-summary-topic ()
  (make-topic
   :id "asdf-quick-start-summary"
   :title "ASDF quick-start summary"
   :summary "The quick-start view of ASDF organizes the manual around using systems, defining systems, and extending ASDF."
   :references '("Understanding ASDF Systems in HyperDoc"
                 "ASDF Components Workflow")))

(defun asdf-user-workflow-topic ()
  (make-topic
   :id "asdf-user-workflow"
   :title "ASDF user workflow"
   :summary "The user-facing ASDF workflow is about locating and loading existing Common Lisp systems."
   :references '("ASDF Components Workflow"
                 "HyperDoc Server")))

(defun asdf-system-definition-topic ()
  (make-topic
   :id "asdf-system-definition"
   :title "ASDF system definition"
   :summary "The author-facing ASDF workflow is about defining systems with defsystem, including their components, dependencies, and publication metadata."
   :references '("ASDF Components Workflow"
                 "Definitive Common Lisp Books"
                 "Creating a HyperDoc")))

(defun asdf-extension-protocol-topic ()
  (make-topic
   :id "asdf-extension-protocol"
   :title "ASDF extension protocol"
   :summary "The implementer-facing ASDF workflow is about extending ASDF's object model and operations."
   :references '("ASDF Components Workflow")))

(defun build-system-versus-package-manager-topic ()
  (make-topic
   :id "build-system-versus-package-manager"
   :title "Build system versus package manager"
   :summary "ASDF is the build/load system, while tools such as Quicklisp provide the distribution and installation layer around reusable Common Lisp libraries."
   :references '("ASDF Components Workflow"
                 "Definitive Common Lisp Books")))

(defun quicklisp-topic ()
  (make-topic
   :id "quicklisp"
   :title "Quicklisp"
   :summary "Quicklisp is the practical library distribution layer commonly used alongside ASDF, helping users obtain systems that ASDF can then find and load."
   :references '("ASDF Components Workflow"
                 "Definitive Common Lisp Books"
                 "Goals and values")))

(defun asdf-install-topic ()
  (make-topic
   :id "asdf-install"
   :title "ASDF-Install"
   :summary "ASDF-Install is an obsolete, unmaintained installer that is separate from ASDF."
   :references '("ASDF Components Workflow")))

(defun clbuild-topic ()
  (make-topic
   :id "clbuild"
   :title "clbuild"
   :summary "clbuild is a source-based Common Lisp project management tool historically used alongside ASDF."
   :references '("ASDF Components Workflow")))

(defun asdf-source-registry-topic ()
  (make-topic
   :id "asdf-source-registry"
   :title "ASDF source registry"
   :summary "The ASDF source registry determines where ASDF looks for system definitions before asdf:find-system can resolve them, whether those systems come from a local checkout or a library distribution layer."
   :references '("Understanding ASDF Systems in HyperDoc"
                 "ASDF Components Workflow"
                 "ASDF Systems, Examples, and Tests in HyperDoc"
                 "Definitive Common Lisp Books"
                 "HyperDoc Server")))

(defun asdf-system-topic ()
  (make-topic
   :id "asdf-system"
   :title "ASDF system"
   :summary "Named top-level ASDF component defined by defsystem and used as the main practical boundary for project organization and for operations such as load-op and test-op."
   :references '("Understanding ASDF Systems in HyperDoc"
                 "ASDF Components Workflow"
                 "ASDF Systems, Examples, and Tests in HyperDoc"
                 "Definitive Common Lisp Books"
                 "Creating a HyperDoc")))

(defun asdf-component-topic ()
  (make-topic
   :id "asdf-component"
   :title "ASDF component"
   :summary "An ASDF component is any node in the .asd graph; systems, modules, and source files are all components under one system boundary described by the system definition."
   :references '("Understanding ASDF Systems in HyperDoc"
                 "ASDF Components Workflow"
                 "ASDF Systems, Examples, and Tests in HyperDoc"
                 "Definitive Common Lisp Books"
                 "Reloading HyperDoc After Adding Lisp Objects")))

(defun asdf-module-serial-order-topic ()
  (make-topic
   :id "asdf-module-serial-order"
   :title "ASDF module serial order"
   :summary "When :serial t is used, component order defines load order and therefore definition availability."
   :references '("Understanding ASDF Systems in HyperDoc"
                 "ASDF Components Workflow"
                 "Creating a HyperDoc")))

(defun asdf-operations-topic ()
  (make-topic
   :id "asdf-operations"
   :title "ASDF operations"
   :summary "Operations such as load and test act on systems/components and matter for how HyperDoc examples and tests are organized."
   :references '("Understanding ASDF Systems in HyperDoc"
                 "ASDF Components Workflow"
                 "HyperDoc Test Runner"
                 "ASDF Systems, Examples, and Tests in HyperDoc")))

(defun asdf-system-boundaries-topic ()
  (make-topic
   :id "asdf-system-boundaries"
   :title "ASDF system boundaries"
   :summary "System boundaries define ownership, loading, examples, and test scope in HyperDoc."
   :references '("Understanding ASDF Systems in HyperDoc"
                 "ASDF Systems, Examples, and Tests in HyperDoc"
                 "HyperDoc Runtime Model"
                 "Documentation Surfaces in HyperDoc")))

(defun slash-named-asdf-systems-topic ()
  (make-topic
   :id "slash-named-asdf-systems"
   :title "Slash-named ASDF systems"
   :summary "Repository convention using systems such as hyperdoc/explorer to separate runtime roles and surfaces."
   :references '("Understanding ASDF Systems in HyperDoc"
                 "Dependencies"
                 "Creating a HyperDoc"
                 "ASDF Systems, Examples, and Tests in HyperDoc")))

(defun asdf-load-system-force-topic ()
  (make-topic
   :id "asdf-load-system-force"
   :title "asdf:load-system :force t"
   :summary "Forces recompilation/reload of components to refresh a stale image when new definitions were added."
   :references '("ASDF Components Workflow"
                 "Reloading HyperDoc After Adding Lisp Objects")))

(defun asdf-find-system-topic ()
  (make-topic
   :id "asdf-find-system"
   :title "asdf:find-system"
   :summary "Resolves whether a named system is visible in the current source registry before load/operation."
   :references '("Understanding ASDF Systems in HyperDoc"
                 "ASDF Components Workflow"
                 "ASDF Systems, Examples, and Tests in HyperDoc"
                 "HyperDoc Server")))

(defun understanding-asdf-systems-in-hyperdoc-topic ()
  (make-topic
   :id "understanding-asdf-systems-in-hyperdoc"
   :title "Understanding ASDF systems in HyperDoc"
   :summary "Conceptual page explaining ASDF systems, components, operations, and why system boundaries define documentation scope in this repository."
   :references '("Understanding ASDF Systems in HyperDoc"
                 "ASDF Components Workflow"
                 "ASDF Systems, Examples, and Tests in HyperDoc"
                 "Creating a HyperDoc"
                 "Dependencies")))

(defun undefined-function-triage-topic ()
  (make-topic
   :id "undefined-function-triage"
   :title "Undefined-function triage"
   :summary "Diagnostic path: verify symbol binding, verify component inclusion in .asd, then reload/restart."
   :references '("ASDF Components Workflow"
                 "Reloading HyperDoc After Adding Lisp Objects")))

(defun sbcl-process-topic ()
  (make-topic
   :id "sbcl-process"
   :title "SBCL process"
   :summary "A running SBCL image with its own package state, loaded systems, source registry, and thread-local debugger context."
   :references '("SBCL Process"
                 "Source-oriented and image-oriented development in Common Lisp"
                 "ASDF Components Workflow"
                 "HyperDoc Server")))

(defun sbcl-topic ()
  (make-topic
   :id "sbcl"
   :title "SBCL"
   :summary "Steel Bank Common Lisp implementation used to run HyperDoc systems, compile components, and host server/inspector runtime behavior."
   :references '("SBCL"
                 "SBCL bootstrapping model"
                 "SBCL Process"
                 "ASDF Components Workflow"
                 "HyperDoc Server")))

(defun sbcl-bootstrapping-topic ()
  (make-topic
   :id "sbcl-bootstrapping"
   :title "SBCL bootstrapping"
   :summary "The build discipline that uses a host Common Lisp to construct SBCL while keeping the final target build independent of accidental host-image state."
   :references '("SBCL bootstrapping model"
                 "Host and target separation in SBCL"
                 "SBCL build stages: cross-compiler, genesis, cold core, cold init"
                 "SBCL")))

(defun source-oriented-development-topic ()
  (make-topic
   :id "source-oriented-development"
   :title "Source-oriented development"
   :summary "Common Lisp workflow in which source files remain the durable artifacts and rebuilds from scratch remain authoritative."
   :references '("Source-oriented and image-oriented development in Common Lisp"
                 "SBCL bootstrapping model"
                 "Understanding ASDF Systems in HyperDoc"
                 "SBCL Process")))

(defun generated-topic-asset-form-operator-named-p (value name)
  (and (symbolp value)
       (string= (symbol-name value) name)))

(defun generated-topic-asset-topic-plist (form)
  (when (and (consp form)
             (generated-topic-asset-form-operator-named-p
              (first form)
              "DEFUN"))
    (let ((body (cdddr form)))
      (when (and (= (length body) 1)
                 (consp (first body))
                 (generated-topic-asset-form-operator-named-p
                  (first (first body))
                  "MAKE-TOPIC"))
        (rest (first body))))))

(defun unquote-generated-topic-value (value)
  (if (and (consp value)
           (eq (first value) 'quote))
      (second value)
      value))

(defun generated-topic-from-asset (asset-relative-path topic-id)
  (let ((asset-path (asdf:system-relative-pathname :hyperdoc asset-relative-path)))
    (when (uiop:file-exists-p asset-path)
      (with-open-file (stream asset-path
                              :direction :input
                              :external-format :utf-8)
        (loop for form = (read stream nil :eof)
              until (eq form :eof)
              for topic-plist = (generated-topic-asset-topic-plist form)
              when (and topic-plist
                        (string= (or (getf topic-plist :id) "")
                                 topic-id))
              do (return
                   (make-topic
                    :id (getf topic-plist :id)
                    :title (getf topic-plist :title)
                    :summary (getf topic-plist :summary)
                    :references
                    (copy-list
                     (unquote-generated-topic-value
                      (getf topic-plist :references))))))))))

;; Evolving ASDF source-station topics.
(defun evolving-asdf-paper-topic ()
  (make-topic
   :id "evolving-asdf-paper"
   :title "Evolving ASDF paper"
   :summary "Rideau and Goldman's 2010 ASDF 2 paper, assimilated as a source-station for build-system protocol, hot upgrade, configuration, and social coordination in Common Lisp."
   :references '("Evolving ASDF: More Cooperation, Less Coordination"
                 "Understanding ASDF Systems in HyperDoc"
                 "ASDF Components Workflow"
                 "Source-oriented and image-oriented development in Common Lisp")))

(defun asdf-social-coordination-cost-topic ()
  (make-topic
   :id "asdf-social-coordination-cost"
   :title "ASDF social coordination cost"
   :summary "The community-wide synchronization burden created when build-system changes require vendors, users, libraries, and running images to coordinate manually."
   :references '("Evolving ASDF: More Cooperation, Less Coordination"
                 "Understanding ASDF Systems in HyperDoc"
                 "Source-oriented and image-oriented development in Common Lisp")))

(defun asdf-hot-upgrade-boundary-topic ()
  (make-topic
   :id "asdf-hot-upgrade-boundary"
   :title "ASDF hot upgrade boundary"
   :summary "The boundary where ASDF must upgrade itself inside a running Common Lisp image without assuming restart, vendor synchronization, or perfect monotonicity."
   :references '("Evolving ASDF: More Cooperation, Less Coordination"
                 "A framework for maintaining the coherence of a running Lisp"
                 "Source-oriented and image-oriented development in Common Lisp")))

(defun asdf-configuration-surface-topic ()
  (make-topic
   :id "asdf-configuration-surface"
   :title "ASDF configuration surface"
   :summary "The ASDF 2 shift toward explicit, portable configuration for source discovery and related build behavior instead of ad hoc post-load setup."
   :references '("Evolving ASDF: More Cooperation, Less Coordination"
                 "ASDF Components Workflow"
                 "Understanding ASDF Systems in HyperDoc")))

(defun asdf-output-translations-topic ()
  (make-topic
   :id "asdf-output-translations"
   :title "ASDF output translations"
   :summary "The ASDF mechanism for redirecting compiler outputs into implementation- and user-specific locations, avoiding shared FASL collisions and unsafe writes."
   :references '("Evolving ASDF: More Cooperation, Less Coordination"
                 "ASDF Components Workflow"
                 "Understanding ASDF Systems in HyperDoc")))

(defun asdf-traverse-plan-semantics-topic ()
  (make-topic
   :id "asdf-traverse-plan-semantics"
   :title "ASDF traverse plan semantics"
   :summary "The ASDF planning seam where operation/component dependency traversal determines what must be recompiled, loaded, or synchronized across composite components."
   :references '("Evolving ASDF: More Cooperation, Less Coordination"
                 "ASDF Components Workflow"
                 "ASDF Systems, Examples, and Tests in HyperDoc")))

(defun shop3-planning-layer-for-hyperdoc-topic ()
  (make-topic
   :id "shop3-planning-layer-for-hyperdoc"
   :title "SHOP3 Planning Layer for HyperDoc"
   :summary "Optional plan-only SHOP3 HTN planning layer that proposes ordered HyperDoc maintenance plans while leaving all source edits, checks, DMX writes, and commits manual."
   :references '("SHOP3 Planning Layer for HyperDoc"
                 "ASDF Systems, Examples, and Tests in HyperDoc"
                 "Understanding ASDF Systems in HyperDoc"
                 "Planning Routes through Uncertain Territory")))


(defun asdf-community-infrastructure-topic ()
  (make-topic
   :id "asdf-community-infrastructure"
   :title "ASDF community infrastructure"
   :summary "ASDF as shared Common Lisp infrastructure whose success turned build/load behavior into a community coordination surface."
   :references '("Evolving ASDF: More Cooperation, Less Coordination"
                 "Understanding ASDF Systems in HyperDoc"
                 "Source-oriented and image-oriented development in Common Lisp")))

(defun asdf-vendor-synchronization-topic ()
  (make-topic
   :id "asdf-vendor-synchronization"
   :title "ASDF vendor synchronization"
   :summary "The coordination burden created when implementation-shipped ASDF versions must be updated by vendors before users and library authors can rely on fixes."
   :references '("Evolving ASDF: More Cooperation, Less Coordination"
                 "ASDF social coordination cost"
                 "ASDF hot upgrade boundary")))

(defun asdf-convergence-through-divergence-topic ()
  (make-topic
   :id "asdf-convergence-through-divergence"
   :title "ASDF convergence through divergence"
   :summary "The ASDF 2 strategy in which allowing local upgrade and temporary version divergence reduces release-cycle coupling and encourages later ecosystem convergence."
   :references '("Evolving ASDF: More Cooperation, Less Coordination"
                 "ASDF vendor synchronization"
                 "ASDF social coordination cost")))


