;;;; HyperDoc authored topic family
;;;; Generated by splitting the former hyperdoc/topics.lisp monolith.

(in-package :hyperdoc)

;; Topic objects for capability-scoped extension and packaged-app story-item notes.
(defparameter *capability-scoped-extension-doc-references*
  '("Universal Thing and Browser Isolation in FedWiki"
    "The iFrame Is Not the Compute Sandbox"
    "Mech CODE Block analysis"
    "Capability-scoped Extensions for FedWiki"
    "WebXDC-style Story Items for FedWiki and HyperDoc"))

(defun capability-scoped-extension-topic ()
  (make-topic
   :id "capability-scoped-extension"
   :title "Capability-scoped extension"
   :summary "Host-mediated extension unit whose powers are explicitly bounded instead of inheriting arbitrary page JavaScript authority."
   :references *capability-scoped-extension-doc-references*))

(defun declarative-extension-manifest-topic ()
  (make-topic
   :id "declarative-extension-manifest"
   :title "Declarative extension manifest"
   :summary "Up-front declaration of extension intent, requested powers, and integration boundary before execution."
   :references *capability-scoped-extension-doc-references*))

(defun consent-gated-execution-topic ()
  (make-topic
   :id "consent-gated-execution"
   :title "Consent-gated execution"
   :summary "Execution boundary that requires explicit user approval before a page-authored or packaged extension can exercise declared powers."
   :references *capability-scoped-extension-doc-references*))

(defun shared-state-app-story-item-topic ()
  (make-topic
   :id "shared-state-app-story-item"
   :title "Shared-state app story item"
   :summary "Story item that carries an app container together with item-local shared state for bounded parent/app interaction."
   :references *capability-scoped-extension-doc-references*))

(defun webxdc-style-story-item-topic ()
  (make-topic
   :id "webxdc-style-story-item"
   :title "WebXDC-style story item"
   :summary "Packaged app story-item model that treats WebXDC-style delivery and shared state as distinct from the actual compute sandbox."
   :references *capability-scoped-extension-doc-references*))

(defun ward-beck-diagram-1986-topic ()
  (make-topic
   :id "ward-beck-diagram-1986"
   :title "Ward/Beck diagram for object-oriented programs (1986)"
   :summary "Citation anchor: Ward Cunningham and Kent Beck, OOPSLA 1986 (Portland), frame object-collaboration diagrams as executable explanation work."
   :references '("Smalltalk Browser Frame and Scene in HyperDoc"
                 "https://c2.com/doc/case87.html")))

(defun ward-collaborating-objects-topic ()
  (make-topic
   :id "ward-collaborating-objects"
   :title "Collaborating objects diagrams"
   :summary "Ward first drew collaboration diagrams by hand in the Computer Research Lab to explain object behavior to colleagues."
   :references '("Smalltalk Browser Frame and Scene in HyperDoc"
                 "https://c2.com/doc/case87.html")))

(defun class-browser-inspector-debugger-triangulation-topic ()
  (make-topic
   :id "class-browser-inspector-debugger-triangulation"
   :title "Class browser/inspector/debugger triangulation"
   :summary "Diagram extraction combined three windows: class browser, object inspector, and single-step debugger."
   :references '("Smalltalk Browser Frame and Scene in HyperDoc"
                 "Stepper Debugger Surface")))

(defun compiledmethod-interpretnextinstruction-topic ()
  (make-topic
   :id "compiledmethod-interpretnextinstruction"
   :title "CompiledMethod interpretNextInstructionFor: aContext"
   :summary "This stepping primitive exposed execution semantics; once identified, only drawing what it says remained."
   :references '("Smalltalk Browser Frame and Scene in HyperDoc"
                 "https://c2.com/doc/case87.html")))

(defun expanding-tools-literate-environment-topic ()
  (make-topic
   :id "expanding-tools-literate-environment"
   :title "Expanding the Role of Tools in a Literate Programming Environment"
   :summary "CASE'87 line of work: tools should compose around explanation, not just editing, anticipating scene-level workflow support."
   :references '("Smalltalk Browser Frame and Scene in HyperDoc"
                 "https://c2.com/doc/case87.html")))

(defun ward-diagramming-debugger-remembrance-topic ()
  (make-topic
   :id "ward-diagramming-debugger-remembrance"
   :title "Ward diagramming-debugger remembrance"
   :summary "Ward's later recollection ties diagram generation directly to debugger stepping and executable explanation."
   :references '("Smalltalk Browser Frame and Scene in HyperDoc"
                 "Diagramming Debugger")))

(defun mech-op-args-emit-dispatch-topic ()
  (make-topic
   :id "mech-op-args-emit-dispatch"
   :title "Mech op/args and emit dispatch"
   :summary "Mech exposes a block-level executable seam: split command into op and args, assemble execution context, then dispatch to blocks[op].emit."
   :references '("Smalltalk Browser Frame and Scene in HyperDoc"
                 "Mech Credible Maintenance Story"
                 "Mech Execution Context and Emit Protocol"
                 "Runtime Dispatch Seams in HyperDoc")))

(defun runtime-dispatch-seam-topic ()
  (make-topic
   :id "runtime-dispatch-seam"
   :title "Runtime dispatch seam"
   :summary "A compact execution boundary where authored syntax has been normalized enough for action and explanation to attach to the same event."
   :references '("Boundary"
                 "Transition boundary"
                 "Runtime Dispatch Seams in HyperDoc"
                 "Smalltalk Browser Frame and Scene in HyperDoc"
                 "Mech Execution Context and Emit Protocol")))

(defun execution-context-bundle-topic ()
  (make-topic
   :id "execution-context-bundle"
   :title "Execution context bundle"
   :summary "The assembled runtime package of command, op, args, body, element, and state used to execute and inspect a Mech block."
   :references '("Mech Execution Context and Emit Protocol"
                 "Runtime Dispatch Seams in HyperDoc")))

(defun block-level-interpreter-seam-topic ()
  (make-topic
   :id "block-level-interpreter-seam"
   :title "Block-level interpreter seam"
   :summary "A domain-specific execution seam above the VM level but below page-level narrative."
   :references '("Runtime Dispatch Seams in HyperDoc"
                 "Stepper Debugger Surface"
                 "Smalltalk Browser Frame and Scene in HyperDoc")))

(defun explanation-from-execution-topic ()
  (make-topic
   :id "explanation-from-execution"
   :title "Explanation from execution"
   :summary "Explanation generated from the same runtime event that performs the work, instead of reconstructed later."
   :references '("Runtime Dispatch Seams in HyperDoc"
                 "Smalltalk Browser Frame and Scene in HyperDoc"
                 "Inspectable Mech Runs")))

(defun executable-explanation-topic ()
  (make-topic
   :id "executable-explanation"
   :title "Executable explanation"
   :summary "Explanatory artifacts derived directly from operational semantics."
   :references '("Runtime Dispatch Seams in HyperDoc"
                 "Smalltalk Browser Frame and Scene in HyperDoc")))

(defun runtime-provenance-topic ()
  (make-topic
   :id "runtime-provenance"
   :title "Runtime provenance"
   :summary "Traceable links from generated output or findings back to the execution step and source that produced them."
   :references '("Runtime Dispatch Seams in HyperDoc"
                 "Mech Execution Context and Emit Protocol"
                 "Inspectable Mech Runs")))

(defun block-registry-protocol-topic ()
  (make-topic
   :id "block-registry-protocol"
   :title "Block registry protocol"
   :summary "The implicit interface formed by blocks[op] and emit methods, defining Mech's executable vocabulary."
   :references '("Mech Execution Context and Emit Protocol"
                 "Mech Plugin Progress March 2026")))

(defun mech-code-to-graphviz-preview-path-topic ()
  (make-topic
   :id "mech-code-to-graphviz-preview-path"
   :title "Mech CODE-to-graphviz preview path"
   :summary "Current upstream Mech can preview Graphviz directly when a page-local code item makes CODE populate state.items with a graphviz story item and PREVIEW items publishes it unchanged."
   :references '("Mech CODE Block analysis"
                 "Mech Execution Context and Emit Protocol"
                 "FedWiki Graphviz story item render trace")))

(defun quick-brown-fox-text-to-graph-example-topic ()
  (make-topic
   :id "quick-brown-fox-text-to-graph-example"
   :title "Quick Brown Fox text-to-graph example"
   :summary "Worked example: split plain text into successive character edges and emit Graphviz DOT as a previewable graphviz story item."
   :references '("Mech CODE Block analysis"
                 "Mech Execution Context and Emit Protocol")))

(defun discourse-graphs-adaptation-boundary-topic ()
  (make-topic
   :id "discourse-graphs-adaptation-boundary"
   :title "Discourse Graphs adaptation boundary"
   :summary "Boundary object for slices where tracked wiki-plugin-mech matches Ward upstream but the dreyeck Discourse-Graphs behavior lives in an external adapted runtime rather than in this checkout."
   :references '("Mech CODE Block analysis"
                 "FedWiki Graphviz story item render trace")))

(defun live-mech-deployment-provenance-topic ()
  (make-topic
   :id "live-mech-deployment-provenance"
   :title "Live Mech deployment provenance"
   :summary "Deployment-provenance object for proving what live hosts actually serve for Mech from served plugin metadata, served assets, hashes, and live page content."
   :references '("FedWiki Graphviz story item render trace"
                 "Mech CODE Block analysis")))

(defun host-by-host-live-runtime-comparison-topic ()
  (make-topic
   :id "host-by-host-live-runtime-comparison"
   :title "Host-by-host live runtime comparison"
   :summary "Host-separated runtime comparison that keeps each host's served plugin metadata, asset evidence, and classification explicit instead of collapsing them into one blended deployment story."
   :references '("FedWiki Graphviz story item render trace")))

(defun patched-mech-discourse-graphs-block-vocabulary-topic ()
  (make-topic
   :id "patched-mech-discourse-graphs-block-vocabulary"
   :title "Patched Mech / Discourse-Graphs block vocabulary"
   :summary "Downstream Mech block vocabulary such as EXTRACT, EDGES, questions, claims, and WALK roles that marks the patched Discourse-Graphs lineage distinct from upstream 47c."
   :references '("FedWiki Graphviz story item render trace"
                 "Mech CODE Block analysis")))

(defun operation-argument-normalization-topic ()
  (make-topic
   :id "operation-argument-normalization"
   :title "Operation/argument normalization"
   :summary "The parse step that turns command text into a stable operation name plus argument list."
   :references '("Mech Execution Context and Emit Protocol"
                 "Runtime Dispatch Seams in HyperDoc")))

(defun structured-findings-tally-topic ()
  (make-topic
   :id "structured-findings-tally"
   :title "Structured findings tally"
   :summary "A categorized account of boundaries and losses encountered during execution or generation."
   :references '("Mech Credible Maintenance Story"
                 "Mech Plugin Progress March 2026"
                 "Inspectable Mech Runs")))

(defun first-class-run-record-topic ()
  (make-topic
   :id "first-class-run-record"
   :title "First-class run record"
   :summary "An inspectable object representing one Mech execution with steps, state, artifacts, and findings."
   :references '("Inspectable Mech Runs"
                 "Runtime Dispatch Seams in HyperDoc"
                 "Mech Credible Maintenance Story")))

(defun diagnostic-publication-topic ()
  (make-topic
   :id "diagnostic-publication"
   :title "Diagnostic publication"
   :summary "Publishing execution findings as visible story items or inspectable objects rather than hiding them in console output."
   :references '("Mech Plugin Progress March 2026"
                 "Mech Credible Maintenance Story"
                 "Mech Execution Context and Emit Protocol")))

(defun execution-step-object-topic ()
  (make-topic
   :id "execution-step-object"
   :title "Execution step object"
   :summary "A proposed inspectable object for one executed Mech block step, including source command, normalized form, state effects, and findings."
   :references '("Inspectable Mech Runs"
                 "Mech Execution Context and Emit Protocol")))

(defun state-delta-topic ()
  (make-topic
   :id "state-delta"
   :title "State delta"
   :summary "A record of how one execution step changes the working state carried through a run."
   :references '("Inspectable Mech Runs"
                 "Mech Execution Context and Emit Protocol")))

(defun artifact-provenance-topic ()
  (make-topic
   :id "artifact-provenance"
   :title "Artifact provenance"
   :summary "The link between an emitted artifact and the execution step or source command that produced it."
   :references '("Inspectable Mech Runs"
                 "Runtime Dispatch Seams in HyperDoc")))

(defun findings-ledger-topic ()
  (make-topic
   :id "findings-ledger"
   :title "Findings ledger"
   :summary "A durable inspectable record of warnings, errors, and boundary findings accumulated across one run."
   :references '("Inspectable Mech Runs"
                 "Structured findings tally")))

(defun replay-trail-topic ()
  (make-topic
   :id "replay-trail"
   :title "Replay trail"
   :summary "A stepwise trace that lets one review how a run advanced from authored commands to emitted artifacts and findings."
   :references '("Inspectable Mech Runs"
                 "First-class run record")))

(defun retrospective-explanation-pass-topic ()
  (make-topic
   :id "retrospective-explanation-pass"
   :title "Retrospective explanation pass"
   :summary "A later reconstruction layer that tries to infer source, context, branches, outputs, and failures after execution has already collapsed into output."
   :references '("Runtime Dispatch Seams in HyperDoc"
                 "Smalltalk Browser Frame and Scene in HyperDoc"
                 "HyperDoc Evaluation and Inspection Model")))

(defun execution-evidence-object-topic ()
  (make-topic
   :id "execution-evidence-object"
   :title "Execution evidence object"
   :summary "An inspectable record emitted at execution time that preserves what operation ran, in what context, with what outputs, limits, or failures."
   :references '("Boundary"
                 "Boundary report"
                 "HyperDoc Evaluation and Inspection Model"
                 "Inspectable Mech Runs"
                 "Mech Credible Maintenance Story")))

(defun boundary-topic ()
  (make-topic
   :id "boundary"
   :title "Boundary"
   :summary "A bounded transition or contract edge where one mode of access, representation, authority, or execution gives way to another."
   :references '("Boundary"
                 "Contract boundary"
                 "Transition boundary"
                 "Authentication boundary"
                 "Read-write boundary"
                 "Boundary report"
                 "Operational definition: boundary, contract boundary, transition boundary, boundary report"
                 "Runtime Dispatch Seams in HyperDoc"
                 "DMX note read/write boundary"
                 "DMX workspace journal model")) )

(defun contract-boundary-topic ()
  (make-topic
   :id "contract-boundary"
   :title "Contract boundary"
   :summary "A boundary definition that states what counts as valid access, representation, or mutation across a stable contract edge."
   :references '("Contract boundary"
                 "Boundary"
                 "Read-write boundary"
                 "DMX note read/write boundary"
                 "DMX machine-readable read paths"
                 "Operational definition: boundary, contract boundary, transition boundary, boundary report")))

(defun transition-boundary-topic ()
  (make-topic
   :id "transition-boundary"
   :title "Transition boundary"
   :summary "A boundary definition for a stage crossing inside one concrete run, where later stages depend on crossing an earlier guarded step."
   :references '("Transition boundary"
                 "Boundary"
                 "DMX workspace journal model"
                 "Diagnosing DMX workspace repair triage"
                 "Using authenticated workspace assignment repair console"
                 "Runtime Dispatch Seams in HyperDoc"
                 "Operational definition: boundary, contract boundary, transition boundary, boundary report")))

(defun authentication-boundary-topic ()
  (make-topic
   :id "authentication-boundary"
   :title "Authentication boundary"
   :summary "A boundary where read-only or unauthenticated access gives way to explicit-auth guarded mutation or session-backed access."
   :references '("Authentication boundary"
                 "Boundary"
                 "Using authenticated workspace assignment repair console"
                 "Inspectable authentication-path traces for repair console"
                 "DMX Credentials"
                 "DMX session bootstrap and JSESSIONID"
                 "Operational definition: boundary, contract boundary, transition boundary, boundary report")))

(defun read-write-boundary-topic ()
  (make-topic
   :id "read-write-boundary"
   :title "Read-write boundary"
   :summary "A contract boundary that distinguishes what may be read, what may be written, and which object or representation is the stable mutation target."
   :references '("Read-write boundary"
                 "Boundary"
                 "Contract boundary"
                 "DMX note read/write boundary"
                 "DMX machine-readable read paths"
                 "DMX workspace journal model"
                 "Operational definition: boundary, contract boundary, transition boundary, boundary report")))

(defun boundary-report-topic ()
  (make-topic
   :id "boundary-report"
   :title "Boundary report"
   :summary "A report of what an execution could not resolve, represent, or complete cleanly at its authoritative seam."
   :references '("Boundary report"
                 "Boundary"
                 "Operational definition: boundary, contract boundary, transition boundary, boundary report"
                 "Mech Credible Maintenance Story"
                 "Mech Plugin Progress March 2026"
                 "Inspectable Mech Runs")))

(defun generation-explanation-twin-output-topic ()
  (make-topic
   :id "generation-explanation-twin-output"
   :title "Generation/explanation twin output"
   :summary "The design principle that execution should emit both the produced artifact and its explanatory evidence as coequal outputs."
   :references '("Mech Plugin Progress March 2026"
                 "Runtime Dispatch Seams in HyperDoc"
                 "Mech Execution Context and Emit Protocol")))

(defun raw-console-trace-topic ()
  (make-topic
   :id "raw-console-trace"
   :title "Raw console trace"
   :summary "A transient linear diagnostic stream emitted during execution before it has been promoted into structured inspectable objects."
   :references '("HyperDoc Evaluation and Inspection Model"
                 "HyperDoc Runtime Model")))

(defun pane-run-topic ()
  (make-topic
   :id "pane-run"
   :title "Pane run"
   :summary "An inspectable record of one pane's creation, view selection, rendering, and navigation activity."
   :references '("HyperDoc Runtime Model"
                 "HyperDoc Evaluation and Inspection Model")))

(defun view-render-event-topic ()
  (make-topic
   :id "view-render-event"
   :title "View render event"
   :summary "One render-time event capturing a selected view, target object, timings, cache state, and related metrics."
   :references '("HyperDoc Evaluation and Inspection Model"
                 "HyperDoc Runtime Model")))

(defun inspector-session-topic ()
  (make-topic
   :id "inspector-session"
   :title "Inspector session"
   :summary "An inspectable record of one inspector interaction session across panes, selections, and renders."
   :references '("HyperDoc Runtime Model"
                 "HyperDoc Evaluation and Inspection Model")))

(defun same-protocol-evidence-topic ()
  (make-topic
   :id "same-protocol-evidence"
   :title "Same-protocol evidence"
   :summary "Execution evidence emitted by the same protocol that performs the work, rather than reconstructed in a later pass."
   :references '("Runtime Dispatch Seams in HyperDoc"
                 "HyperDoc Evaluation and Inspection Model"
                 "Smalltalk Browser Frame and Scene in HyperDoc")))

(defun transient-diagnostic-stream-topic ()
  (make-topic
   :id "transient-diagnostic-stream"
   :title "Transient diagnostic stream"
   :summary "A sequence-preserving but weak form of execution evidence that remains console-bound, linear, and non-queryable as objects."
   :references '("HyperDoc Evaluation and Inspection Model"
                 "Mech Credible Maintenance Story")))

(defun objectified-execution-evidence-topic ()
  (make-topic
   :id "objectified-execution-evidence"
   :title "Objectified execution evidence"
   :summary "Execution evidence promoted from transient trace lines into first-class inspectable runtime objects."
   :references '("HyperDoc Runtime Model"
                 "HyperDoc Evaluation and Inspection Model"
                 "HyperDoc Test Runner")))

(defun persistence-of-investigation-context-topic ()
  (make-topic
   :id "persistence-of-investigation-context"
   :title "Persistence of investigation context"
   :summary "The requirement that investigation state, explanatory evidence, and execution context survive a run as first-class inspectable objects instead of disappearing into transient traces."
   :references '("Smalltalk Browser Frame and Scene in HyperDoc"
                 "HyperDoc Runtime Model"
                 "Inspectable Mech Runs")))

(defun literate-tracing-topic ()
  (make-topic
   :id "literate-tracing"
   :title "Literate Tracing"
   :summary "A documentation approach that explains systems through annotated concrete execution traces instead of source exposition alone."
   :references '("https://arxiv.org/abs/2510.09073"
                 "https://2025.splashcon.org/details/splash-2025-Onward-papers/11/Literate-Tracing"
                 "https://brown.columbia.edu/portfolio/literate-tracing-unusually-interactive-visual-and-informative-software-documentation/")))

(defun a-language-based-on-two-relations-between-symbols-topic ()
  (make-topic
   :id "a-language-based-on-two-relations-between-symbols"
   :title "A Language Based on Two Relations between Symbols"
   :summary "Paper-level topic for Agustin Rafael Martinez's 2022 Onward! paper on Representar, a language organized around substitution and categorization across visual and textual programming surfaces with inspectable substitution execution and domain-specific notation."
   :references '("A Language Based on Two Relations between Symbols"
                 "A Language Based on Two Relations between Symbols arrangement"
                 "Reference Systems in HyperDoc"
                 "HyperTalk and English-ish Programming"
                 "Topic arrangement in HyperDoc")))

(defun a-language-based-on-two-relations-between-symbols-arrangement-topic ()
  (make-topic
   :id "a-language-based-on-two-relations-between-symbols-arrangement"
   :title "A Language Based on Two Relations between Symbols arrangement"
   :summary "Authored arrangement view preserving the paper, its supplement, and the nearby HyperDoc comparison neighborhood without asserting semantic identity."
   :references '("A Language Based on Two Relations between Symbols arrangement"
                 "A Language Based on Two Relations between Symbols"
                 "Reference Systems in HyperDoc"
                 "Documentation Surfaces in HyperDoc"
                 "Topic arrangement in HyperDoc")))

(defun python-json-tool-source-topic ()
  (make-topic
   :id "python-json-tool-source"
   :title "Python json.tool source"
   :summary "The json.tool CLI lives in the Python standard library module json/tool.py and can be inspected locally via json.tool.__file__."
   :references '("Python json.tool Source and Usage"
                 "https://github.com/python/cpython/blob/main/Lib/json/tool.py")))

;; Civilian resilience topics for autonomous-weapons threat environments.
(defun surviving-autonomous-weapons-environment-topic ()
  (make-topic
   :id "surviving-in-an-autonomous-weapons-environment"
   :title "Surviving in an Autonomous Weapons Environment"
   :summary "Civilian resilience baseline for preserving life, service continuity, and accountability under autonomous-threat conditions."
   :references '("Surviving in an Autonomous Weapons Environment"
                 "Autonomous Weapons Resilience Playbook"
                 "Post-Incident Recovery Under Autonomous Threat")))

(defun autonomous-weapons-resilience-playbook-topic ()
  (make-topic
   :id "autonomous-weapons-resilience-playbook"
   :title "Autonomous Weapons Resilience Playbook"
   :summary "Layered preparedness, protection, continuity, and recovery framework for civilian communities exposed to autonomous weapons risks."
   :references '("Autonomous Weapons Resilience Playbook"
                 "Surviving in an Autonomous Weapons Environment")))

(defun post-incident-recovery-under-autonomous-threat-topic ()
  (make-topic
   :id "post-incident-recovery-under-autonomous-threat"
   :title "Post-Incident Recovery Under Autonomous Threat"
   :summary "Post-incident stabilization and recovery model centered on evidence preservation, service restoration, and institutional learning."
   :references '("Post-Incident Recovery Under Autonomous Threat"
                 "Autonomous Weapons Resilience Playbook")))

(defun autonomous-weapons-civilian-resilience-topic ()
  (make-topic
   :id "autonomous-weapons-civilian-resilience"
   :title "Autonomous-weapons civilian resilience"
   :summary "Operational view of civilian resilience capabilities required when autonomous systems compress warning and response windows."
   :references '("Autonomous Weapons Resilience Playbook"
                 "Surviving in an Autonomous Weapons Environment")))

(defun autonomous-threat-risk-model-topic ()
  (make-topic
   :id "autonomous-threat-risk-model"
   :title "Autonomous-threat risk model"
   :summary "Risk model combining infrastructure dependency, warning reliability, and disruption impact under autonomous-threat scenarios."
   :references '("Autonomous Weapons Resilience Playbook")))

(defun protective-infrastructure-hardening-topic ()
  (make-topic
   :id "protective-infrastructure-hardening"
   :title "Protective infrastructure hardening"
   :summary "Practical hardening focus on shelters, power, communications, and medical services to reduce civilian harm."
   :references '("Autonomous Weapons Resilience Playbook")))

(defun civilian-alerting-fallback-channels-topic ()
  (make-topic
   :id "civilian-alerting-fallback-channels"
   :title "Civilian alerting fallback channels"
   :summary "Redundant alert and coordination channels used when primary communications are degraded or unavailable."
   :references '("Autonomous Weapons Resilience Playbook"
                 "Surviving in an Autonomous Weapons Environment")))

(defun disinformation-verification-loop-topic ()
  (make-topic
   :id "disinformation-verification-loop"
   :title "Disinformation verification loop"
   :summary "Structured verification cycle for filtering false reports and preserving trusted situational awareness."
   :references '("Autonomous Weapons Resilience Playbook")))

(defun continuity-of-care-under-disruption-topic ()
  (make-topic
   :id "continuity-of-care-under-disruption"
   :title "Continuity of care under disruption"
   :summary "Medical and social-care continuity planning for prolonged disruption and contested logistics."
   :references '("Autonomous Weapons Resilience Playbook"
                 "Post-Incident Recovery Under Autonomous Threat")))

(defun autonomous-weapons-governance-accountability-topic ()
  (make-topic
   :id "autonomous-weapons-governance-accountability"
   :title "Autonomous-weapons governance accountability"
   :summary "Governance requirement to preserve human accountability, evidence trails, and legal oversight during and after incidents."
   :references '("Autonomous Weapons Resilience Playbook"
                 "Post-Incident Recovery Under Autonomous Threat")))

(defun incident-ledger-and-evidence-topic ()
  (make-topic
   :id "incident-ledger-and-evidence"
   :title "Incident ledger and evidence"
   :summary "Structured incident ledger and chain-of-custody practices that support reliable recovery and review."
   :references '("Post-Incident Recovery Under Autonomous Threat")))

(defun service-restoration-prioritization-topic ()
  (make-topic
   :id "service-restoration-prioritization"
   :title "Service restoration prioritization"
   :summary "Prioritization model for restoring essential services under constrained resources after disruptive incidents."
   :references '("Post-Incident Recovery Under Autonomous Threat")))

(defun community-psychological-recovery-topic ()
  (make-topic
   :id "community-psychological-recovery"
   :title "Community psychological recovery"
   :summary "Community mental-health support and social-cohesion recovery operations after persistent high-stress incidents."
   :references '("Post-Incident Recovery Under Autonomous Threat")))

(defun after-action-learning-loop-topic ()
  (make-topic
   :id "after-action-learning-loop"
   :title "After-action learning loop"
   :summary "Closed-loop process for turning incident findings into revised procedures, training, and resilience improvements."
   :references '("Post-Incident Recovery Under Autonomous Threat"
                 "Autonomous Weapons Resilience Playbook")))

;; Glamorous Toolkit acquisition/install topics.
(defun gtoolkit-acquisition-modes-topic ()
  (make-topic
   :id "gtoolkit-acquisition-modes"
   :title "Glamorous Toolkit acquisition modes"
   :summary "GT can be used either from a ready-made distribution or by cloning/building from source."
   :references '("Installing Glamorous Toolkit"
                 "Acknowledgements"
                 "https://gtoolkit.com/download/"
                 "https://github.com/feenkcom/gtoolkit")))

(defun gtoolkit-ready-made-distribution-topic ()
  (make-topic
   :id "gtoolkit-ready-made-distribution"
   :title "Glamorous Toolkit ready-made distribution"
   :summary "The packaged download is the default path for using GT without building it from source."
   :references '("Installing Glamorous Toolkit"
                 "Acknowledgements"
                 "https://gtoolkit.com/download/")))

(defun gtoolkit-source-install-topic ()
  (make-topic
   :id "gtoolkit-source-install"
   :title "Glamorous Toolkit source install"
   :summary "The source-install path installs the VM, clones the GitHub repository, and builds an image; upstream says this is useful for developing GT itself."
   :references '("Installing Glamorous Toolkit"
                 "https://gtoolkit.com/download/"
                 "https://github.com/feenkcom/gtoolkit")))

(defun gtoolkit-moldable-development-topic ()
  (make-topic
   :id "gtoolkit-moldable-development"
   :title "Glamorous Toolkit as moldable development environment"
   :summary "GT is presented upstream as the Moldable Development Environment and is already acknowledged in HyperDoc as a reference platform."
   :references '("Installing Glamorous Toolkit"
                 "Acknowledgements"
                 "Design"
                 "Goals and values"
                 "https://github.com/feenkcom/gtoolkit"
                 "https://moldabledevelopment.com/")))

(defun gtoolkit-nix-installation-note-topic ()
  (make-topic
   :id "gtoolkit-nix-installation-note"
   :title "Glamorous Toolkit Nix installation note"
   :summary "The official download page defers Nix-specific usage instructions to the GT book."
   :references '("Installing Glamorous Toolkit"
                 "https://gtoolkit.com/download/"
                 "https://book.gtoolkit.com")))

(defun determinate-nix-on-macos-intel-topic ()
  (make-topic
   :id "determinate-nix-on-macos-intel"
   :title "Determinate Nix on macOS Intel"
   :summary "Entry-point page for the current macOS Intel recovery boundary: Determinate support dropped for Intel hosts, so upstream Nix is the primary reinstall path."
   :references '("Determinate Nix on macOS Intel"
                 "Inspect Nix Install State on macOS"
                 "Reinstall Upstream Nix on macOS"
                 "Restore Last Working Determinate Nix on macOS Intel"
                 "Fix Fish direnv Hook Error"
                 "https://github.com/DeterminateSystems/nix-installer/releases/tag/v3.13.0"
                 "https://nix.dev/manual/nix/2.32/installation/installing-binary.html")))

(defun inspect-nix-install-state-on-macos-topic ()
  (make-topic
   :id "inspect-nix-install-state-on-macos"
   :title "Inspect Nix Install State on macOS"
   :summary "Operational inspection page for confirming host architecture, reading /nix install markers, and interpreting the transition from broken residue to a live upstream Nix install on macOS."
   :references '("Inspect Nix Install State on macOS"
                 "Determinate Nix on macOS Intel"
                 "Reinstall Upstream Nix on macOS"
                 "Restore Last Working Determinate Nix on macOS Intel"
                 "https://github.com/DeterminateSystems/nix-installer"
                 "https://nix.dev/manual/nix/2.32/installation/uninstall"
                 "https://github.com/NixOS/nix/issues/7894")))

(defun reinstall-upstream-nix-on-macos-topic ()
  (make-topic
   :id "reinstall-upstream-nix-on-macos"
   :title "Reinstall Upstream Nix on macOS"
   :summary "Primary recovery procedure for Intel macOS hosts: remove any Determinate-managed install, reinstall upstream Nix with the official macOS daemon path, and handle final macOS shell-setup edge cases."
   :references '("Reinstall Upstream Nix on macOS"
                 "Determinate Nix on macOS Intel"
                 "Inspect Nix Install State on macOS"
                 "Clear Stale Nix Installer Backup Files on macOS"
                 "Fix Nix SSL Certificate Path on macOS"
                 "Fix Fish direnv Hook Error"
                 "https://nix.dev/manual/nix/2.32/installation/installing-binary.html"
                 "https://nix.dev/manual/nix/2.32/installation/uninstall"
                 "https://github.com/NixOS/nix/issues/7894")))

(defun fix-nix-ssl-certificate-path-on-macos-topic ()
  (make-topic
   :id "fix-nix-ssl-certificate-path-on-macos"
   :title "Fix Nix SSL Certificate Path on macOS"
   :summary "Focused recovery page for the post-install SSL error in which Nix keeps using /etc/ssl/certs/ca-certificates.crt until ssl-cert-file is written persistently into /etc/nix/nix.conf."
   :references '("Fix Nix SSL Certificate Path on macOS"
                 "Reinstall Upstream Nix on macOS"
                 "Inspect Nix Install State on macOS"
                 "Fix Fish direnv Hook Error")))

(defun clear-stale-nix-installer-backup-files-on-macos-topic ()
  (make-topic
   :id "clear-stale-nix-installer-backup-files-on-macos"
   :title "Clear Stale Nix Installer Backup Files on macOS"
   :summary "Focused recovery page for stale backup-before-nix shell files that block an upstream macOS reinstall after architecture selection has already succeeded, including the distinction between a missing bashrc and a live bashrc plus stale backup."
   :references '("Clear Stale Nix Installer Backup Files on macOS"
                 "Reinstall Upstream Nix on macOS"
                 "Inspect Nix Install State on macOS"
                 "Determinate Nix on macOS Intel"
                 "https://nix.dev/manual/nix/2.32/installation/installing-binary.html"
                 "https://nix.dev/manual/nix/2.32/installation/uninstall")))

(defun restore-last-working-determinate-nix-on-macos-intel-topic ()
  (make-topic
   :id "restore-last-working-determinate-nix-on-macos-intel"
   :title "Restore Last Working Determinate Nix on macOS Intel"
   :summary "Legacy fallback page for trying the last plausible pre-drop Determinate installer line on Intel macOS, explicitly framed as unsupported best effort."
   :references '("Restore Last Working Determinate Nix on macOS Intel"
                 "Determinate Nix on macOS Intel"
                 "Inspect Nix Install State on macOS"
                 "Reinstall Upstream Nix on macOS"
                 "https://github.com/DeterminateSystems/nix-installer/releases/tag/v3.13.0"
                 "https://github.com/DeterminateSystems/nix-installer")))

(defun fix-fish-direnv-hook-error-topic ()
  (make-topic
   :id "fix-fish-direnv-hook-error"
   :title "Fix Fish direnv Hook Error"
   :summary "Shell-startup cleanup for fish plus the distinction that once direnv and nix-direnv checks pass, any failing direnv reload belongs to the project flake, potentially at a patchPhase or patch-tool boundary, rather than to missing direnv integration."
   :references '("Fix Fish direnv Hook Error"
                 "Inspect Nix Install State on macOS"
                 "Reinstall Upstream Nix on macOS"
                 "Fix Nix SSL Certificate Path on macOS"
                 "Determinate Nix on macOS Intel")))

(defun gtoolkit-and-hyperdoc-topic ()
  (make-topic
   :id "gtoolkit-and-hyperdoc"
   :title "Glamorous Toolkit and HyperDoc"
   :summary "Conceptual bridge page describing correspondences and distinctions between GT as a moldable environment and HyperDoc as a hypertext documentation system."
   :references '("Glamorous Toolkit and HyperDoc"
                 "Acknowledgements"
                 "Design"
                 "Goals and values"
                 "Installing Glamorous Toolkit"
                 "https://github.com/feenkcom/gtoolkit")))

(defun reference-platforms-topic ()
  (make-topic
   :id "reference-platforms"
   :title "Reference platforms"
   :summary "Reference platforms are used as conceptual anchors to compare adopted ideas, reinterpretations, and intentional omissions."
   :references '("Glamorous Toolkit and HyperDoc"
                 "Acknowledgements"
                 "Design")))

