;;;; HyperDoc authored topic family
;;;; Generated by splitting the former hyperdoc/topics.lisp monolith.

(in-package :hyperdoc)

;; Targeting-failure and civilian-harm accountability topics.
(defun minab-school-strike-allegations-topic ()
  (make-topic
   :id "minab-school-strike-allegations"
   :title "Minab school strike allegations"
   :summary "Allegation-qualified incident page for a supplied news text about an alleged school strike in Minab, preserving uncertainty about attribution, stale-target hypotheses, and accountability questions."
   :references '("Minab school strike allegations"
                 "Stale target coordinates"
                 "Precision weapons and wrong-target failure"
                 "Public attribution after disputed airstrikes"
                 "Human responsibility in AI-assisted targeting")))

(defun stale-target-coordinates-topic ()
  (make-topic
   :id "stale-target-coordinates"
   :title "Stale target coordinates"
   :summary "Failure mode in which a weapon can strike the wrong place precisely because the coordinates or site description are obsolete rather than because guidance failed."
   :references '("Stale target coordinates"
                 "Target validation"
                 "Precision weapons and wrong-target failure"
                 "Minab school strike allegations")))

(defun target-validation-topic ()
  (make-topic
   :id "target-validation"
   :title "Target validation"
   :summary "Pre-strike process for checking whether target coordinates, site status, classification, and collateral assumptions are still current enough to justify action."
   :references '("Target validation"
                 "Stale target coordinates"
                 "Civilian harm accountability"
                 "Minab school strike allegations")))

(defun precision-weapon-mistargeting-topic ()
  (make-topic
   :id "precision-weapon-mistargeting"
   :title "Precision weapons and wrong-target failure"
   :summary "Critical distinction between a precise weapon and a correct target: the munition can fly accurately while still being aimed at stale or incorrect coordinates."
   :references '("Precision weapons and wrong-target failure"
                 "Stale target coordinates"
                 "Target validation"
                 "Minab school strike allegations")))

(defun military-civilian-site-adjacency-topic ()
  (make-topic
   :id "military-civilian-site-adjacency"
   :title "Military target adjacency and dual-use misclassification"
   :summary "Risk that a civilian site near a military site inherits stale labels, ambiguous classification, or false target confidence through adjacency or dual-use assumptions."
   :references '("Military target adjacency and dual-use misclassification"
                 "Target validation"
                 "Stale target coordinates"
                 "Minab school strike allegations")))

(defun civilian-harm-accountability-topic ()
  (make-topic
   :id "civilian-harm-accountability"
   :title "Civilian harm accountability"
   :summary "Accountability frame for civilian deaths or injuries caused by targeting operations, keeping questions of negligence, legality, doctrine, and review depth visible without forcing premature legal closure."
   :references '("Civilian harm accountability"
                 "Civilian casualty mitigation in targeting operations"
                 "Command responsibility in targeting"
                 "Minab school strike allegations")))

(defun civilian-casualty-mitigation-topic ()
  (make-topic
   :id "civilian-casualty-mitigation"
   :title "Civilian casualty mitigation in targeting operations"
   :summary "Operational capacity for reducing civilian harm before launch through staffing, recent intelligence, escalation paths, and meaningful abort authority."
   :references '("Civilian casualty mitigation in targeting operations"
                 "Civilian harm accountability"
                 "Human responsibility in AI-assisted targeting")))

(defun command-responsibility-in-targeting-topic ()
  (make-topic
   :id "command-responsibility-in-targeting"
   :title "Command responsibility in targeting"
   :summary "Responsibility of commanders and approving structures for targeting doctrine, review quality, staffing, and the organizational conditions that shape strike decisions."
   :references '("Civilian harm accountability"
                 "Civilian casualty mitigation in targeting operations"
                 "Human responsibility in AI-assisted targeting"
                 "Minab school strike allegations")))

(defun disputed-strike-attribution-topic ()
  (make-topic
   :id "disputed-strike-attribution"
   :title "Public attribution after disputed airstrikes"
   :summary "Difference between immediate public blame claims after an airstrike and later attribution built from technical reconstruction and evidentiary review."
   :references '("Public attribution after disputed airstrikes"
                 "Investigating missile-origin claims"
                 "Minab school strike allegations")))

(defun missile-origin-forensics-topic ()
  (make-topic
   :id "missile-origin-forensics"
   :title "Investigating missile-origin claims"
   :summary "Forensic analysis of missile-origin hypotheses using imagery, fragments, inventory knowledge, trajectory reasoning, and other evidence layers rather than rhetoric alone."
   :references '("Investigating missile-origin claims"
                 "Public attribution after disputed airstrikes"
                 "Minab school strike allegations")))

(defun ai-assisted-targeting-topic ()
  (make-topic
   :id "ai-assisted-targeting"
   :title "AI-assisted targeting"
   :summary "Targeting workflow in which software helps rank, fuse, or interpret inputs without removing human responsibility for strike approval and civilian-harm review."
   :references '("Human responsibility in AI-assisted targeting"
                 "Civilian casualty mitigation in targeting operations"
                 "Minab school strike allegations")))

(defun human-in-the-loop-targeting-topic ()
  (make-topic
   :id "human-in-the-loop-targeting"
   :title "Human-in-the-loop targeting"
   :summary "Claim that a human remains in the decision chain for a strike, which must be evaluated against the quality of review time, information access, and substantive authority rather than signature alone."
   :references '("Human responsibility in AI-assisted targeting"
                 "Civilian harm accountability"
                 "Minab school strike allegations")))

;; Denkpanzer/think-tank conflict topics.
(defun denkpanzer-paper-2013-topic ()
  (make-topic
   :id "denkpanzer-paper-2013"
   :title "Denkpanzer paper 2013"
   :summary "Provenance topic for Ralf Barkow's 2013 work Denkpanzer stören, keeping the paper's Swiss think-tank framing and extracted conflict concepts linked without flattening them into one thesis."
   :references '("Denkpanzer paper 2013"
                 "Swiss think-tank model transfer"
                 "Power-of-definition conflict"
                 "Communication intensification as conflict early warning"
                 "Think-tank ideological temporization")))

(defun swiss-think-tank-model-transfer-topic ()
  (make-topic
   :id "swiss-think-tank-model-transfer"
   :title "Swiss think-tank model transfer"
   :summary "Analytic frame for asking how an Anglo-Saxon think-tank pattern is imported into Swiss organizational and media conditions and how local actors react to that import."
   :references '("Swiss think-tank model transfer"
                 "Denkpanzer paper 2013"
                 "Think-tank ideological temporization")))

(defun power-of-definition-conflict-topic ()
  (make-topic
   :id "power-of-definition-conflict"
   :title "Power-of-definition conflict"
   :summary "Conflict over who gets to define the relevant problem, values, and legitimate interpretation of a social situation, especially where hegemony and public framing are contested."
   :references '("Power-of-definition conflict"
                 "Denkpanzer paper 2013"
                 "Communication intensification as conflict early warning")))

(defun communication-intensification-early-warning-topic ()
  (make-topic
   :id "communication-intensification-early-warning"
   :title "Communication intensification as conflict early warning"
   :summary "The use of dense bursts of public communication as an observable signal that routine or fundamental social conflict may be intensifying."
   :references '("Communication intensification as conflict early warning"
                 "Power-of-definition conflict"
                 "Denkpanzer paper 2013")))

(defun think-tank-ideological-temporization-topic ()
  (make-topic
   :id "think-tank-ideological-temporization"
   :title "Think-tank ideological temporization"
   :summary "Observation of ideology through timing, attention cycles, and staged media situations rather than as a fixed left/right label alone."
   :references '("Think-tank ideological temporization"
                 "Swiss think-tank model transfer"
                 "Denkpanzer paper 2013")))

