;;;; HyperDoc authored topic family
;;;; Generated by splitting the former hyperdoc/topics.lisp monolith.

(in-package :hyperdoc)

;; Core topic objects for Concepts/DMX/Topic Maps page.
(defun concept-operational-definition ()
  (make-topic
   :id "concept-operational-definition"
   :title "Concept"
   :summary "A concept is an identifiable subject with stable identity, names, occurrences, and associations."
   :references '("Operational Definition of Subject Identity"
                 "Concepts, DMX Topics, and Topic Maps")))

(defun topic-map-operational-definition ()
  (make-topic
   :id "topic-map-operational-definition"
   :title "Topic Map"
   :summary "A topic map is a graph of topics that separates subject identity from any single document or rendering."
   :references '("Concepts, DMX Topics, and Topic Maps")))

(defun dmx-topic-operational-definition ()
  (make-topic
   :id "dmx-topic-operational-definition"
   :title "DMX Topic"
   :summary "A DMX topic is an addressable runtime topic object with type/value/association structure."
   :references '("Concepts, DMX Topics, and Topic Maps")))

(defun concepts-dmx-topics-and-topic-maps-topic ()
  (make-topic
   :id "concepts-dmx-topics-and-topic-maps"
   :title "Concepts, DMX Topics, and Topic Maps"
   :summary "Explains how concepts, topic maps, and DMX topics relate, why associations are first-class topics, and how Touch-Fahrplan's station/route metaphor preserves that stronger model."
   :references '("Concept"
                 "Topic Map"
                 "DMX Topic"
                 "Demonstrating DMX Topic Proxies in HyperDoc")))

;; Topic objects for AArch64 SD-image preparation flow.
(defun create-sd-card-from-playground-task-topic ()
  (make-topic
   :id "create-sd-card-from-playground-task"
   :title "Create NixOS SD card from HyperDoc Playground task"
   :summary "DITA-style task for producing and flashing a Raspberry Pi NixOS SD card using runbook-aligned command plans from Playground."
   :references '("Create NixOS SD Card from HyperDoc Playground"
                 "Runbook - Build and Flash NixOS SD Image for Kioskbeerli"
                 "Prepare the AArch64 image")))

(defun sd-card-command-plan-playground-topic ()
  (make-topic
   :id "sd-card-command-plan-playground"
   :title "SD card command plan in Playground"
   :summary "Inspectable command-plan and dry-run functions that mirror the official runbook sequence."
   :references '("Create NixOS SD Card from HyperDoc Playground"
                 "Runbook - Build and Flash NixOS SD Image for Kioskbeerli"
                 "SBCL Process")))

(defun sd-card-procedure-step-raw-structure-fix-topic ()
  (make-topic
   :id "sd-card-procedure-step-raw-structure-fix"
   :title "SD-card procedure-step raw-structure fix"
   :summary "Raw Structure now derives from semantic step slots via computed raw-structure, preventing NIL views when id/title/summary/commands are present."
   :references '("Create NixOS SD Card from HyperDoc Playground"
                 "Official Tutorial: NixOS SD Image on Raspberry Pi 4/400"
                 "official-rpi-tutorial-step-raw-structure-regression-example"
                 "a735927")))

(defun semantic-navigation-visible-clickable-topic ()
  (make-topic
   :id "semantic-navigation-visible-clickable"
   :title "Semantic navigation visible and clickable"
   :summary "Primary navigation must stay semantic, visible, and clickable; raw structure is diagnostics-only and must not become the primary path."
   :references '("Create NixOS SD Card from HyperDoc Playground"
                 "Surface and Artifact Answers"
                 "Communication Surfaces Policy")))

(defun semantic-first-anchor-resolution-topic ()
  (make-topic
   :id "semantic-first-anchor-resolution"
   :title "Semantic-first anchor resolution"
   :summary "Connect treats visible selection as a presentation gesture, resolves it to a semantic anchor, and keeps DOM or selector data as fallback metadata only."
   :references '("Semantic-first anchor resolution"
                 "Concepts, DMX Topics, and Topic Maps"
                 "Documentation Architecture in HyperDoc")))

(defun sd-image-zstd-to-img-handoff-defect-topic ()
  (make-topic
   :id "sd-image-zstd-to-img-handoff-defect"
   :title "SD-image zstd-to-img handoff defect"
   :summary "Relation bug between official steps 1 and 2: download produces .zstd while flash requires .img; fixed by explicit decompression step, with .img.zst/.img coexistence treated as normal."
   :references '("Official Tutorial: NixOS SD Image on Raspberry Pi 4/400"
                 "Create NixOS SD Card from HyperDoc Playground"
                 "Violated handoff"
                 "official-rpi-zstd-to-img-handoff-regression-example")))

(defun hydra-latest-filename-handoff-defect-topic ()
  (hydra-filename-loss-topic))

(defun hydra-filename-loss-topic ()
  (make-topic
   :id "hydra-filename-loss"
   :title "Hydra filename loss"
   :summary "Failure classification: naive latest/download/1 retrieval can save as file '1', losing artifact filename provenance and requiring recovery."
   :references '("Official Tutorial: NixOS SD Image on Raspberry Pi 4/400"
                 "SD-image zstd-to-img handoff defect"
                 "Create NixOS SD Card from HyperDoc Playground"
                 "official-rpi-hydra-filename-preservation-regression-example")))

(defun expr-string-quoting-regression-topic ()
  (make-topic
   :id "expr-string-quoting-regression"
   :title "Expr string quoting regression"
   :summary "Resolved regression where expr links with Lisp string args rendered visible labels but produced no clickable inspector refs."
   :references '("Official Tutorial: NixOS SD Image on Raspberry Pi 4/400"
                 "writing-pages.md"
                 "da8c815"
                 "3cf4ff4")))

(defun rpi-first-boot-access-paths-topic ()
  (make-topic
   :id "rpi-first-boot-access-paths"
   :title "Raspberry Pi first-boot access paths"
   :summary "Distinguishes stock official SD-image boot, one-time local-console bootstrap, and fully headless preconfigured-image access."
   :references '("Official Tutorial: NixOS SD Image on Raspberry Pi 4/400"
                 "Prepare the AArch64 image"
                 "Runbook - Build and Flash NixOS SD Image for Kioskbeerli"
                 "Salon Pi 4 Kiosk Hardening Checklist"
                 "Two Installation Models: SD Image vs Classic Installer")))

(defun nixos-rebuild-topic ()
  (make-topic
   :id "nixos-rebuild"
   :title "nixos-rebuild"
   :summary "Umbrella topic for rebuild operations in this SD-image workflow."
   :references '("Official Tutorial: NixOS SD Image on Raspberry Pi 4/400"
                 "Runbook - Build and Flash NixOS SD Image for Kioskbeerli"
                 "Two Installation Models: SD Image vs Classic Installer")))

(defun nixos-rebuild-boot-topic ()
  (make-topic
   :id "nixos-rebuild-boot"
   :title "nixos-rebuild boot"
   :summary "Write next boot generation to /boot; preferred first rebuild in the flashed SD-image workflow."
   :references '("Official Tutorial: NixOS SD Image on Raspberry Pi 4/400"
                 "Runbook - Build and Flash NixOS SD Image for Kioskbeerli"
                 "Invariant: Boot Partition Must Be Big Enough"
                 "Two Installation Models: SD Image vs Classic Installer")))

(defun nixos-rebuild-switch-topic ()
  (make-topic
   :id "nixos-rebuild-switch"
   :title "nixos-rebuild switch"
   :summary "Activate immediately; only use later, after reboot safety is established."
   :references '("Official Tutorial: NixOS SD Image on Raspberry Pi 4/400"
                 "Runbook - Build and Flash NixOS SD Image for Kioskbeerli"
                 "Pre-flight Checklist for Raspberry Pi NixOS SD Images")))

(defun nixos-rebuild-test-topic ()
  (make-topic
   :id "nixos-rebuild-test"
   :title "nixos-rebuild test"
   :summary "Runtime-only activation; does not prove boot-path safety."
   :references '("Invariant: Boot Partition Must Be Big Enough"
                 "Pre-flight Checklist for Raspberry Pi NixOS SD Images")))

(defun first-rebuild-before-first-reboot-topic ()
  (make-topic
   :id "first-rebuild-before-first-reboot"
   :title "First rebuild before first reboot"
   :summary "The first configuration change after flashing should be followed by nixos-rebuild boot, then reboot."
   :references '("Official Tutorial: NixOS SD Image on Raspberry Pi 4/400"
                 "Runbook - Build and Flash NixOS SD Image for Kioskbeerli"
                 "Two Installation Models: SD Image vs Classic Installer")))

(defun reboot-safety-gate-topic ()
  (make-topic
   :id "reboot-safety-gate"
   :title "Reboot safety gate"
   :summary "Pre-flight checks required before trusting the next reboot after rebuild."
   :references '("Pre-flight Checklist for Raspberry Pi NixOS SD Images"
                 "Runbook - Build and Flash NixOS SD Image for Kioskbeerli"
                 "Invariant: Boot Partition Must Be Big Enough")))

(defun boot-partition-capacity-for-nixos-rebuild-boot-topic ()
  (make-topic
   :id "boot-partition-capacity-for-nixos-rebuild-boot"
   :title "Boot partition capacity for nixos-rebuild boot"
   :summary "nixos-rebuild boot depends on adequate /boot capacity and intact extlinux state."
   :references '("Invariant: Boot Partition Must Be Big Enough"
                 "Pre-flight Checklist for Raspberry Pi NixOS SD Images"
                 "Runbook - Build and Flash NixOS SD Image for Kioskbeerli")))

(defun sd-image-first-rebuild-model-topic ()
  (make-topic
   :id "sd-image-first-rebuild-model"
   :title "SD-image first rebuild model"
   :summary "The preinstalled-image workflow uses nixos-rebuild boot; contrast with installer workflow."
   :references '("Two Installation Models: SD Image vs Classic Installer"
                 "Official Tutorial: NixOS SD Image on Raspberry Pi 4/400"
                 "Runbook - Build and Flash NixOS SD Image for Kioskbeerli")))

(defun classic-installer-model-topic ()
  (make-topic
   :id "classic-installer-model"
   :title "Classic installer model"
   :summary "The /mnt installer path uses nixos-install, not nixos-rebuild boot."
   :references '("Two Installation Models: SD Image vs Classic Installer"
                 "Official Tutorial: NixOS SD Image on Raspberry Pi 4/400")))

(defun dreyeck-supported-deployment-model-topic ()
  (make-topic
   :id "dreyeck-supported-deployment-model"
   :title "dreyeck supported deployment model"
   :summary "Verify locally, then deploy dreyeck.ch from local flake state; do not repair the server by branch checkout."
   :references '("Get hauptsache working on dreyeck.ch"
                 "Deploy dreyeck.ch from the local flake"
                 "Verify HyperDoc locally before deployment")))

(defun dreyeck-mcp-additive-host-integration-topic ()
  (make-topic
   :id "dreyeck-mcp-additive-host-integration"
   :title "dreyeck MCP additive host integration"
   :summary "Keep the MCP package and reusable NixOS module in the HyperDoc repo, but install a host-owned module copy and store-pinned additive sidecar under /etc/nixos so hyperdoc-mcp runs beside the existing workspace-based hyperdoc.service without evaluating a mutable checkout at activation time."
   :references '("Add HyperDoc MCP beside the authoritative host config on dreyeck.ch"
                 "DMX MCP server for shared workspace"
                 "Roll back HyperDoc on dreyeck.ch")))

(defun git-repository-root-override-semantics-topic ()
  (make-topic
   :id "git-repository-root-override-semantics"
   :title "Git Repository Root Override Semantics"
   :summary "Git-backed history surfaces first honor explicit repository-root overrides and otherwise fall back to the loaded system source tree, which means packaged releases and live checkouts intentionally differ."
   :references '("Git Repository Root Override Semantics"
                 "Canonical Route Discovery for Runtime Smoke Tests"
                 "Git History Surface for HyperDoc")))

(defun static-route-observability-topic ()
  (make-topic
   :id "static-route-observability"
   :title "Static route observability"
   :summary "Operational skill for computing which runtime component owns a static asset path before falling back to live HTTP probes."
   :references '("Static route observability"
                 "Diagnose static asset route ownership")))

(defun diagnose-static-asset-route-ownership-topic ()
  (make-topic
   :id "diagnose-static-asset-route-ownership"
   :title "Diagnose static asset route ownership"
   :summary "Task skill for deciding whether a broken asset belongs to the CLOG static root or to an explicit mounted asset route."
   :references '("Diagnose static asset route ownership"
                 "Static route observability")))

(defun static-asset-path-resolution-topic ()
  (make-topic
   :id "static-asset-path-resolution"
   :title "Static asset path resolution"
   :summary "Inspectable mapping from a public asset path to its owning route contract, root path, and resolved file."
   :references '("Static route observability"
                 "Diagnose static asset route ownership")))

(defun annotated-merge-forecast-paths-topic ()
  (make-topic
   :id "annotated-merge-forecast-paths"
   :title "Annotated merge-forecast paths"
   :summary "Skill for treating merge-forecast path rows as inspectable objects with path annotations, related decisions, and a custom context-command surface."
   :references '("Annotated merge-forecast paths"
                 "Add or edit an annotation from a path context menu"
                 "Git History Surface for HyperDoc")))

(defun add-or-edit-an-annotation-from-a-path-context-menu-topic ()
  (make-topic
   :id "add-or-edit-an-annotation-from-a-path-context-menu"
   :title "Add or edit an annotation from a path context menu"
   :summary "Task skill for opening the draft or explicit path-annotation object behind a merge-forecast row without executing a merge."
   :references '("Add or edit an annotation from a path context menu"
                 "Annotated merge-forecast paths"
                 "Git History Surface for HyperDoc")))

(defun context-commands-for-inspectable-path-rows-topic ()
  (make-topic
   :id "context-commands-for-inspectable-path-rows"
   :title "Context commands for inspectable path rows"
   :summary "Current HyperDoc pattern where hidden object-ref actions, custom JS/CSS, and row target objects provide Details, Add annotation, Edit annotation, and Related decisions commands."
   :references '("Annotated merge-forecast paths"
                 "Add or edit an annotation from a path context menu"
                 "Git History Surface for HyperDoc")))

(defun inspectable-operational-targets-topic ()
  (make-topic
   :id "inspectable-operational-targets"
   :title "Inspectable operational targets"
   :summary "Skill for representing live hosts and host-aware Git operations as inspectable objects that render concrete shell materializations without executing them."
   :references '("Inspectable operational targets"
                 "Materialize a host-aware operation without executing it"
                 "Operational Target Objects for dreyeck.ch")))

(defun materialize-a-host-aware-operation-without-executing-it-topic ()
  (make-topic
   :id "materialize-a-host-aware-operation-without-executing-it"
   :title "Materialize a host-aware operation without executing it"
   :summary "Task skill for inspecting a host target or Git remote operation and extracting the exact shell block to run manually on the target host."
   :references '("Materialize a host-aware operation without executing it"
                 "Inspectable operational targets"
                 "Operational Target Objects for dreyeck.ch")))

(defun nixos-host-target-objects-topic ()
  (make-topic
   :id "nixos-host-target-objects"
   :title "NixOS host target objects"
   :summary "Object pattern that captures a host's SSH identity, checkout root, service name, and deployment mode so operational commands can be materialized consistently."
   :references '("Inspectable operational targets"
                 "Materialize a host-aware operation without executing it"
                 "Operational Target Objects for dreyeck.ch")))

(defun dreyeck-git-readiness-topic ()
  (make-topic
   :id "dreyeck-git-readiness"
   :title "Dreyeck Git readiness for upstream-backed inspection"
   :summary "Operator-facing readiness model for deciding whether the current dreyeck runtime can inspect Konrad's upstream/main history locally, and for exposing explicit add-remote and fetch operations when it cannot."
   :references '("Dreyeck Git readiness for upstream-backed inspection"
                 "Operational Target Objects for dreyeck.ch"
                 "Check upstream commit assimilation equivalence"
                 "Graphviz story item upstream assimilation example"
                 "Prove commit equivalence from graph/history")))

(defun prove-commit-equivalence-from-graph-history-topic ()
  (make-topic
   :id "prove-commit-equivalence-from-graph-history"
   :title "Prove commit equivalence from graph/history"
   :summary "Read-only skill for distinguishing direct ancestry from replay-equivalent content by combining merge-base, cherry, left/right history, and range-diff with an explicit shared base."
   :references '("Prove commit equivalence from graph/history"
                 "Check upstream commit assimilation equivalence"
                 "Graphviz story item upstream assimilation example"
                 "Check whether a preserved commit was replayed equivalently"
                 "Why a commit hash can stay outside the target branch even when its content is integrated")))

(defun check-whether-a-preserved-commit-was-replayed-equivalently-topic ()
  (make-topic
   :id "check-whether-a-preserved-commit-was-replayed-equivalently"
   :title "Check whether a preserved commit was replayed equivalently"
   :summary "Task skill for proving whether a preserved source commit is absent from target ancestry only as an original hash while an equivalent replay exists on the target branch."
   :references '("Check whether a preserved commit was replayed equivalently"
                 "Check upstream commit assimilation equivalence"
                 "Prove commit equivalence from graph/history"
                 "Why a commit hash can stay outside the target branch even when its content is integrated")))

(defun check-upstream-commit-assimilation-equivalence-topic ()
  (make-topic
   :id "check-upstream-commit-assimilation-equivalence"
   :title "Check upstream commit assimilation equivalence"
   :summary "Task skill for deciding whether an upstream commit should be cherry-picked, manually assimilated, or treated as already present in effect on the target branch by layering semantic proof and focused validation on top of commit-equivalence proof."
   :references '("Check upstream commit assimilation equivalence"
                 "Dreyeck Git readiness for upstream-backed inspection"
                 "Graphviz story item upstream assimilation example"
                 "Prove commit equivalence from graph/history"
                 "Check whether a preserved commit was replayed equivalently"
                 "Why a commit hash can stay outside the target branch even when its content is integrated")))

(defun graphviz-story-item-upstream-assimilation-example-topic ()
  (make-topic
   :id "graphviz-story-item-upstream-assimilation-example"
   :title "Graphviz story item upstream assimilation example"
   :summary "Worked example for the upstream commit assimilation skill showing that upstream graphviz commit ceae9d is already assimilated in effect on hauptsache because earlier local commit b1e8d404, the current text-backed constructor path, the corpus trace, and focused rendering validation already carry the live behavior."
   :references '("Graphviz story item upstream assimilation example"
                 "Dreyeck Git readiness for upstream-backed inspection"
                 "Check upstream commit assimilation equivalence"
                 "Prove commit equivalence from graph/history"
                 "FedWiki Graphviz story item render trace")))

(defun commit-equivalence-vs-ancestry-topic ()
  (make-topic
   :id "commit-equivalence-vs-ancestry"
   :title "Commit equivalence vs ancestry"
   :summary "Concept boundary between original commit identity and content equivalence, where a target branch can integrate a patch under a replayed hash without containing the original commit object."
   :references '("Why a commit hash can stay outside the target branch even when its content is integrated"
                 "Check upstream commit assimilation equivalence"
                 "Prove commit equivalence from graph/history"
                 "Check whether a preserved commit was replayed equivalently")))

(defun synchronization-as-a-visualization-problem-topic ()
  (make-topic
   :id "synchronization-as-a-visualization-problem"
   :title "Synchronization as a Visualization Problem"
   :summary "Synchronization becomes a HyperDoc exploration surface when the main question is how to make the onset of global coherence legible rather than merely computable."
   :references '("Synchronization as a Visualization Problem")))

(defun legacy-workspace-checkout-unit-topic ()
  (make-topic
   :id "legacy-workspace-checkout-unit"
   :title "Legacy workspace-checkout hyperdoc.service"
   :summary "Old unit model that starts HyperDoc from /home/rgb/workspace/hyperdoc/start.sh instead of packaged host deployment."
   :references '("Detect legacy workspace-checkout hyperdoc.service on dreyeck.ch"
                 "Locate and replace the legacy workspace hyperdoc.service definition")))

(defun legacy-sbcl-path-failure-topic ()
  (make-topic
   :id "legacy-sbcl-path-failure"
   :title "Legacy sbcl PATH failure"
   :summary "Legacy workspace service can fail with status 127 when start.sh calls sbcl but service PATH does not provide it."
   :references '("Diagnose sbcl command-not-found in the legacy hyperdoc.service"
                 "Detect legacy workspace-checkout hyperdoc.service on dreyeck.ch")))

(defun replace-legacy-unit-with-flake-host-profile-topic ()
  (make-topic
   :id "replace-legacy-unit-with-flake-host-profile"
   :title "Replace legacy unit with flake host profile"
   :summary "Remove workspace-checkout unit wiring and use flake-driven host deployment outputs for dreyeck.ch."
   :references '("Locate and replace the legacy workspace hyperdoc.service definition"
                 "Deploy dreyeck.ch from the local flake")))

(defun deployment-command-locality-topic ()
  (make-topic
   :id "deployment-command-locality"
   :title "Deployment command locality"
   :summary "Distinguish controller-local commands, commands executed remotely on dreyeck.ch via SSH, and public URL probes."
   :references '("Back up dreyeck.ch before deployment"
                 "Record dreyeck.ch generation before rebuild"
                 "Verify HyperDoc on dreyeck.ch"
                 "Rehearse dreyeck.ch deployment with runner")))

(defun dreyeck-backup-before-rebuild-topic ()
  (make-topic
   :id "dreyeck-backup-before-rebuild"
   :title "dreyeck backup before rebuild"
   :summary "Create timestamped backups on dreyeck.ch before any dry-activate, test, or switch activation."
   :references '("Back up dreyeck.ch before deployment"
                 "Record dreyeck.ch generation before rebuild")))

(defun dreyeck-generation-record-topic ()
  (make-topic
   :id "dreyeck-generation-record"
   :title "dreyeck generation record"
   :summary "Capture list-generations and current/booted system links before activation changes."
   :references '("Record dreyeck.ch generation before rebuild"
                 "Roll back HyperDoc on dreyeck.ch")))

(defun dreyeck-local-verification-gate-topic ()
  (make-topic
   :id "dreyeck-local-verification-gate"
   :title "dreyeck local verification gate"
   :summary "Local deployment gate using git status, nix flake check, and release-smoke before remote activation."
   :references '("Verify HyperDoc locally before deployment"
                 "Deploy dreyeck.ch from the local flake")))

(defun cautious-nixos-rebuild-activation-sequence-topic ()
  (make-topic
   :id "cautious-nixos-rebuild-activation-sequence"
   :title "Cautious nixos-rebuild activation sequence"
   :summary "Use dry-activate, then test, verify HTTP checks, and only then run switch."
   :references '("Deploy dreyeck.ch from the local flake"
                 "Verify HyperDoc on dreyeck.ch"
                 "Roll back HyperDoc on dreyeck.ch")))

(defun dreyeck-http-smoke-probes-topic ()
  (make-topic
   :id "dreyeck-http-smoke-probes"
   :title "dreyeck HTTP smoke probes"
   :summary "Post-activation checks for boot page, official tutorial page, and URL helper asset."
   :references '("Verify HyperDoc on dreyeck.ch"
                 "Deploy dreyeck.ch from the local flake")))

(defun nixos-generation-rollback-topic ()
  (make-topic
   :id "nixos-generation-rollback"
   :title "NixOS generation rollback"
   :summary "Rollback via nixos-rebuild --rollback or activate a specific system generation link."
   :references '("Roll back HyperDoc on dreyeck.ch"
                 "Deploy dreyeck.ch from the local flake")))

(defun dreyeck-runner-rehearsal-topic ()
  (make-topic
   :id "dreyeck-runner-rehearsal"
   :title "dreyeck runner rehearsal"
   :summary "Runner-driven non-destructive rehearsal path that performs backup, generation record, verify, dry-activate, test, and HTTP checks without implicit switch."
   :references '("Rehearse dreyeck.ch deployment with runner"
                 "Deploy dreyeck.ch from the local flake")))

(defun deploy-or-restart-dreyeck-and-confirm-live-parity-topic ()
  (make-topic
   :id "deploy-or-restart-dreyeck-and-confirm-live-parity"
   :title "Deploy or restart dreyeck and confirm live parity"
   :summary "Operator task that sequences local verification, cautious deploy or restart, and post-start parity checks for the dreyeck service."
   :references '("Onboarding dreyeck deployment and restart"
                 "Deploy or restart dreyeck and confirm live parity"
                 "Deploy dreyeck.ch from the local flake"
                 "Restart dreyeck release service"
                 "Confirm scoped example parity on dreyeck")))

(defun restart-dreyeck-release-service-topic ()
  (make-topic
   :id "restart-dreyeck-release-service"
   :title "Restart dreyeck release service"
   :summary "Restart the packaged dreyeck HyperDoc service, verify that it comes back, and treat restart as a scoped operational path distinct from full deployment."
   :references '("Restart dreyeck release service"
                 "HyperDoc Server"
                 "Verify HyperDoc on dreyeck.ch")))

(defun confirm-scoped-example-parity-on-dreyeck-topic ()
  (make-topic
   :id "confirm-scoped-example-parity-on-dreyeck"
   :title "Confirm scoped example parity on dreyeck"
   :summary "Post-start task for confirming that portable and ops example scopes are present on dreyeck through both UI evidence and runtime probes."
   :references '("Confirm scoped example parity on dreyeck"
                 "Probe dreyeck runtime load set"
                 "Verify HyperDoc on dreyeck.ch"
                 "Portable examples in HyperDoc")))

(defun probe-dreyeck-runtime-load-set-topic ()
  (make-topic
   :id "probe-dreyeck-runtime-load-set"
   :title "Probe dreyeck runtime load set"
   :summary "Inspect loaded ASDF systems and discover-example-checks results on dreyeck to confirm whether the intended scoped example layers are active."
   :references '("Probe dreyeck runtime load set"
                 "HyperDoc Server"
                 "Confirm scoped example parity on dreyeck")))

(defun scoped-example-parity-topic ()
  (make-topic
   :id "scoped-example-parity"
   :title "Scoped example parity"
   :summary "Operational parity in which localhost and dreyeck expose the same intended example scopes for their loaded HyperDoc systems."
   :references '("Scoped example parity"
                 "Confirm scoped example parity on dreyeck"
                 "Portable examples in HyperDoc")))

(defun startup-load-set-mismatch-topic ()
  (make-topic
   :id "startup-load-set-mismatch"
   :title "Startup load-set mismatch"
   :summary "A deployment/runtime drift where startup reaches the server implementation but under-loads the HyperDoc systems needed for the intended discoverable surfaces."
   :references '("Startup load-set mismatch"
                 "HyperBook server vs HyperDoc server load set"
                 "HyperDoc Server")))

(defun load-before-serve-for-scoped-examples-topic ()
  (make-topic
   :id "load-before-serve-for-scoped-examples"
   :title "Load before serve for scoped examples"
   :summary "Portable and ops example scopes only become discoverable if their ASDF systems are loaded before the service begins serving HyperDoc."
   :references '("Load before serve for scoped examples"
                 "HyperDoc Server"
                 "Portable examples in HyperDoc")))

(defun hyperbook-server-vs-hyperdoc-server-load-set-topic ()
  (make-topic
   :id "hyperbook-server-vs-hyperdoc-server-load-set"
   :title "HyperBook server vs HyperDoc server load set"
   :summary "Loading :hyperbook/server reaches the generic server implementation, while :hyperdoc/server reaches the HyperDoc-specific load set expected for scoped example parity."
   :references '("HyperBook server vs HyperDoc server load set"
                 "HyperDoc Server"
                 "Startup load-set mismatch")))

(defun live-parity-evidence-topic ()
  (make-topic
   :id "live-parity-evidence"
   :title "Live parity evidence"
   :summary "Acceptable evidence for parity includes HTTP/UI confirmation, runtime probe confirmation, and service-status or log confirmation, with stronger weight on direct runtime evidence."
   :references '("Live parity evidence"
                 "Confirm scoped example parity on dreyeck"
                 "Probe dreyeck runtime load set")))

(defun training-arc-deploy-and-restart-dreyeck-safely-topic ()
  (make-topic
   :id "training-arc-deploy-and-restart-dreyeck-safely"
   :title "Training arc: deploy and restart dreyeck safely"
   :summary "Guided sequence that teaches a new operator to verify locally, back up, rehearse, deploy or restart, and roll back dreyeck safely."
   :references '("Training arc: deploy and restart dreyeck safely"
                 "Onboarding dreyeck deployment and restart"
                 "Deploy dreyeck.ch from the local flake"
                 "Roll back HyperDoc on dreyeck.ch")))

(defun training-arc-verify-scoped-examples-after-deployment-topic ()
  (make-topic
   :id "training-arc-verify-scoped-examples-after-deployment"
   :title "Training arc: verify scoped examples after deployment"
   :summary "Guided sequence for understanding load-set mismatch, probing the running image, and confirming portable and ops example parity after deployment or restart."
   :references '("Training arc: verify scoped examples after deployment"
                 "Onboarding dreyeck deployment and restart"
                 "Confirm scoped example parity on dreyeck"
                 "Probe dreyeck runtime load set")))

(defun new-team-member-onboarding-for-dreyeck-operations-topic ()
  (make-topic
   :id "new-team-member-onboarding-for-dreyeck-operations"
   :title "New team member onboarding for dreyeck operations"
   :summary "Learning/training topic that introduces what dreyeck is, what can be rehearsed locally, what touches the remote host, and how to judge success or failure safely."
   :references '("New team member onboarding for dreyeck operations"
                 "Onboarding dreyeck deployment and restart"
                 "Training arc: deploy and restart dreyeck safely"
                 "Training arc: verify scoped examples after deployment")))

(defun onboarding-dreyeck-deployment-and-restart-topic ()
  (make-topic
   :id "onboarding-dreyeck-deployment-and-restart"
   :title "Onboarding dreyeck deployment and restart"
   :summary "Entry-point topic for learning how to deploy or restart dreyeck, verify live parity, and recover safely using the existing HyperDoc deployment runbooks."
   :references '("Onboarding dreyeck deployment and restart"
                 "Deploy or restart dreyeck and confirm live parity"
                 "Training arc: deploy and restart dreyeck safely"
                 "Training arc: verify scoped examples after deployment")))

(defun dmx-topic-912138 ()
  (make-topic
   :id "dmx-topic-912138"
   :title "DMX Topic 912138"
   :summary "External DMX topic reference for the AArch64 image preparation context."
   :references '("https://dmx.ralfbarkow.ch/systems.dmx.webclient/#/topicmap/912102/topic/912138/info")))

;; Command and artifact topics for the tutorial sequence.
(defun nix-shell-topic ()
  (make-topic
   :id "nix-shell"
   :title "nix-shell"
   :summary "Ephemeral environment launcher used to provide wget/zstd for image preparation."
   :references '("Prepare the AArch64 image")))

(defun wget-topic ()
  (make-topic
   :id "wget"
   :title "wget"
   :summary "Downloader used to fetch the selected Hydra SD-image artifact."
   :references '("Prepare the AArch64 image")))

(defun zstd-topic ()
  (make-topic
   :id "zstd"
   :title "zstd"
   :summary "Compression tool used for .img.zst artifacts."
   :references '("Prepare the AArch64 image")))

(defun unzstd-topic ()
  (make-topic
   :id "unzstd-d"
   :title "unzstd -d"
   :summary "Decompression command to convert .img.zst into a flashable .img."
   :references '("Prepare the AArch64 image")))

(defun dmesg-follow-topic ()
  (make-topic
   :id "dmesg-follow"
   :title "dmesg --follow"
   :summary "Kernel log follow mode used to observe SD-card device attach events."
   :references '("Prepare the AArch64 image")))

(defun hydra-latest-job-topic ()
  (make-topic
   :id "hydra-latest-job"
   :title "Hydra latest SD-image job"
   :summary "Hydra unstable job endpoint used to select the latest successful aarch64 SD-image build."
   :references '("https://hydra.nixos.org/job/nixos/unstable/nixos.sd_image.aarch64-linux")))

(defun hydra-build-323111513-topic ()
  (make-topic
   :id "hydra-build-323111513"
   :title "Hydra build 323111513"
   :summary "Concrete chosen build artifact for the current preparation pass."
   :references '("https://hydra.nixos.org/build/323111513")))

(defun nixos-image-sd-card-26-05pre958232-80bdc1e5ce51-aarch64-linux-img-zst-topic ()
  (make-topic
   :id "nixos-image-sd-card-26-05pre958232-80bdc1e5ce51-aarch64-linux-img-zst"
   :title "nixos-image-sd-card-26.05pre958232.80bdc1e5ce51-aarch64-linux.img.zst"
   :summary "Concrete Hydra SD-image artifact filename selected for the current aarch64 preparation flow."
   :references '("Prepare the AArch64 image"
                 "Hydra build 323111513"
                 "https://hydra.nixos.org/build/323111513/download/1/nixos-image-sd-card-26.05pre958232.80bdc1e5ce51-aarch64-linux.img.zst")))

(defun hydra-click-path-hop-topic ()
  (make-topic
   :id "hydra-click-path-hop"
   :title "Hydra click-path hop"
   :summary "A single navigational step in the tutorial Hydra path: job page -> build page -> concrete artifact download."
   :references '("Official Tutorial: NixOS SD Image on Raspberry Pi 4/400"
                 "Hydra latest SD-image job"
                 "Hydra build 323111513"
                 "nixos-image-sd-card-26.05pre958232.80bdc1e5ce51-aarch64-linux.img.zst")))

(defun hydra-latest-download-link-topic ()
  (make-topic
   :id "hydra-latest-download-link"
   :title "Hydra latest download link"
   :summary "Stable 'latest' download-by-type link for SD-image artifacts."
   :references '("https://hydra.nixos.org/job/nixos/unstable/nixos.sd_image.aarch64-linux/latest/download-by-type/file/sd-image"
                 "https://hydra.nixos.org/job/nixos/unstable/nixos.sd_image.aarch64-linux/latest/download/1")))

(defun hydra-download-artifact-procedure-topic ()
  (make-topic
   :id "hydra-download-artifact-procedure"
   :title "Download artifact from Hydra"
   :summary "Normative successful path: resolve the exact Hydra build behind latest/download/1, read build product 1 metadata, download the named .img.zst explicitly as the published filename, verify it against the published SHA-256, decompress to .img, and use .img as flash input while .img.zst may remain as preserved download identity."
   :references '("Prepare the AArch64 image"
                 "Runbook - Build and Flash NixOS SD Image for Kioskbeerli"
                 "Hydra artifact to flashable image handoff"
                 "Hydra latest SD-image job"
                 "Hydra latest download link"
                 "Verify Hydra artifact checksum"
                 "Hydra filename loss"
                 "hydra-filename-outcome-states-example")))

(defun hydra-artifact-to-flashable-image-handoff-topic ()
  (make-topic
   :id "hydra-artifact-to-flashable-image-handoff"
   :title "Hydra artifact to flashable image handoff"
   :summary "Decompression handoff transforms the downloaded .img.zst artifact into a flashable .img; both files may coexist afterward and only .img is flash input."
   :references '("Prepare the AArch64 image"
                 "Runbook - Build and Flash NixOS SD Image for Kioskbeerli"
                 "Official Tutorial: NixOS SD Image on Raspberry Pi 4/400"
                 "hydra-filename-outcome-states-example")))

(defun hydra-sha256-topic ()
  (make-topic
   :id "hydra-sha256"
   :title "Hydra artifact SHA-256"
   :summary "Published SHA-256 for Hydra build product 1; the authoritative machine-readable source is the exact build JSON field buildproducts[\"1\"][\"sha256hash\"]."
   :references '("Prepare the AArch64 image"
                 "Runbook - Build and Flash NixOS SD Image for Kioskbeerli"
                 "Verify Hydra artifact checksum"
                 "https://hydra.nixos.org/job/nixos/unstable/nixos.sd_image.aarch64-linux/latest/download/1")))

(defun verify-hydra-artifact-checksum-topic ()
  (make-topic
   :id "verify-hydra-artifact-checksum"
   :title "Verify Hydra artifact checksum"
   :summary "Resolve the exact Hydra build behind latest/download/1, fetch build product 1 metadata from that build URL as JSON, and compare the local SHA-256 to buildproducts[\"1\"][\"sha256hash\"] before decompression."
   :references '("Prepare the AArch64 image"
                 "Runbook - Build and Flash NixOS SD Image for Kioskbeerli"
                 "Hydra latest download link"
                 "Hydra artifact SHA-256")))

;; Procedure-step topics for "Prepare the AArch64 image".
(defun aarch64-procedure-select-source-topic ()
  (make-topic
   :id "aarch64-procedure-select-source"
   :title "Procedure step 1: select one source of truth"
   :summary "Choose exactly one source for the SD image artifact: official prebuilt image or project build output."
   :references '("Prepare the AArch64 image"
                 "Official Tutorial: NixOS SD Image on Raspberry Pi 4/400"
                 "Runbook - Build and Flash NixOS SD Image for Kioskbeerli")))

(defun aarch64-procedure-record-provenance-topic ()
  (make-topic
   :id "aarch64-procedure-record-provenance"
   :title "Procedure step 2: record provenance"
   :summary "Download or build the artifact and capture provenance metadata (URL/build/commit/date)."
   :references '("Prepare the AArch64 image"
                 "Hydra latest SD-image job"
                 "Hydra build 323111513")))

(defun aarch64-procedure-decompress-topic ()
  (make-topic
   :id "aarch64-procedure-decompress"
   :title "Procedure step 3: decompress image"
   :summary "Decompress the .img.zst artifact into a flashable .img using zstd/unzstd; .img.zst and .img may coexist afterward."
   :references '("Prepare the AArch64 image"
                 "zstd"
                 "unzstd -d")))

(defun aarch64-procedure-verify-integrity-topic ()
  (make-topic
   :id "aarch64-procedure-verify-integrity"
   :title "Procedure step 4: verify integrity"
   :summary "Verify the downloaded artifact by matching the local SHA-256 to Hydra's published build product 1 SHA-256 before decompression and flashing."
   :references '("Prepare the AArch64 image"
                 "Hydra artifact SHA-256"
                 "Verify Hydra artifact checksum")))

(defun aarch64-procedure-confirm-architecture-topic ()
  (make-topic
   :id "aarch64-procedure-confirm-architecture"
   :title "Procedure step 5: confirm architecture"
   :summary "Confirm artifact naming and target architecture include aarch64-linux."
   :references '("Prepare the AArch64 image")))

;; Journal integrity findings as inspectable topics.
(defun chronology-violation-topic ()
  (make-topic
   :id "chronology-violation"
   :title "Chronology violation"
   :summary "Journal action dates go backward, so action order is no longer monotonic."
   :references '("Journalmatic Journal Checker"
                 "Journalmatic Repair Tools"
                 "journalmatic-rectify-chronology-example")))

(defun replay-precondition-violation-topic ()
  (make-topic
   :id "replay-precondition-violation"
   :title "Replay precondition violation"
   :summary "Journal replay preconditions fail (e.g. add/edit/remove references unseen ids), so revision reconstruction can fail."
   :references '("Journalmatic Journal Checker"
                 "Journalmatic Revision Replay"
                 "journalmatic-checker-example")))

(defun journal-checker-commit-gate-topic ()
  (make-topic
   :id "journal-checker-commit-gate"
   :title "Journal checker commit gate"
   :summary "Semantic gate for localhost FedWiki page commits; pages are blocked on CREATION/CHRONOLOGY/REVISION/MALFORMED findings, so syntax-only json.tool is not sufficient."
   :references '("Journalmatic Journal Checker"
                 "Journal Gate Script and Lisp Implementation"
                 "HyperBook Journal Tools"
                 "Python json.tool Source and Usage")))

(defun journal-gate-script-lisp-topic ()
  (make-topic
   :id "journal-gate-script-lisp"
   :title "Journal gate script and Lisp implementation"
   :summary "Repo-owned journal gate script and Lisp helpers print per-page findings, expose inspectable pass/fail results, and exit nonzero on blocking journal errors."
   :references '("Journalmatic Journal Checker"
                 "Journal Gate Script and Lisp Implementation"
                 "HyperBook Journal Tools"
                 "journalmatic-commit-gate-script-example")))

(defun journal-date-origin-and-fork-chronology-topic ()
  (make-topic
   :id "journal-date-origin-and-fork-chronology"
   :title "Journal date origin and fork chronology"
   :summary "Journal action dates should come from runtime epoch millis with max(now, last-date + 1); hardcoded timestamps can trigger fork-related chronology or revision failures."
   :references '("Journal Gate Script and Lisp Implementation"
                 "Journalmatic Journal Checker"
                 "journalmatic-date-origin-example")))

(defun journal-monotonic-normalization-topic ()
  (make-topic
   :id "journal-monotonic-normalization"
   :title "Journal monotonic normalization"
   :summary "Normalize journal action dates in existing action order as a replayability repair step, but still run the commit gate afterward rather than treating normalization as a bypass."
   :references '("Journal Gate Script and Lisp Implementation"
                 "Journalmatic Repair Tools"
                 "journalmatic-monotonic-normalization-example")))

(defun fedwiki-page-generation-workflow-topic ()
  (make-topic
   :id "fedwiki-page-generation-workflow"
   :title "FedWiki page-generation workflow"
   :summary "Reproducible Lisp page generation uses deterministic story/journal construction plus wiki-client-style date assignment (max(now, last+1))."
   :references '("FedWiki Page-Generation Workflow"
                 "Journal Gate Script and Lisp Implementation"
                 "journalmatic-page-generation-workflow-example"
                 "journalmatic-page-generation-wiki-client-style-example"
                 "https://github.com/fedwiki/wiki-client/commit/d4420c72a49305ca52d18ce8203bc95bdd3f59d2")))

(defun fedwiki-domain-expiry-topic ()
  (make-topic
   :id "fedwiki-domain-expiry-and-dns-cache-decay"
   :title "FedWiki Domain Expiry and DNS Cache Decay"
   :summary "Case-study topic for the March 2026 fed.wiki domain-expiry incident, emphasizing staggered client failure, cache decay, and cautious interpretation of residual traffic."
   :references '("FedWiki Domain Expiry and DNS Cache Decay"
                 "DNS Cache Decay in Browser-Centric Systems"
                 "Emergency Host Overrides for Federated Sites"
                 "Opening external FedWiki sites")))

(defun dns-cache-decay-topic ()
  (make-topic
   :id "dns-cache-decay-in-browser-centric-systems"
   :title "DNS Cache Decay in Browser-Centric Systems"
   :summary "Resolution state can decay unevenly across browser, OS, resolver, and connection layers, producing staggered browser-centric outages instead of a single failure cliff."
   :references '("DNS Cache Decay in Browser-Centric Systems"
                 "FedWiki Domain Expiry and DNS Cache Decay"
                 "Emergency Host Overrides for Federated Sites")))

(defun dns-propagation-lag-topic ()
  (make-topic
   :id "dns-propagation-lag-across-resolver-layers"
   :title "DNS Propagation Lag Across Resolver Layers"
   :summary "Registrar state, authoritative DNS, recursive resolvers, OS caches, browser caches, and live connections can shed stale reachability on different timelines during one DNS incident; the emphasis here is cache divergence more than classic fresh-record propagation."
   :references '("DNS Cache Decay in Browser-Centric Systems"
                 "FedWiki Domain Expiry and DNS Cache Decay")))

(defun emergency-host-overrides-topic ()
  (make-topic
   :id "emergency-host-overrides-for-federated-sites"
   :title "Emergency Host Overrides for Federated Sites"
   :summary "Temporary /etc/hosts mappings can preserve access to a small trusted set of federated sites when DNS is unstable, but they are a bounded continuity tactic rather than a general fix."
   :references '("Emergency Host Overrides for Federated Sites"
                 "FedWiki Domain Expiry and DNS Cache Decay"
                 "DNS Cache Decay in Browser-Centric Systems")))

(defun residual-traffic-interpretation-topic ()
  (make-topic
   :id "residual-traffic-interpretation-after-dns-failure"
   :title "Residual Traffic Interpretation After DNS Failure"
   :summary "Nonzero or regular traffic after a DNS failure can still be explained by bots, monitors, retry loops, or cached IP use, so it is weak evidence for takeover by itself."
   :references '("FedWiki Domain Expiry and DNS Cache Decay"
                 "DNS Cache Decay in Browser-Centric Systems")))

(defun clickable-commit-ids-in-fedwiki-stories-topic ()
  (make-topic
   :id "clickable-commit-ids-in-fedwiki-stories"
   :title "Clickable commit IDs in FedWiki stories"
   :summary "FedWiki story rendering can turn full Git commit hashes into ordinary external links to archived Software Heritage revision pages without changing page authoring."
   :references '("Clickable commit IDs in FedWiki stories"
                 "Software Heritage revision links from Git commit hashes"
                 "Translate a full Git commit hash in story text into a Software Heritage revision link"
                 "Verify Software Heritage revision link extraction from story text"
                 "Why a Git commit hash in story text did not become a Software Heritage link"
                 "Everything in Git? Identity Across Systems"
                 "Opening external FedWiki sites")))

(defun software-heritage-revision-link-topic ()
  (make-topic
   :id "software-heritage-revision-link"
   :title "Software Heritage revision link"
   :summary "A Software Heritage revision link uses an SWHID of the form swh:1:rev:<hash> to point at an archived commit-level object."
   :references '("Clickable commit IDs in FedWiki stories"
                 "Software Heritage revision links from Git commit hashes"
                 "Translate a full Git commit hash in story text into a Software Heritage revision link"
                 "Verify Software Heritage revision link extraction from story text"
                 "Why a Git commit hash in story text did not become a Software Heritage link"
                 "https://docs.softwareheritage.org/devel/swh-model/persistent-identifiers.html")))

(defun document-capability-as-dita-like-clickthrough-cluster-topic ()
  (make-topic
   :id "document-capability-as-dita-like-clickthrough-cluster"
   :title "Document capability as DITA-like click-through cluster"
   :summary "Document one concrete capability as a tightly linked concept, task, verification, and troubleshooting neighborhood so readers can learn it step by step."
   :references '("Document capability as DITA-like click-through cluster"
                 "Clickable commit IDs in FedWiki stories"
                 "Software Heritage revision links from Git commit hashes"
                 "Translate a full Git commit hash in story text into a Software Heritage revision link"
                 "Verify Software Heritage revision link extraction from story text"
                 "Why a Git commit hash in story text did not become a Software Heritage link")))

(defun git-blame-operation-topic ()
  (make-topic
   :id "git-blame-operation"
   :title "Git blame operation"
   :summary "Use git blame on exact file lines to prove which commit introduced timestamp behavior in wiki-client."
   :references '("FedWiki Page-Generation Workflow"
                 "wiki-client-blame-operation-example"
                 "https://github.com/fedwiki/wiki-client/commit/d4420c72a49305ca52d18ce8203bc95bdd3f59d2")))

(defun fedwiki-story-item-id-policy-topic ()
  (make-topic
   :id "fedwiki-story-item-id-policy"
   :title "FedWiki story item id policy"
   :summary "Use stable, opaque story item ids (canonical 16-hex form) in journaled pages; semantic labels belong in text, slugs, and topic ids."
   :references '("FedWiki Story Item IDs"
                 "Journalmatic Journal Checker"
                 "Python json.tool Source and Usage")))

(defun optional-semantic-adaptation-for-fedwiki-story-items-topic ()
  (make-topic
   :id "optional-semantic-adaptation-for-fedwiki-story-items"
   :title "Optional semantic adaptation for FedWiki story items"
   :summary "Keep FedWiki story-item import source-faithful, then let selected render methods opt into a second-stage semantic adaptation that yields either an adapted semantic object or an inspectable adaptation failure before preferred rendering and safe fallback."
   :references '("Optional semantic adaptation for FedWiki story items"
                 "FedWiki Video Snippet Plugin for HyperDoc"
                 "Implementing a FedWiki Video Snippet Adapter"
                 "FedWiki Graphviz story item render trace"
                 "The iFrame Is Not the Compute Sandbox")))

(defun fedwiki-id-runtime-contract-topic ()
  (make-topic
   :id "fedwiki-id-runtime-contract"
   :title "FedWiki id runtime contract"
   :summary "Wiki client and server treat item ids as replay keys for add/edit/remove/move journal actions; id stability is a runtime contract."
   :references '("FedWiki Story Item IDs"
                 "Journalmatic Revision Replay"
                 "Journalmatic Journal Checker")))

(defun semantic-item-id-effects-topic ()
  (make-topic
   :id "semantic-item-id-effects"
   :title "Semantic item id effects"
   :summary "Semantic item ids can improve readability but increase coupling to wording and can raise replay breakage risk during refactors."
   :references '("FedWiki Story Item IDs"
                 "Journalmatic Repair Tools"
                 "Journalmatic Journal Checker")))

(defun fedwiki-id-normalization-map-topic ()
  (make-topic
   :id "fedwiki-id-normalization-map"
   :title "FedWiki id normalization map"
   :summary "Old-to-new story/journal id mapping artifacts preserve lookup after bulk semantic-to-opaque id normalization."
   :references '("FedWiki Story Item IDs"
                 "fedwiki-story-id-normalization-map-2026-03-06"
                 "Journalmatic Journal Checker")))

(defun fedwiki-site-to-dmx-import-topic ()
  (make-topic
   :id "fedwiki-site-to-dmx-import"
   :title "FedWiki site to DMX import"
   :summary "Runtime importer that enumerates local FedWiki pages and upserts them into DMX through an emerging plugin write model keyed by stable domain-plus-slug identities."
   :references '("FedWiki Site to DMX Import"
                 "FedWiki JSON-init HTTP fallback"
                 "DMX FedWiki Write Model"
                 "DMX plugin extension boundary"
                 "Topics HyperBook in HyperDoc"
                 "Concepts, DMX Topics, and Topic Maps")))

(defun fedwiki-json-init-http-fallback-topic ()
  (make-topic
   :id "fedwiki-json-init-http-fallback"
   :title "FedWiki JSON-init HTTP fallback"
   :summary "Shared FedWiki recovery seam that retries sitemap/plugin JSON discovery over HTTP once when the original JSON endpoint yields HTML or another init-format failure."
   :references '("FedWiki JSON-init HTTP fallback"
                 "Opening external FedWiki sites"
                 "FedWiki Site to DMX Import")))

(defun dmx-plugin-extension-boundary-topic ()
  (make-topic
   :id "dmx-plugin-extension-boundary"
   :title "DMX plugin extension boundary"
   :summary "An early-stage plugin can extend DMX with new capabilities before those capabilities are stabilized as platform contract."
   :references '("DMX FedWiki Write Model"
                 "FedWiki Site to DMX Import"
                 "Concepts, DMX Topics, and Topic Maps")))

(defun py4dmx-topic ()
  (make-topic
   :id "py4dmx"
   :title "Py4dmx"
   :summary "External Python CLI/source cluster for scripting DMX REST operations such as session bootstrap, workspace and topicmap lookup, topic and assoc creation, topicmap reveal, plugin GET/POST, vCard import, and generic delete helpers, useful as comparison evidence for HyperDoc's narrower DMX boundary."
   :references '("Py4dmx"
                 "DMX machine-readable read paths"
                 "DMX session bootstrap and JSESSIONID"
                 "Using guarded workspace topic lifecycle tools"
                 "HyperDoc DMX architectural implications"
                 "https://forum.dmx.berlin/t/py4dmx-a-python-project-to-play-with-dmxs-rest-api/45"
                 "https://github.com/junes/py4dmx")))

(defun dmx-twins-topic ()
  (make-topic
   :id "dmx-twins"
   :title "DMX twins"
   :summary "Correspondence model for DMX-side artifacts that mirror HyperDoc page/topic intent, including first-class route/association subjects with explicit roles when needed, without implying literal structural identity or live synchronization."
   :references '("DMX twins"
                 "Documentation Surfaces in HyperDoc"
                 "Page/topic/twin correspondence"
                 "Concepts, DMX Topics, and Topic Maps"
                 "DMX FedWiki Write Model"
                 "Definitive Common Lisp Books")))

(defun runtime-write-live-proof-gate-topic ()
  (make-topic
   :id "runtime-write-live-proof-gate"
   :title "Runtime write live-proof gate"
   :summary "Operational rule that a runtime write path is not live-proven until a real create-then-update replay succeeds on a configured target."
   :references '("FedWiki Site to DMX Import"
                 "DMX FedWiki Write Model"
                 "Authoring Documentation in HyperDoc"
                 "Documentation validation and commit gates")))

(defun dmx-workspace-sharing-mode-topic ()
  (make-topic
   :id "dmx-workspace-sharing-mode"
   :title "DMX workspace sharing modes for AI context windows"
   :summary "For AI-facing DMX use, Public is the conservative world-readable choice and Common is the deliberate world read/write choice."
   :references '("Use a DMX Common workspace as a world read/write context window"
                 "Codex read/write boundary for a DMX topicmap"
                 "Why a DMX webclient URL alone is not a durable Codex interface"
                 "https://dmx.readthedocs.io/en/latest/user.html#workspace-sharing-modes")))

(defun dmx-context-window-topic ()
  (make-topic
   :id "dmx-context-window"
   :title "Use a DMX Common workspace as a world read/write context window"
   :summary "Choose a DMX Common workspace as a context window only when the material is intentionally open for world read/write use."
   :references '("DMX workspace sharing modes for AI context windows"
                 "Common workspace"
                 "Codex read/write boundary for a DMX topicmap"
                 "Why a DMX webclient URL alone is not a durable Codex interface"
                 "https://dmx.ralfbarkow.ch/systems.dmx.webclient/#/topicmap/919822")))

(defun common-workspace-topic ()
  (make-topic
   :id "common-workspace"
   :title "Common workspace"
   :summary "A DMX Common workspace is the deliberate choice when anonymous or world write access is intentionally part of the operating model."
   :references '("Use a DMX Common workspace as a world read/write context window"
                 "DMX workspace sharing modes for AI context windows"
                 "https://dmx.readthedocs.io/en/latest/user.html#workspace-sharing-modes"
                 "https://dmx.readthedocs.io/en/latest/admin.html#request-filters")))

(defun codex-dmx-access-boundary-topic ()
  (make-topic
   :id "codex-dmx-access-boundary"
   :title "Codex read/write boundary for a DMX topicmap"
   :summary "A DMX topicmap link is an operational target reference, not proof that Codex already has live read/write access."
   :references '("Why a DMX webclient URL alone is not a durable Codex interface"
                 "Use a DMX Common workspace as a world read/write context window"
                 "DMX workspace sharing modes for AI context windows"
                 "https://dmx.ralfbarkow.ch/systems.dmx.webclient/#/topicmap/919822")))

(defun dmx-webclient-url-alone-is-not-a-durable-codex-interface-topic ()
  (make-topic
   :id "dmx-webclient-url-alone-is-not-a-durable-codex-interface"
   :title "Why a DMX webclient URL alone is not a durable Codex interface"
   :summary "A DMX webclient hash URL opens a browser-facing SPA state, not a durable agent interface or stable machine-writable contract."
   :references '("Codex read/write boundary for a DMX topicmap"
                 "Use a DMX Common workspace as a world read/write context window"
                 "DMX workspace sharing modes for AI context windows"
                 "https://dmx.ralfbarkow.ch/systems.dmx.webclient/#/topicmap/919822")))

(defun definitive-common-lisp-books-topic ()
  (make-topic
   :id "definitive-common-lisp-books"
   :title "Definitive Common Lisp Books"
   :summary "Curated reading map for Common Lisp books, separating first books, advanced technique, object-system references, and historical references."
   :references '("Definitive Common Lisp Books")))

(defun definitive-common-lisp-books-arrangement-topic ()
  (make-topic
   :id "definitive-common-lisp-books-arrangement"
   :title "Definitive Common Lisp Books arrangement"
   :summary "Authored arrangement view for the Definitive Common Lisp Books cluster, capturing nearby HyperDoc topics and supporting external anchors without asserting semantic associations."
   :references '("Definitive Common Lisp Books arrangement"
                 "Definitive Common Lisp Books"
                 "Topic factory"
                 "Authored topic factories"
                 "Topic arrangement in HyperDoc")))

(defun winston-and-horn-lisp-1989-topic ()
  (make-topic
   :id "winston-and-horn-lisp-1989"
   :title "Winston and Horn Lisp (1989)"
   :summary "Book-level topic for Patrick Henry Winston and Berthold Klaus Paul Horn's Lisp, 3rd Edition as an older Common Lisp background source spanning core Lisp practice, later-language features, and AI-oriented examples with early CLOS-era framing."
   :references '("Winston and Horn Lisp (1989)"
                 "Winston and Horn Lisp topic arrangement"
                 "Definitive Common Lisp Books")))

(defun winston-and-horn-lisp-topic-arrangement-topic ()
  (make-topic
   :id "winston-and-horn-lisp-topic-arrangement"
   :title "Winston and Horn Lisp topic arrangement"
   :summary "Authored arrangement view preserving the book's chapter and subtopic neighborhood without turning table-of-contents adjacency into stronger semantic claims."
   :references '("Winston and Horn Lisp topic arrangement"
                 "Winston and Horn Lisp (1989)"
                 "Definitive Common Lisp Books"
                 "Topic arrangement in HyperDoc"
                 "Topics HyperBook in HyperDoc")))

(defun teaching-sequence-topic ()
  (make-topic
   :id "teaching-sequence"
   :title "Teaching sequence"
   :summary "An ordered instructional unit that organizes overview, content, reinforcement, and assessment around a single learning objective."
   :references '("Winston and Horn Lisp (1989)"
                 "Winston and Horn Lisp topic arrangement")))

(defun teaching-arc-topic ()
  (make-topic
   :id "teaching-arc"
   :title "Teaching arc"
   :summary "A higher-level pedagogical grouping that orders and relates teaching sequences into a larger progression such as a lesson, module, or course."
   :references '("Winston and Horn Lisp (1989)"
                 "Winston and Horn Lisp topic arrangement")))
