;;;; HyperDoc authored topic family
;;;; Generated by splitting the former hyperdoc/topics.lisp monolith.

(in-package :hyperdoc)

;;; dm6 AppEmbed / HyperDoc inline proof milestone topics

(defun dm6-appembed-evidence-events-commit-topic ()
  (make-topic
   :id "git-commit-73c51b7-dm6-appembed-evidence-events"
   :title "73c51b7 Add HyperDoc evidence events to AppEmbed"
   :summary "The dm6-elm commit that exposes AppEmbed evidence events for HyperDoc, including import, store snapshot, selection, drag, and cross-boundary evidence."
   :references '("DM6 AppEmbed HyperDoc inline proof milestone"
                 "DM6 AppEmbed HyperDoc Inline Proof"
                 "Git History Surface for HyperDoc"
                 "Association Topics for Stable Identity and Mutable Titles")))

(defun hyperdoc-dm6-inline-proof-commit-topic ()
  (make-topic
   :id "git-commit-54d1237-dm6-appembed-inline-proof"
   :title "54d1237 Add dm6 AppEmbed HyperDoc inline proof"
   :summary "The HyperDoc commit that adds the inline dm6 AppEmbed proof page, deployed AppEmbed bundle, and browser-side adapter for structured evidence capture."
   :references '("DM6 AppEmbed HyperDoc inline proof milestone"
                 "DM6 AppEmbed HyperDoc Inline Proof"
                 "Git History Surface for HyperDoc"
                 "Association Topics for Stable Identity and Mutable Titles")))

(defun dm6-appembed-hyperdoc-inline-proof-milestone-topic ()
  (make-topic
   :id "dm6-appembed-hyperdoc-inline-proof-milestone"
   :title "DM6 AppEmbed HyperDoc inline proof milestone"
   :summary "Association topic linking the dm6-elm evidence-port AppEmbed commit with the HyperDoc inline proof commit as one cross-repository milestone: visible embedded dm6 rendering plus structured evidence capture."
   :references '("73c51b7 Add HyperDoc evidence events to AppEmbed"
                 "54d1237 Add dm6 AppEmbed HyperDoc inline proof"
                 "DM6 AppEmbed HyperDoc Inline Proof"
                 "Git History Surface for HyperDoc"
                 "Association Topics for Stable Identity and Mutable Titles")))

(defun elm-pages-effects-as-data-topic ()
  (make-topic
   :id "elm-pages-effects-as-data"
   :title "elm-pages Effects as Data"
   :summary "The elm-pages testing/debugging pattern where framework effects are represented as values that tests and visual debuggers can inspect, replace, and replay."
   :references '("DM6 AppEmbed HyperDoc Inline Proof"
                 "DM6 AppEmbed HyperDoc inline proof milestone"
                 "Debugging Reinvented in HyperDoc")))

(defun dm6-embedded-evidence-timeline-topic ()
  (make-topic
   :id "dm6-embedded-evidence-timeline"
   :title "DM6 embedded evidence timeline"
   :summary "The ordered HyperDoc-visible record of AppEmbed boot, imported data, store snapshots, selections, drags, crosses, and other dm6-elm model transitions."
   :references '("73c51b7 Add HyperDoc evidence events to AppEmbed"
                 "DM6 AppEmbed HyperDoc Inline Proof"
                 "Git History Surface for HyperDoc")))

(defun dm6-page-local-topicmap-seed-topic ()
  (make-topic
   :id "dm6-page-local-topicmap-seed"
   :title "DM6 page-local topicmap seed"
   :summary "A generated native AppEmbed model embedded in a HyperDoc DM6 island, derived deterministically from the page's own Plump parse tree while excluding the generated seed script itself."
   :references '("DM6 AppEmbed HyperDoc Inline Proof"
                 "DM6 AppEmbed contract boundary"
                 "DM6 embedded evidence timeline")))

(defun dm6-appembed-contract-boundary-topic ()
  (make-topic
   :id "dm6-appembed-contract-boundary"
   :title "DM6 AppEmbed contract boundary"
   :summary "The stable embedding boundary where external hosts boot dm6-elm through Elm.AppEmbed with string flags slug and stored, without depending on internal app modules."
   :references '("DM6 AppEmbed HyperDoc Inline Proof"
                 "Contract boundary"
                 "Documentation Surfaces in HyperDoc")))

(defun dm6-elm-and-elm-pages-debugger-comparison-topic ()
  (make-topic
   :id "dm6-elm-and-elm-pages-debugger-comparison"
   :title "dm6-elm and elm-pages debugger comparison"
   :summary "A comparison that maps elm-pages BackendTasks, fetchers, cookies, redirects, and ErrorPages to dm6-elm's embedded values: FedWiki page JSON, AppEmbed flags, decoded model state, ports, input events, selections, drags, crosses, and store snapshots."
   :references '("elm-pages Effects as Data"
                 "DM6 embedded evidence timeline"
                 "DM6 AppEmbed contract boundary")))
