;;;; HyperDoc authored topic family
;;;; Generated by splitting the former hyperdoc/topics.lisp monolith.

(in-package :hyperdoc)

;;; dm6 AppEmbed / HyperDoc inline proof milestone topics

(defun dm6-appembed-evidence-events-commit-topic ()
  (make-topic
   :id "git-commit-73c51b7-dm6-appembed-evidence-events"
   :title "73c51b7 Add HyperDoc evidence events to AppEmbed"
   :summary "The dm6-elm commit that exposes AppEmbed evidence events for HyperDoc, including import, store snapshot, selection, drag, and cross-boundary evidence."
   :references '("DM6 AppEmbed HyperDoc inline proof milestone"
                 "DM6 AppEmbed HyperDoc Inline Proof"
                 "Git History Surface for HyperDoc"
                 "Association Topics for Stable Identity and Mutable Titles")))

(defun hyperdoc-dm6-inline-proof-commit-topic ()
  (make-topic
   :id "git-commit-54d1237-dm6-appembed-inline-proof"
   :title "54d1237 Add dm6 AppEmbed HyperDoc inline proof"
   :summary "The HyperDoc commit that adds the inline dm6 AppEmbed proof page, deployed AppEmbed bundle, and browser-side adapter for structured evidence capture."
   :references '("DM6 AppEmbed HyperDoc inline proof milestone"
                 "DM6 AppEmbed HyperDoc Inline Proof"
                 "Git History Surface for HyperDoc"
                 "Association Topics for Stable Identity and Mutable Titles")))

(defun dm6-appembed-hyperdoc-inline-proof-milestone-topic ()
  (make-topic
   :id "dm6-appembed-hyperdoc-inline-proof-milestone"
   :title "DM6 AppEmbed HyperDoc inline proof milestone"
   :summary "Association topic linking the dm6-elm evidence-port AppEmbed commit with the HyperDoc inline proof commit as one cross-repository milestone: visible embedded dm6 rendering plus structured evidence capture."
   :references '("73c51b7 Add HyperDoc evidence events to AppEmbed"
                 "54d1237 Add dm6 AppEmbed HyperDoc inline proof"
                 "DM6 AppEmbed HyperDoc Inline Proof"
                 "Git History Surface for HyperDoc"
                 "Association Topics for Stable Identity and Mutable Titles")))
