;;;; HyperDoc authored topic family
;;;; Generated by splitting the former hyperdoc/topics.lisp monolith.

(in-package :hyperdoc)

;; Topic objects for the Drew McDermott Mind and Mechanism compatibility slice.
(defun computationalism-topic ()
  (make-topic
   :id "computationalism"
   :title "Computationalism"
   :summary "View that minds can be explained in terms of computation, with the relevant mechanisms realized in concrete information-processing systems."
   :references '("Computationalism in Mind and Mechanism"
                 "Mind and Mechanism compatibility with HyperDoc"
                 "Drew McDermott Lisp, Planning, and Software")))

(defun symbols-and-semantics-topic ()
  (make-topic
   :id "symbols-and-semantics"
   :title "Symbols and semantics"
   :summary "Question of how symbol structures in computational systems acquire meanings that matter to explanation and behavior."
   :references '("Symbols and semantics in Mind and Mechanism"
                 "Mind and Mechanism compatibility with HyperDoc"
                 "PDDL and Opt in Drew McDermott's work")))

(defun informational-meaning-topic ()
  (make-topic
   :id "informational-meaning"
   :title "Informational meaning"
   :summary "Meaning relation in which an event provides evidence about a situation because its occurrence changes the probability of that situation."
   :references '("Symbols and semantics in Mind and Mechanism"
                 "Mind and Mechanism compatibility with HyperDoc")))

(defun intentionality-topic ()
  (make-topic
   :id "intentionality"
   :title "Intentionality"
   :summary "Capacity of mental or symbolic states to be about something, approached here through their causal roles and environmental relations."
   :references '("Symbols and semantics in Mind and Mechanism"
                 "Mind and Mechanism compatibility with HyperDoc"
                 "PDDL and Opt in Drew McDermott's work")))

;; Topic objects for the McDermott-Davis route-planning source slice.
(defun planning-routes-through-uncertain-territory-topic ()
  (make-topic
   :id "planning-routes-through-uncertain-territory"
   :title "Planning routes through uncertain territory"
   :summary "McDermott and Davis's route-planning source model for navigating partly known space with topological facts, metric fuzzy maps, spatial retrieval, and staged obstacle handling."
   :references '("Planning Routes through Uncertain Territory"
                 "Drew McDermott Lisp, Planning, and Software"
                 "Drew McDermott topic arrangement")))

(defun topological-and-metric-spatial-reasoning-topic ()
  (make-topic
   :id "topological-and-metric-spatial-reasoning"
   :title "Topological and metric spatial reasoning"
   :summary "Spatial representation split in which qualitative inclusion, overlap, and barrier facts remain distinct from metric position, orientation, scale, and distance constraints."
   :references '("Planning Routes through Uncertain Territory"
                 "Focused semantic source stations"
                 "Canonical Route Discovery for Runtime Smoke Tests")))

(defun fuzzy-map-topic ()
  (make-topic
   :id "fuzzy-map"
   :title "Fuzzy map"
   :summary "Metric spatial representation that stores relative positions, orientations, and scales in multiple frames of reference using interval-valued fuzzy coordinates and fuzzboxes."
   :references '("Planning Routes through Uncertain Territory"
                 "Topological and metric spatial reasoning")))

(defun frob-tree-topic ()
  (make-topic
   :id "frob-tree"
   :title "Frob tree"
   :summary "Tree of hybrid frame/object nodes used by McDermott and Davis to organize fuzzy map frames and the memorized fuzzy quantities between adjacent frobs."
   :references '("Planning Routes through Uncertain Territory"
                 "Fuzzy map")))

(defun spatial-fact-assimilation-topic ()
  (make-topic
   :id "spatial-fact-assimilation"
   :title "Spatial fact assimilation"
   :summary "Process of incorporating new spatial facts by constraining fuzzy coordinate ranges when possible and remapping or growing the frob tree when needed."
   :references '("Planning Routes through Uncertain Territory"
                 "Fuzzy map"
                 "Frob tree"
                 "Source-station assimilation routine")))

(defun spatial-discrimination-tree-topic ()
  (make-topic
   :id "spatial-discrimination-tree"
   :title "Spatial discrimination tree"
   :summary "Inverted spatial retrieval index used by FIND to retrieve objects from location and other attributes instead of only computing properties of named objects."
   :references '("Planning Routes through Uncertain Territory"
                 "Fuzzy map"
                 "Topological and metric spatial reasoning")))

(defun route-planning-under-uncertainty-topic ()
  (make-topic
   :id "route-planning-under-uncertainty"
   :title "Route planning under uncertainty"
   :summary "Route generation strategy that first estimates direction and topological path, then refines the plan by handling obstacles, conduits, and local details."
   :references '("Planning Routes through Uncertain Territory"
                 "Barrier/conduit route planning"
                 "SPAM spatial module"
                 "Canonical Route Discovery for Runtime Smoke Tests")))

(defun barrier-conduit-route-planning-topic ()
  (make-topic
   :id "barrier-conduit-route-planning"
   :title "Barrier/conduit route planning"
   :summary "Obstacle-handling vocabulary for route planning that distinguishes barriers, conduits, semiconduits, traversal barriers, and penetration barriers for a given traveler."
   :references '("Planning Routes through Uncertain Territory"
                 "Route planning under uncertainty")))

(defun spam-spatial-module-topic ()
  (make-topic
   :id "spam-spatial-module"
   :title "SPAM spatial module"
   :summary "McDermott and Davis's implemented spatial module integrating TOPO, MEASURE, FIND, fuzzy map assimilation, and route planning over uncertain territory."
   :references '("Planning Routes through Uncertain Territory"
                 "Spatial discrimination tree"
                 "Spatial fact assimilation"
                 "Route planning under uncertainty")))

;; Topic objects for iconic retrieval and route-language assimilation.
(defun iconic-state-topic ()
  (make-topic
   :id "iconic-state"
   :title "Iconic state"
   :summary "Potentially grounded semantic station or inspectable world-state proxy that a HyperDoc route can retrieve or re-enter, rather than a bare symbolic label."
   :references '("Iconic route language in HyperDoc"
                 "Inspectable iconic retrieval objects"
                 "Focused semantic source stations")))

(defun iconic-hypothesis-topic ()
  (make-topic
   :id "iconic-hypothesis"
   :title "Iconic hypothesis"
   :summary "Working claim that language supports understanding by retrieving grounded or iconic state instead of merely attaching arbitrary labels to symbols."
   :references '("Iconic route language in HyperDoc"
                 "Inspectable iconic retrieval objects"
                 "Symbols and semantics in Mind and Mechanism")))

(defun understanding-as-retrieval-topic ()
  (make-topic
   :id "understanding-as-retrieval"
   :title "Understanding as retrieval"
   :summary "HyperDoc reading in which understanding succeeds when a cue or route re-enters the grounded state, evidence chain, trajectory, or interpretation path that makes the meaning inspectable."
   :references '("Iconic route language in HyperDoc"
                 "Inspectable iconic retrieval objects"
                 "Focused semantic source stations"
                 "Symbols and semantics in Mind and Mechanism")))

(defun language-as-retrieval-vehicle-topic ()
  (make-topic
   :id "language-as-retrieval-vehicle"
   :title "Language as retrieval vehicle"
   :summary "View that language cues can serve as durable route starters into richer grounded semantic state, not only as names or labels."
   :references '("Iconic route language in HyperDoc"
                 "Inspectable iconic retrieval objects"
                 "Symbols and semantics in Mind and Mechanism")))

(defun neural-state-machine-model-topic ()
  (make-topic
   :id "neural-state-machine-model"
   :title "Neural State Machine Model"
   :summary "Paper-specific model in which semantic distinctions appear as state trajectories through grounded or iconic representation rather than as static token labels."
   :references '("Iconic route language in HyperDoc"
                 "Inspectable iconic retrieval objects"
                 "Symbols and semantics in Mind and Mechanism")))

(defun iconic-route-language-in-hyperdoc-topic ()
  (make-topic
   :id "iconic-route-language-in-hyperdoc"
   :title "Iconic route language in HyperDoc"
   :summary "Assimilation of the iconic hypothesis into Touch-Fahrplan: stations can stand for grounded semantic states, routes can act as retrieval relations, and following a route can re-enter an inspectable state or trajectory."
   :references '("Iconic route language in HyperDoc"
                 "Inspectable iconic retrieval objects"
                 "Skillization in HyperDoc"
                 "Focused semantic source stations"
                 "Symbols and semantics in Mind and Mechanism")))

(defun world-state-topic ()
  (make-topic
   :id "world-state"
   :title "World state"
   :summary "Static or temporal arrangement in the world that a learning state machine mirrors through grounded/iconic representation."
   :references '("Iconic route language in HyperDoc"
                 "Inspectable iconic retrieval objects")))

(defun world-state-proxy-topic ()
  (make-topic
   :id "world-state-proxy"
   :title "World-state proxy"
   :summary "Inspectable HyperDoc stand-in for a grounded semantic state or event pattern that can anchor iconic retrieval."
   :references '("Iconic route language in HyperDoc"
                 "Inspectable iconic retrieval objects"
                 "Symbols and semantics in Mind and Mechanism")))

(defun acquisition-of-iconic-representation-topic ()
  (make-topic
   :id "acquisition-of-iconic-representation"
   :title "Acquisition of iconic representation"
   :summary "Creation of state structure with a many-to-some relationship to world states and their temporal changes."
   :references '("Inspectable iconic retrieval objects"
                 "Iconic route language in HyperDoc")))

(defun linguistic-retrieval-cue-topic ()
  (make-topic
   :id "linguistic-retrieval-cue"
   :title "Linguistic retrieval cue"
   :summary "Symbolic trigger or route starter that retrieves an iconic representation without collapsing into the grounded state it points to."
   :references '("Iconic route language in HyperDoc"
                 "Inspectable iconic retrieval objects"
                 "Symbols and semantics in Mind and Mechanism")))

(defun iconic-retrieval-route-topic ()
  (make-topic
   :id "iconic-retrieval-route"
   :title "Iconic retrieval route"
   :summary "First-class route relation that links a cue to a grounded/iconic state and the trajectory by which it is retrieved."
   :references '("Iconic route language in HyperDoc"
                 "Inspectable iconic retrieval objects"
                 "Symbols and semantics in Mind and Mechanism")))

(defun iconic-state-trajectory-topic ()
  (make-topic
   :id "iconic-state-trajectory"
   :title "Iconic state trajectory"
   :summary "Inspectable path through iconic state structure that preserves semantic distinctions such as case-role readings."
   :references '("Inspectable iconic retrieval objects"
                 "Iconic route language in HyperDoc")))

(defun reentrant-state-topic ()
  (make-topic
   :id "reentrant-state"
   :title "Reentrant state"
   :summary "Iconic state that remains re-enterable from perceptual or symbolic cueing rather than vanishing after one pass through the sequence."
   :references '("Inspectable iconic retrieval objects"
                 "Iconic route language in HyperDoc")))

(defun early-processing-topic ()
  (make-topic
   :id "early-processing"
   :title "Early processing"
   :summary "Pre-fashioned processing stage that precedes iconic state formation and performs fixed sensory tasks such as edge extraction or auditory encoding."
   :references '("Inspectable iconic retrieval objects"
                 "Iconic route language in HyperDoc")))

(defun grounded-symbolic-operation-topic ()
  (make-topic
   :id "grounded-symbolic-operation"
   :title "Grounded symbolic operation"
   :summary "Integrated mode in which symbolic cues and grounded/iconic states remain distinct but operate together inside one system."
   :references '("Symbols and semantics in Mind and Mechanism"
                 "Inspectable iconic retrieval objects"
                 "Iconic route language in HyperDoc")))

;; Topic objects for the narrow Zotero title-to-local-PDF bridge slice.
(defun zotero-library-topic ()
  (make-topic
   :id "zotero-library"
   :title "Zotero library"
   :summary "Read-only bibliographic source that HyperDoc can query by exact title and then inspect through typed item, attachment, and path-resolution report objects."
   :references '("Zotero library bridge for HyperDoc"
                 "Resolve a local PDF from Zotero in HyperDoc"
                 "Zettelkasten note lookup for Zotero resolution")))

(defun zotero-recent-changes-query-topic ()
  (make-topic
   :id "zotero-recent-changes-query"
   :title "Zotero recent changes query"
   :summary "Read-only query object that orders local Zotero items by the real items.dateModified field, preserves SQLite attempt evidence, and carries typed recent-change hits."
   :references '("Recent changes in a local Zotero library")))

(defun zotero-recent-change-hit-topic ()
  (make-topic
   :id "zotero-recent-change-hit"
   :title "Zotero recent change hit"
   :summary "Typed hit object for one recent Zotero row, exposing item identity, chosen timestamp field and value, raw row data, and a stable evidence path back into the selected query attempt."
   :references '("Recent changes in a local Zotero library")))

(defun zotero-attachment-topic ()
  (make-topic
   :id "zotero-attachment"
   :title "Zotero attachment"
   :summary "Child Zotero item that carries attachment metadata such as parent item id, item key, link mode, content type, and stored or linked path data."
   :references '("Zotero attachment path resolution"
                 "Zotero library bridge for HyperDoc"
                 "Resolve a local PDF from Zotero in HyperDoc")))

(defun attachment-path-resolution-topic ()
  (make-topic
   :id "attachment-path-resolution"
   :title "Attachment path resolution"
   :summary "Explicit report that turns Zotero attachment metadata into a concrete local filesystem path or a typed failure mode without fabricating a path."
   :references '("Zotero attachment path resolution"
                 "Resolve a local PDF from Zotero in HyperDoc")))

(defun linked-file-attachment-topic ()
  (make-topic
   :id "linked-file-attachment"
   :title "Linked file attachment"
   :summary "Attachment whose path already points to an external local file location and must be normalized and existence-checked directly."
   :references '("Zotero attachment path resolution"
                 "Resolve a local PDF from Zotero in HyperDoc")))

(defun stored-attachment-topic ()
  (make-topic
   :id "stored-attachment"
   :title "Stored attachment"
   :summary "Attachment stored under the Zotero storage root and resolved by combining the configured storage directory, the attachment key, and the stored path metadata."
   :references '("Zotero attachment path resolution"
                 "Resolve a local PDF from Zotero in HyperDoc"
                 "Zotero library bridge for HyperDoc")))

;; Topic objects for bibliography subcollection import and authoring plans.
(defun bibliography-subcollection-topic ()
  (make-topic
   :id "bibliography-subcollection"
   :title "Bibliography subcollection"
   :summary "First-class collection object that preserves bibliography provenance such as source system, collection path, and imported entry set separately from editorial topic inference."
   :references '("Bibliography subcollections in HyperDoc"
                 "Coachmark bibliography authoring plan")))

(defun bibliography-entry-topic ()
  (make-topic
   :id "bibliography-entry"
   :title "Bibliography entry"
   :summary "Normalized inspectable bibliography record with stable provenance and parsed bibliographic fields such as title, authors, year, work type, venue, DOI, URL, notes, and raw source text."
   :references '("Bibliography subcollections in HyperDoc"
                 "Coachmark bibliography authoring plan")))

(defun candidate-topic-topic ()
  (make-topic
   :id "candidate-topic"
   :title "Candidate topic"
   :summary "Heuristic editorial topic candidate extracted from bibliography provenance and entry metadata, kept inspectable rather than treated as ground truth."
   :references '("Bibliography subcollections in HyperDoc"
                 "Coachmark bibliography authoring plan"
                 "How to merge proposed topic additions into hyperdoc/topics.lisp")))

(defun topic-comparison-report-topic ()
  (make-topic
   :id "topic-comparison-report"
   :title "Topic comparison report"
   :summary "Inspectable comparison object that checks a candidate topic against the current Topics HyperBook by exact title first, then alias, near-duplicate, and broader-topic review."
   :references '("Bibliography subcollections in HyperDoc"
                 "Coachmark bibliography authoring plan"
                 "Review of the first merge-proposed-topic-additions HTML")))

(defun authoring-decision-topic ()
  (make-topic
   :id "authoring-decision"
   :title "Authoring decision"
   :summary "Editorial decision object that records whether a candidate should merge into an existing topic, become a new topic/page scaffold, or remain only as arrangement or continuity-shell evidence."
   :references '("Bibliography subcollections in HyperDoc"
                 "Coachmark bibliography authoring plan"
                 "Authoring Documentation in HyperDoc")))

(defun hyperdoc-authoring-plan-topic ()
  (make-topic
   :id "hyperdoc-authoring-plan"
   :title "HyperDoc authoring plan"
   :summary "Inspectable plan that turns bibliography candidates and topic comparison reports into explicit topic/page actions plus a separate materialization preview."
   :references '("Bibliography subcollections in HyperDoc"
                 "Coachmark bibliography authoring plan"
                 "Authoring Documentation in HyperDoc")))

(defun topic-to-zotero-enrichment-route-topic ()
  (make-topic
   :id "topic-to-zotero-enrichment-route"
   :title "Topic-to-Zotero enrichment route"
   :summary
   "First-class route/association object that ties one HyperDoc topic station to a read-only Zotero source station before any live Zotero query runs."
   :references
   '("Zotero library bridge for HyperDoc"
     "Bibliography subcollections in HyperDoc"
     "Associations"
     "Normal association submit path vs evidence path")))

(defun inspectable-zotero-enrichment-plan-for-a-topic-topic ()
  (make-topic
   :id "inspectable-zotero-enrichment-plan-for-a-topic"
   :title "Inspectable Zotero enrichment plan for a topic"
   :summary "Inspectable query-plan object that makes the intended Zotero query text, match mode, backend seam, execution path, and repair hints visible before the live query boundary."
   :references '("Topic-to-Zotero enrichment route"
                 "Zotero library bridge for HyperDoc")))

(defun topic-enrichment-report-topic ()
  (make-topic
   :id "topic-enrichment-report"
   :title "Topic enrichment report"
   :summary "Inspectable report object that keeps Zotero query evidence, matched items, candidate signals, and editorial consequences separate on the enriched topic path."
   :references '("Inspectable Zotero enrichment plan for a topic"
                 "Bibliography subcollections in HyperDoc")))

(defun annotation-topic ()
  (make-topic
   :id "dock-annotation"
   :title "Annotation"
   :summary "Generic route target/topic-object that classifies annotation relations, so a selected source station such as Text pages can lay a route to Annotation and reopen the same inspectable relation later."
   :references '("Dock capabilities in HyperDoc"
                 "Dock presentation state model"
                 "A DOM-annotation connect gesture"
                 "Associations")))

(defun dock-capabilities-in-hyperdoc-topic ()
  (make-topic
   :id "dock-capabilities-in-hyperdoc"
   :title "Dock capabilities in HyperDoc"
   :summary "Pane-local Dock framing in which inspector tabs stay the durable inspection surface while Connect is introduced to users as Lay route, Annotation remains a sibling capability, and richer DMX traversal stays in the pane body."
   :references '("Dock capabilities in HyperDoc"
                 "Discoverability propagation in HyperDoc"
                 "Dock presentation state model"
                 "Annotation"
                 "A DOM-annotation connect gesture")))

(defun dock-presentation-state-model-topic ()
  (make-topic
   :id "dock-presentation-state-model"
   :title "Dock presentation state model"
   :summary "Inspectable state model for latent, introduction, active, degraded, and rediscovery Dock presentation, together with claim-code evidence for how Lay route / Connect, Annotation, mobile route-laying, and DMX traversal fit the same UX grammar."
   :references '("Dock presentation state model"
                 "Discoverability propagation in HyperDoc"
                 "Dock capabilities in HyperDoc"
                 "Annotation")))

(defun source-pane-layout-evidence-topic ()
  (make-topic
   :id "source-pane-layout-evidence"
   :title "Source pane layout evidence"
   :summary "Inspectable evidence cluster for the split html/markdown source contract: plain Source reading, explicit Connect source anchoring, pane-slot shell, shared line rendering, CSS, JS, and representative runtime state."
   :references '("Source pane layout evidence"
                 "Make Alternate Source the Default Source View"
                 "Workspace-native annotations in a DMX workspace"
                 "A DOM-annotation connect gesture"
                 "Dock capabilities in HyperDoc")))

(defun focused-semantic-source-stations-topic ()
  (make-topic
   :id "focused-semantic-source-stations"
   :title "Focused semantic source stations"
   :summary "Durable source-review surface that names semantically meaningful source stations as grounded retrieval targets, keeps route judgments inspectable, and leaves the broader HyperDoc-owned journal migration deferred."
   :references '("Focused semantic source stations"
                 "Iconic route language in HyperDoc"
                 "DMX MCP server for shared workspace"
                 "Context window workspace as shared blackboard"
                 "DMX workspace journal model"
                 "Authoritative Journal-Backed Page Store"
                 "Annotation"
                 "A DOM-annotation connect gesture")))
