;;;; HyperDoc authored topic family
;;;; Generated by splitting the former hyperdoc/topics.lisp monolith.

(in-package :hyperdoc)

(defvar *the-life-cycle-of-collective-knowledge-topic-asset*)
(defvar *reproducible-devenv-as-knowledge-artifact-topic-asset*)

(defun make-generated-page-topic-with-fallback
    (topic-id chunk-finder asset-relative-path)
  (handler-case
      (let ((chunk (funcall chunk-finder topic-id :signal-error? t)))
        (make-topic
         :id (id-of chunk)
         :title (title-of chunk)
         :summary (summary-of chunk)
         :references (references-of chunk)))
    (error (condition)
      (or (generated-topic-from-asset asset-relative-path topic-id)
          (error "Failed to reconstruct generated topic ~S from source pipeline (~A) or fallback asset ~A."
                 topic-id
                 condition
                 asset-relative-path)))))

(defun make-the-life-cycle-of-collective-knowledge-topic (topic-id)
  (make-generated-page-topic-with-fallback
   topic-id
   #'find-the-life-cycle-of-collective-knowledge-topic-chunk
   *the-life-cycle-of-collective-knowledge-topic-asset*))

(defun the-life-cycle-of-collective-knowledge-topic ()
  (make-the-life-cycle-of-collective-knowledge-topic
   "the-life-cycle-of-collective-knowledge"))

(defun collective-knowledge-topic ()
  (make-the-life-cycle-of-collective-knowledge-topic
   "collective-knowledge"))

(defun refinement-of-information-into-knowledge-topic ()
  (make-the-life-cycle-of-collective-knowledge-topic
   "refinement-of-information-into-knowledge"))

(defun digital-fragility-of-software-source-code-topic ()
  (make-the-life-cycle-of-collective-knowledge-topic
   "digital-fragility-of-software-source-code"))

(defun computational-reproducibility-is-not-enough-topic ()
  (make-the-life-cycle-of-collective-knowledge-topic
   "computational-reproducibility-is-not-enough"))

(defun software-interoperability-across-time-topic ()
  (make-the-life-cycle-of-collective-knowledge-topic
   "software-interoperability-across-time"))

(defun stable-software-environments-topic ()
  (make-the-life-cycle-of-collective-knowledge-topic
   "stable-software-environments"))

(defun code-as-knowledge-representation-topic ()
  (make-topic
   :id "code-as-knowledge-representation"
   :title "Code as knowledge representation"
   :summary "In HyperDoc, code is treated both as a representation of knowledge and as a medium for building situated tools that help inspect and process that knowledge."
   :references '("Design"
                 "Goals and values"
                 "HyperDoc Runtime Model")))

(defun computational-story-topic ()
  (make-topic
   :id "computational-story"
   :title "Computational story"
   :summary "A computational story combines narrative, the steps of a computation, and its intermediate results without collapsing them into one linear notebook-style execution stream."
   :references '("Design"
                 "Goals and values")))

(defun common-lisp-as-implementation-substrate-topic ()
  (make-topic
   :id "common-lisp-as-implementation-substrate"
   :title "Common Lisp as implementation substrate"
   :summary "Common Lisp is HyperDoc's current implementation substrate because it combines interactivity, introspection, and long-term stability in a form that still supports durable source reconstruction."
   :references '("Design"
                 "Goals and values"
                 "Creating a HyperDoc"
                 "Source-oriented and image-oriented development in Common Lisp"
                 "The Life Cycle of Collective Knowledge")))

(defun hypermedia-item-as-in-memory-object-topic ()
  (make-topic
   :id "hypermedia-item-as-in-memory-object"
   :title "Hypermedia item as in-memory object"
   :summary "In the current Common Lisp implementation, each hypermedia item is represented by a live object, often acting as a proxy to a file, source artifact, or network resource."
   :references '("HyperDoc Runtime Model"
                 "Creating a HyperDoc"
                 "Design")))

(defun inspector-as-browser-topic ()
  (make-topic
   :id "inspector-as-browser"
   :title "Inspector as browser"
   :summary "Inspector as browser means that an object inspector is not just a debugging tool but the current primary browsing surface for HyperDoc's page and object model."
   :references '("HyperDoc Runtime Model"
                 "Design"
                 "Glamorous Toolkit and HyperDoc")))

(defun hyperdoc-as-protocol-topic ()
  (make-topic
   :id "hyperdoc-as-protocol"
   :title "HyperDoc as protocol"
   :summary "HyperDoc as protocol is the longer-term direction in which HyperDoc units could interact through a more explicit protocol and support multiple browsers without being tied to one implementation technology."
   :references '("Design"
                 "HyperDoc Runtime Model"
                 "HyperDoc and HyperBook")))

(defun make-reproducible-devenv-as-knowledge-artifact-topic (topic-id)
  (make-generated-page-topic-with-fallback
   topic-id
   #'find-reproducible-devenv-as-knowledge-artifact-topic-chunk
   *reproducible-devenv-as-knowledge-artifact-topic-asset*))

(defun reproducible-devenv-as-knowledge-artifact-topic ()
  (make-reproducible-devenv-as-knowledge-artifact-topic
   "reproducible-devenv-as-knowledge-artifact"))

(defun devenv-as-knowledge-artifact-topic ()
  (make-reproducible-devenv-as-knowledge-artifact-topic
   "devenv-as-knowledge-artifact"))

(defun environment-topic-traceability-topic ()
  (make-reproducible-devenv-as-knowledge-artifact-topic
   "environment-topic-traceability"))

(defun localhost-fedwiki-page-promotion-workflow-topic ()
  (make-topic
   :id "localhost-fedwiki-page-promotion-workflow"
   :title "Localhost FedWiki page promotion workflow"
   :summary "Reusable workflow that reads a localhost FedWiki page, normalizes story items and fragments, promotes topic chunks, composes a durable HyperDoc page, and routes optional DMX dry-run or live snippet writes through a guarded long-form payload boundary without collapsing authored pages into live proxies."
   :references '("Localhost FedWiki page promotion workflow"
                 "DMX MCP server for shared workspace"
                 "Context window workspace as shared blackboard"
                 "The Life Cycle of Collective Knowledge"
                 "Reproducible DevEnv as Knowledge Artifact"
                 "Authored topic factories"
                 "DMX FedWiki Write Model"
                 "HyperDoc DMX architectural implications"
                 "DMX MCP server for shared workspace"
                 "Context window workspace as shared blackboard"
                 "Shared-workspace collaboration model"
                 "Documentation Surfaces in HyperDoc")))

(defun dmx-fedwiki-write-model-topic ()
  (make-topic
   :id "dmx-fedwiki-write-model"
   :title "DMX FedWiki Write Model"
   :summary "HyperDoc-side DMX write contract that treats DMX as a persistence boundary and routes topicmap-context writes through canonical long-form payload validation."
   :references '("DMX FedWiki Write Model"
                 "DMX workspace journal model"
                 "DMX MCP server for shared workspace"
                 "Context window workspace as shared blackboard"
                 "DMX topicmap 919822 repair runbook"
                 "DMX note read/write boundary"
                 "DMX machine-readable read paths"
                 "DMX MCP server for shared workspace"
                 "HyperDoc DMX architectural implications"
                 "FedWiki Site to DMX Import"
                 "Localhost FedWiki page promotion workflow")))

(defun dmx-mcp-server-shared-workspace-topic ()
  (make-topic
   :id "dmx-mcp-server-shared-workspace"
   :title "DMX MCP server for shared workspace"
   :summary "Streamable HTTP MCP server that projects the DMX context-window workspace as a shared blackboard and routes every narrow write through HyperDoc's validated DMX adapter instead of raw permissive DMX endpoints."
   :references '("DMX MCP server for shared workspace"
                 "Add HyperDoc MCP beside the authoritative host config on dreyeck.ch"
                 "Context window workspace as shared blackboard"
                 "DMX workspace journal model"
                 "DMX FedWiki Write Model"
                 "HyperDoc DMX architectural implications"
                 "DMX topicmap 919822 repair runbook"
                 "Localhost FedWiki page promotion workflow")))

(defun context-window-workspace-shared-blackboard-topic ()
  (make-topic
   :id "context-window-workspace-shared-blackboard"
   :title "Context window workspace as shared blackboard"
   :summary "Collaboration model in which DMX topicmap 919822 acts as a bounded shared blackboard for me, ChatGPT, and Codex through typed note and handover tools instead of arbitrary topic mutation."
   :references '("Context window workspace as shared blackboard"
                 "DMX MCP server for shared workspace"
                 "DMX FedWiki Write Model"
                 "HyperDoc DMX architectural implications"
                 "DMX topicmap 919822 repair runbook"
                 "Localhost FedWiki page promotion workflow")))

(defun dmx-topicmap-919822-repair-runbook-topic ()
  (make-topic
   :id "dmx-topicmap-919822-repair-runbook"
   :title "DMX topicmap 919822 repair runbook"
   :summary "Durable incident and repair runbook for the short-key-only topicmap-context defect that broke DMX topicmap 919822, including diagnosis, live repair, wider audit, and rollback."
   :references '("DMX topicmap 919822 repair runbook"
                 "DMX machine-readable read paths"
                 "DMX note read/write boundary"
                 "DMX MCP server for shared workspace"
                 "Context window workspace as shared blackboard"
                 "Localhost FedWiki page promotion workflow"
                 "DMX FedWiki Write Model"
                 "HyperDoc DMX architectural implications"
                 "Concepts, DMX Topics, and Topic Maps")))

(defun hyperdoc-dmx-architectural-implications-topic ()
  (make-topic
   :id "hyperdoc-dmx-architectural-implications"
   :title "HyperDoc DMX architectural implications"
   :summary "Architectural consequences of the DMX topicmap 919822 incident: HyperDoc keeps DMX writes narrow, typed, dry-run-first, and fail-soft because generic DMX persistence boundaries cannot be assumed safe by default."
   :references '("HyperDoc DMX architectural implications"
                 "Py4dmx"
                 "DMX MCP server for shared workspace"
                 "Context window workspace as shared blackboard"
                 "DMX topicmap 919822 repair runbook"
                 "DMX FedWiki Write Model"
                 "DMX MCP server for shared workspace"
                 "Context window workspace as shared blackboard"
                 "Shared-workspace collaboration model"
                 "DMX note read/write boundary"
                 "Localhost FedWiki page promotion workflow"
                 "Failure as Inspectable Object")))

(defun dmx-mcp-server-for-shared-workspace-topic ()
  (make-topic
   :id "dmx-mcp-server-for-shared-workspace"
   :title "DMX MCP server for shared workspace"
   :summary "Streamable HTTP MCP server in HyperDoc that exposes the context-window workspace and selected DMX topics/topicmaps as resources and read tools while keeping writes on a narrow validated note and handover boundary."
   :references '("DMX MCP server for shared workspace"
                 "Add HyperDoc MCP beside the authoritative host config on dreyeck.ch"
                 "Context window workspace as shared blackboard"
                 "DMX workspace journal model"
                 "DMX note read/write boundary"
                 "DMX machine-readable read paths"
                 "Shared-workspace collaboration model"
                 "DMX FedWiki Write Model"
                 "HyperDoc DMX architectural implications"
                 "Localhost FedWiki page promotion workflow")))

(defun dmx-workspace-journal-model-topic ()
  (make-topic
   :id "dmx-workspace-journal-model"
   :title "DMX workspace journal model"
   :summary "HyperDoc-owned DMX projection journal layer for shared-workspace notes, topics, and topicmap membership in topicmap 919822, used today for replay, restore, and diff-based reconciliation without treating DMX as the ultimate journal authority."
   :references '("Surface"
                 "Surface boundary"
                 "Boundary"
                 "Transition boundary"
                 "DMX workspace journal model"
                 "DMX workspace journal reconcile call graph"
                 "Context window workspace as shared blackboard"
                 "Shared-workspace collaboration model"
                 "DMX MCP server for shared workspace"
                 "DMX note read/write boundary"
                 "DMX FedWiki Write Model"
                 "Authoritative Journal-Backed Page Store"
                 "Topic factory and DMX reincarnation"
                 "FedWiki Journal Tools in HyperDoc"
                 "Journalmatic Revision Replay")))

(defun workspace-native-annotations-in-a-dmx-workspace-topic ()
  (make-topic
   :id "workspace-native-annotations-in-a-dmx-workspace"
   :title "Workspace-native annotations in a DMX workspace"
   :summary "Pattern where a pane-local dock annotation preserves native hyperdoc.annotation semantics, while current live HTTP persistence normally stores the full native payload losslessly inside a dmx.notes.note compatibility carrier in topicmap 919822 and reopens as a workspace-dock-annotation; authored promotion stays separate."
   :references '("Workspace-native annotations in a DMX workspace"
                 "Annotation"
                 "Add or edit an annotation from a path context menu"
                 "Context window workspace as shared blackboard"
                 "Using guarded workspace topic lifecycle tools"
                 "DMX FedWiki Write Model"
                 "DMX workspace journal model"
                 "DMX note read/write boundary"
                 "Localhost FedWiki page promotion workflow"
                 "Chunk notes and manifest notes in a DMX workspace")))

(defun dmx-workspace-journal-reconcile-call-graph-topic ()
  (make-topic
   :id "dmx-workspace-journal-reconcile-call-graph"
   :title "DMX workspace journal reconcile call graph"
   :summary "Inspectable call graph for reconcile-on-read in topicmap 919822, showing why companion journal note 924694 must stay on an in-memory-only diff path while explicit write flows still use the append/persist edge."
   :references '("Surface"
                 "Failure surface"
                 "DMX workspace journal reconcile call graph"
                 "Code path graphs in HyperDoc"
                 "DMX workspace journal model"
                 "DMX topicmap 919822 repair runbook"
                 "DMX note read/write boundary"
                 "DMX MCP server for shared workspace"
                 "Context window workspace as shared blackboard")))

(defun context-window-workspace-as-shared-blackboard-topic ()
  (make-topic
   :id "context-window-workspace-as-shared-blackboard"
   :title "Context window workspace as shared blackboard"
   :summary "Treat DMX topicmap 919822, context-window, as a small curated shared blackboard and rebuildable shared projection between me, ChatGPT, and Codex, not as a raw transcript archive or the only durable authority."
   :references '("Context window workspace as shared blackboard"
                 "DMX MCP server for shared workspace"
                 "DMX workspace journal model"
                 "Shared-workspace collaboration model"
                 "DMX note read/write boundary"
                 "DMX machine-readable read paths"
                 "HyperDoc DMX architectural implications"
                 "Authoritative Journal-Backed Page Store"
                 "Topic factory and DMX reincarnation"
                 "Localhost FedWiki page promotion workflow"
                 "DMX topicmap 919822 repair runbook")))

(defun dmx-note-read-write-boundary-topic ()
  (make-topic
   :id "dmx-note-read-write-boundary"
   :title "DMX note read/write boundary"
   :summary "Read DMX notes through the full parent-note topic projection, write them only by updating the parent dmx.notes.note payload, and treat append_workspace_note as noteKey-idempotent only when the read client can resolve the existing parent note."
   :references '("Boundary"
                 "Contract boundary"
                 "Read-write boundary"
                 "DMX note read/write boundary"
                 "DMX machine-readable read paths"
                 "DMX FedWiki Write Model"
                 "DMX MCP server for shared workspace"
                 "DMX workspace journal model"
                 "Context window workspace as shared blackboard"
                 "Shared-workspace collaboration model")))

(defun dmx-machine-readable-read-paths-topic ()
  (make-topic
   :id "dmx-machine-readable-read-paths"
   :title "DMX machine-readable read paths"
   :summary "Canonical machine-readable DMX reads use explicit core/topic and topicmaps endpoints with children included, while webclient hash routes remain browser navigation surfaces rather than tool-facing contracts."
   :references '("DMX machine-readable read paths"
                 "Py4dmx"
                 "DMX topicmap 919822 repair runbook"
                 "DMX note read/write boundary"
                 "DMX MCP server for shared workspace"
                 "Context window workspace as shared blackboard"
                 "Shared-workspace collaboration model")))

(defun shared-workspace-collaboration-model-topic ()
  (make-topic
   :id "shared-workspace-collaboration-model"
   :title "Shared-workspace collaboration model"
   :summary "The collaboration model keeps each HyperDoc instance as the durable journal and inspection side, uses the context-window workspace as a curated shared blackboard and rebuildable shared projection, and lets me, ChatGPT, and Codex converge through the same MCP-facing DMX surfaces."
   :references '("Shared-workspace collaboration model"
                 "Context window workspace as shared blackboard"
                 "DMX MCP server for shared workspace"
                 "DMX workspace journal model"
                 "DMX note read/write boundary"
                 "DMX machine-readable read paths"
                 "Authoritative Journal-Backed Page Store"
                 "Topic factory and DMX reincarnation"
                 "HyperDoc DMX architectural implications"
                 "Localhost FedWiki page promotion workflow")))

(defun how-to-work-safely-in-topicmap-context-window-919822-topic ()
  (make-topic
   :id "how-to-work-safely-in-topicmap-context-window-919822"
   :title "How to work safely in topicmap context-window (919822)"
   :summary "Short operator-facing entrypoint for DMX topicmap 919822 that routes reads, guarded notes, annotation continuation, diagnosis, and explicit-auth repair without confusing visibility with ownership or widening HyperDoc into generic DMX mutation."
   :references '("How to work safely in topicmap context-window (919822)"
                 "Context window workspace as shared blackboard"
                 "DMX MCP server for shared workspace"
                 "DMX machine-readable read paths"
                 "Using guarded workspace topic lifecycle tools"
                 "Workspace-native annotations in a DMX workspace"
                 "Diagnosing DMX workspace assignment and topicmap placement"
                 "Diagnosing DMX workspace repair triage"
                 "Using authenticated workspace assignment repair console"
                 "HyperDoc three-mode DMX auth crosswalk")))

(defun using-guarded-workspace-topic-lifecycle-tools-topic ()
  (make-topic
   :id "using-guarded-workspace-topic-lifecycle-tools"
   :title "Using guarded workspace topic lifecycle tools"
   :summary "Operational runbook for creating, updating, placing, unlinking, and ownership-limited deleting of guarded workspace topics in topicmap 919822 through the MCP boundary."
   :references '("Using guarded workspace topic lifecycle tools"
                 "DMX MCP server for shared workspace"
                 "Context window workspace as shared blackboard"
                 "DMX note read/write boundary"
                 "DMX FedWiki Write Model"
                 "Shared-workspace collaboration model")))

(defun diagnosing-dmx-workspace-assignment-and-topicmap-placement-topic ()
  (make-topic
   :id "diagnosing-dmx-workspace-assignment-and-topicmap-placement"
   :title "Diagnosing DMX workspace assignment and topicmap placement"
   :summary "Read-only inspector walkthrough for one DMX object that keeps workspace assignment separate from topicmap placement and exposes the raw endpoints used to diagnose missing workspace assignment defects."
   :references '("Diagnosing DMX workspace assignment and topicmap placement"
                 "Using guarded workspace topic lifecycle tools"
                 "Context window workspace as shared blackboard"
                 "DMX MCP server for shared workspace"
                 "DMX note read/write boundary")))

(defun operational-definition-chunk-chunk-note-manifest-note-content-topic ()
  (make-topic
   :id "operational-definition-chunk-chunk-note-manifest-note-content-topic"
   :title "Operational definition: chunk, chunk note, manifest note, content topic"
   :summary "Title-first launcher entry for the live DMX workspace note behind canary 922464, opening the real DMX topic proxy with Workspace diagnostics and Repair console instead of a reminder note."
   :references '("Operational definition: chunk, chunk note, manifest note, content topic"
                 "Using authenticated workspace assignment repair console"
                 "Diagnosing DMX workspace assignment and topicmap placement"
                 "Inspectable authentication-path traces for repair console"
                 "Chunk notes and manifest notes in a DMX workspace")))

(defun diagnosing-dmx-workspace-repair-triage-topic ()
  (make-topic
   :id "diagnosing-dmx-workspace-repair-triage"
   :title "Diagnosing DMX workspace repair triage"
   :summary "Read-only batch inspector for HyperDoc-owned objects in topicmap 919822 that are still visible in the shared blackboard but remain missing workspace assignment."
   :references '("Surface"
                 "Diagnostic surface"
                 "Failure surface"
                 "Boundary"
                 "Transition boundary"
                 "Diagnosing DMX workspace repair triage"
                 "Diagnosing DMX workspace assignment and topicmap placement"
                 "Using guarded workspace topic lifecycle tools"
                 "Context window workspace as shared blackboard"
                 "DMX MCP server for shared workspace"
                 "DMX note read/write boundary")))

(defun using-authenticated-workspace-assignment-repair-console-topic ()
  (make-topic
   :id "using-authenticated-workspace-assignment-repair-console"
   :title "Using authenticated workspace assignment repair console"
   :summary "HyperDoc-side repair console that keeps diagnosis read-only, accepts explicit ephemeral DMX credentials at action time, and reuses the guarded workspace-assignment repair executor for one object or the current backlog."
   :references '("Surface"
                 "Mutation surface"
                 "Failure surface"
                 "Boundary"
                 "Authentication boundary"
                 "Transition boundary"
                 "Using authenticated workspace assignment repair console"
                 "Diagnosing DMX workspace assignment and topicmap placement"
                 "Diagnosing DMX workspace repair triage"
                 "Using guarded workspace topic lifecycle tools"
                 "DMX note read/write boundary"
                 "Context window workspace as shared blackboard")))

(defun inspectable-authentication-path-traces-for-repair-console-topic ()
  (make-topic
   :id "inspectable-authentication-path-traces-for-repair-console"
   :title "Inspectable authentication-path traces for repair console"
   :summary "Step-by-step auth-state-machine guide for the HyperDoc repair console, including dmx-auth-path-example learning objects, username/password session bootstrap, direct header/token request shapes, result readback evidence, and a 922464-focused 401 debugging checklist."
   :references '("Inspectable authentication-path traces for repair console"
                 "Using authenticated workspace assignment repair console"
                 "Diagnosing DMX workspace assignment and topicmap placement"
                 "Diagnosing DMX workspace repair triage"
                 "DMX note read/write boundary"
                 "Context window workspace as shared blackboard")))

(defun guarded-local-neo4j-repair-boundary-in-hyperdoc-topic ()
  (make-topic
   :id "guarded-local-neo4j-repair-boundary-in-hyperdoc"
   :title "Guarded local Neo4j repair boundary in HyperDoc"
   :summary "Local-first repair boundary for one supported Neo4j datastore maintenance case in which HyperDoc keeps inspection, plan, approval, execution, and verification explicit instead of widening into a raw Neo4j console."
   :references '("Guarded local Neo4j repair boundary in HyperDoc"
                 "Guarded datastore repair"
                 "Datastore adapter boundary"
                 "Inspectable operational targets"
                 "Materialize a host-aware operation without executing it"
                 "Surface"
                 "Mutation surface"
                 "Boundary"
                 "Repairing duplicate DMX admin username ambiguity")))

(defun guarded-datastore-repair-topic ()
  (make-topic
   :id "guarded-datastore-repair"
   :title "Guarded datastore repair"
   :summary "A bounded maintenance surface that models one supported datastore repair as inspectable report, plan, refusal, execution, and verification objects instead of exposing general mutation power."
   :references '("Guarded local Neo4j repair boundary in HyperDoc"
                 "Repairing duplicate DMX admin username ambiguity"
                 "Inspectable operational targets"
                 "Materialize a host-aware operation without executing it"
                 "Boundary"
                 "Mutation surface")))

(defun datastore-adapter-boundary-topic ()
  (make-topic
   :id "datastore-adapter-boundary"
   :title "Datastore adapter boundary"
   :summary "A narrow host-defined adapter seam in which Lisp owns policy and refusal while a replaceable helper touches only the datastore-specific substrate needed for one supported case."
   :references '("Guarded local Neo4j repair boundary in HyperDoc"
                 "Repairing duplicate DMX admin username ambiguity"
                 "Boundary"
                 "Implementation Boundary for Capability-scoped Extensions")))

(defun repairing-duplicate-dmx-admin-username-ambiguity-topic ()
  (make-topic
   :id "repairing-duplicate-dmx-admin-username-ambiguity"
   :title "Repairing duplicate DMX admin username ambiguity"
   :summary "Workflow page for the duplicate-admin Neo4j repair slice: inspect the duplicate username report, classify canonical versus stale in Lisp, build a reviewed rename plan, and verify the result without exposing a generic Neo4j console."
   :references '("Repairing duplicate DMX admin username ambiguity"
                 "Guarded local Neo4j repair boundary in HyperDoc"
                 "Guarded datastore repair"
                 "Datastore adapter boundary"
                 "Using authenticated workspace assignment repair console"
                 "Py4dmx"
                 "DMX session bootstrap and JSESSIONID"
                 "HyperDoc DMX architectural implications")))

(defun dmx-credentials-topic ()
  (make-topic
   :id "dmx-credentials"
   :title "DMX Credentials"
   :summary "DMX Credentials are the parsed username/password/methodName structure behind Authorization header handling, not a separate HyperDoc-invented credential store."
   :references '("DMX Credentials"
                 "DMX Authorization header to Credentials path"
                 "DMX AuthorizationMethod"
                 "DMX session bootstrap and JSESSIONID"
                 "HyperDoc three-mode DMX auth crosswalk"
                 "Inspectable authentication-path traces for repair console")))

(defun dmx-authorizationmethod-topic ()
  (make-topic
   :id "dmx-authorizationmethod"
   :title "DMX AuthorizationMethod"
   :summary "AuthorizationMethod is the DMX extension point for non-Basic Authorization schemes, which makes bearer-style support installation-dependent rather than universally native."
   :references '("DMX AuthorizationMethod"
                 "DMX Credentials"
                 "DMX Authorization header to Credentials path"
                 "HyperDoc three-mode DMX auth crosswalk"
                 "Inspectable authentication-path traces for repair console")))

(defun dmx-anonymousaccessfilter-topic ()
  (make-topic
   :id "dmx-anonymousaccessfilter"
   :title "DMX AnonymousAccessFilter"
   :summary "AnonymousAccessFilter is DMX's request-prefix fallback for anonymous read or write allowances, not a primary guarded repair credential mode."
   :references '("DMX AnonymousAccessFilter"
                 "DMX Authorization header to Credentials path"
                 "HyperDoc three-mode DMX auth crosswalk"
                 "Using authenticated workspace assignment repair console"
                 "Inspectable authentication-path traces for repair console")))

(defun dmx-authorization-header-to-credentials-path-topic ()
  (make-topic
   :id "dmx-authorization-header-to-credentials-path"
   :title "DMX Authorization header to Credentials path"
   :summary "DMX reads Authorization, constructs Credentials, resolves AuthorizationMethod for non-Basic methods, checks credentials, and on success attaches username to the servlet session."
   :references '("DMX Authorization header to Credentials path"
                 "DMX Credentials"
                 "DMX AuthorizationMethod"
                 "DMX AnonymousAccessFilter"
                 "DMX session bootstrap and JSESSIONID"
                 "HyperDoc three-mode DMX auth crosswalk"
                 "Inspectable authentication-path traces for repair console")))

(defun dmx-session-bootstrap-and-jsessionid-topic ()
  (make-topic
   :id "dmx-session-bootstrap-and-jsessionid"
   :title "DMX session bootstrap and JSESSIONID"
   :summary "HyperDoc's username/password input mode derives a Basic login bootstrap and later guarded requests carry the JSESSIONID aftermath plus workspace cookie rather than treating cookies as a primary operator input mode."
   :references '("DMX session bootstrap and JSESSIONID"
                 "Py4dmx"
                 "Using authenticated workspace assignment repair console"
                 "Inspectable authentication-path traces for repair console"
                 "DMX Authorization header to Credentials path"
                 "HyperDoc three-mode DMX auth crosswalk")))

(defun hyperdoc-three-mode-dmx-auth-crosswalk-topic ()
  (make-topic
   :id "hyperdoc-three-mode-dmx-auth-crosswalk"
   :title "HyperDoc three-mode DMX auth crosswalk"
   :summary "Inspectable learning surface built from dmx-auth-path-example objects that keeps username/password, full Authorization header, and bearer token input modes aligned with DMX Credentials parsing, AuthorizationMethod resolution, AnonymousAccessFilter fallback, and the later JSESSIONID/session-cookie aftermath."
   :references '("HyperDoc three-mode DMX auth crosswalk"
                 "DMX Credentials"
                 "DMX AuthorizationMethod"
                 "DMX AnonymousAccessFilter"
                 "DMX Authorization header to Credentials path"
                 "DMX session bootstrap and JSESSIONID"
                 "Using authenticated workspace assignment repair console"
                 "Inspectable authentication-path traces for repair console"
                 "Operational definition: chunk, chunk note, manifest note, content topic"
                 "DMX MCP server for shared workspace"
                 "Workspace-native annotations in a DMX workspace")))

(defun exchange-artifact-topic ()
  (make-topic
   :id "exchange-artifact"
   :title "Exchange artifact"
   :summary "Larger transport object that must be exchanged through the topicmap as multiple notes, indexed by exactly one manifest note and not authoritative for the underlying content topics."
   :references '("Chunk notes and manifest notes in a DMX workspace"
                 "Manifest note"
                 "Chunk note"
                 "Content topic"
                 "Context window workspace as shared blackboard"
                 "Shared-workspace collaboration model")))

(defun manifest-note-topic ()
  (make-topic
   :id "manifest-note"
   :title "Manifest note"
   :summary "Authoritative index note for one exchange artifact that says what the whole artifact is, how many parts it has, what each part covers, and whether the partition is lossless."
   :references '("Chunk notes and manifest notes in a DMX workspace"
                 "Exchange artifact"
                 "Chunk note"
                 "DMX note read/write boundary"
                 "Context window workspace as shared blackboard")))

(defun chunk-note-topic ()
  (make-topic
   :id "chunk-note"
   :title "Chunk note"
   :summary "A dmx.notes.note transport container for exactly one declared part of an exchange artifact, durable for replay and audit but not primary subject matter."
   :references '("Chunk notes and manifest notes in a DMX workspace"
                 "Exchange artifact"
                 "Manifest note"
                 "Chunk"
                 "Context window workspace as shared blackboard"
                 "DMX note read/write boundary"
                 "Declarative chunk wiring for page-lookup issues and first real Topics chunk")))

(defun content-topic ()
  (make-topic
   :id "content-topic"
   :title "Content topic"
   :summary "Normal workspace topic whose purpose is substantive knowledge; if a chunk note carries a readout of that topic, the topic remains authoritative for the underlying subject matter."
   :references '("Chunk notes and manifest notes in a DMX workspace"
                 "Exchange artifact"
                 "Context window workspace as shared blackboard"
                 "Concepts, DMX Topics, and Topic Maps")))

(defun image-oriented-development-topic ()
  (make-topic
   :id "image-oriented-development"
   :title "Image-oriented development"
   :summary "Workflow in which a live Lisp image is incrementally mutated during exploration or implementation work, with source reconstruction still needed for durable rebuilds."
   :references '("Source-oriented and image-oriented development in Common Lisp"
                 "SBCL Process"
                 "SBCL bootstrapping model")))

(defun host-target-separation-topic ()
  (make-topic
   :id "host-target-separation"
   :title "Host/target separation"
   :summary "Explicit distinction between the host Common Lisp used during bootstrap and the target SBCL being built."
   :references '("Host and target separation in SBCL"
                 "SBCL bootstrapping model"
                 "SBCL build stages: cross-compiler, genesis, cold core, cold init")))

(defun cross-compiler-topic ()
  (make-topic
   :id "cross-compiler"
   :title "Cross-compiler"
   :summary "Bootstrap compiler layer that runs in the host Lisp but emits target SBCL code."
   :references '("SBCL build stages: cross-compiler, genesis, cold core, cold init"
                 "Host and target separation in SBCL"
                 "SBCL bootstrapping model")))

(defun genesis-build-stage-topic ()
  (make-topic
   :id "genesis-build-stage"
   :title "Genesis build stage"
   :summary "SBCL bootstrap stage that simulates loading target FASLs and writes the cold core image."
   :references '("SBCL build stages: cross-compiler, genesis, cold core, cold init"
                 "SBCL bootstrapping model")))

(defun cold-core-topic ()
  (make-topic
   :id "cold-core"
   :title "Cold core"
   :summary "Bootstrap image written before cold init, containing the target runtime state needed to start SBCL."
   :references '("SBCL build stages: cross-compiler, genesis, cold core, cold init"
                 "SBCL bootstrapping model")))

(defun cold-init-topic ()
  (make-topic
   :id "cold-init"
   :title "Cold init"
   :summary "First target runtime initialization that completes startup from the cold core."
   :references '("SBCL build stages: cross-compiler, genesis, cold core, cold init"
                 "SBCL bootstrapping model")))

(defun bootstrap-determinism-topic ()
  (make-topic
   :id "bootstrap-determinism"
   :title "Bootstrap determinism"
   :summary "Goal that the final SBCL build result should not depend on accidental state in the host compiler image."
   :references '("SBCL bootstrapping model"
                 "Host and target separation in SBCL"
                 "SBCL build stages: cross-compiler, genesis, cold core, cold init")))

(defun image-as-deployment-artifact-topic ()
  (make-topic
   :id "image-as-deployment-artifact"
   :title "Image as deployment artifact"
   :summary "Saved image used mainly as a runnable delivery artifact rather than the durable source of truth for ordinary application development."
   :references '("Source-oriented and image-oriented development in Common Lisp"
                 "SBCL Process"
                 "SBCL")))

(defun live-image-versus-durable-source-topic ()
  (make-topic
   :id "live-image-versus-durable-source"
   :title "Live image versus durable source"
   :summary "Boundary between mutable runtime image state used for live work and source files that remain authoritative for rebuilds."
   :references '("Source-oriented and image-oriented development in Common Lisp"
                 "SBCL Process"
                 "Understanding ASDF Systems in HyperDoc"
                 "SBCL bootstrapping model")))

(defun running-image-coherence-topic ()
  (make-topic
   :id "running-image-coherence"
   :title "Running image coherence"
   :summary "The problem of keeping a live Lisp image internally consistent and intelligible as chunks, dependencies, and derived runtime state evolve and must stay fresh relative to their basis."
   :references '("A framework for maintaining the coherence of a running Lisp"
                 "McDermott Running Image Coherence Crosswalk"
                 "Drew McDermott Lisp, Planning, and Software"
                 "Source-oriented and image-oriented development in Common Lisp")))

(defun chunk-topic ()
  (make-topic
   :id "chunk"
   :title "Chunk"
   :summary "McDermott’s inspectable unit of running-image coherence: a piece of information with a particular state, form, or location whose freshness can be maintained relative to a basis."
   :references '("A framework for maintaining the coherence of a running Lisp"
                 "McDermott Running Image Coherence Crosswalk"
                 "Core Chunk Classes"
                 "Chunk notes and manifest notes in a DMX workspace")))

(defun normal-association-submit-path-vs-evidence-path-topic ()
  (make-topic
   :id "normal-association-submit-path-vs-evidence-path"
   :title "Normal association submit path vs evidence path"
   :summary "Operational distinction between the standard button-payload-v2 association submit path, where source and target transport is authoritative, and the connect-request-evidence-v1 evidence path, where snapshot transport is authoritative."
   :references '("Snapshot transport"
                 "Submit-boundary Connect session snapshot"
                 "A DOM-annotation connect gesture"
                 "Running image coherence")))

(defun snapshot-transport-topic ()
  (make-topic
   :id "snapshot-transport"
   :title "Snapshot transport"
   :summary "Submit-boundary carrier seam by which browser-captured Connect snapshot JSON crosses from pane UI state into the server-side payload for later request evidence or snapshot inspection."
   :references '("Normal association submit path vs evidence path"
                 "Submit-boundary Connect session snapshot"
                 "A DOM-annotation connect gesture"
                 "Running image coherence")))

(defun association-topics-topic ()
  (make-topic
   :id "association-topics"
   :title "Association topics"
   :summary "Reviewed topic identity for relations that deserve durable authored treatment, using exact canonical title as the merge key and a proposal step before editing topic factories."
   :references '("Association Topics for Stable Identity and Mutable Titles"
                 "How to merge proposed topic additions into hyperdoc/topics.lisp"
                 "Relating the review contents to existing HyperDoc topics and pages")))

(defun reviewed-relation-topic-promotion-and-application-topic ()
  (make-topic
   :id "reviewed-relation-topic-promotion-and-application"
   :title "Reviewed relation-topic promotion and application"
   :summary "Operational pattern in which runtime relation objects stay first-class inspectables, promotion and patch planning remain advisory by default, and authored repo mutation happens only through an explicit approval-gated application seam."
   :references '("Reviewed relation-topic promotion and application"
                 "Association Topics for Stable Identity and Mutable Titles"
                 "How to merge proposed topic additions into hyperdoc/topics.lisp")))

(defun bootstrappability-as-social-architecture-topic ()
  (make-topic
   :id "bootstrappability-as-social-architecture"
   :title "Bootstrappability as social architecture"
   :summary "Build design choice that reduces contributor friction by making bootstrap steps more ordinary, predictable, and teachable."
   :references '("SBCL bootstrapping model"
                 "SBCL"
                 "Host and target separation in SBCL")))

(defun isolated-evaluation-workers-topic ()
  (make-topic
   :id "isolated-evaluation-workers"
   :title "Isolated evaluation workers"
   :summary "Run risky evaluation in dedicated worker processes or sandboxes only where needed, while keeping main server state stable."
   :references '("SBCL Process"
                 "Stepper Debugger Surface"
                 "HyperDoc Server")))

(defun fedwiki-content-runtime-policy-split-topic ()
  (make-topic
   :id "fedwiki-content-runtime-policy-split"
   :title "FedWiki content and runtime policy split"
   :summary "Keep page identity and content in FedWiki; keep runtime execution policy in HyperDoc/inspector tooling."
   :references '("SBCL Process"
                 "FedWiki Story Item IDs"
                 "HyperDoc Server")))
