;;;; HyperDoc authored topic family
;;;; Generated by splitting the former hyperdoc/topics.lisp monolith.

(in-package :hyperdoc)

(defun make-hypercard-topic (&key id title summary references)
  (make-topic
   :id id
   :title title
   :summary summary
   :references references))

(defun hypercard-topic ()
  (make-hypercard-topic
   :id "hypercard"
   :title "HyperCard"
   :summary "HyperCard is Apple's card-and-stack hypermedia authoring system whose significance for HyperDoc lies in its integrated authoring surface, approachable scripting, and unusually strong sense of software malleability."
   :references '("HyperCard on the Macintosh"
                 "HyperCard and HyperDoc"
                 "HyperCard reference platform neighborhood"
                 "Reference Systems in HyperDoc")))

(defun hypertalk-topic ()
  (make-hypercard-topic
   :id "hypertalk"
   :title "HyperTalk"
   :summary "HyperTalk is the object-centered scripting language of HyperCard, notable for attaching handlers to visible objects through an English-like but still formal programming surface."
   :references '("HyperTalk and English-ish Programming"
                 "HyperCard on the Macintosh"
                 "HyperCard and HyperDoc")))

(defun hypercard-stack-topic ()
  (make-hypercard-topic
   :id "hypercard-stack"
   :title "HyperCard stack"
   :summary "A HyperCard stack is the main container that holds cards, scripts, structure, and user data in one authorable artifact."
   :references '("HyperCard on the Macintosh"
                 "HyperTalk and English-ish Programming")))

(defun hypercard-card-topic ()
  (make-hypercard-topic
   :id "hypercard-card"
   :title "HyperCard card"
   :summary "A HyperCard card is the primary visible surface within a stack, combining displayed content with object-level behavior."
   :references '("HyperCard on the Macintosh"
                 "HyperTalk and English-ish Programming")))

(defun hypercard-background-layer-topic ()
  (make-hypercard-topic
   :id "hypercard-background-layer"
   :title "HyperCard background layer"
   :summary "The background layer in HyperCard carries shared fields, buttons, and scripts across multiple cards in the same stack."
   :references '("HyperCard on the Macintosh"
                 "HyperTalk and English-ish Programming")))

(defun hypercard-foreground-layer-topic ()
  (make-hypercard-topic
   :id "hypercard-foreground-layer"
   :title "HyperCard foreground layer"
   :summary "The foreground layer in HyperCard is the card-specific visible surface where local content and interactions differ from the shared background."
   :references '("HyperCard on the Macintosh"
                 "HyperTalk and English-ish Programming")))

(defun hypercard-field-topic ()
  (make-hypercard-topic
   :id "hypercard-field"
   :title "HyperCard field"
   :summary "A HyperCard field is a text-bearing object that can display, collect, and script textual content inside a stack."
   :references '("HyperCard on the Macintosh"
                 "HyperTalk and English-ish Programming")))

(defun hypercard-button-topic ()
  (make-hypercard-topic
   :id "hypercard-button"
   :title "HyperCard button"
   :summary "A HyperCard button is a visible or invisible interactive object that can trigger navigation, actions, or custom handlers."
   :references '("HyperCard on the Macintosh"
                 "HyperTalk and English-ish Programming")))

(defun transparent-button-hotspot-topic ()
  (make-hypercard-topic
   :id "transparent-button-hotspot"
   :title "Transparent button hotspot"
   :summary "A transparent button hotspot turns an arbitrary area of a card into an interactive region without adding visible chrome."
   :references '("HyperCard on the Macintosh"
                 "Hypermedia authoring")))

(defun stack-contained-data-topic ()
  (make-hypercard-topic
   :id "stack-contained-data"
   :title "Stack-contained data"
   :summary "HyperCard kept scripts, structure, and user data inside the same stack artifact, reducing the gap between content editing and persistence."
   :references '("HyperCard on the Macintosh"
                 "HyperCard and HyperDoc")))

(defun automatic-persistence-topic ()
  (make-hypercard-topic
   :id "automatic-persistence"
   :title "Automatic persistence"
   :summary "Automatic persistence names the HyperCard feeling that edits and data changes become real without a separate deployment or database-management step."
   :references '("HyperCard on the Macintosh"
                 "Integrated authoring environment")))

(defun end-user-programming-topic ()
  (make-hypercard-topic
   :id "end-user-programming"
   :title "End-user programming"
   :summary "End-user programming treats programming as something reachable by ordinary users through direct tools, visible objects, and low-friction feedback."
   :references '("HyperCard on the Macintosh"
                 "HyperCard and HyperDoc"
                 "HyperCard reference platform neighborhood")))

(defun integrated-authoring-environment-topic ()
  (make-hypercard-topic
   :id "integrated-authoring-environment"
   :title "Integrated authoring environment"
   :summary "An integrated authoring environment keeps editing, behavior, testing, and persistence close enough that the user edits the same surface that is being used."
   :references '("HyperCard on the Macintosh"
                 "HyperCard and HyperDoc"
                 "Documentation Surfaces in HyperDoc")))

(defun direct-manipulation-authoring-topic ()
  (make-hypercard-topic
   :id "direct-manipulation-authoring"
   :title "Direct manipulation authoring"
   :summary "Direct manipulation authoring means shaping interactive artifacts by acting on visible objects directly rather than only through distant configuration."
   :references '("HyperCard on the Macintosh"
                 "HyperCard and HyperDoc"
                 "HyperCard reference platform neighborhood")))

(defun built-in-paint-tools-topic ()
  (make-hypercard-topic
   :id "built-in-paint-tools"
   :title "Built-in paint tools"
   :summary "Built-in paint tools matter in HyperCard because drawing, layout, and interaction design happen inside the same authoring surface as scripting."
   :references '("HyperCard on the Macintosh")))

(defun immediate-feedback-loop-topic ()
  (make-hypercard-topic
   :id "immediate-feedback-loop"
   :title "Immediate feedback loop"
   :summary "An immediate feedback loop lets authors modify content or behavior and test the result without a disruptive phase change into a different tool or deployment surface."
   :references '("HyperCard on the Macintosh"
                 "HyperCard and HyperDoc")))

(defun content-behavior-co-location-topic ()
  (make-hypercard-topic
   :id "content-behavior-co-location"
   :title "Content/behavior co-location"
   :summary "Content/behavior co-location means the visible artifact and its behavior definitions remain close enough that explanation and modification are cheap."
   :references '("HyperCard on the Macintosh"
                 "HyperCard and HyperDoc")))

(defun editable-application-surface-topic ()
  (make-hypercard-topic
   :id "editable-application-surface"
   :title "Editable application surface"
   :summary "An editable application surface is one where using the software and altering the software happen on visibly related surfaces rather than in sealed layers."
   :references '("HyperCard and HyperDoc"
                 "HyperCard on the Macintosh")))

(defun object-message-scripting-topic ()
  (make-hypercard-topic
   :id "object-message-scripting"
   :title "Object/message scripting"
   :summary "Object/message scripting attaches behavior to objects and routes messages through a visible hierarchy rather than treating code as detached from the artifact."
   :references '("HyperTalk and English-ish Programming"
                 "HyperCard on the Macintosh")))

(defun english-ish-programming-topic ()
  (make-hypercard-topic
   :id "english-ish-programming"
   :title "English-ish programming"
   :summary "English-ish programming uses approachable, sentence-like notation to lower entry cost while still depending on real structural rules and exactness."
   :references '("HyperTalk and English-ish Programming"
                 "HyperCard reference platform neighborhood")))

(defun script-editor-limitations-topic ()
  (make-hypercard-topic
   :id "script-editor-limitations"
   :title "Script editor limitations"
   :summary "HyperCard's script editor limitations matter because the language was approachable while the surrounding programming ergonomics remained comparatively sparse."
   :references '("HyperTalk and English-ish Programming"
                 "HyperCard on the Macintosh")))

(defun applescript-interoperability-topic ()
  (make-hypercard-topic
   :id "applescript-interoperability"
   :title "AppleScript interoperability"
   :summary "AppleScript interoperability marks the boundary where HyperCard's approachable built-in scripting could cooperate with broader Macintosh automation rather than trying to absorb every capability itself."
   :references '("HyperTalk and English-ish Programming"
                 "HyperCard on the Macintosh"
                 "HyperCard reference platform neighborhood")))

(defun xcmd-extension-boundary-topic ()
  (make-hypercard-topic
   :id "xcmd-extension-boundary"
   :title "XCMD extension boundary"
   :summary "The XCMD boundary names the point where HyperCard relied on external compiled extensions for capabilities beyond core HyperTalk and built-in objects."
   :references '("HyperTalk and English-ish Programming"
                 "HyperCard Successors, Preservation, and Revival Attempts")))

(defun xfcn-extension-boundary-topic ()
  (make-hypercard-topic
   :id "xfcn-extension-boundary"
   :title "XFCN extension boundary"
   :summary "The XFCN boundary names the external-function extension mechanism that let HyperCard reach beyond its built-in language and object model."
   :references '("HyperTalk and English-ish Programming"
                 "HyperCard Successors, Preservation, and Revival Attempts")))

(defun hypermedia-authoring-topic ()
  (make-hypercard-topic
   :id "hypermedia-authoring"
   :title "Hypermedia authoring"
   :summary "Hypermedia authoring combines linked navigation, media placement, interaction, and structural editing into one authoring workflow."
   :references '("HyperCard on the Macintosh"
                 "HyperCard reference platform neighborhood"
                 "Reference Systems in HyperDoc")))

(defun hypercard-and-the-web-topic ()
  (make-hypercard-topic
   :id "hypercard-and-the-web"
   :title "HyperCard and the web"
   :summary "HyperCard and the web is a comparative topic about linked cards versus linked documents, and about how much authorability remained visible to ordinary users."
   :references '("HyperCard on the Macintosh"
                 "HyperCard and HyperDoc"
                 "HyperCard reference platform neighborhood")))

(defun hypercard-as-reference-platform-topic ()
  (make-hypercard-topic
   :id "hypercard-as-reference-platform"
   :title "HyperCard as reference platform"
   :summary "HyperCard is a reference platform for HyperDoc because it proves that integrated authoring, scripting, storage, and user-owned malleability can coexist in one approachable surface."
   :references '("HyperCard on the Macintosh"
                 "HyperCard and HyperDoc"
                 "Reference Systems in HyperDoc"
                 "HyperCard reference platform neighborhood")))

(defun natural-language-programming-limits-topic ()
  (make-hypercard-topic
   :id "natural-language-programming-limits"
   :title "Natural language programming limits"
   :summary "Natural-language-style programming can improve approachability without removing the need for explicit structure, exact syntax, and constrained semantics."
   :references '("HyperTalk and English-ish Programming"
                 "English-ish programming")))

(defun no-code-comparison-topic ()
  (make-hypercard-topic
   :id "no-code-comparison"
   :title "No-code comparison"
   :summary "No-code comparison asks whether a platform exposes making to the user or mainly hides it behind managed builders and generated results."
   :references '("HyperCard and HyperDoc"
                 "HyperCard reference platform neighborhood")))

(defun vibe-coding-comparison-topic ()
  (make-hypercard-topic
   :id "vibe-coding-comparison"
   :title "Vibe coding comparison"
   :summary "Vibe coding comparison highlights the difference between generated software results and tools that expose the making process directly to users."
   :references '("HyperCard and HyperDoc"
                 "HyperCard reference platform neighborhood")))

(defun software-malleability-topic ()
  (make-hypercard-topic
   :id "software-malleability"
   :title "Software malleability"
   :summary "Software malleability is the degree to which a system lets users move from using software to altering or extending it without a severe surface break."
   :references '("HyperCard on the Macintosh"
                 "HyperCard and HyperDoc"
                 "HyperCard reference platform neighborhood"
                 "Reference Systems in HyperDoc")))

(defun user-owned-software-surfaces-topic ()
  (make-hypercard-topic
   :id "user-owned-software-surfaces"
   :title "User-owned software surfaces"
   :summary "User-owned software surfaces are interfaces that let users inspect, alter, and keep control over the artifacts they rely on instead of treating them as sealed products."
   :references '("HyperCard and HyperDoc"
                 "HyperCard on the Macintosh"
                 "Software malleability")))

(defun hypercard-preservation-topic ()
  (make-hypercard-topic
   :id "hypercard-preservation"
   :title "HyperCard preservation"
   :summary "HyperCard preservation concerns how stacks, scripts, media, and workflows can be retained or translated when the original platform is no longer a standard contemporary environment."
   :references '("HyperCard Successors, Preservation, and Revival Attempts"
                 "HyperCard on the Macintosh")))

(defun hypercard-emulation-topic ()
  (make-hypercard-topic
   :id "hypercard-emulation"
   :title "HyperCard emulation"
   :summary "HyperCard emulation keeps the original environment accessible enough to inspect and run stacks, while still falling short of full historical continuity."
   :references '("HyperCard Successors, Preservation, and Revival Attempts"
                 "HyperCard preservation")))

(defun hypercard-reference-platform-neighborhood-topic ()
  (make-hypercard-topic
   :id "hypercard-reference-platform-neighborhood"
   :title "HyperCard reference platform neighborhood"
   :summary "Arrangement page preserving the editorial neighborhood among HyperCard, HyperTalk, GT, no-code, vibe coding, and adjacent malleability references without claiming semantic identity."
   :references '("HyperCard reference platform neighborhood"
                 "Reference Systems in HyperDoc"
                 "Topic arrangement in HyperDoc")))

(defun moldable-development-reference-systems-topic ()
  (make-topic
   :id "moldable-development-reference-systems"
   :title "Moldable development reference systems"
   :summary "Systems used as reference points for moldable-development practices while preserving local goals, constraints, and media choices."
   :references '("Glamorous Toolkit and HyperDoc"
                 "Goals and values"
                 "https://moldabledevelopment.com/"
                 "https://github.com/feenkcom/gtoolkit")))

(defun hyperdoc-reference-systems-topic ()
  (make-topic
   :id "hyperdoc-reference-systems"
   :title "HyperDoc reference systems"
   :summary "Reference systems in HyperDoc documentation are explicit conceptual anchors used to compare, adapt, and bound design choices."
   :references '("Reference Systems in HyperDoc"
                 "Design"
                 "Goals and values"
                 "Glamorous Toolkit and HyperDoc")))

(defun reference-system-boundaries-topic ()
  (make-topic
   :id "reference-system-boundaries"
   :title "Reference system boundaries"
   :summary "Boundary statements preserve differences between systems with shared concerns, preventing accidental equivalence in architecture or workflow."
   :references '("Reference Systems in HyperDoc"
                 "Glamorous Toolkit and HyperDoc"
                 "Communication Surfaces Policy")))

(defun adopting-without-equating-topic ()
  (make-topic
   :id "adopting-without-equating"
   :title "Adopting without equating"
   :summary "HyperDoc can adopt methods from reference systems while keeping scope, medium, and ownership distinctions explicit."
   :references '("Reference Systems in HyperDoc"
                 "Glamorous Toolkit and HyperDoc"
                 "Acknowledgements")))

(defun documentation-surfaces-in-hyperdoc-topic ()
  (make-topic
   :id "documentation-surfaces-in-hyperdoc"
   :title "Documentation Surfaces in HyperDoc"
   :summary "Defines durable pages, topic objects, inspectable object handles, and FedWiki twins as distinct documentation surfaces with explicit correspondence rules."
   :references '("Surface"
                 "Surface boundary"
                 "Documentation Surfaces in HyperDoc"
                 "Reference Systems in HyperDoc"
                 "Communication Surfaces Policy")))

(defun topic-arrangement-in-hyperdoc-topic ()
  (make-topic
   :id "topic-arrangement-in-hyperdoc"
   :title "Topic arrangement in HyperDoc"
   :summary "An authored documentation surface for representing topic proximity, grouping, and editorial neighborhood without asserting semantic associations."
   :references '("Topic arrangement in HyperDoc"
                 "Documentation Surfaces in HyperDoc"
                 "Topics HyperBook in HyperDoc"
                 "Topic factory"
                 "Authored topic factories"
                 "Definitive Common Lisp Books")))

(defun hyperdoc-surface-boundaries-topic ()
  (make-topic
   :id "hyperdoc-surface-boundaries"
   :title "HyperDoc surface boundaries"
   :summary "Boundary rules separating narrative pages, inspectable topic objects, embedded object handles, and parallel FedWiki artifacts."
   :references '("Surface"
                 "Surface boundary"
                 "Documentation Surfaces in HyperDoc"
                 "Communication Surfaces Policy"
                 "Reference Systems in HyperDoc")))

(defun page-topic-twin-correspondence-topic ()
  (make-topic
   :id "page-topic-twin-correspondence"
   :title "Page/topic/twin correspondence"
   :summary "Correspondence model linking pages, topic objects, and FedWiki twins by intent and references rather than literal structural identity."
   :references '("Documentation Surfaces in HyperDoc"
                 "Communication Surfaces Policy"
                 "Glamorous Toolkit and HyperDoc")))

(defun authoring-documentation-in-hyperdoc-topic ()
  (make-topic
   :id "authoring-documentation-in-hyperdoc"
   :title "Authoring Documentation in HyperDoc"
   :summary "Operational guidance for writing documentation slices across durable pages, topic objects, inspectable handles, and optional FedWiki twins."
   :references '("Authoring Documentation in HyperDoc"
                 "Documentation Surfaces in HyperDoc"
                 "Reference Systems in HyperDoc"
                 "Communication Surfaces Policy")))

(defun documentation-authoring-decisions-topic ()
  (make-topic
   :id "documentation-authoring-decisions"
   :title "Documentation authoring decisions"
   :summary "Decision rules for when to create pages, topics, inspectable objects, and FedWiki twins without forcing structural symmetry."
   :references '("Authoring Documentation in HyperDoc"
                 "Documentation Surfaces in HyperDoc"
                 "Design"
                 "Goals and values")))

(defun documentation-validation-and-commit-gates-topic ()
  (make-topic
   :id "documentation-validation-and-commit-gates"
   :title "Documentation validation and commit gates"
   :summary "Validation and commit-slicing gates for documentation work, including load, topic, coverage, and FedWiki syntax/semantic checks."
   :references '("Authoring Documentation in HyperDoc"
                 "Documentation Surfaces in HyperDoc"
                 "Communication Surfaces Policy")))

(defun documentation-architecture-in-hyperdoc-topic ()
  (make-topic
   :id "documentation-architecture-in-hyperdoc"
   :title "Documentation Architecture in HyperDoc"
   :summary "Entry-point map for the documentation architecture cluster, including scope, reading order, and relation model."
   :references '("Documentation Architecture in HyperDoc"
                 "Installing Glamorous Toolkit"
                 "Glamorous Toolkit and HyperDoc"
                 "Reference Systems in HyperDoc"
                 "Documentation Surfaces in HyperDoc"
                 "Authoring Documentation in HyperDoc")))

(defun documentation-cluster-reading-order-topic ()
  (make-topic
   :id "documentation-cluster-reading-order"
   :title "Documentation cluster reading order"
   :summary "Recommended reading sequence from installation context to conceptual framing, surface model, and operational authoring guidance."
   :references '("Documentation Architecture in HyperDoc"
                 "Installing Glamorous Toolkit"
                 "Glamorous Toolkit and HyperDoc"
                 "Reference Systems in HyperDoc"
                 "Documentation Surfaces in HyperDoc"
                 "Authoring Documentation in HyperDoc")))

(defun documentation-governance-topic ()
  (make-topic
   :id "documentation-governance"
   :title "Documentation governance"
   :summary "Governance model defining how durable pages, topic objects, inspectable handles, and optional FedWiki twins stay aligned without forced symmetry."
   :references '("Documentation Architecture in HyperDoc"
                 "Documentation Surfaces in HyperDoc"
                 "Authoring Documentation in HyperDoc"
                 "Reference Systems in HyperDoc")))

(defun hyperdoc-runtime-model-topic ()
  (make-topic
   :id "hyperdoc-runtime-model"
   :title "HyperDoc runtime model"
   :summary "Shared runtime vocabulary for pages, topics, inspectable objects, and linked collaboration surfaces in HyperDoc."
   :references '("HyperDoc Runtime Model"
                 "Documentation Architecture in HyperDoc"
                 "Documentation Surfaces in HyperDoc"
                 "Design")))

(defun hyperdoc-runtime-entities-topic ()
  (make-topic
   :id "hyperdoc-runtime-entities"
   :title "HyperDoc runtime entities"
   :summary "Core runtime entities include page objects, topic objects, inspectable links, inspector views, and linked page records."
   :references '("HyperDoc Runtime Model"
                 "Documentation Surfaces in HyperDoc"
                 "Authoring Documentation in HyperDoc"
                 "What is a moldable inspector?")))

(defun hyperdoc-runtime-boundaries-topic ()
  (make-topic
   :id "hyperdoc-runtime-boundaries"
   :title "HyperDoc runtime boundaries"
   :summary "Boundary model separating page narrative, topic semantics, inspector behavior, and FedWiki story/journal collaboration layers."
   :references '("HyperDoc Runtime Model"
                 "Reference Systems in HyperDoc"
                 "Documentation Surfaces in HyperDoc"
                 "FedWiki Page-Generation Workflow")))

(defun hyperdoc-routing-and-navigation-model-topic ()
  (make-topic
   :id "hyperdoc-routing-and-navigation-model"
   :title "HyperDoc routing and navigation model"
   :summary "Architectural model describing how HyperDoc resolves and opens local and remote page targets across contexts."
   :references '("HyperDoc Routing and Navigation Model"
                 "HyperDoc Runtime Model"
                 "Documentation Surfaces in HyperDoc"
                 "Design")))

(defun hyperdoc-navigation-targets-topic ()
  (make-topic
   :id "hyperdoc-navigation-targets"
   :title "HyperDoc navigation targets"
   :summary "Navigation target model distinguishing stable page keys/slugs from display titles across local and remote contexts."
   :references '("HyperDoc Routing and Navigation Model"
                 "HyperDoc Runtime Model"
                 "FedWiki Page-Generation Workflow"
                 "Documentation Surfaces in HyperDoc")))

(defun hyperdoc-routing-boundaries-topic ()
  (make-topic
   :id "hyperdoc-routing-boundaries"
   :title "HyperDoc routing boundaries"
   :summary "Boundary rules separating routing resolution, pane interaction behavior, and source-specific lookup responsibility."
   :references '("HyperDoc Routing and Navigation Model"
                 "HyperDoc Runtime Model"
                 "Documentation Surfaces in HyperDoc"
                 "Authoring Documentation in HyperDoc")))

(defun hyperdoc-evaluation-and-inspection-model-topic ()
  (make-topic
   :id "hyperdoc-evaluation-and-inspection-model"
   :title "HyperDoc evaluation and inspection model"
   :summary "Architectural model for expr evaluation, object inspection, and view rendering in HyperDoc."
   :references '("HyperDoc Evaluation and Inspection Model"
                 "HyperDoc Runtime Model"
                 "HyperDoc Routing and Navigation Model"
                 "What is a moldable inspector?")))

(defun hyperdoc-evaluation-boundaries-topic ()
  (make-topic
   :id "hyperdoc-evaluation-boundaries"
   :title "HyperDoc evaluation boundaries"
   :summary "Boundary rules separating value production, inspection behavior, page navigation, and debugging responsibility."
   :references '("HyperDoc Evaluation and Inspection Model"
                 "HyperDoc Runtime Model"
                 "Documentation Surfaces in HyperDoc"
                 "Design")))

(defun hyperdoc-view-selection-topic ()
  (make-topic
   :id "hyperdoc-view-selection"
   :title "HyperDoc view selection"
   :summary "View-selection model mapping evaluated objects to inspectable views through moldable inspector extension points."
   :references '("HyperDoc Evaluation and Inspection Model"
                 "What is a moldable inspector?"
                 "HyperDoc Runtime Model"
                 "Authoring Documentation in HyperDoc")))

(defun path-topic ()
  (make-topic
   :id "path"
   :title "Path"
   :summary "A path is a bounded inspectable transformation chain whose intermediate states and evidence are rendered from runtime object data rather than left as prose only."
   :references '("Path"
                 "State machine"
                 "HyperDoc Evaluation and Inspection Model"
                 "Inspectable authentication-path traces for repair console")))

(defun state-machine-topic ()
  (make-topic
   :id "state-machine"
   :title "State machine"
   :summary "A state machine is a reusable bounded transition object plus derived views for states, transitions, constraints, and one concrete run."
   :references '("State machine"
                 "Operational definition: state machine, state, transition, guard, run trace"
                 "HyperDoc Evaluation and Inspection Model"
                 "A framework for maintaining the coherence of a running Lisp"
                 "McDermott Running Image Coherence Crosswalk"
                 "Path"
                 "Inspectable authentication-path traces for repair console")))

(defun state-topic ()
  (make-topic
   :id "state"
   :title "State"
   :summary "A state is a named point in a bounded machine whose role, entry condition, exit condition, and evidence can be inspected directly."
   :references '("State"
                 "State machine"
                 "Operational definition: state machine, state, transition, guard, run trace"
                 "Path")))

(defun transition-topic ()
  (make-topic
   :id "transition"
   :title "Transition"
   :summary "A transition is an admissible move between named states, carrying trigger, guard, evidence, and side-effect information."
   :references '("Transition"
                 "State machine"
                 "Operational definition: state machine, state, transition, guard, run trace"
                 "Path")))

(defun guard-topic ()
  (make-topic
   :id "guard"
   :title "Guard"
   :summary "A guard is the explicit condition or support predicate that must hold for a transition to be taken."
   :references '("Guard"
                 "State machine"
                 "Operational definition: state machine, state, transition, guard, run trace"
                 "A framework for maintaining the coherence of a running Lisp")))

(defun event-topic ()
  (make-topic
   :id "event"
   :title "Event"
   :summary "An event is the named trigger or observed occurrence that drives a permitted transition through a state machine."
   :references '("Event"
                 "State machine"
                 "Operational definition: state machine, state, transition, guard, run trace"
                 "Path")))

(defun terminal-state-topic ()
  (make-topic
   :id "terminal-state"
   :title "Terminal state"
   :summary "A terminal state is an explicitly typed machine state where the bounded traversal is considered complete."
   :references '("Terminal state"
                 "State machine"
                 "Operational definition: state machine, state, transition, guard, run trace")))

(defun failure-state-topic ()
  (make-topic
   :id "failure-state"
   :title "Failure state"
   :summary "A failure state is an explicitly typed terminal branch recording unmet guards, violated constraints, or other named failure classifications."
   :references '("Failure state"
                 "State machine"
                 "Operational definition: state machine, state, transition, guard, run trace"
                 "McDermott Running Image Coherence Crosswalk")))

(defun state-machine-run-topic ()
  (make-topic
   :id "state-machine-run"
   :title "State-machine run"
   :summary "A concrete traversal of one reusable machine, keeping input, visited states, transition trace, evidence trace, and current status inspectable."
   :references '("State-machine run"
                 "State machine"
                 "Operational definition: state machine, state, transition, guard, run trace"
                 "HyperDoc Evaluation and Inspection Model"
                 "Inspectable authentication-path traces for repair console")))

(defun state-machine-trace-topic ()
  (make-topic
   :id "state-machine-trace"
   :title "State-machine trace"
   :summary "An ordered evidence-bearing account of one run, including visited states, taken or skipped transitions, timestamps, and failure boundaries."
   :references '("State-machine trace"
                 "State-machine run"
                 "State machine"
                 "Inspectable authentication-path traces for repair console"
                 "HyperDoc three-mode DMX auth crosswalk")))

(defun state-machine-visualization-topic ()
  (make-topic
   :id "state-machine-visualization"
   :title "State-machine visualization"
   :summary "Derived Graphviz, directed-graph, timeline, and transition-matrix views that render a machine definition or one run from the underlying object data."
   :references '("State-machine visualization"
                 "State machine"
                 "State-machine trace"
                 "HyperDoc Evaluation and Inspection Model"
                 "Path")))

(defun operational-definition-state-machine-state-transition-guard-run-trace-topic ()
  (make-topic
   :id "operational-definition-state-machine-state-transition-guard-run-trace"
   :title "Operational definition: state machine, state, transition, guard, run trace"
   :summary "Operational definition page that fixes the reusable definition/run split, typed state and transition roles, and evidence-bearing traversal model for HyperDoc state machines."
   :references '("Operational definition: state machine, state, transition, guard, run trace"
                 "State machine"
                 "Path"
                 "HyperDoc Evaluation and Inspection Model"
                 "A framework for maintaining the coherence of a running Lisp"
                 "McDermott Running Image Coherence Crosswalk")))

(defun vom-antisemitismus-der-keiner-sein-will-topic ()
  (make-topic
   :id "vom-antisemitismus-der-keiner-sein-will"
   :title "Vom Antisemitismus, der keiner sein will"
   :summary "Source argument page reconstructing Richard Schuberth's claim that anti-Israel discourse often presents itself as something other than antisemitism."
   :references '("Vom Antisemitismus, der keiner sein will"
                 "Ein paar Widersprüche des postkolonialen Denkens"
                 "Israel als Projektionsfläche"
                 "Wer will glückliche Palästinenser?"
                 "Palästinensische Stimmen gegen Projektion und Hamas")))

(defun antisemitism-debate-topic ()
  (make-topic
   :id "antisemitism-debate"
   :title "Antisemitism debate"
   :summary "Topic for the contested argument that contemporary anti-Israel discourse can function as disavowed antisemitism."
   :references '("Vom Antisemitismus, der keiner sein will"
                 "Israel als Projektionsfläche"
                 "Temporalismus")))

(defun postcolonial-critique-topic ()
  (make-topic
   :id "postcolonial-critique"
   :title "Postcolonial critique"
   :summary "Topic for Schuberth's critique of postcolonial discourse as identity-political, antiuniversalist, and prone to projection."
   :references '("Vom Antisemitismus, der keiner sein will"
                 "Ein paar Widersprüche des postkolonialen Denkens"
                 "Temporalismus")))

(defun universalism-topic ()
  (make-topic
   :id "universalism"
   :title "Universalism"
   :summary "Topic for the conflict between universalist standards and cultural-essentializing or identity-political frameworks in Schuberth's argument."
   :references '("Vom Antisemitismus, der keiner sein will"
                 "Ein paar Widersprüche des postkolonialen Denkens")))

(defun progress-and-modernity-topic ()
  (make-topic
   :id "progress-and-modernity"
   :title "Progress and modernity"
   :summary "Topic covering Schuberth's disputed use of developmental difference, modernity, and progress against postcolonial tabooing of such distinctions."
   :references '("Temporalismus"
                 "Ein paar Widersprüche des postkolonialen Denkens"
                 "Vom Antisemitismus, der keiner sein will")))

(defun double-standard-topic ()
  (make-topic
   :id "double-standard"
   :title "Double standard"
   :summary "Topic for Schuberth's claim that Israel is judged under a different moral and political standard than other actors or regimes."
   :references '("Temporalismus"
                 "Israel als Projektionsfläche"
                 "Vom Antisemitismus, der keiner sein will")))

(defun projection-topic ()
  (make-topic
   :id "projection"
   :title "Projection"
   :summary "Topic for the claim that Israel and Palestinians are turned into symbolic surfaces for external ideological needs."
   :references '("Ein paar Widersprüche des postkolonialen Denkens"
                 "Israel als Projektionsfläche"
                 "Wer will glückliche Palästinenser?"
                 "Vom Antisemitismus, der keiner sein will")))

(defun dehumanization-topic ()
  (make-topic
   :id "dehumanization"
   :title "Dehumanization"
   :summary "Topic for the argument that symbolic victimization can erase concrete Palestinian life and subjectivity."
   :references '("Wer will glückliche Palästinenser?"
                 "Palästinensische Stimmen gegen Projektion und Hamas"
                 "Vom Antisemitismus, der keiner sein will")))

(defun palestinian-subjectivity-topic ()
  (make-topic
   :id "palestinian-subjectivity"
   :title "Palestinian subjectivity"
   :summary "Topic for the contrast between symbolic Palestinian victim-figures and concrete Palestinian persons with divergent lives and views."
   :references '("Wer will glückliche Palästinenser?"
                 "Palästinensische Stimmen gegen Projektion und Hamas")))

(defun palestinian-dissent-topic ()
  (make-topic
   :id "palestinian-dissent"
   :title "Palestinian dissent"
   :summary "Topic for examples of Palestinian voices resisting Hamas or western projection frameworks in Schuberth's reconstruction."
   :references '("Palästinensische Stimmen gegen Projektion und Hamas"
                 "Wer will glückliche Palästinenser?"
                 "Vom Antisemitismus, der keiner sein will")))

(defun time-machine-backup-setup-topic ()
  (make-topic
   :id "time-machine-backup-setup"
   :title "Time Machine backup setup"
   :summary "Operational setup path for getting a working macOS Time Machine backup to a direct disk or SMB-capable NAS target."
   :references '("Time Machine Backup Setup"
                 "Time Machine Backup Troubleshooting"
                 "Time Machine Backup Verification"
                 "Time Machine Backup on Synology NAS")))

(defun time-machine-backup-troubleshooting-topic ()
  (make-topic
   :id "time-machine-backup-troubleshooting"
   :title "Time Machine backup troubleshooting"
   :summary "Diagnostic sequence for cases where a Time Machine destination is visible but backups do not start, stall, or fail."
   :references '("Time Machine Backup Troubleshooting"
                 "Time Machine Backup Setup"
                 "Time Machine Backup Verification"
                 "Time Machine Backup on Synology NAS")))

(defun time-machine-backup-verification-topic ()
  (make-topic
   :id "time-machine-backup-verification"
   :title "Time Machine backup verification"
   :summary "Checks for confirming that a configured Time Machine destination is producing usable backups rather than only appearing configured."
   :references '("Time Machine Backup Verification"
                 "Time Machine Backup Troubleshooting"
                 "Time Machine Backup Setup")))

(defun time-machine-backup-on-synology-nas-topic ()
  (make-topic
   :id "time-machine-backup-on-synology-nas"
   :title "Time Machine backup on Synology NAS"
   :summary "Synology-specific SMB and Bonjour setup path for exposing a shared folder as a Time Machine destination for macOS."
   :references '("Time Machine Backup on Synology NAS"
                 "Time Machine Backup Setup"
                 "Time Machine Backup Troubleshooting")))

(defun topics-hyperbook-in-hyperdoc-topic ()
  (make-topic
   :id "topics-hyperbook-in-hyperdoc"
   :title "Topics HyperBook in HyperDoc"
   :summary "HyperDoc topic objects are exposed as first-class pages in the Topics hyperbook, with internal topic-to-page relations derived from backlinks."
   :references '("Topics HyperBook in HyperDoc"
                 "Documentation Surfaces in HyperDoc"
                 "Authoring Documentation in HyperDoc"
                 "Documentation Architecture in HyperDoc")))

(defun demonstrating-dmx-topic-proxies-in-hyperdoc-topic ()
  (make-topic
   :id "demonstrating-dmx-topic-proxies-in-hyperdoc"
   :title "Demonstrating DMX Topic Proxies in HyperDoc"
   :summary "Clickable walkthrough showing how authored topic pages in HyperBook topics differ from live DMX-backed runtime proxy objects in the inspector."
   :references '("Concepts, DMX Topics, and Topic Maps"
                 "Topics HyperBook in HyperDoc"
                 "Documentation Surfaces in HyperDoc")))

(defun topic-factory-topic ()
  (make-topic
   :id "topic-factory"
   :title "Topic factory"
   :summary "An authored Lisp function that returns a topic object and serves as the durable reconstruction point for HyperDoc’s topic-page surface."
   :references '("Topic factory"
                 "Topics HyperBook in HyperDoc"
                 "Demonstrating DMX Topic Proxies in HyperDoc"
                 "Documentation Surfaces in HyperDoc")))

(defun authored-topic-factories-topic ()
  (make-topic
   :id "authored-topic-factories"
   :title "Authored topic factories"
   :summary "Authored topic-constructor functions currently living under hyperdoc/topics/ as the Lisp reconstruction layer for HyperDoc's topic-page surface, distinct from Dreyeck/DMX production topic persistence."
   :references '("Authored topic factories"
                 "Topic factory"
                 "Topics HyperBook in HyperDoc"
                 "Demonstrating DMX Topic Proxies in HyperDoc")))

(defun topic-backlinks-model-topic ()
  (make-topic
   :id "topic-backlinks-model"
   :title "Topic backlinks model"
   :summary "Authored page-to-topic links in HyperDoc generate automatic topic-to-page backlinks through the existing HyperBook link extraction and backlink machinery."
   :references '("Topics HyperBook in HyperDoc"
                 "HyperDoc Routing and Navigation Model"
                 "Documentation Surfaces in HyperDoc")))

(defun topic-editorial-references-topic ()
  (make-topic
   :id "topic-editorial-references"
   :title "Topic editorial references"
   :summary "Optional editorial references on topic objects remain reader-visible curated context and are distinct from automatically derived backlinks."
   :references '("Topics HyperBook in HyperDoc"
                 "Editorial References in Topic Pages"
                 "Authoring Documentation in HyperDoc"
                 "Documentation Surfaces in HyperDoc")))

(defun topic-title-changes-and-canonical-link-maintenance-topic ()
  (make-topic
   :id "topic-title-changes-and-canonical-link-maintenance"
   :title "Topic title changes and canonical link maintenance"
   :summary "Changing a topic title is also a link migration problem because canonical topic page ids are titles and authored topic links plus backlinks depend on exact title matches."
   :references '("Topic Title Changes and Canonical Link Maintenance"
                 "Topics HyperBook in HyperDoc"
                 "HyperDoc Routing and Navigation Model")))

(defun editorial-references-in-topic-pages-topic ()
  (make-topic
   :id "editorial-references-in-topic-pages"
   :title "Editorial references in topic pages"
   :summary "Editorial references remain optional reader-visible curated context, but they are no longer the primary mechanism for internal topic-to-page association."
   :references '("Editorial References in Topic Pages"
                 "Topics HyperBook in HyperDoc"
                 "Authoring Documentation in HyperDoc"
                 "Documentation Surfaces in HyperDoc")))

(defun tectonopedia-topic ()
  (make-topic
   :id "tectonopedia"
   :title "Tectonopedia"
   :summary "Reference encyclopedia in the Tectonic ecosystem whose content is technical documentation written in TeX and compiled into a web application."
   :references '("Tectonopedia"
                 "Tectonopedia and HyperDoc"
                 "Reference Systems in HyperDoc")))

(defun tectonopedia-and-hyperdoc-topic ()
  (make-topic
   :id "tectonopedia-and-hyperdoc"
   :title "Tectonopedia and HyperDoc"
   :summary "Comparison page positioning Tectonopedia as a reference system for documentation and publication architecture without equating it to HyperDoc."
   :references '("Tectonopedia and HyperDoc"
                 "Tectonopedia"
                 "Reference Systems in HyperDoc"
                 "Design")))

(defun tectonic-html-documentation-pipeline-topic ()
  (make-topic
   :id "tectonic-html-documentation-pipeline"
   :title "Tectonic HTML documentation pipeline"
   :summary "Pipeline in which TeX-authored documentation is compiled through Tectonic and Tectonopedia tooling into raw HTML and then bundled into a web application."
   :references '("Tectonopedia"
                 "Design"
                 "Reference Systems in HyperDoc")))

(defun tex-authored-web-documentation-topic ()
  (make-topic
   :id "tex-authored-web-documentation"
   :title "TeX-authored web documentation"
   :summary "Documentation model in which TeX source acts as the authoring substrate for navigable web-published technical documentation."
   :references '("Tectonopedia"
                 "Design"
                 "Tectonopedia and HyperDoc")))

(defun reference-encyclopedia-topic ()
  (make-topic
   :id "reference-encyclopedia"
   :title "Reference encyclopedia"
   :summary "Documentation system aimed at serving as an encyclopedic reference surface rather than only a linear narrative or static manual."
   :references '("Tectonopedia"
                 "Reference Systems in HyperDoc"
                 "Documentation Surfaces in HyperDoc")))

(defun asdf-systems-as-scope-topic ()
  (make-topic
   :id "asdf-systems-as-scope"
   :title "ASDF systems as scope"
   :summary "ASDF systems act as HyperDoc's primary scope objects because they are the named top-level build/load/test boundaries that group examples, code ownership, and test surfaces."
   :references '("Understanding ASDF Systems in HyperDoc"
                 "ASDF Systems, Examples, and Tests in HyperDoc"
                 "ASDF Components Workflow"
                 "Documentation Architecture in HyperDoc"
                 "HyperDoc Runtime Model")))

(defun scoped-examples-topic ()
  (make-topic
   :id "scoped-examples"
   :title "Scoped examples"
   :summary "HyperDoc examples belong to a specific ASDF system scope and are presented as exploratory runnable slices with first-class example-entry, example-result, and example-run objects."
   :references '("Understanding ASDF Systems in HyperDoc"
                 "ASDF Systems, Examples, and Tests in HyperDoc"
                 "Running HyperDoc Examples"
                 "Documentation Surfaces in HyperDoc"
                 "HyperDoc Runtime Model")))

(defun example-entry-topic ()
  (make-topic
   :id "example-entry"
   :title "Example entry"
   :summary "First-class descriptor for one loaded defexample registration, scoped by ASDF system and carrying selector, package, source file, source page, locator, tags, and optional class/group label."
   :references '("Running HyperDoc Examples"
                 "ASDF Systems, Examples, and Tests in HyperDoc"
                 "hyperdoc/check-runner.lisp"
                 "hyperdoc/example-core.lisp")))

(defun example-result-topic ()
  (make-topic
   :id "example-result"
   :title "Example result"
   :summary "Inspectable execution result for one example entry, preserving status, value, condition, backtrace, duration, assertions, and a source path derived from the entry metadata."
   :references '("Running HyperDoc Examples"
                 "ASDF Systems, Examples, and Tests in HyperDoc"
                 "HyperDoc Evaluation and Inspection Model"
                 "hyperdoc/check-runner.lisp")))

(defun example-source-reference-topic ()
  (make-topic
   :id "example-source-reference"
   :title "Example source reference"
   :summary "Source-navigation object derived from an example entry, resolving to a file source, persisted topic source artifact, or explicit unavailable diagnostic rather than the raw runtime function object."
   :references '("Running HyperDoc Examples"
                 "ASDF Systems, Examples, and Tests in HyperDoc"
                 "hyperdoc/check-runner.lisp"
                 "hyperdoc/example-source-artifacts.lisp"
                 "hyperdoc-explorer/check-runner.lisp")))

(defun example-source-artifact-topic ()
  (make-topic
   :id "example-source-artifact"
   :title "Example source artifact"
   :summary "Durable persisted source record for topic-backed examples, carrying topic identity, ASDF system, function symbol, locator, source language/form kind, source text, timestamps, and provenance for inspector and future LISP-CRITIC use."
   :references '("Running HyperDoc Examples"
                 "ASDF Systems, Examples, and Tests in HyperDoc"
                 "hyperdoc/example-source-artifacts.lisp"
                 "hyperdoc-explorer/check-runner.lisp")))

(defun example-run-topic ()
  (make-topic
   :id "example-run"
   :title "Example run"
   :summary "System-scoped batch object for running examples only, with example entries, example results, timestamps, and summary counts for executed, success, failure, error, skipped, and not-executed examples."
   :references '("Running HyperDoc Examples"
                 "ASDF Systems, Examples, and Tests in HyperDoc"
                 "FedWiki-attached ASDF system"
                 "hyperdoc/check-runner.lisp")))

(defun run-action-for-examples-topic ()
  (make-topic
   :id "run-action-for-examples"
   :title "Run action for examples"
   :summary "Example execution is a direct action on a scoped example surface, analogous to GT's per-example Run interaction, while preserving inspectable results."
   :references '("Understanding ASDF Systems in HyperDoc"
                 "ASDF Systems, Examples, and Tests in HyperDoc"
                 "Running HyperDoc Examples"
                 "HyperDoc Evaluation and Inspection Model"
                 "Glamorous Toolkit and HyperDoc")))

(defun portable-examples-topic ()
  (make-topic
   :id "portable-examples"
   :title "Portable examples"
   :summary "Examples that live in the separate system :hyperdoc/examples so they can remain reusable and unloaded until that portable example layer is explicitly requested."
   :references '("Portable examples in HyperDoc"
                 "ASDF Systems, Examples, and Tests in HyperDoc"
                 "Running HyperDoc Examples"
                 "Understanding ASDF Systems in HyperDoc")))

(defun portable-example-scope-topic ()
  (make-topic
   :id "portable-example-scope"
   :title "Portable example scope"
   :summary "The system-scoped discovery boundary for examples that belong to :hyperdoc/examples rather than to base :hyperdoc or the ops-specific :hyperdoc/examples/ops layer."
   :references '("Portable examples in HyperDoc"
                 "Running HyperDoc Examples"
                 "ASDF Systems, Examples, and Tests in HyperDoc")))

(defun example-system-boundary-topic ()
  (make-topic
   :id "example-system-boundary"
   :title "Example system boundary"
   :summary "The ASDF boundary that determines which example functions become discoverable for a given system and which example layers stay unloaded."
   :references '("Portable examples in HyperDoc"
                 "ASDF Systems, Examples, and Tests in HyperDoc"
                 "Understanding ASDF Systems in HyperDoc"
                 "Running HyperDoc Examples")))

(defun lazy-example-discovery-topic ()
  (make-topic
   :id "lazy-example-discovery"
   :title "Lazy example discovery"
   :summary "Example discovery should reflect the systems already loaded in the image, so portable and ops-specific examples remain absent until their owning systems are explicitly loaded."
   :references '("Portable examples in HyperDoc"
                 "Running HyperDoc Examples"
                 "ASDF Systems, Examples, and Tests in HyperDoc")))

(defun examples-system-layering-topic ()
  (make-topic
   :id "examples-system-layering"
   :title "Example system layering"
   :summary "The repo's example architecture is layered across base :hyperdoc examples, portable :hyperdoc/examples examples, and ops-specific :hyperdoc/examples/ops examples."
   :references '("Portable examples in HyperDoc"
                 "Running HyperDoc Examples"
                 "ASDF Systems, Examples, and Tests in HyperDoc"
                 "Understanding ASDF Systems in HyperDoc")))

(defun validation-surfaces-topic ()
  (make-topic
   :id "validation-surfaces"
   :title "Tests"
   :summary "User-facing test surfaces verify a system and should remain distinct from both exploratory examples and the root identity views of HyperDoc."
   :references '("Understanding ASDF Systems in HyperDoc"
                 "ASDF Systems, Examples, and Tests in HyperDoc"
                 "HyperDoc Test Runner"
                 "Documentation Surfaces in HyperDoc"
                 "HyperDoc Runtime Model")))

(defun hyperdoc-checks-runner-topic ()
  (make-topic
   :id "hyperdoc-checks-runner"
   :title "HyperDoc test runner"
   :summary "Legacy in-image runner boundary retained for current repository validation and compatibility while examples move to first-class example-entry, example-result, and example-run objects."
   :references '("Understanding ASDF Systems in HyperDoc"
                 "HyperDoc Test Runner"
                 "ASDF Systems, Examples, and Tests in HyperDoc"
                 "Running HyperDoc Examples"
                 "HyperDoc Evaluation and Inspection Model"
                 "HyperDoc Runtime Model")))

(defun check-spec-topic ()
  (make-topic
   :id "check-spec"
   :title "Check spec"
   :summary "A reusable runtime descriptor for one check, including its kind, stable identifier, human label, rerun locator, and optional grouping tags."
   :references '("HyperDoc Test Runner"
                 "ASDF Systems, Examples, and Tests in HyperDoc"
                 "Running HyperDoc Examples")))

(defun check-result-topic ()
  (make-topic
   :id "check-result"
   :title "Check result"
   :summary "An inspectable execution outcome for one check, including status, returned value or failure condition, captured backtrace, and duration."
   :references '("HyperDoc Test Runner"
                 "ASDF Systems, Examples, and Tests in HyperDoc"
                 "HyperDoc Evaluation and Inspection Model")))

(defun check-run-topic ()
  (make-topic
   :id "check-run"
   :title "Check run"
   :summary "A batch execution object that groups discovered checks, accumulates results, summarizes status counts, and supports rerun-failed workflows."
   :references '("HyperDoc Test Runner"
                 "ASDF Systems, Examples, and Tests in HyperDoc"
                 "HyperDoc Runtime Model"
                 "HyperDoc Evaluation and Inspection Model")))

(defun running-dmx-topic-proxy-smoke-tests-topic ()
  (make-topic
   :id "running-dmx-topic-proxy-smoke-tests"
   :title "Running DMX topic proxy smoke tests"
   :summary "Step-by-step procedure for running the focused DMX topic proxy smoke test from the HyperDoc dev shell."
   :references '("Running DMX Topic Proxy Smoke Tests"
                 "HyperDoc Test Runner"
                 "Running HyperDoc Examples"
                 "Demonstrating DMX Topic Proxies in HyperDoc")))

(defun dmx-topic-proxy-smoke-tests-topic ()
  (make-topic
   :id "dmx-topic-proxy-smoke-tests"
   :title "DMX topic proxy smoke tests"
   :summary "Focused smoke tests covering DMX topic proxy wrappers, topicmap helper handling, endpoint regression behavior, and the unknown-wrapper condition."
   :references '("Running DMX Topic Proxy Smoke Tests"
                 "Demonstrating DMX Topic Proxies in HyperDoc"
                 "HyperDoc Test Runner")))

(defun focused-test-runners-topic ()
  (make-topic
   :id "focused-test-runners"
   :title "Focused test runners"
   :summary "Direct test-entry commands used to run one narrow test slice without invoking the entire HyperDoc test suite."
   :references '("Running DMX Topic Proxy Smoke Tests"
                 "HyperDoc Test Runner"
                 "Running HyperDoc Examples"
                 "Documentation Architecture in HyperDoc")))
