;;;; HyperDoc authored topic family
;;;; Generated by splitting the former hyperdoc/topics.lisp monolith.

(in-package :hyperdoc)

(defun mobile-progressive-chrome-in-hyperdoc-topic ()
  (make-topic
   :id "mobile-progressive-chrome-in-hyperdoc"
   :title "Mobile progressive chrome in HyperDoc"
   :summary "Mobile HyperDoc behavior in which capabilities collapse behind )(, inspector tabs collapse behind a rotated )(, and route capture starts only after explicit Connect."
   :references '("Mobile progressive chrome in HyperDoc"
                 "Dock presentation state model"
                 "DM6 AppEmbed HyperDoc Inline Proof")))

(defun mobile-progressive-chrome-scxml-topic ()
  (make-topic
   :id "mobile-progressive-chrome-scxml"
   :title "Mobile progressive chrome SCXML"
   :summary "SCXML-like behavior model for the mobile capabilities layer, inspector-tabs layer, route-laying events, guards, and invariants."
   :references '("Mobile progressive chrome in HyperDoc"
                 "hyperdoc/mobile-progressive-chrome.scxml"
                 "Dock presentation state model")))

(defun mobile-progressive-chrome-plan-topic ()
  (make-topic
   :id "mobile-progressive-chrome-plan"
   :title "Mobile progressive chrome plan"
   :summary "SHOP3-like implementation plan recording task status, evidence paths, validation paths, and dependencies for mobile progressive chrome."
   :references '("Mobile progressive chrome in HyperDoc"
                 "Mobile progressive chrome SCXML"
                 "Dock presentation state model")))
