;;;; HyperDoc authored topic family
;;;; Generated by splitting the former hyperdoc/topics.lisp monolith.

(in-package :hyperdoc)

;; Source-station assimilation routine topics.
(defun source-station-assimilation-routine-topic ()
  (make-topic
   :id "source-station-assimilation-routine"
   :title "Source-station assimilation routine"
   :summary "Reusable routine for assimilating a source artifact into HyperDoc with bounded implementation, durable documentation, and replayable validation."
   :references '("Source-station assimilation routine"
                 "Lafont 1990 Interaction Nets"
                 "Focused semantic source stations")))

(defun intake-boundary-for-source-assimilation-topic ()
  (make-topic
   :id "intake-boundary-for-source-assimilation"
   :title "Intake boundary for source assimilation"
   :summary "Classification pass that separates primary source, implementation seed, notes, and generated artifacts while preserving source-truth boundaries."
   :references '("Source-station assimilation routine"
                 "Lafont 1990 Interaction Nets")))

(defun source-station-page-construction-topic ()
  (make-topic
   :id "source-station-page-construction"
   :title "Source-station page construction"
   :summary "Routine step that creates the source-station page with bibliography, core concepts, crosswalk, related pages, and explicit remaining gaps."
   :references '("Source-station assimilation routine"
                 "Lafont 1990 Interaction Nets"
                 "Authoring Documentation in HyperDoc")))

(defun topic-factory-assimilation-pass-topic ()
  (make-topic
   :id "topic-factory-assimilation-pass"
   :title "Topic-factory assimilation pass"
   :summary "Collision-checked topic-factory update that adds durable source, concept, implementation, and validation handles for the assimilation slice."
   :references '("Source-station assimilation routine"
                 "Authoring Documentation in HyperDoc")))

(defun implementation-seed-assimilation-topic ()
  (make-topic
   :id "implementation-seed-assimilation"
   :title "Implementation seed assimilation"
   :summary "Bounded code-assimilation step that places source-derived code in repo-native modules, preserves API continuity, hardens safety, and avoids completeness overclaims."
   :references '("Source-station assimilation routine"
                 "Lafont 1990 Interaction Nets"
                 "Interaction-net implementation seed")))

(defun assimilation-validation-matrix-topic ()
  (make-topic
   :id "assimilation-validation-matrix"
   :title "Assimilation validation matrix"
   :summary "Replayable validation checklist covering doc-slice checks, targeted smoke tests, broader smoke suites, and bounded reporting of external full-suite blockers."
   :references '("Source-station assimilation routine"
                 "Running DMX topic proxy smoke tests")))

(defun assimilation-handover-report-shape-topic ()
  (make-topic
   :id "assimilation-handover-report-shape"
   :title "Assimilation handover report shape"
   :summary "Standard report shape for assimilation slices: Surface Answer, Artifact Answer, reconstruction deltas, replay checks, and named blockers."
   :references '("Source-station assimilation routine"
                 "Source-oriented and image-oriented development in Common Lisp")))

(defun assimilation-acceptance-criteria-topic ()
  (make-topic
   :id "assimilation-acceptance-criteria"
   :title "Assimilation acceptance criteria"
   :summary "Completion criteria ensuring renderable source pages, collision-safe topics, loadable code, passing targeted tests, and explicit source/implementation boundaries."
   :references '("Source-station assimilation routine"
                 "Lafont 1990 Interaction Nets")))


;; Zettel 6537 / Advice Taker source-reader topics.

(defun read-zettel-6537-and-advice-taker-topic ()
  (make-topic
   :id "read-zettel-6537-and-advice-taker"
   :title "Read Zettel 6537 and Advice Taker"
   :summary "Plan-first source-reader slice that records SHOP3 task topics before reading authoritative Zettel 6537 file text, FedWiki projection/context, and the Advice Taker note through local-only reader surfaces."
   :references '("Read Zettel 6537 and Advice Taker"
                 "hyperdoc/read-zettel-6537-and-advice-taker-shop3-plan.sexp"
                 "Source-station assimilation routine"
                 "Focused semantic source stations")))

(defun source-reader-task-decomposition-topic ()
  (make-topic
   :id "source-reader-task-decomposition"
   :title "Source-reader task decomposition"
   :summary "SHOP3-shaped decomposition that requires plan artifact and explicit task-topic materialization before any source-reader implementation code is added."
   :references '("Read Zettel 6537 and Advice Taker"
                 "hyperdoc/read-zettel-6537-and-advice-taker-shop3-plan.sexp")))

(defun zettel-reader-topic ()
  (make-topic
   :id "zettel-reader"
   :title "Zettel reader"
   :summary "Read-only local projection/context reader that extracts Zettel evidence from the localhost FedWiki Physics, Not Advice page without treating that page as the authoritative Zettel text source."
   :references '("Read Zettel 6537 and Advice Taker"
                 "Physics, Not Advice")))

(defun implement-zettel-6537-zettelkasten-file-reader-topic ()
  (make-topic
   :id "implement-zettel-6537-zettelkasten-file-reader"
   :title "Implement Zettel 6537 Zettelkasten file reader"
   :summary "Follow-up SHOP3 task that adds the direct Zettelkasten-file reader only after materializing the authority/projection task topics and edges."
   :references '("Read Zettel 6537 and Advice Taker"
                 "hyperdoc/implement-zettel-6537-zettelkasten-file-reader-shop3-plan.sexp")))

(defun zettel-6537-topic ()
  (make-topic
   :id "zettel-6537"
   :title "Zettel 6537"
   :summary "Durable Zettel identity for the German planning passage whose authoritative text is read from configured local Zettelkasten file roots."
   :references '("Read Zettel 6537 and Advice Taker"
                 "hyperdoc/implement-zettel-6537-zettelkasten-file-reader-shop3-plan.sexp"
                 "Physics, Not Advice")))

(defun zettel-6537-zettelkasten-file-source-topic ()
  (make-topic
   :id "zettel-6537-zettelkasten-file-source"
   :title "Zettel 6537 Zettelkasten File Source"
   :summary "Authoritative local file source for Zettel 6537, located by filename through configured Zettelkasten roots or an explicit fixture root override."
   :references '("Read Zettel 6537 and Advice Taker"
                 "hyperdoc/implement-zettel-6537-zettelkasten-file-reader-shop3-plan.sexp"
                 "Zettelkasten note lookup for Zotero resolution")))

(defun zettelkasten-file-reader-topic ()
  (make-topic
   :id "zettelkasten-file-reader"
   :title "Zettelkasten file reader"
   :summary "Local-only note-file reader that locates a Zettel by filename under configured roots, reads UTF-8 text, and returns source identity, provenance, fragments, derived topics, and explicit failure state."
   :references '("Read Zettel 6537 and Advice Taker"
                 "Zettelkasten note lookup for Zotero resolution")))

(defun zettelkasten-file-source-authority-topic ()
  (make-topic
   :id "zettelkasten-file-source-authority"
   :title "Zettelkasten file source authority"
   :summary "Authority boundary stating that configured Zettelkasten files, not FedWiki projections, provide the canonical text for Zettel 6537 reader evidence."
   :references '("Read Zettel 6537 and Advice Taker"
                 "hyperdoc/implement-zettel-6537-zettelkasten-file-reader-shop3-plan.sexp")))

(defun zettel-6537-fedwiki-projection-topic ()
  (make-topic
   :id "zettel-6537-fedwiki-projection"
   :title "Zettel 6537 FedWiki Projection"
   :summary "Projection and interpretive bridge for Zettel 6537 through the localhost FedWiki Physics, Not Advice page."
   :references '("Read Zettel 6537 and Advice Taker"
                 "Physics, Not Advice")))

(defun zettel-6537-source-authority-reconciliation-topic ()
  (make-topic
   :id "zettel-6537-source-authority-reconciliation"
   :title "Zettel 6537 Source Authority Reconciliation"
   :summary "Boundary topic that reconciles the authoritative Zettelkasten file source with the FedWiki Physics, Not Advice projection/context bridge."
   :references '("Read Zettel 6537 and Advice Taker"
                 "hyperdoc/implement-zettel-6537-zettelkasten-file-reader-shop3-plan.sexp"
                 "Physics, Not Advice")))

(defun fedwiki-page-reader-topic ()
  (make-topic
   :id "fedwiki-page-reader"
   :title "FedWiki page reader"
   :summary "Read-only local reader for localhost FedWiki page JSON, returning source identity, provenance, story fragments, derived topics, and bounded failure state."
   :references '("Read Zettel 6537 and Advice Taker"
                 "Physics, Not Advice"
                 "Advice Taker")))

(defun advice-taker-note-reader-topic ()
  (make-topic
   :id "advice-taker-note-reader"
   :title "Advice Taker note reader"
   :summary "Read-only local reader for the Advice Taker FedWiki page and ASDF asset, reporting partial status when the transcript text is absent."
   :references '("Read Zettel 6537 and Advice Taker"
                 "Advice Taker")))

(defun zettel-6537-source-station-topic ()
  (make-topic
   :id "zettel-6537-source-station"
   :title "Zettel 6537 Source Station"
   :summary "Stable source-station handle for FedWiki-projected Zettel 6537 planning evidence; the authoritative text source is the Zettelkasten file source."
   :references '("Read Zettel 6537 and Advice Taker"
                 "Physics, Not Advice"
                 "Focused semantic source stations")))

(defun physics-not-advice-source-station-topic ()
  (make-topic
   :id "physics-not-advice-source-station"
   :title "Physics, Not Advice Source Station"
   :summary "Stable source station for the localhost FedWiki page physics-not-advice, used as the bridge between Zettel 6537, Advice Taker, PDDL, and planning-as-contingency-reduction."
   :references '("Read Zettel 6537 and Advice Taker"
                 "Physics, Not Advice")))

(defun advice-taker-source-station-topic ()
  (make-topic
   :id "advice-taker-source-station"
   :title "Advice Taker Source Station"
   :summary "Stable source station for the Advice Taker localhost FedWiki page and local ASDF topicmap asset."
   :references '("Read Zettel 6537 and Advice Taker"
                 "Advice Taker")))

(defun dmx-sqlite-task-topic-store-topic ()
  (make-topic
   :id "dmx-sqlite-task-topic-store"
   :title "DMX SQLite task-topic store"
   :summary "Dreyeck DMX SQLite mirror surface that stores the source-reader plan/task topic cluster under stable local ids for later inspection."
   :references '("Read Zettel 6537 and Advice Taker"
                 "hyperdoc/read-zettel-6537-and-advice-taker-shop3-plan.sexp")))

(defun source-reader-replay-validation-topic ()
  (make-topic
   :id "source-reader-replay-validation"
   :title "Source-reader replay validation"
   :summary "Replay contract for the Zettel 6537 and Advice Taker reader slice: local-only readers, idempotent task-topic materialization, parseable source artifacts, and no network requirement."
   :references '("Read Zettel 6537 and Advice Taker"
                 "Source-station assimilation routine")))


;; SIFT careers source-station topics.

(defun smart-information-flow-technologies-topic ()
  (make-topic
   :id "smart-information-flow-technologies"
   :title "Smart Information Flow Technologies"
   :summary "SIFT as presented in the pasted careers source: a Minneapolis-based research and development company with distributed staff and work across cyber, AI, NLP, planning, healthcare, supervisory control, and human-automation interaction."
   :references '("Smart Information Flow Technologies Careers"
                 "SIFT careers topic arrangement")))

(defun sift-careers-page-topic ()
  (make-topic
   :id "sift-careers-page"
   :title "SIFT careers page"
   :summary "Pasted SIFT careers source station that records role, skills, work-environment, eligibility, and equal-opportunity claims without treating them as a live job-board scrape."
   :references '("Smart Information Flow Technologies Careers"
                 "SIFT careers topic arrangement"
                 "Source-station assimilation routine")))

(defun sift-cyber-ai-nlp-roles-topic ()
  (make-topic
   :id "sift-cyber-ai-nlp-roles"
   :title "SIFT cyber AI and NLP roles"
   :summary "Role family in the pasted SIFT source covering Researcher, Associate Researcher, and Research Intern positions focused on Cyber, AI, and NLP."
   :references '("Smart Information Flow Technologies Careers"
                 "SIFT careers topic arrangement"
                 "Smart Information Flow Technologies")))

(defun sift-researcher-role-topic ()
  (make-topic
   :id "sift-researcher-role"
   :title "SIFT researcher role"
   :summary "Full-time Researcher role in the pasted SIFT source, requiring a Master's degree, Ph.D., or equivalent experience, advanced proficiency, and current high-need emphasis on binary analysis and NLP using BERT-like tools."
   :references '("Smart Information Flow Technologies Careers"
                 "SIFT cyber AI and NLP roles" "SIFT skills matrix")))

(defun sift-associate-researcher-role-topic ()
  (make-topic
   :id "sift-associate-researcher-role"
   :title "SIFT associate researcher role"
   :summary "Full-time Associate Researcher role in the pasted SIFT source, framed around a Bachelor's degree, advanced related-field proficiency, rapid learning, new language acquisition, and prototype production."
   :references '("Smart Information Flow Technologies Careers"
                 "SIFT cyber AI and NLP roles" "SIFT skills matrix")))

(defun sift-research-intern-role-topic ()
  (make-topic
   :id "sift-research-intern-role"
   :title "SIFT research intern role"
   :summary "Salaried internship role in the pasted SIFT source for graduate and advanced undergraduate students, typically 6-12 months, with design, implementation, evaluation, proposal, program-management, publication, and dissertation-relevant opportunities."
   :references '("Smart Information Flow Technologies Careers"
                 "SIFT cyber AI and NLP roles")))

(defun sift-interdisciplinary-rd-areas-topic ()
  (make-topic
   :id "sift-interdisciplinary-rd-areas"
   :title "SIFT interdisciplinary R&D areas"
   :summary "Research-and-development areas named in the pasted SIFT source: NLP, automated planning, cybersecurity, supervisory control, healthcare, and human-automation interaction."
   :references '("Smart Information Flow Technologies Careers"
                 "SIFT careers topic arrangement"
                 "Smart Information Flow Technologies")))

(defun sift-skills-matrix-topic ()
  (make-topic
   :id "sift-skills-matrix"
   :title "SIFT skills matrix"
   :summary "Skill matrix extracted from the pasted SIFT source, spanning engineering languages and web tooling, constraint and functional programming, AI planning, plan recognition, NLP, computational linguistics, machine learning, optimization, formal methods, control theory, HCI, UI, and simulation."
   :references '("Smart Information Flow Technologies Careers"
                 "SIFT careers topic arrangement")))

(defun sift-flexible-research-work-environment-topic ()
  (make-topic
   :id "sift-flexible-research-work-environment"
   :title "SIFT flexible research work environment"
   :summary "Work-environment claim in the pasted SIFT source: flexible hours, substantial home-office work, non-bureaucratic collaboration, and principal hiring locations in Minneapolis and Boston."
   :references '("Smart Information Flow Technologies Careers"
                 "SIFT careers topic arrangement"
                 "Smart Information Flow Technologies")))

(defun sift-employment-eligibility-restriction-topic ()
  (make-topic
   :id "sift-employment-eligibility-restriction"
   :title "SIFT employment eligibility restriction"
   :summary "Employment boundary in the pasted SIFT source stating that, due to contract work, SIFT positions are limited to United States citizens or permanent residents."
   :references '("Smart Information Flow Technologies Careers"
                 "SIFT careers topic arrangement")))
