;;;; HyperDoc authored topic family
;;;; Generated by splitting the former hyperdoc/topics.lisp monolith.

(in-package :hyperdoc)

;; Topic objects for the generic surface abstraction.
(defun surface-topic ()
  (make-topic
   :id "surface"
   :title "Surface"
   :summary "A bounded operational interface through which a user or robot can inspect, diagnose, act on, or publish some aspect of a HyperDoc-managed system."
   :references '("Surface"
                 "Documentation Surfaces in HyperDoc"
                 "Communication Surfaces Policy"
                 "Surface and Artifact Answers"
                 "Surface Answer"
                 "HyperDoc Evaluation and Inspection Model")))

(defun diagnostic-surface-topic ()
  (make-topic
   :id "diagnostic-surface"
   :title "Diagnostic surface"
   :summary "A read-only surface that preserves inspection, triage, and evidence without widening into mutation."
   :references '("Diagnostic surface"
                 "Surface"
                 "Diagnosing DMX workspace repair triage"
                 "DMX workspace journal model")))

(defun mutation-surface-topic ()
  (make-topic
   :id "mutation-surface"
   :title "Mutation surface"
   :summary "An action-bearing surface that performs bounded mutation while keeping its inputs, auth requirements, and adjacent diagnostic surfaces explicit."
   :references '("Mutation surface"
                 "Surface"
                 "Using authenticated workspace assignment repair console"
                 "Surface boundary")))

(defun failure-surface-topic ()
  (make-topic
   :id "failure-surface"
   :title "Failure surface"
   :summary "A first-class blocked or failure-oriented surface that preserves evidence, classification, and adjacent next-step surfaces instead of burying failure in prose."
   :references '("Failure surface"
                 "Surface"
                 "Diagnosing DMX workspace repair triage"
                 "DMX workspace journal reconcile call graph")))

(defun surface-boundary-topic ()
  (make-topic
   :id "surface-boundary"
   :title "Surface boundary"
   :summary "The explicit boundary rules that govern what one surface allows, what it forbids, and how it connects to adjacent surfaces without collapsing them together."
   :references '("Surface boundary"
                 "Surface"
                 "Documentation Surfaces in HyperDoc"
                 "Communication Surfaces Policy"
                 "Using authenticated workspace assignment repair console")))

(defun source-readable-view-contract-topic ()
  (make-topic
   :id "source-readable-view-contract"
   :title "Source readable view contract"
   :summary "Inspector contract that makes the default Source tab a plain readable file-content view, without source-v1 provider metadata."
   :references '("Make Alternate Source the Default Source View"
                 "Source pane layout evidence")))

(defun connect-source-view-topic ()
  (make-topic
   :id "connect-source-view"
   :title "Connect source view"
   :summary "Inspector contract for the explicit source-v1 source-line anchoring surface titled Connect source."
   :references '("Make Alternate Source the Default Source View"
                 "Source pane layout evidence"
                 "Dock capabilities in HyperDoc")))

(defun source-surface-strategy-contract-topic ()
  (make-topic
   :id "source-surface-strategy-contract"
   :title "Source surface strategy contract"
   :summary "Strategy abstraction that keeps plain and connect source surfaces inspectable, swappable, and diagnosable while plain is the default."
   :references '("Make Alternate Source the Default Source View"
                 "Source pane layout evidence")))

;; Topic objects for answer-surface distinction.
(defun surface-answer-topic ()
  (make-topic
   :id "surface-answer"
   :title "Surface Answer"
   :summary "Immediate terminal/Codex response that states the current result and decisions in the active session."
   :references '("Surface"
                 "Surface and Artifact Answers"
                 "Communication Surfaces Policy")))

(defun artifact-answer-topic ()
  (make-topic
   :id "artifact-answer"
   :title "Artifact Answer"
   :summary "Durable answer captured as HyperDoc/FedWiki/Lisp artifacts that can be replayed and inspected later."
   :references '("Surface and Artifact Answers"
                 "Communication Surfaces Policy")))

(defun reconstruction-protocol-topic ()
  (make-topic
   :id "reconstruction-protocol"
   :title "Reconstruction protocol"
   :summary "Protocol requiring each answer to include process trace, artifact deltas, and replay checks."
   :references '("Surface and Artifact Answers"
                 "Communication Surfaces Policy")))

(defun skillization-loop-topic ()
  (make-topic
   :id "skillization-loop"
   :title "Skillization loop"
   :summary "Recurring workflow extraction into callable Lisp/skill routines so repeated tasks move from ad-hoc execution to reusable runtime behavior."
   :references '("Surface and Artifact Answers"
                 "ASDF Components Workflow")))

(defun skillization-topic ()
  (make-topic
   :id "skillization"
   :title "Skillization"
   :summary "HyperDoc pattern that turns a recurring editorial move into durable pages, topic factories, inspectable definition objects, and narrow validation."
   :references '("Skillization in HyperDoc"
                 "Operational definition: skill pattern, conceptual center, discoverability propagation"
                 "Iconic route language in HyperDoc"
                 "Surface and Artifact Answers")))

(defun skill-pattern-topic ()
  (make-topic
   :id "skill-pattern"
   :title "Skill pattern"
   :summary "Reusable local documentation pattern with a fixed purpose, bounded slice shape, and stable acceptance rule."
   :references '("Skillization in HyperDoc"
                 "Operational definition: skill pattern, conceptual center, discoverability propagation")))

(defun ownership-extraction-with-compatibility-shell-topic ()
  (make-topic
   :id "ownership-extraction-with-compatibility-shell"
   :title "Ownership Extraction with Compatibility Shell"
   :summary "Refactoring pattern for moving situated project state out of a reusable substrate while leaving temporary compatibility coordinates behind."
   :references '("HyperDoc Core"
                 "Ownership Extraction with Compatibility Shell"
                 "Codex Belongs to Dreyeck"
                 "afa829b9 refactor(codex): move collaboration surface into dreyeck")))

(defun hyperdoc-core-topic ()
  (make-topic
   :id "hyperdoc-core"
   :title "HyperDoc core"
   :summary "Ownership boundary for Konrad Hinsen's upstream HyperDoc lineage and generic substrate patches, distinct from the local hyperdoc/ path and from Dreyeck-owned production topic storage."
   :references '("HyperDoc Core"
                 "Ownership Extraction with Compatibility Shell"
                 "Codex Belongs to Dreyeck"
                 "https://codeberg.org/khinsen/hyperdoc/"
                 "0d5bd1b0fba64f0bf9ab1cea21f01603c058f7cc")))

(defun conceptual-center-topic ()
  (make-topic
   :id "conceptual-center"
   :title "Conceptual center"
   :summary "First documentation slice that lands the local editorial center for a concept in HyperDoc's own language before propagation begins."
   :references '("Conceptual center in HyperDoc"
                 "Operational definition: skill pattern, conceptual center, discoverability propagation"
                 "Iconic route language in HyperDoc")))

(defun discoverability-propagation-topic ()
  (make-topic
   :id "discoverability-propagation"
   :title "Discoverability propagation"
   :summary "Second documentation slice that adds one-click orientation from adjacent surfaces to an already-landed conceptual center."
   :references '("Discoverability propagation in HyperDoc"
                 "Operational definition: skill pattern, conceptual center, discoverability propagation"
                 "Dock capabilities in HyperDoc"
                 "Dock presentation state model")))

(defun docs-only-propagation-slice-topic ()
  (make-topic
   :id "docs-only-propagation-slice"
   :title "Docs-only propagation slice"
   :summary "Conservative propagation slice that adds page-level discoverability cues without topic growth, runtime redesign, or hidden architecture changes."
   :references '("Discoverability propagation in HyperDoc"
                 "Operational definition: skill pattern, conceptual center, discoverability propagation"
                 "Dock capabilities in HyperDoc"
                 "Dock presentation state model")))

(defun architectural-drift-topic ()
  (make-topic
   :id "architectural-drift"
   :title "Architectural drift"
   :summary "Failure mode in which a narrow propagation slice quietly reopens architecture, runtime design, or fresh topic growth."
   :references '("Discoverability propagation in HyperDoc"
                 "Operational definition: skill pattern, conceptual center, discoverability propagation")))

(defun review-contract-topic ()
  (make-topic
   :id "review-contract"
   :title "Review contract"
   :summary "Durable declaration of the priorities, priors, comparison mode, burden of proof, rejection policy, and output shape for one review task."
   :references '("Inspectable review contracts for automated code review"
                 "Surface and Artifact Answers"
                 "Konrad Feedback on Communication Pages")))

(defun review-priorities-topic ()
  (make-topic
   :id "review-priorities"
   :title "Review priorities"
   :summary "Declared optimization weights for a review, such as clarity, inspectability, local convention fit, or performance."
   :references '("Inspectable review contracts for automated code review"
                 "Surface and Artifact Answers")))

(defun review-priors-topic ()
  (make-topic
   :id "review-priors"
   :title "Review priors"
   :summary "Declared assumptions brought into a review before reading the code, such as trusted-reference roles, candidate roles, or expected local patterns."
   :references '("Inspectable review contracts for automated code review"
                 "Surface and Artifact Answers")))

(defun comparison-mode-topic ()
  (make-topic
   :id "comparison-mode"
   :title "Comparison mode"
   :summary "Declared task relation between candidate and reference, distinguishing symmetric comparison from exemplar, pedagogical, or regression review."
   :references '("Inspectable review contracts for automated code review"
                 "Konrad Feedback on Communication Pages")))

(defun asymmetric-exemplar-review-topic ()
  (make-topic
   :id "asymmetric-exemplar-review"
   :title "Asymmetric exemplar review"
   :summary "Review mode in which a candidate is critiqued against a trusted exemplar under declared priors, rather than compared symmetrically in the abstract."
   :references '("Inspectable review contracts for automated code review"
                 "Konrad Feedback on Communication Pages")))

(defun lisp-critic-review-integration-plan-topic ()
  (make-topic
   :id "lisp-critic-review-integration-plan"
   :title "LISP-CRITIC review integration plan"
   :summary "First-class HyperDoc plan for integrating the FedWiki-sourced LISP-CRITIC asset into automated review contracts without executing or vendoring it in this slice."
   :references '("Integrate LISP-CRITIC into HyperDoc automated review"
                 "DITA-like task topics for LISP-CRITIC review integration"
                 "Inspectable review contracts for automated code review"
                 "Goldberg reading comprehension questions")))

(defun lisp-critic-review-task-decomposition-topic ()
  (make-topic
   :id "lisp-critic-review-task-decomposition"
   :title "LISP-CRITIC review task decomposition"
   :summary "DITA-like task topic decomposition and plan-task relation surface for the LISP-CRITIC review integration plan."
   :references '("DITA-like task topics for LISP-CRITIC review integration"
                 "Integrate LISP-CRITIC into HyperDoc automated review"
                 "Review contract"
                 "Goldberg reading comprehension questions")))

(defun lisp-critic-execution-adapter-contract-topic ()
  (make-topic
   :id "lisp-critic-execution-adapter-contract"
   :title "LISP-CRITIC execution adapter contract"
   :summary "Source-station-backed critic contract that invokes the local FedWiki LISP-CRITIC asset when available and records raw run evidence without normalizing findings."
   :references '("LISP-CRITIC execution adapter contract"
                 "Integrate LISP-CRITIC into HyperDoc automated review"
                 "DITA-like task topics for LISP-CRITIC review integration"
                 "Review contract")))

(defun programming-style-readability-problem-topic ()
  (make-topic
   :id "programming-style-readability-problem"
   :title "Programming style readability problem"
   :summary "Distinction between execution success and human readability: a program can run while still being hard to understand, criticize, rewrite, maintain, and learn from."
   :references '("Programming style readability problem"
                 "Goldberg Programmer as Reader"
                 "Kernighan Plauger critical reading plan"
                 "Critical reading to rewriting")))

(defun kernighan-plauger-critical-reading-topic ()
  (make-topic
   :id "kernighan-plauger-critical-reading"
   :title "Kernighan/Plauger critical reading"
   :summary "Base programming-style method: read a real program example critically, identify shortcomings, rewrite it for clarity, compare before and after, and extract a reusable style rule."
   :references '("Kernighan Plauger critical reading plan"
                 "Programming style readability problem"
                 "Critical reading to rewriting"
                 "Inspectable review contracts for automated code review")))

(defun critical-reading-rewriting-style-rule-topic ()
  (make-topic
   :id "critical-reading-rewriting-style-rule"
   :title "Critical reading to rewriting"
   :summary "Reader operation cycle that turns concrete program criticism into a clearer rewrite and then into a transferable programming-style lesson."
   :references '("Critical reading to rewriting"
                 "Kernighan Plauger critical reading plan"
                 "Programming style readability problem"
                 "Goldberg reader operations")))

(defun goldberg-long-recognized-problem-crosswalk-topic ()
  (make-topic
   :id "goldberg-long-recognized-problem-crosswalk"
   :title "Goldberg long recognized problem crosswalk"
   :summary "Crosswalk showing Goldberg's Programmer as Reader as an exploratory-environment restatement of the older program-readability problem."
   :references '("Goldberg long recognized problem crosswalk"
                 "Goldberg Programmer as Reader"
                 "Goldberg reader operations"
                 "Programming style readability problem")))

(defun knuth-web-projection-response-topic ()
  (make-topic
   :id "knuth-web-projection-response"
   :title "Knuth WEB as projection response"
   :summary "Crosswalk that treats WEB as a projection-oriented response: reader-order arrangement with a preserved machine-order projection, distinct from the Kernighan/Plauger base style-training cycle."
   :references '("Knuth WEB as projection response"
                 "How to Read a Web"
                 "How to Read a Web topic arrangement"
                 "Critical reading to rewriting")))

(defun codex-resume-branch-context-topic ()
  (make-topic
   :id "codex-resume-branch-context"
   :title "Codex resume branch context"
   :summary "Codex resume exposes the related git branch per session; interpret and replay session outputs in that branch context."
   :references '("Surface and Artifact Answers"
                 "Communication Surfaces Policy")))

(defun single-slice-codex-thread-topic ()
  (make-topic
   :id "single-slice-codex-thread"
   :title "Single-slice Codex thread"
   :summary "A Codex thread should carry exactly one active slice so scope, file boundaries, and validation assumptions stay stable."
   :references '("Codex handover for HyperDoc"
                 "Surface and Artifact Answers")))

(defun filled-task-slice-topic ()
  (make-topic
   :id "filled-task-slice"
   :title "Filled task slice"
   :summary "A usable Codex handover names a concrete task, exact scope, and exact validation path rather than leaving placeholders."
   :references '("Codex handover for HyperDoc"
                 "Authoring Documentation in HyperDoc")))

(defun prompt-local-slice-contract-topic ()
  (make-topic
   :id "prompt-local-slice-contract"
   :title "Prompt-local slice contract"
   :summary "Keep durable repo norms in AGENTS.md and use the prompt only for the current slice contract: task, file boundary, validation, and return shape."
   :references '("Codex handover for HyperDoc"
                 "Authoring Documentation in HyperDoc"
                 "Reconstruction protocol")))

(defun authoritative-nix-develop-validation-topic ()
  (make-topic
   :id "authoritative-nix-develop-validation"
   :title "Authoritative nix develop validation"
   :summary "When host-shell dependency loading fails, rerun the named validation inside nix develop and treat that result as authoritative unless host portability is the explicit goal."
   :references '("Codex handover for HyperDoc"
                 "Canonical docs-topic split and coverage gate workflow")))

(defun inventory-outcome-topic ()
  (make-topic
   :id "inventory-outcome"
   :title "Inventory outcome"
   :summary "Prompt field that specifies the required end-state page inventory, including the authoritative page count and the explicit policy for any retained continuity shell."
   :references '("Codex handover for HyperDoc"
                 "Authoring Documentation in HyperDoc")))

(defun continuity-shell-by-design-topic ()
  (make-topic
   :id "continuity-shell-by-design"
   :title "Continuity shell by design"
   :summary "When a canonical guidance page is retitled, keep at most one minimal non-authoritative forwarding page at the immediately previous canonical title if continuity still matters."
   :references '("Codex handover for HyperDoc"
                 "Best handover to Codex for HyperDoc"
                 "Authoring Documentation in HyperDoc")))

(defun exact-outcome-reporting-topic ()
  (make-topic
   :id "exact-outcome-reporting"
   :title "Exact outcome reporting"
   :summary "A completed Codex slice reports exact files changed, exact validation commands, exact outcomes, and remaining risks instead of generic completion language."
   :references '("Codex handover for HyperDoc"
                 "Surface and Artifact Answers"
                 "Reconstruction protocol")))

(defun path-sensitive-pre-commit-gate-topic ()
  (make-topic
   :id "path-sensitive-pre-commit-gate"
   :title "Path-sensitive pre-commit gate"
   :summary "Pre-commit validation should classify the staged HyperDoc slice before selecting either the light static-page gate or the full Lisp/Nix/server load gate."
   :references '("Codex commit hygiene and staging boundaries"
                 "Generate repo-native HyperDoc HTML"
                 "Authoring Documentation in HyperDoc")))

(defun static-hyperdoc-html-page-gate-topic ()
  (make-topic
   :id "static-hyperdoc-html-page-gate"
   :title "Static HyperDoc HTML page gate"
   :summary "The light page gate is limited to direct staged hyperdoc/*.html additions or edits with repo-native page shape and no executable or runtime markers."
   :references '("Codex commit hygiene and staging boundaries"
                 "Generate repo-native HyperDoc HTML"
                 "Authoring Documentation in HyperDoc")))

(defun executable-hyperdoc-html-page-gate-topic ()
  (make-topic
   :id "executable-hyperdoc-html-page-gate"
   :title "Executable HyperDoc HTML page gate"
   :summary "HyperDoc HTML that embeds executable expressions, generated source references, scripts, or loader/runtime behavior must take the full load gate until a stronger page-runtime gate exists."
   :references '("Codex commit hygiene and staging boundaries"
                 "Generate repo-native HyperDoc HTML"
                 "Authoring Documentation in HyperDoc")))

(defun docs-topic-slice-and-coverage-gate-workflow-topic ()
  (make-topic
   :id "docs-topic-slice-and-coverage-gate-workflow"
   :title "Docs/topic slice and coverage-gate workflow"
   :summary "Canonical maintenance workflow: split docs/topic work into atomic commits and replay topic-coverage checks at commit boundaries."
   :references '("Canonical docs-topic split and coverage gate workflow"
                 "Surface and Artifact Answers"
                 "Reconstruction protocol")))

(defun hyperdoc-operating-environment-assessment-2026-03-06-topic ()
  (make-topic
   :id "hyperdoc-operating-environment-assessment-2026-03-06"
   :title "HyperDoc Operating Environment Assessment 2026-03-06"
   :summary "Assessment that frames HyperDoc as a documented operating environment with explicit maintenance doctrine, highlights three-surface drift risk, and recommends stronger semantic indexing and routine smoke checks."
   :references '("HyperDoc Operating Environment Assessment 2026-03-06"
                 "Communication Surfaces Policy"
                 "ASDF Components Workflow"
                 "HyperDoc Server"
                 "Stepper Debugger Surface"
                 "Diagramming Debugger Surface")))

(defun violated-handoff-topic ()
  (make-topic
   :id "violated-handoff"
   :title "Violated handoff"
   :summary "A handoff is violated when a claimed completed transfer lacks the artifacts, links, or replay checks needed for the receiver to continue without re-deriving context."
   :references '("Surface and Artifact Answers"
                 "Communication Surfaces Policy"
                 "Reconstruction protocol")))

(defun express-both-sides-of-handoff-without-manually-reversing-perspective-topic ()
  (make-topic
   :id "express-both-sides-handoff-without-manually-reversing-perspective"
   :title "Express both sides of a handoff without manually reversing perspective"
   :summary "Model a handoff as one inspectable relation object that exposes producer output and consumer precondition simultaneously, avoiding perspective-flip narration."
   :references '("Violated handoff"
                 "SD-image zstd-to-img handoff defect"
                 "Reconstruction protocol")))

(defun prose-to-object-bridge-topic ()
  (make-topic
   :id "prose-to-object-bridge"
   :title "Prose to object bridge"
   :summary "Operational claims in prose should expose clickable inspectable objects so execution and replay can start from semantic objects, not raw structure."
   :references '("Surface and Artifact Answers"
                 "Create NixOS SD Card from HyperDoc Playground"
                 "Communication Surfaces Policy")))

(defun display-argument-removal-topic ()
  (make-topic
   :id "display-argument-removal"
   :title "Remove :display argument"
   :summary "Remove explicit :display overrides and rely on each object's text representation for consistent semantic navigation labels."
   :references '("Surface and Artifact Answers"
                 "Writing text pages"
                 "Defining custom views")))

(defun semantic-object-ref-renderer-topic ()
  (make-topic
   :id "semantic-object-ref-renderer"
   :title "Semantic object-ref renderer"
   :summary "Confirmed: the SD-card command-plan renderer uses semantic object-ref links for navigation, with raw structure kept as diagnostics-only."
   :references '("Create NixOS SD Card from HyperDoc Playground"
                 "Surface and Artifact Answers"
                 "sd-card-primary-semantic-entrypoints-example")))
