;;;; HyperDoc authored topic family
;;;; Generated by splitting the former hyperdoc/topics.lisp monolith.

(in-package :hyperdoc)

(defun make-winston-and-horn-topic (id title summary)
  (make-topic
   :id id
   :title title
   :summary summary
   :references '("Winston and Horn Lisp (1989)"
                 "Winston and Horn Lisp topic arrangement"
                 "Definitive Common Lisp Books")))

(defun understanding-symbol-manipulation-topic ()
  (make-winston-and-horn-topic
   "understanding-symbol-manipulation"
   "Understanding Symbol Manipulation"
   "Introduction to symbolic processing in Common Lisp, covering core list and tree thinking, common myths about Lisp, and the book's target dialect."))

(defun basic-lisp-primitives-topic ()
  (make-winston-and-horn-topic
   "basic-lisp-primitives"
   "Basic Lisp Primitives"
   "Basic evaluation and data-building primitives such as quoting, list construction, assignment, and numeric operations."))

(defun procedure-definition-and-binding-topic ()
  (make-winston-and-horn-topic
   "procedure-definition-and-binding"
   "Procedure Definition and Binding"
   "Procedure definition with DEFUN plus local binding forms such as LET and LET* and their effect on parameter scope."))

(defun predicates-and-conditionals-topic ()
  (make-winston-and-horn-topic
   "predicates-and-conditionals"
   "Predicates and Conditionals"
   "Boolean predicates and conditional forms including IF, WHEN, UNLESS, COND, and CASE as tools for problem reduction."))

(defun procedure-abstraction-and-recursion-topic ()
  (make-winston-and-horn-topic
   "procedure-abstraction-and-recursion"
   "Procedure Abstraction and Recursion"
   "Procedure decomposition and recursive structure, including optional, rest, key, and aux parameters."))

(defun data-abstraction-and-mapping-topic ()
  (make-winston-and-horn-topic
   "data-abstraction-and-mapping"
   "Data Abstraction and Mapping"
   "Data-abstraction style and mapping-oriented list processing with functions such as MAPCAR, REMOVE-IF, COUNT-IF, and FIND-IF."))

(defun iteration-on-numbers-and-lists-topic ()
  (make-winston-and-horn-topic
   "iteration-on-numbers-and-lists"
   "Iteration on Numbers and Lists"
   "Iteration constructs for numeric and list traversals including DOLIST, DOTIMES, DO, LOOP, PROG1, and PROGN."))

(defun file-editing-compiling-and-loading-topic ()
  (make-winston-and-horn-topic
   "file-editing-compiling-and-loading"
   "File Editing, Compiling, and Loading"
   "Basic Lisp development workflow around editing source, compiling files, and loading systems into a running image."))

(defun printing-and-reading-topic ()
  (make-winston-and-horn-topic
   "printing-and-reading"
   "Printing and Reading"
   "The reader and printer model, including strings, streams, FORMAT, and READ as the I/O surface of Common Lisp."))

(defun rules-for-good-programming-and-tools-for-debugging-topic ()
  (make-winston-and-horn-topic
   "rules-for-good-programming-and-tools-for-debugging"
   "Rules for Good Programming and Tools for Debugging"
   "Programming style rules paired with debugging and inspection tools such as TRACE, STEP, BREAK, TIME, DESCRIBE, and DRIBBLE."))

(defun properties-and-arrays-topic ()
  (make-winston-and-horn-topic
   "properties-and-arrays"
   "Properties and Arrays"
   "Property lists and arrays as alternative storage structures with constructors, readers, and writers."))

(defun macros-and-backquote-topic ()
  (make-winston-and-horn-topic
   "macros-and-backquote"
   "Macros and Backquote"
   "Macro definition and backquote notation for building source transformations and reusable syntactic extensions."))

(defun structures-topic ()
  (make-winston-and-horn-topic
   "structures"
   "Structures"
   "Structured records and accessors as a practical data-abstraction technique."))

(defun classes-and-generic-functions-topic ()
  (make-winston-and-horn-topic
   "classes-and-generic-functions"
   "Classes and Generic Functions"
   "CLOS introduction through classes, generic functions, methods, inheritance, and precedence."))

(defun lexical-variables-generators-and-encapsulation-topic ()
  (make-winston-and-horn-topic
   "lexical-variables-generators-and-encapsulation"
   "Lexical Variables, Generators, and Encapsulation"
   "Lexical scope, closures, and generator-style procedures used to encapsulate state and behavior."))

(defun special-variables-topic ()
  (make-winston-and-horn-topic
   "special-variables"
   "Special Variables"
   "Dynamically scoped variables, DEFVAR, and the runtime behavior of special bindings."))

(defun list-storage-surgery-and-reclamation-topic ()
  (make-winston-and-horn-topic
   "list-storage-surgery-and-reclamation"
   "List Storage, Surgery, and Reclamation"
   "Box-and-pointer list structure, destructive updates, and garbage collection."))

(defun lisp-in-lisp-topic ()
  (make-winston-and-horn-topic
   "lisp-in-lisp"
   "Lisp in Lisp"
   "Meta-circular interpretation themes such as environments, call-by-value evaluation, and implementing Lisp mechanisms in Lisp."))

(defun examples-involving-search-topic ()
  (make-winston-and-horn-topic
   "examples-involving-search"
   "Examples Involving Search"
   "Comparative search examples covering breadth-first, depth-first, best-first, hill-climbing, branch-and-bound, beam search, and queens problems."))

(defun examples-involving-simulation-topic ()
  (make-winston-and-horn-topic
   "examples-involving-simulation"
   "Examples Involving Simulation"
   "Simulation examples built around task, event, and PERT-style modeling."))

(defun the-blocks-world-with-classes-and-methods-topic ()
  (make-winston-and-horn-topic
   "the-blocks-world-with-classes-and-methods"
   "The Blocks World with Classes and Methods"
   "Blocks-world example using classes, methods, before and after behavior, printed instances, and automatic procedure assembly."))

(defun answering-questions-about-goals-topic ()
  (make-winston-and-horn-topic
   "answering-questions-about-goals"
   "Answering Questions about Goals"
   "Goal-tree examples for answering how, why, and when questions about planned behavior."))

(defun constraint-propagation-topic ()
  (make-winston-and-horn-topic
   "constraint-propagation"
   "Constraint Propagation"
   "Arithmetic and logical constraint propagation as a problem-solving style."))

(defun symbolic-pattern-matching-topic ()
  (make-winston-and-horn-topic
   "symbolic-pattern-matching"
   "Symbolic Pattern Matching"
   "Pattern matching and abstraction boundaries around symbolic matching procedures."))

(defun streams-and-delayed-evaluation-topic ()
  (make-winston-and-horn-topic
   "streams-and-delayed-evaluation"
   "Streams and Delayed Evaluation"
   "Lazy stream processing through delayed evaluation and encapsulation."))

(defun rule-based-expert-systems-and-forward-chaining-topic ()
  (make-winston-and-horn-topic
   "rule-based-expert-systems-and-forward-chaining"
   "Rule-Based Expert Systems and Forward Chaining"
   "Forward-chaining expert-system style rule execution."))

(defun backward-chaining-and-prolog-topic ()
  (make-winston-and-horn-topic
   "backward-chaining-and-prolog"
   "Backward Chaining and PROLOG"
   "Backward chaining and PROLOG-style query reasoning."))

(defun interpreting-transition-trees-topic ()
  (make-winston-and-horn-topic
   "interpreting-transition-trees"
   "Interpreting Transition Trees"
   "Execution model for interpreting transition-tree structures."))

(defun compiling-transition-trees-topic ()
  (make-winston-and-horn-topic
   "compiling-transition-trees"
   "Compiling Transition Trees"
   "Compilation strategies for turning transition trees into faster executable procedures."))

(defun procedure-writing-programs-and-database-interfaces-topic ()
  (make-winston-and-horn-topic
   "procedure-writing-programs-and-database-interfaces"
   "Procedure-Writing Programs and Database Interfaces"
   "Procedure synthesis examples combined with natural-language and database interface work."))

(defun finding-patterns-in-images-topic ()
  (make-winston-and-horn-topic
   "finding-patterns-in-images"
   "Finding Patterns in Images"
   "Image-oriented pattern matching and geometric constraint examples."))

(defun converting-notations-manipulating-matrices-and-finding-roots-topic ()
  (make-winston-and-horn-topic
   "converting-notations-manipulating-matrices-and-finding-roots"
   "Converting Notations, Manipulating Matrices, and Finding Roots"
   "Notation translation, sparse matrices, complex numbers, and polynomial root finding."))

(defun the-computation-of-the-class-precedence-list-topic ()
  (make-winston-and-horn-topic
   "the-computation-of-the-class-precedence-list"
   "The Computation of the Class Precedence List"
   "Appendix topic on computing the class precedence list within the object system."))

(defun symbol-manipulation-topic ()
  (make-winston-and-horn-topic
   "symbol-manipulation"
   "Symbol manipulation"
   "Symbolic expression handling tradition the book uses as the entry point to Lisp programming."))

(defun procedure-abstraction-topic ()
  (make-winston-and-horn-topic
   "procedure-abstraction"
   "Procedure abstraction"
   "Breaking programs into reusable procedures with explicit interfaces and decomposed control flow."))

(defun data-abstraction-topic ()
  (make-winston-and-horn-topic
   "data-abstraction"
   "Data abstraction"
   "Separating representation from use so programs can evolve without rewriting all callers."))

(defun programming-cliche-topic ()
  (make-winston-and-horn-topic
   "programming-cliche"
   "Programming cliché"
   "Reusable small-scale programming pattern taught as a practical design aid."))

(defun mapping-primitive-topic ()
  (make-winston-and-horn-topic
   "mapping-primitive"
   "Mapping primitive"
   "Common Lisp higher-order list-processing operator such as MAPCAR, REMOVE-IF, COUNT-IF, or FIND-IF."))

(defun generic-function-topic ()
  (make-winston-and-horn-topic
   "generic-function"
   "Generic function"
   "CLOS dispatch entry point that separates operation names from class-specific methods."))

(defun method-inheritance-topic ()
  (make-winston-and-horn-topic
   "method-inheritance"
   "Method inheritance"
   "Reuse and precedence behavior of methods across CLOS class hierarchies."))

(defun lexical-closure-topic ()
  (make-winston-and-horn-topic
   "lexical-closure"
   "Lexical closure"
   "Procedure paired with its captured lexical environment to encapsulate state or delayed computation."))

(defun special-variable-topic ()
  (make-winston-and-horn-topic
   "special-variable"
   "Special variable"
   "Dynamically scoped binding used for process-wide or context-wide configuration."))

(defun garbage-collection-topic ()
  (make-winston-and-horn-topic
   "garbage-collection"
   "Garbage collection"
   "Runtime reclamation of unreachable storage after list surgery or ordinary allocation."))

(defun search-strategy-topic ()
  (make-winston-and-horn-topic
   "search-strategy"
   "Search strategy"
   "Generic frame for the book's comparative search procedures and heuristics."))

(defun constraint-propagation-concept-topic ()
  (make-winston-and-horn-topic
   "constraint-propagation-concept"
   "Constraint propagation"
   "Computation model that narrows possibilities by passing local constraints through a network."))

(defun symbolic-pattern-matching-concept-topic ()
  (make-winston-and-horn-topic
   "symbolic-pattern-matching-concept"
   "Symbolic pattern matching"
   "Matching symbolic structures against templates to drive transformations or reasoning."))

(defun unification-topic ()
  (make-winston-and-horn-topic
   "unification"
   "Unification"
   "Stronger form of symbolic matching that solves the bindings needed to make structures agree."))

(defun stream-topic ()
  (make-winston-and-horn-topic
   "stream"
   "Stream"
   "Delayed sequence interface used to compute values incrementally."))

(defun delayed-evaluation-topic ()
  (make-winston-and-horn-topic
   "delayed-evaluation"
   "Delayed evaluation"
   "Technique for deferring computation until requested, supporting streams and controlled work expansion."))

(defun forward-chaining-topic ()
  (make-winston-and-horn-topic
   "forward-chaining"
   "Forward chaining"
   "Rule-execution style that starts from available facts and derives new consequences."))

(defun backward-chaining-topic ()
  (make-winston-and-horn-topic
   "backward-chaining"
   "Backward chaining"
   "Goal-directed rule or query style that works backward from a target proposition."))

(defun transition-tree-topic ()
  (make-winston-and-horn-topic
   "transition-tree"
   "Transition tree"
   "Decision or state-transition structure used for interpretation or compilation."))

(defun natural-language-interface-topic ()
  (make-winston-and-horn-topic
   "natural-language-interface"
   "Natural-language interface"
   "Procedure or rule layer that maps user-language inputs onto structured commands or queries."))

(defun class-precedence-list-topic ()
  (make-winston-and-horn-topic
   "class-precedence-list"
   "Class precedence list"
   "Ordered CLOS class linearization used to resolve inheritance and method lookup."))

