;;;; Source-backed Git commit inspection objects.
;;;; Created from SLY MREPL; reload this file instead of redefining ad hoc.


(IN-PACKAGE :HYPERDOC)


(DEFINE-CONDITION GIT-COMMAND-FAILED
    (ERROR)
    ((REPOSITORY-ROOT :READER GIT-COMMAND-FAILED-REPOSITORY-ROOT-OF :INITARG
      :REPOSITORY-ROOT)
     (ARGUMENTS :READER GIT-COMMAND-FAILED-ARGUMENTS-OF :INITARG :ARGUMENTS)
     (EXIT-CODE :READER GIT-COMMAND-FAILED-EXIT-CODE-OF :INITARG :EXIT-CODE)
     (STDOUT :READER GIT-COMMAND-FAILED-STDOUT-OF :INITARG :STDOUT)
     (STDERR :READER GIT-COMMAND-FAILED-STDERR-OF :INITARG :STDERR))
  (:REPORT
   (LAMBDA (CONDITION STREAM)
     (FORMAT STREAM
             "Git command failed in ~A: git ~{~A~^ ~} exited with ~D.~%~A"
             (GIT-COMMAND-FAILED-REPOSITORY-ROOT-OF CONDITION)
             (GIT-COMMAND-FAILED-ARGUMENTS-OF CONDITION)
             (GIT-COMMAND-FAILED-EXIT-CODE-OF CONDITION)
             (GIT-COMMAND-FAILED-STDERR-OF CONDITION)))))


(DEFUN GIT-RUN-STRING (REPOSITORY-ROOT &REST ARGUMENTS)
  "Run git command ARGUMENTS in REPOSITORY-ROOT and return stdout."
  (MULTIPLE-VALUE-BIND (STDOUT STDERR EXIT-CODE)
      (UIOP/RUN-PROGRAM:RUN-PROGRAM (CONS "git" ARGUMENTS) :DIRECTORY
                                    REPOSITORY-ROOT :OUTPUT :STRING
                                    :ERROR-OUTPUT :STRING :IGNORE-ERROR-STATUS
                                    T)
    (UNLESS (ZEROP EXIT-CODE)
      (ERROR 'GIT-COMMAND-FAILED :REPOSITORY-ROOT REPOSITORY-ROOT :ARGUMENTS
             ARGUMENTS :EXIT-CODE EXIT-CODE :STDOUT STDOUT :STDERR STDERR))
    STDOUT))


(DEFUN TRIM-GIT-OUTPUT (STRING)
  (STRING-TRIM '(#\  #\Tab #\Newline #\Return) STRING))


(DEFCLASS GIT-COMMIT NIL
          ((REPOSITORY :READER GIT-COMMIT-REPOSITORY-OF :INITARG :REPOSITORY)
           (COMMIT-ISH :READER GIT-COMMIT-ISH-OF :INITARG :COMMIT-ISH :INITFORM
            "HEAD" :TYPE STRING)
           (HASH :READER GIT-COMMIT-HASH-OF :INITARG :HASH :TYPE STRING))
          (:DOCUMENTATION
           "Source-backed object representing a Git commit in the live HyperDoc checkout."))


(DEFMETHOD PRINT-OBJECT ((COMMIT GIT-COMMIT) STREAM)
  (PRINT-UNREADABLE-OBJECT (COMMIT STREAM :TYPE T :IDENTITY NIL)
    (FORMAT STREAM "~A"
            (SUBSEQ (GIT-COMMIT-HASH-OF COMMIT) 0
                    (MIN 12 (LENGTH (GIT-COMMIT-HASH-OF COMMIT)))))))


(DEFVAR *LAST-INSPECTED-GIT-COMMIT* NIL)


(DEFUN MAKE-GIT-COMMIT
       (
        &KEY (REPOSITORY (CURRENT-GIT-REPOSITORY-CHECKOUT))
        (COMMIT-ISH "HEAD"))
  "Resolve COMMIT-ISH in REPOSITORY and return a GIT-COMMIT object."
  (LET* ((REPO-ROOT (GIT-REPOSITORY-ROOT-OF REPOSITORY))
         (HASH
          (TRIM-GIT-OUTPUT (GIT-RUN-STRING REPO-ROOT "rev-parse" COMMIT-ISH))))
    (MAKE-INSTANCE 'GIT-COMMIT :REPOSITORY REPOSITORY :COMMIT-ISH COMMIT-ISH
                   :HASH HASH)))


(DEFUN CURRENT-HEAD-GIT-COMMIT ()
  "Return an inspectable object for HEAD in the current HyperDoc checkout."
  (SETF *LAST-INSPECTED-GIT-COMMIT* (MAKE-GIT-COMMIT :COMMIT-ISH "HEAD")))


(DEFUN GIT-COMMIT-ONE-LINE (COMMIT)
  (GIT-RUN-STRING (GIT-REPOSITORY-ROOT-OF (GIT-COMMIT-REPOSITORY-OF COMMIT))
   "show" "--no-patch" "--oneline" "--decorate" "--no-color"
   (GIT-COMMIT-HASH-OF COMMIT)))


(DEFUN GIT-COMMIT-METADATA (COMMIT)
  (GIT-RUN-STRING (GIT-REPOSITORY-ROOT-OF (GIT-COMMIT-REPOSITORY-OF COMMIT))
   "show" "--no-patch" "--format=fuller" "--no-color"
   (GIT-COMMIT-HASH-OF COMMIT)))


(DEFUN GIT-COMMIT-STAT (COMMIT)
  (GIT-RUN-STRING (GIT-REPOSITORY-ROOT-OF (GIT-COMMIT-REPOSITORY-OF COMMIT))
   "show" "--stat" "--oneline" "--no-color" (GIT-COMMIT-HASH-OF COMMIT)))


(DEFUN GIT-COMMIT-PATCH (COMMIT)
  (GIT-RUN-STRING (GIT-REPOSITORY-ROOT-OF (GIT-COMMIT-REPOSITORY-OF COMMIT))
   "show" "--stat" "--patch" "--no-color" (GIT-COMMIT-HASH-OF COMMIT)))


(DEFUN GIT-COMMIT-CHANGED-FILES (COMMIT)
  (LET ((OUTPUT
         (GIT-RUN-STRING
          (GIT-REPOSITORY-ROOT-OF (GIT-COMMIT-REPOSITORY-OF COMMIT)) "show"
          "--name-status" "--format=" "--no-color"
          (GIT-COMMIT-HASH-OF COMMIT))))
    (REMOVE "" (UIOP/UTILITY:SPLIT-STRING OUTPUT :SEPARATOR '(#\Newline)) :TEST
            #'STRING=)))

