
(:KIND :SHOP3-HTN-PLAN :NAME READ-THROUGH-ZETTEL-6537 :DOMAIN
 ZETTELKASTEN3-READING-DOMAIN :PROBLEM READ-THROUGH-ZETTEL-6537-PROBLEM
 :INITIAL-TASK-NETWORK
 ((READ-THROUGH-ZKN3-ZETTEL "6537"
   #1=#P"/Users/rgb/rgb~Zettelkasten/Zettelkasten-Dateien/rgb.zkn3"))
 :INITIAL-STATE
 ((ZETTELKASTEN3-CONTAINER #1#) (FILE-KIND #1# FILE-OR-ARCHIVE)
  (NOT-DIRECTORY-PATHNAME #1#) (CONTAINS-ARCHIVE-MEMBER #1# "zknFile.xml")
  (WANTED-ZETTEL-ID "6537"))
 :METHODS
 ((:METHOD READ-THROUGH-ZKN3-ZETTEL :TASK
   (READ-THROUGH-ZKN3-ZETTEL ?ZETTEL-ID ?ZKN3-CONTAINER) :PRECONDITIONS
   ((ZETTELKASTEN3-CONTAINER ?ZKN3-CONTAINER)
    (FILE-KIND ?ZKN3-CONTAINER FILE-OR-ARCHIVE)
    (NOT-DIRECTORY-PATHNAME ?ZKN3-CONTAINER))
   :SUBTASKS
   (:ORDERED (!RECORD-SHOP3-PLAN READ-THROUGH-ZETTEL-6537)
    (!CLASSIFY-ZKN3-CONTAINER ?ZKN3-CONTAINER)
    (!EXTRACT-ZKN3-MEMBER ?ZKN3-CONTAINER "zknFile.xml")
    (!PARSE-ZKN-FILE-XML #2=#P"/tmp/hyperdoc-zkn3-read/zknFile.xml")
    (!LOCATE-ZKN3-ZETTEL-ENTRY #2# ?ZETTEL-ID)
    (!EXTRACT-ZKN3-ZETTEL-TEXT ?ZETTEL-ID)
    (!INSPECT-ZETTEL-SOURCE-RESULT ?ZETTEL-ID) (!READ-ZETTEL-TEXT ?ZETTEL-ID)
    (!RECORD-READING-RESULT ?ZETTEL-ID)
    (!CLOSE-SHOP3-PLAN READ-THROUGH-ZETTEL-6537))))
 :OPERATORS
 ((!RECORD-SHOP3-PLAN ?PLAN-ID) (!CLASSIFY-ZKN3-CONTAINER ?ZKN3-CONTAINER)
  (!EXTRACT-ZKN3-MEMBER ?ZKN3-CONTAINER ?MEMBER-NAME)
  (!PARSE-ZKN-FILE-XML ?ZKN-FILE)
  (!LOCATE-ZKN3-ZETTEL-ENTRY ?ZKN-FILE ?ZETTEL-ID)
  (!EXTRACT-ZKN3-ZETTEL-TEXT ?ZETTEL-ID)
  (!INSPECT-ZETTEL-SOURCE-RESULT ?ZETTEL-ID) (!READ-ZETTEL-TEXT ?ZETTEL-ID)
  (!RECORD-READING-RESULT ?ZETTEL-ID) (!CLOSE-SHOP3-PLAN ?PLAN-ID))
 :INVALID-OPERATORS
 (((!LOCATE-LOOSE-ZETTEL-FILE ?SOURCE ?ZETTEL-ID) :BECAUSE
   ((AUTHORITATIVE-ZETTELKASTEN-FORMAT ZETTELKASTEN3-ZKN3-CONTAINER)))
  ((!OPEN-PATH
    #P"/Users/rgb/rgb~Zettelkasten/Zettelkasten-Dateien/rgb.zkn3/zknFile.xml")
   :BECAUSE ((FILE-KIND #1# FILE-OR-ARCHIVE) (NOT-DIRECTORY-PATHNAME #1#))))
 :SELECTED-PLAN
 ((!RECORD-SHOP3-PLAN READ-THROUGH-ZETTEL-6537) (!CLASSIFY-ZKN3-CONTAINER #1#)
  (!EXTRACT-ZKN3-MEMBER #1# "zknFile.xml") (!PARSE-ZKN-FILE-XML #2#)
  (!LOCATE-ZKN3-ZETTEL-ENTRY #2# "6537") (!EXTRACT-ZKN3-ZETTEL-TEXT "6537")
  (!INSPECT-ZETTEL-SOURCE-RESULT "6537") (!READ-ZETTEL-TEXT "6537")
  (!RECORD-READING-RESULT "6537") (!CLOSE-SHOP3-PLAN READ-THROUGH-ZETTEL-6537))
 :CURRENT-TASK (!RECORD-SHOP3-PLAN READ-THROUGH-ZETTEL-6537)
 :NEXT-EXECUTABLE-TASK (!EXTRACT-ZKN3-MEMBER #1# "zknFile.xml"))
