(:TASK
 (!RETAIN-HYPERDOC-ONLY-FORK-PROVENANCE :PAGE WHAT-GRAPHVIZ-DOES :SOURCE-SLUG
  "what-graphviz-does" :TARGET-SITE "wiki.ralfbarkow.ch" :TARGET-SLUG
  "what-graphviz-does")
 :PARENT-TASK
 (!CONSTRUCT-EXPLICIT-FORK-JOURNAL-ACTION :PAGE WHAT-GRAPHVIZ-DOES :TYPE "fork"
  :SITE "does.ward.dojo.fed.wiki" :DATE :EXECUTION-TIME-MONOTONIC-EPOCH-MILLIS)
 :STAGE-BOUNDARY
 ((MAY-RETAIN-HYPERDOC-ONLY-FORK-PROVENANCE T)
  (MAY-WRITE-PROVENANCE-EVIDENCE-ARTIFACT T) (MAY-REFETCH-REMOTE-PAGE-JSON NIL)
  (MAY-CONSTRUCT-FORK-JOURNAL-ACTION NIL)
  (MAY-WRITE-LOCAL-PAGE-JSON-AS-FORK NIL) (MAY-LOAD-MISSING-SOURCE-FILES NIL)
  (MAY-WRITE-PAGE-ATTACHED-ASDF NIL) (MAY-CREATE-SQLITE NIL) (MAY-COMMIT NIL))
 :CANONICAL-FORK-ACTION
 (("type" . "fork") ("site" . "does.ward.dojo.fed.wiki")
  ("date" . 1783525442000))
 :CANONICAL-FORK-ACTION-VALIDATION
 (:CANONICAL-ACTION-PRESENT-P T :CANONICAL-ACTION-KEYS ("type" "site" "date")
  :CANONICAL-ACTION-HAS-ONLY-TYPE-SITE-DATE-P T :CANONICAL-ACTION-VALID-P T)
 :HYPERDOC-ONLY-PROVENANCE
 (:PAGE :WHAT-GRAPHVIZ-DOES :SOURCE-SITE "does.ward.dojo.fed.wiki" :SOURCE-SLUG
  "what-graphviz-does" :SOURCE-TITLE "What Graphviz Does" :TARGET-SITE
  "wiki.ralfbarkow.ch" :TARGET-SLUG "what-graphviz-does" :TARGET-PAGE-FILE
  "/Users/rgb/.wiki/wiki.ralfbarkow.ch/pages/what-graphviz-does"
  :READER-PURPOSE "dense paragraph -> jargon fragments -> hierarchy" :ROUTE
  :HYPERDOC-LOCAL-MATERIALIZATION-ROUTE :CANONICAL-FORK-ACTION-DATE
  1783525442000)
 :VALIDATION
 (:HYPERDOC-ONLY-PROVENANCE-RETAINED-P T
  :PROVENANCE-KEPT-OUTSIDE-CANONICAL-FORK-ACTION-P T :SOURCE-SLUG-RETAINED-P T
  :TARGET-SITE-RETAINED-P T :TARGET-SLUG-RETAINED-P T :PROVENANCE-VALID-P T)
 :ACCEPTANCE-FOR-CURRENT-TASK
 ((HYPERDOC-ONLY-FORK-PROVENANCE-RETAINED T)
  (CANONICAL-FORK-ACTION-NOT-EXTENDED T)
  (SOURCE-SLUG-KEPT-OUTSIDE-CANONICAL-ACTION T)
  (TARGET-SITE-KEPT-OUTSIDE-CANONICAL-ACTION T)
  (TARGET-SLUG-KEPT-OUTSIDE-CANONICAL-ACTION T) (NO-LOCAL-PAGE-JSON-WRITTEN T)
  (NO-ASDF-WRITTEN T) (NO-SQLITE-CREATED T) (NO-COMMIT-PERFORMED T))
 :NEXT-TASK
 (!ADAPT-FEDWIKI-MATERIALIZATION-ENTRY-FOR-REMOTE-FORK-PAGE WHAT-GRAPHVIZ-DOES))
