(:TASK (!VALIDATE-REMOTE-PAGE-TITLE WHAT-GRAPHVIZ-DOES "What Graphviz Does")
 :PARENT-TASK (!FETCH-REMOTE-PAGE-JSON WHAT-GRAPHVIZ-DOES) :STAGE-BOUNDARY
 ((MAY-VALIDATE-REMOTE-PAGE-JSON T)
  (MAY-WRITE-TITLE-VALIDATION-EVIDENCE-ARTIFACT T)
  (MAY-FETCH-REMOTE-PAGE-JSON NIL) (MAY-CONSTRUCT-FORK-JOURNAL-ACTION NIL)
  (MAY-LOAD-MISSING-SOURCE-FILES NIL) (MAY-WRITE-LOCAL-PAGE-JSON-AS-FORK NIL)
  (MAY-WRITE-PAGE-ATTACHED-ASDF NIL) (MAY-CREATE-SQLITE NIL) (MAY-COMMIT NIL))
 :SOURCE-PAGE
 (:SITE "does.ward.dojo.fed.wiki" :SLUG "what-graphviz-does" :EXPECTED-TITLE
  "What Graphviz Does")
 :FETCH-SUMMARY
 (:TASK (!FETCH-REMOTE-PAGE-JSON WHAT-GRAPHVIZ-DOES) :FETCH-ROUTE
  :EXISTING-FETCH-PAGE-JSON-OPERATOR :EVIDENCE-ARTIFACT-WRITTEN-P T
  :EVIDENCE-ARTIFACT-PATH
  "/Users/rgb/workspace/hyperdoc/hyperdoc/what-graphviz-does-remote-page-fetch.evidence.sexp"
  :TITLE #1="What Graphviz Does" :TITLE-MATCHES-EXPECTED-P T :STORY-COUNT 3
  :JOURNAL-COUNT 12 :RAW-JSON-LENGTH NIL :RAW-JSON-PRESENT-P NIL
  :PAGE-JSON-PRESENT-P T :ACCEPTANCE
  ((REMOTE-PAGE-JSON-FETCHED T) (NO-FORK-ACTION-CONSTRUCTED T)
   (NO-LOCAL-PAGE-JSON-WRITTEN T) (NO-ASDF-WRITTEN T) (NO-SQLITE-CREATED T)
   (NO-COMMIT-PERFORMED T))
  :NEXT-TASK
  (!VALIDATE-REMOTE-PAGE-TITLE WHAT-GRAPHVIZ-DOES "What Graphviz Does"))
 :TITLE-VALIDATION
 (:EXPECTED-TITLE "What Graphviz Does" :ACTUAL-TITLE #1# :TITLE-VALID-P T)
 :ACCEPTANCE-FOR-CURRENT-TASK
 ((REMOTE-PAGE-TITLE-VALIDATED T) (TITLE-MATCHES-EXPECTED-P T)
  (NO-REFETCH-PERFORMED T) (NO-FORK-ACTION-CONSTRUCTED T)
  (NO-LOCAL-PAGE-JSON-WRITTEN T) (NO-ASDF-WRITTEN T) (NO-SQLITE-CREATED T)
  (NO-COMMIT-PERFORMED T))
 :NEXT-TASK (!VALIDATE-REMOTE-PAGE-STORY-SHAPE WHAT-GRAPHVIZ-DOES))
