(:TASK (!FETCH-REMOTE-PAGE-JSON WHAT-GRAPHVIZ-DOES) :STAGE-BOUNDARY
 ((MAY-FETCH-REMOTE-PAGE-JSON T) (MAY-WRITE-FETCH-EVIDENCE-ARTIFACT T)
  (MAY-CONSTRUCT-FORK-JOURNAL-ACTION NIL) (MAY-LOAD-MISSING-SOURCE-FILES NIL)
  (MAY-WRITE-LOCAL-PAGE-JSON-AS-FORK NIL) (MAY-WRITE-PAGE-ATTACHED-ASDF NIL)
  (MAY-CREATE-SQLITE NIL) (MAY-COMMIT NIL))
 :SOURCE-PAGE
 (:SITE "does.ward.dojo.fed.wiki" :SLUG "what-graphviz-does" :TITLE
  "What Graphviz Does" :SOURCE-URL
  "http://does.ward.dojo.fed.wiki/view/what-graphviz-does")
 :FETCH-RESULT
 (:ROUTE :EXISTING-FETCH-PAGE-JSON-OPERATOR :OPERATOR
  "HYPERBOOK/FEDWIKI::FETCH-PAGE-JSON" :PAGE-JSON
  (:UNREADABLE-LIVE-OBJECT "#<HASH-TABLE :TEST EQUAL :COUNT 3 {7022BB66C3}>"))
 :PARSED-PAGE-SUMMARY
 (:TITLE "What Graphviz Does" :TITLE-MATCHES-EXPECTED-P T :STORY-COUNT 3
  :JOURNAL-COUNT 12 :RAW-JSON-LENGTH NIL)
 :ACCEPTANCE-FOR-CURRENT-TASK
 ((REMOTE-PAGE-JSON-FETCHED T) (EXISTING-FETCH-OPERATOR-USED T)
  (CURL-FALLBACK-USED NIL) (NO-FORK-ACTION-CONSTRUCTED T)
  (NO-LOCAL-PAGE-JSON-WRITTEN T) (NO-ASDF-WRITTEN T) (NO-SQLITE-CREATED T)
  (NO-COMMIT-PERFORMED T))
 :NEXT-TASK
 (!VALIDATE-REMOTE-PAGE-TITLE WHAT-GRAPHVIZ-DOES "What Graphviz Does"))
