(:TASK (!WRITE-REMOTE-FORK-MATERIALIZATION-ENTRY WHAT-GRAPHVIZ-DOES)
 :PARENT-TASK
 (!ADAPT-FEDWIKI-MATERIALIZATION-ENTRY-FOR-REMOTE-FORK-PAGE WHAT-GRAPHVIZ-DOES)
 :STAGE-BOUNDARY
 ((MAY-WRITE-LOCAL-PAGE-JSON-AS-FORK T) (MAY-BACKUP-EXISTING-TARGET-PAGE T)
  (MAY-WRITE-MATERIALIZATION-ENTRY-EVIDENCE-ARTIFACT T)
  (MAY-REFETCH-REMOTE-PAGE-JSON NIL) (MAY-CONSTRUCT-FORK-JOURNAL-ACTION NIL)
  (MAY-LOAD-PAGE-ASDF-ASSET-WRITER-SYSTEM NIL)
  (MAY-WRITE-PAGE-ATTACHED-ASDF NIL) (MAY-CREATE-SQLITE NIL) (MAY-COMMIT NIL))
 :TARGET-PAGE
 (:PATH
  #A((60) BASE-CHAR
     . "/Users/rgb/.wiki/wiki.ralfbarkow.ch/pages/what-graphviz-does")
  :EXISTED-BEFORE-WRITE-P NIL :BACKUP-PATH NIL :BACKUP-WRITTEN-P NIL
  :FILE-LENGTH-AFTER-WRITE 10416)
 :JSON-WRITER (:ENCODER-SYMBOL #A((18) BASE-CHAR . "SHASHT::WRITE-JSON"))
 :CANDIDATE-BEFORE-WRITE
 (:TITLE "What Graphviz Does" :STORY-ITEM-IDS
  ("c558c39c83b0a0b9" "34e2de627fb48408" "6f9382b76ff19154") :JOURNAL-COUNT 13
  :LAST-JOURNAL-ACTION
  (("type" . "fork") ("site" . "does.ward.dojo.fed.wiki")
   ("date" . 1783525442000))
  :CANDIDATE-VALID-P T)
 :WRITTEN-PAGE-VALIDATION
 (:TITLE #A((18) BASE-CHAR . "What Graphviz Does") :STORY-ITEM-IDS
  (#A((16) BASE-CHAR . "c558c39c83b0a0b9")
   #A((16) BASE-CHAR . "34e2de627fb48408")
   #A((16) BASE-CHAR . "6f9382b76ff19154"))
  :JOURNAL-COUNT 13 :LAST-JOURNAL-ACTION
  ((#A((4) BASE-CHAR . "type") . #A((4) BASE-CHAR . "fork"))
   (#A((4) BASE-CHAR . "site")
    . #A((23) BASE-CHAR . "does.ward.dojo.fed.wiki"))
   (#A((4) BASE-CHAR . "date") . 1783525442000))
  :WRITTEN-PAGE-VALID-P T)
 :CANONICAL-BOUNDARIES
 ((STORY-ITEM-IDS-PRESERVED T) (STORY-ORDER-PRESERVED T)
  (SOURCE-JOURNAL-PRESERVED-WITH-FORK-ACTION-APPENDED T)
  (CANONICAL-FORK-ACTION-IS-TYPE-SITE-DATE-ONLY T)
  (HYPERDOC-ONLY-PROVENANCE-NOT-WRITTEN-INTO-PAGE-JSON T)
  (GRAPHVIZ-NOT-EXECUTED T) (PLUGIN-ITEMS-NOT-NORMALIZED T))
 :ACCEPTANCE-FOR-CURRENT-TASK
 ((LOCAL-PAGE-JSON-WRITTEN-AS-FORK T)
  (EXISTING-TARGET-PAGE-BACKED-UP-IF-PRESENT T) (WRITTEN-PAGE-TITLE-VALID T)
  (WRITTEN-STORY-ITEM-IDS-PRESERVED T)
  (WRITTEN-JOURNAL-HAS-FORK-ACTION-APPENDED T) (NO-ASDF-WRITTEN T)
  (NO-SQLITE-CREATED T) (NO-COMMIT-PERFORMED T))
 :NEXT-TASK (!PLAN-PAGE-ATTACHED-ASDF-HOME-OBJECT WHAT-GRAPHVIZ-DOES))
