(:TASK (!VALIDATE-REMOTE-PAGE-STORY-SHAPE WHAT-GRAPHVIZ-DOES) :PARENT-TASK
 (!VALIDATE-REMOTE-PAGE-TITLE WHAT-GRAPHVIZ-DOES "What Graphviz Does")
 :STAGE-BOUNDARY
 ((MAY-VALIDATE-REMOTE-PAGE-JSON T)
  (MAY-WRITE-STORY-SHAPE-VALIDATION-EVIDENCE-ARTIFACT T)
  (MAY-FETCH-REMOTE-PAGE-JSON NIL) (MAY-CONSTRUCT-FORK-JOURNAL-ACTION NIL)
  (MAY-LOAD-MISSING-SOURCE-FILES NIL) (MAY-WRITE-LOCAL-PAGE-JSON-AS-FORK NIL)
  (MAY-WRITE-PAGE-ATTACHED-ASDF NIL) (MAY-CREATE-SQLITE NIL) (MAY-COMMIT NIL))
 :SOURCE-EVIDENCE
 (:FETCH-EVIDENCE-PATH
  "/Users/rgb/workspace/hyperdoc/hyperdoc/what-graphviz-does-remote-page-fetch.evidence.sexp"
  :FETCH-EVIDENCE-PRESENT-P NIL :PAGE-JSON-PRESENT-P NIL)
 :STORY-SHAPE
 (:TITLE NIL :TITLE-VALID-P NIL :STORY-PRESENT-P NIL :STORY-SEQUENCE-P NIL
  :STORY-COUNT NIL :JOURNAL-PRESENT-P NIL :JOURNAL-COUNT NIL
  :STORY-ITEMS-SUMMARY NIL :ALL-STORY-ITEMS-HAVE-IDS-P NIL
  :ALL-STORY-ITEMS-HAVE-TYPES-P NIL :STORY-SHAPE-VALID-P NIL)
 :ACCEPTANCE-FOR-CURRENT-TASK
 ((REMOTE-PAGE-STORY-SHAPE-VALIDATED NIL)
  (SOURCE-PAGE-JSON-REUSED-FROM-FETCH-EVIDENCE T) (NO-REFETCH-PERFORMED T)
  (NO-FORK-ACTION-CONSTRUCTED T) (NO-LOCAL-PAGE-JSON-WRITTEN T)
  (NO-ASDF-WRITTEN T) (NO-SQLITE-CREATED T) (NO-COMMIT-PERFORMED T))
 :NEXT-TASK
 (!PRESERVE-SOURCE-STORY-ITEMS :PAGE WHAT-GRAPHVIZ-DOES
  :PRESERVE-EXISTING-ITEM-IDS T :PRESERVE-EXISTING-STORY-ORDER T))
