(:TASK
 "(!NORMALIZE-PAGE-ATTACHED-ASDF-HOME-EVIDENCE-DESCRIPTORS WHAT-GRAPHVIZ-DOES)"
 :REPAIRS-TASK
 "(!REPAIR-PAGE-ATTACHED-ASDF-HOME-EVIDENCE-DESCRIPTORS WHAT-GRAPHVIZ-DOES)"
 :STAGE-BOUNDARY
 ((MAY-NORMALIZE-HOME-EVIDENCE-DESCRIPTORS T)
  (MAY-LOAD-PAGE-ASDF-ASSET-WRITER-SYSTEM NIL)
  (MAY-WRITE-PAGE-ATTACHED-ASDF NIL) (MAY-CREATE-SQLITE NIL) (MAY-COMMIT NIL))
 :REPAIR-REASON
 "Normalize durable home evidence so descriptors use names, booleans, numbers, and explicit path strings instead of live objects or symbolic object representations."
 :PAGE-ATTACHED-ASDF-HOME-SPEC
 (:SLUG "what-graphviz-does" :SITE-ROOT "/Users/rgb/.wiki/wiki.ralfbarkow.ch/"
  :SYSTEM-NAME "WHAT-GRAPHVIZ-DOES" :SYSTEM-FILE "what-graphviz-does"
  :TEST-SYSTEM-NAME "WHAT-GRAPHVIZ-DOES/TESTS" :PAGE-FILE
  #1="/Users/rgb/.wiki/wiki.ralfbarkow.ch/pages/what-graphviz-does"
  :ASSET-DIRECTORY
  #2="/Users/rgb/.wiki/wiki.ralfbarkow.ch/assets/pages/what-graphviz-does/"
  :ASDF-ENTRYPOINT
  #3="/Users/rgb/.wiki/wiki.ralfbarkow.ch/assets/pages/what-graphviz-does/what-graphviz-does.asd")
 :LOCAL-PAGE (:PAGE-FILE #1# :PAGE-FILE-EXISTS-P T) :ASSET-ROUTE
 (:ASSET-DIRECTORY #2# :ASSET-DIRECTORY-EXISTS-P NIL :ASDF-ENTRYPOINT #3#
  :ASDF-ENTRYPOINT-EXISTS-P NIL)
 :HOME-OBJECT-DESCRIPTOR
 (:PRESENT-P T :TYPE-NAME
  #A((37) BASE-CHAR . "HYPERDOC:FEDWIKI-ATTACHED-ASDF-SYSTEM") :ROLE-NAME
  "FEDWIKI-ATTACHED-ASDF-SYSTEM-HOME-OBJECT" :RETAINED-VARIABLE-NAME
  "*WGD-PAGE-ATTACHED-ASDF-HOME-OBJECT*" :PRINTED-OBJECT-STORED-P NIL)
 :HOME-PAGE-DESCRIPTOR
 (:PRESENT-P T :TYPE-NAME #A((16) BASE-CHAR . "COMMON-LISP:CONS") :KIND-NAME
  ":FEDWIKI-ATTACHED-ASDF-SYSTEM-HOME-PAGE" :TITLE
  "FedWiki-attached ASDF system home page" :STATE
  (:PAGE-IDENTITY "what-graphviz-does" :ASSET-ROOT
   #A((68) BASE-CHAR
      . "/Users/rgb/.wiki/wiki.ralfbarkow.ch/assets/pages/what-graphviz-does/")
   :ASDF-ENTRYPOINT
   #A((90) BASE-CHAR
      . "/Users/rgb/.wiki/wiki.ralfbarkow.ch/assets/pages/what-graphviz-does/what-graphviz-does.asd")
   :SYSTEM-NAME ":WHAT-GRAPHVIZ-DOES" :TEST-SYSTEM-NAME
   ":WHAT-GRAPHVIZ-DOES/TESTS" :LOADED-P NIL :SYSTEM-FOUND-P NIL :REGISTERED-P
   NIL :ASSET-ROOT-EXISTS-P NIL :ASD-EXISTS-P NIL :PACKAGE-PRESENT-P NIL
   :SQLITE-STATUS-NAME ":NOT-APPLICABLE")
  :OBJECT-FIELD-STORED-P NIL :ACTIONS-COUNT 7 :READING-QUESTIONS-COUNT 12
  :RETAINED-VARIABLE-NAME "*WGD-PAGE-ATTACHED-ASDF-HOME-PAGE*"
  :PRINTED-OBJECT-STORED-P NIL)
 :VALIDATION
 (:HOME-OBJECT-RETAINED-P T :HOME-PAGE-RETAINED-P T :HOME-OBJECT-VALID-P T
  :DURABLE-EVIDENCE-CONTAINS-LIVE-OBJECT-P NIL
  :DURABLE-EVIDENCE-CONTAINS-PRINTED-UNREADABLE-OBJECT-SYNTAX-P NIL
  :DURABLE-EVIDENCE-USES-NAME-STRINGS-FOR-TYPES-AND-SYSTEM-NAMES T
  :PAGE-IDENTITY-REMAINS-IN-PAGES-STORE T
  :ASDF-ENTRYPOINT-REMAINS-IN-ASSETS-STORE T :NO-ASDF-WRITER-SYSTEM-LOADED T
  :NO-PAGE-ATTACHED-ASDF-WRITTEN T :NO-SQLITE-CREATED T :NO-COMMIT-PERFORMED T)
 :ACCEPTANCE-FOR-CURRENT-TASK
 ((STRICT-HOME-EVIDENCE-WRITTEN T) (HOME-OBJECT-RETAINED T)
  (HOME-PAGE-RETAINED T)
  (DURABLE-EVIDENCE-USES-NAME-STRINGS-NOT-LIVE-OBJECTS T)
  (DURABLE-EVIDENCE-OMITS-OBJECT-FIELD T)
  (DURABLE-EVIDENCE-CONTAINS-NO-SHARP-ANGLE-OBJECT-SYNTAX T)
  (NO-ASDF-WRITER-SYSTEM-LOADED T) (NO-PAGE-ATTACHED-ASDF-WRITTEN T)
  (NO-SQLITE-CREATED T) (NO-COMMIT-PERFORMED T))
 :NEXT-TASK
 "(!LOAD-PAGE-ASDF-ASSET-WRITER-SYSTEM :SYSTEM :HYPERDOC/FEDWIKI-ASDF-ASSETS)")
