(:TASK
 (!CONSTRUCT-EXPLICIT-FORK-JOURNAL-ACTION :PAGE WHAT-GRAPHVIZ-DOES :TYPE "fork"
  :SITE "does.ward.dojo.fed.wiki" :DATE :EXECUTION-TIME-MONOTONIC-EPOCH-MILLIS)
 :PARENT-TASK
 (!PRESERVE-SOURCE-STORY-ITEMS :PAGE WHAT-GRAPHVIZ-DOES
  :PRESERVE-EXISTING-ITEM-IDS T :PRESERVE-EXISTING-STORY-ORDER T)
 :STAGE-BOUNDARY
 ((MAY-CONSTRUCT-EXPLICIT-FORK-JOURNAL-ACTION T)
  (MAY-WRITE-FORK-ACTION-EVIDENCE-ARTIFACT T)
  (MAY-REFETCH-REMOTE-PAGE-JSON NIL) (MAY-WRITE-LOCAL-PAGE-JSON-AS-FORK NIL)
  (MAY-LOAD-MISSING-SOURCE-FILES NIL) (MAY-WRITE-PAGE-ATTACHED-ASDF NIL)
  (MAY-CREATE-SQLITE NIL) (MAY-COMMIT NIL))
 :SOURCE-PAGE
 (:SITE "does.ward.dojo.fed.wiki" :SLUG "what-graphviz-does" :TITLE
  "What Graphviz Does")
 :DATE-POLICY
 (:EXECUTION-CLOCK-DATE 1783525442000 :SOURCE-JOURNAL-LAST-DATE 1783522915032
  :SELECTED-FORK-DATE 1783525442000 :RULE
  "max(execution-clock-date, source-journal-last-date + 1)"
  :DATE-POLICY-VALID-P T)
 :CANONICAL-FORK-ACTION
 (("type" . "fork") ("site" . "does.ward.dojo.fed.wiki")
  ("date" . 1783525442000))
 :HYPERDOC-ONLY-PROVENANCE
 ((SOURCE-SLUG "what-graphviz-does") (TARGET-SITE "wiki.ralfbarkow.ch")
  (TARGET-SLUG "what-graphviz-does"))
 :VALIDATION
 (:FORK-ACTION-TYPE-IS-FORK-P T :FORK-ACTION-SITE-IS-SOURCE-SITE-P T
  :FORK-ACTION-DATE-PRESENT-P T :FORK-ACTION-DATE-MONOTONIC-P T
  :CANONICAL-ACTION-NOT-EXTENDED-WITH-HYPERDOC-ONLY-FIELDS-P T
  :FORK-ACTION-VALID-P T)
 :ACCEPTANCE-FOR-CURRENT-TASK
 ((EXPLICIT-FORK-JOURNAL-ACTION-CONSTRUCTED T) (FORK-ACTION-TYPE-IS-FORK T)
  (FORK-ACTION-SITE-IS-SOURCE-SITE T)
  (FORK-ACTION-DATE-MONOTONIC-WITH-SOURCE-JOURNAL T)
  (HYPERDOC-ONLY-PROVENANCE-KEPT-OUTSIDE-CANONICAL-ACTION T)
  (NO-LOCAL-PAGE-JSON-WRITTEN T) (NO-ASDF-WRITTEN T) (NO-SQLITE-CREATED T)
  (NO-COMMIT-PERFORMED T))
 :NEXT-TASK
 (!RETAIN-HYPERDOC-ONLY-FORK-PROVENANCE :PAGE WHAT-GRAPHVIZ-DOES :SOURCE-SLUG
  "what-graphviz-does" :TARGET-SITE "wiki.ralfbarkow.ch" :TARGET-SLUG
  "what-graphviz-does"))
