(:TASK
 (!REPAIR-PAGE-ATTACHED-ASDF-HOME-EVIDENCE-DESCRIPTORS WHAT-GRAPHVIZ-DOES)
 :REPAIRS-TASK
 (!REPAIR-PAGE-ATTACHED-ASDF-HOME-OBJECT-EVIDENCE WHAT-GRAPHVIZ-DOES)
 :STAGE-BOUNDARY
 ((MAY-REWRITE-HOME-OBJECT-EVIDENCE-AS-CLEAN-DESCRIPTOR T)
  (MAY-LOAD-PAGE-ASDF-ASSET-WRITER-SYSTEM NIL)
  (MAY-WRITE-PAGE-ATTACHED-ASDF NIL) (MAY-CREATE-SQLITE NIL) (MAY-COMMIT NIL))
 :REPAIR-REASON
 "Previous descriptor was readably printable but too literal: it included printed #<...> object syntax inside a summary string."
 :PAGE-ATTACHED-ASDF-HOME-SPEC
 (:SLUG "what-graphviz-does" :SITE-ROOT
  #A((36) BASE-CHAR . "/Users/rgb/.wiki/wiki.ralfbarkow.ch/") :SYSTEM
  :WHAT-GRAPHVIZ-DOES :SYSTEM-FILE "what-graphviz-does" :TEST-SYSTEM
  :WHAT-GRAPHVIZ-DOES/TESTS :PAGE-FILE
  "/Users/rgb/.wiki/wiki.ralfbarkow.ch/pages/what-graphviz-does"
  :ASSET-DIRECTORY
  "/Users/rgb/.wiki/wiki.ralfbarkow.ch/assets/pages/what-graphviz-does/"
  :ASDF-ENTRYPOINT
  "/Users/rgb/.wiki/wiki.ralfbarkow.ch/assets/pages/what-graphviz-does/what-graphviz-does.asd")
 :LOCAL-PAGE
 (:PAGE-FILE "/Users/rgb/.wiki/wiki.ralfbarkow.ch/pages/what-graphviz-does"
  :PAGE-FILE-EXISTS-P T)
 :ASSET-ROUTE
 (:ASSET-DIRECTORY
  "/Users/rgb/.wiki/wiki.ralfbarkow.ch/assets/pages/what-graphviz-does/"
  :ASSET-DIRECTORY-EXISTS-P NIL :ASDF-ENTRYPOINT
  "/Users/rgb/.wiki/wiki.ralfbarkow.ch/assets/pages/what-graphviz-does/what-graphviz-does.asd"
  :ASDF-ENTRYPOINT-EXISTS-P NIL)
 :HOME-OBJECT-DESCRIPTOR
 (:PRESENT-P T :TYPE
  #A((37) BASE-CHAR . "HYPERDOC:FEDWIKI-ATTACHED-ASDF-SYSTEM") :ROLE
  :FEDWIKI-ATTACHED-ASDF-SYSTEM-HOME-OBJECT :RETAINED-AS
  *WGD-PAGE-ATTACHED-ASDF-HOME-OBJECT* :PRINTED-OBJECT-NOT-STORED-P T)
 :HOME-PAGE-DESCRIPTOR
 (:PRESENT-P T :TYPE #A((4) BASE-CHAR . "CONS") :KIND
  :FEDWIKI-ATTACHED-ASDF-SYSTEM-HOME-PAGE :TITLE
  "FedWiki-attached ASDF system home page" :STATE
  (:PAGE-IDENTITY "what-graphviz-does" :ASSET-ROOT
   #A((68) BASE-CHAR
      . "/Users/rgb/.wiki/wiki.ralfbarkow.ch/assets/pages/what-graphviz-does/")
   :ASDF-ENTRYPOINT
   #A((90) BASE-CHAR
      . "/Users/rgb/.wiki/wiki.ralfbarkow.ch/assets/pages/what-graphviz-does/what-graphviz-does.asd")
   :SYSTEM :WHAT-GRAPHVIZ-DOES :TEST-SYSTEM :WHAT-GRAPHVIZ-DOES/TESTS :LOADED-P
   NIL :SYSTEM-FOUND-P NIL :REGISTERED-P NIL :ASSET-ROOT-EXISTS-P NIL
   :ASD-EXISTS-P NIL :PACKAGE-PRESENT-P NIL :SQLITE-STATUS :NOT-APPLICABLE)
  :OBJECT-FIELD-OMITTED-P T :ACTIONS-COUNT 7 :READING-QUESTIONS-COUNT 12
  :RETAINED-AS *WGD-PAGE-ATTACHED-ASDF-HOME-PAGE* :PRINTED-OBJECT-NOT-STORED-P
  T)
 :VALIDATION
 (:HOME-OBJECT-RETAINED-P T :HOME-PAGE-RETAINED-P T :HOME-OBJECT-VALID-P T
  :DURABLE-EVIDENCE-CONTAINS-LIVE-OBJECT-P NIL
  :DURABLE-EVIDENCE-CONTAINS-PRINTED-UNREADABLE-OBJECT-SYNTAX-P NIL
  :PAGE-IDENTITY-REMAINS-IN-PAGES-STORE T
  :ASDF-ENTRYPOINT-REMAINS-IN-ASSETS-STORE T :NO-ASDF-WRITER-SYSTEM-LOADED T
  :NO-PAGE-ATTACHED-ASDF-WRITTEN T :NO-SQLITE-CREATED T :NO-COMMIT-PERFORMED T)
 :ACCEPTANCE-FOR-CURRENT-TASK
 ((CLEAN-HOME-EVIDENCE-WRITTEN T) (HOME-OBJECT-RETAINED T)
  (HOME-PAGE-RETAINED T) (DURABLE-EVIDENCE-USES-DESCRIPTORS-NOT-LIVE-OBJECTS T)
  (DURABLE-EVIDENCE-OMITS-OBJECT-FIELD T) (NO-ASDF-WRITER-SYSTEM-LOADED T)
  (NO-PAGE-ATTACHED-ASDF-WRITTEN T) (NO-SQLITE-CREATED T)
  (NO-COMMIT-PERFORMED T))
 :NEXT-TASK
 (!LOAD-PAGE-ASDF-ASSET-WRITER-SYSTEM :SYSTEM :HYPERDOC/FEDWIKI-ASDF-ASSETS))
