(:TASK
 (!VALIDATE-REMOTE-PAGE-STORY-SHAPE-FROM-RETAINED-JSON WHAT-GRAPHVIZ-DOES)
 :PARENT-TASK
 (!REPAIR-FETCH-RESULT-RETENTION-FOR-STORY-SHAPE-VALIDATION WHAT-GRAPHVIZ-DOES)
 :STAGE-BOUNDARY
 ((MAY-VALIDATE-RETAINED-REMOTE-PAGE-JSON T)
  (MAY-WRITE-STORY-SHAPE-VALIDATION-EVIDENCE-ARTIFACT T)
  (MAY-REFETCH-REMOTE-PAGE-JSON NIL) (MAY-CONSTRUCT-FORK-JOURNAL-ACTION NIL)
  (MAY-WRITE-LOCAL-PAGE-JSON-AS-FORK NIL) (MAY-LOAD-MISSING-SOURCE-FILES NIL)
  (MAY-WRITE-PAGE-ATTACHED-ASDF NIL) (MAY-CREATE-SQLITE NIL) (MAY-COMMIT NIL))
 :RETAINED-JSON
 (:LIVE-VARIABLE *WGD-REMOTE-PAGE-JSON* :LIVE-VARIABLE-BOUND-P T
  :PAGE-JSON-PRESENT-P T :READABLE-VARIABLE *WGD-REMOTE-PAGE-JSON-READABLE*
  :READABLE-VARIABLE-BOUND-P T)
 :STORY-SHAPE
 (:TITLE "What Graphviz Does" :TITLE-VALID-P T :STORY-PRESENT-P T
  :STORY-SEQUENCE-P T :STORY-COUNT 3 :STORY-COUNT-VALID-P T :JOURNAL-PRESENT-P
  T :JOURNAL-COUNT 12 :SOURCE-JOURNAL-LAST-DATE 1783522915032 :STORY-ITEM-IDS
  (#1="c558c39c83b0a0b9" #2="34e2de627fb48408" #3="6f9382b76ff19154")
  :STORY-ITEM-TYPES (#4="paragraph" #5="paragraph" #6="html")
  :STORY-ITEMS-SUMMARY
  ((:INDEX 0 :ID #1# :TYPE #4# :TEXT-PRESENT-P T :HAS-ID-P T :HAS-TYPE-P T)
   (:INDEX 1 :ID #2# :TYPE #5# :TEXT-PRESENT-P T :HAS-ID-P T :HAS-TYPE-P T)
   (:INDEX 2 :ID #3# :TYPE #6# :TEXT-PRESENT-P T :HAS-ID-P T :HAS-TYPE-P T))
  :ALL-STORY-ITEMS-HAVE-IDS-P T :ALL-STORY-ITEMS-HAVE-TYPES-P T
  :STORY-SHAPE-VALID-P T)
 :ACCEPTANCE-FOR-CURRENT-TASK
 ((REMOTE-PAGE-STORY-SHAPE-VALIDATED-FROM-RETAINED-JSON T)
  (RETAINED-PAGE-JSON-USED T) (NO-REFETCH-PERFORMED T)
  (NO-FORK-ACTION-CONSTRUCTED T) (NO-LOCAL-PAGE-JSON-WRITTEN T)
  (NO-ASDF-WRITTEN T) (NO-SQLITE-CREATED T) (NO-COMMIT-PERFORMED T))
 :NEXT-TASK
 (!PRESERVE-SOURCE-STORY-ITEMS :PAGE WHAT-GRAPHVIZ-DOES
  :PRESERVE-EXISTING-ITEM-IDS T :PRESERVE-EXISTING-STORY-ORDER T))
