(:TASK (!RECORD-CANDIDATE-CHILD-MATERIALIZATION-PLAN WHAT-GRAPHVIZ-DOES)
 :PARENT-TASK
 (!INSPECT-REVISED-CANDIDATE-CHILD-MATERIALIZATION-PLAN WHAT-GRAPHVIZ-DOES)
 :STAGE-BOUNDARY
 ((MAY-WRITE-PLAN-ARTIFACT T) (MAY-FETCH-REMOTE-PAGE-JSON NIL)
  (MAY-CONSTRUCT-FORK-JOURNAL-ACTION NIL) (MAY-LOAD-MISSING-SOURCE-FILES NIL)
  (MAY-WRITE-LOCAL-PAGE-JSON NIL) (MAY-WRITE-PAGE-ATTACHED-ASDF NIL)
  (MAY-CREATE-SQLITE NIL))
 :ARTIFACT
 (:PATH
  "/Users/rgb/workspace/hyperdoc/hyperdoc/what-graphviz-does-local-fork-materialization-plan.sexp"
  :KIND :HYPERDOC-PLAN-ARTIFACT :TOPIC :WHAT-GRAPHVIZ-DOES :TITLE
  "What Graphviz Does local fork materialization plan" :STATUS
  :RECORDED-CANDIDATE-CHILD-PLAN)
 :SOURCE-PAGE
 (:SITE "does.ward.dojo.fed.wiki" :SLUG "what-graphviz-does" :TITLE
  "What Graphviz Does" :SOURCE-URL
  "http://does.ward.dojo.fed.wiki/view/what-graphviz-does")
 :TARGET-PAGE
 (:SITE "wiki.ralfbarkow.ch" :SLUG "what-graphviz-does" :PAGE-FILE
  "/Users/rgb/.wiki/wiki.ralfbarkow.ch/pages/what-graphviz-does"
  :ASSET-DIRECTORY
  "/Users/rgb/.wiki/wiki.ralfbarkow.ch/assets/pages/what-graphviz-does/"
  :ASDF-ENTRYPOINT
  "/Users/rgb/.wiki/wiki.ralfbarkow.ch/assets/pages/what-graphviz-does/what-graphviz-does.asd")
 :RECORDED-PLAN-PRESENT-P T :RECORDED-INSPECTION-PRESENT-P T :RECORDED-PLAN
 #1=(:PARENT-TASK
     (!INSPECT-PAGE-ASDF-ASSET-WRITER-LOAD-BOUNDARY WHAT-GRAPHVIZ-DOES)
     :CURRENT-TASK
     (!REVISE-CANDIDATE-CHILD-MATERIALIZATION-PLAN-WITH-DESIGNED-OPERATORS
      WHAT-GRAPHVIZ-DOES)
     :STAGE-BOUNDARY
     ((MAY-REVISE-CANDIDATE-CHILD-PLAN T)
      (MAY-INSPECT-EXISTING-DESIGN-OBJECTS T) (MAY-FETCH-REMOTE-PAGE-JSON NIL)
      (MAY-CONSTRUCT-FORK-JOURNAL-ACTION NIL)
      (MAY-LOAD-MISSING-SOURCE-FILES NIL) (MAY-WRITE-LOCAL-PAGE-JSON NIL)
      (MAY-WRITE-PAGE-ATTACHED-ASDF NIL) (MAY-CREATE-SQLITE NIL))
     :INPUTS-PRESENT
     (:CANDIDATE-CHILD-PLAN-PRESENT-P T
      :FORK-JOURNAL-ACTION-CONSTRUCTOR-DESIGN-PRESENT-P T
      :REMOTE-FORK-MATERIALIZATION-DESIGN-PRESENT-P T
      :PAGE-ASDF-LOAD-BOUNDARY-PRESENT-P T)
     :SOURCE-PAGE
     (:SITE "does.ward.dojo.fed.wiki" :SLUG "what-graphviz-does" :TITLE
      "What Graphviz Does" :SOURCE-URL
      "http://does.ward.dojo.fed.wiki/view/what-graphviz-does")
     :TARGET-PAGE
     (:SITE "wiki.ralfbarkow.ch" :SLUG "what-graphviz-does" :PAGE-FILE
      "/Users/rgb/.wiki/wiki.ralfbarkow.ch/pages/what-graphviz-does"
      :ASSET-DIRECTORY
      "/Users/rgb/.wiki/wiki.ralfbarkow.ch/assets/pages/what-graphviz-does/"
      :ASDF-ENTRYPOINT
      "/Users/rgb/.wiki/wiki.ralfbarkow.ch/assets/pages/what-graphviz-does/what-graphviz-does.asd")
     :REVISION-RATIONALE
     ((FORK-JOURNAL-CONSTRUCTOR :FROM "generic local fork journal action task"
       :TO
       "explicit canonical fork action with HyperDoc-only provenance separated")
      (REMOTE-FORK-MATERIALIZER :FROM
       "generic materialize-local-page-json-as-fork task" :TO
       "adapt materialization-entry vocabulary for remote JSON fork page, then write only in execution stage")
      (PAGE-ASDF-ASSET-WRITER :FROM "source-located but not fbound functions"
       :TO
       "future ASDF load boundary plus post-load fbound validation before any write")
      (SQLITE-READER-LAYER :FROM "missing exact operator" :TO
       "deferred after local fork JSON and ASDF reader layer are validated"))
     :REVISED-CANDIDATE-CHILD-MATERIALIZATION-PLAN
     (:TASK (!MATERIALIZE-LOCAL-FORK-FROM-JSON WHAT-GRAPHVIZ-DOES) :STATUS
      REVISED-CANDIDATE-NOT-EXECUTED :METHOD
      ((!CONFIRM-EXECUTION-STAGE-BOUNDARY :MAY-FETCH-REMOTE-PAGE-JSON T
        :MAY-CONSTRUCT-EXPLICIT-FORK-JOURNAL-ACTION T
        :MAY-WRITE-LOCAL-PAGE-JSON T :MAY-LOAD-PAGE-ASDF-ASSET-WRITER-SYSTEM T
        :MAY-WRITE-PAGE-ATTACHED-ASDF-AFTER-LOAD-BOUNDARY T :MAY-CREATE-SQLITE
        NIL)
       (!FETCH-REMOTE-PAGE-JSON WHAT-GRAPHVIZ-DOES)
       (!VALIDATE-REMOTE-PAGE-TITLE WHAT-GRAPHVIZ-DOES "What Graphviz Does")
       (!VALIDATE-REMOTE-PAGE-STORY-SHAPE WHAT-GRAPHVIZ-DOES)
       (!PRESERVE-SOURCE-STORY-ITEMS :PAGE WHAT-GRAPHVIZ-DOES
        :PRESERVE-EXISTING-ITEM-IDS T :PRESERVE-EXISTING-STORY-ORDER T)
       (!CONSTRUCT-EXPLICIT-FORK-JOURNAL-ACTION :PAGE WHAT-GRAPHVIZ-DOES :TYPE
        "fork" :SITE "does.ward.dojo.fed.wiki" :DATE
        :EXECUTION-TIME-MONOTONIC-EPOCH-MILLIS)
       (!RETAIN-HYPERDOC-ONLY-FORK-PROVENANCE :PAGE WHAT-GRAPHVIZ-DOES
        :SOURCE-SLUG "what-graphviz-does" :TARGET-SITE "wiki.ralfbarkow.ch"
        :TARGET-SLUG "what-graphviz-does")
       (!ADAPT-FEDWIKI-MATERIALIZATION-ENTRY-FOR-REMOTE-FORK-PAGE
        WHAT-GRAPHVIZ-DOES)
       (!WRITE-REMOTE-FORK-MATERIALIZATION-ENTRY WHAT-GRAPHVIZ-DOES)
       (!PLAN-PAGE-ATTACHED-ASDF-HOME-OBJECT WHAT-GRAPHVIZ-DOES)
       (!LOAD-PAGE-ASDF-ASSET-WRITER-SYSTEM :SYSTEM
        ":HYPERDOC/FEDWIKI-ASDF-ASSETS")
       (!VALIDATE-PAGE-ASDF-ASSET-WRITER-SYMBOLS :REQUIRED
        ("HYPERDOC:MAKE-PAGE-ASDF-ASSET-SPEC" "HYPERDOC:WRITE-PAGE-ASDF-SYSTEM"
         "HYPERDOC:LOAD-PAGE-ASDF-SYSTEM"))
       (!ATTACH-READER-LAYER-AS-PAGE-ATTACHED-ASDF :PAGE WHAT-GRAPHVIZ-DOES
        :AFTER-LOAD-BOUNDARY T :PURPOSE
        "reader operation: dense paragraph -> jargon fragments -> hierarchy")
       (!DEFER-PAGE-LOCAL-SQLITE-READER-LAYER WHAT-GRAPHVIZ-DOES)
       (!INSPECT-LOCAL-FORK-IN-HYPERDOC :VIEWS
        (:PAGE-JSON :JOURNAL :STORY-ITEMS :FORK-PROVENANCE :ASDF-HOME
         :READER-LAYER))))
     :REVISED-SHOP3-METHOD-AS-DATA
     (:DEFDOMAIN WHAT-GRAPHVIZ-DOES-LOCAL-FORK-CANDIDATE-V2
      (:METHOD (!MATERIALIZE-LOCAL-FORK-FROM-JSON ?PAGE)
       ((ROUTE-SELECTED ?PAGE HYPERDOC-LOCAL-MATERIALIZATION-ROUTE)
        (PAGE-MATERIALIZATION-PLANNING-ENTRYPOINT SATISFIED-CURRENT-IMAGE)
        (EXPLICIT-FORK-JOURNAL-ACTION-DESIGN INSPECTED-VALID)
        (REMOTE-FORK-MATERIALIZATION-OPERATOR-DESIGN INSPECTED-VALID)
        (PAGE-ASDF-ASSET-WRITER-LOAD-BOUNDARY INSPECTED-VALID)
        (PAGE-LOCAL-SQLITE-READER-LAYER DEFERRED))
       ((!FETCH-REMOTE-PAGE-JSON ?PAGE)
        (!VALIDATE-REMOTE-PAGE-TITLE ?PAGE "What Graphviz Does")
        (!VALIDATE-REMOTE-PAGE-STORY-SHAPE ?PAGE)
        (!PRESERVE-SOURCE-STORY-ITEMS ?PAGE)
        (!CONSTRUCT-EXPLICIT-FORK-JOURNAL-ACTION ?PAGE)
        (!RETAIN-HYPERDOC-ONLY-FORK-PROVENANCE ?PAGE)
        (!ADAPT-FEDWIKI-MATERIALIZATION-ENTRY-FOR-REMOTE-FORK-PAGE ?PAGE)
        (!WRITE-REMOTE-FORK-MATERIALIZATION-ENTRY ?PAGE)
        (!PLAN-PAGE-ATTACHED-ASDF-HOME-OBJECT ?PAGE)
        (!LOAD-PAGE-ASDF-ASSET-WRITER-SYSTEM :SYSTEM
         ":HYPERDOC/FEDWIKI-ASDF-ASSETS")
        (!VALIDATE-PAGE-ASDF-ASSET-WRITER-SYMBOLS ?PAGE)
        (!ATTACH-READER-LAYER-AS-PAGE-ATTACHED-ASDF ?PAGE)
        (!DEFER-PAGE-LOCAL-SQLITE-READER-LAYER ?PAGE)
        (!INSPECT-LOCAL-FORK-IN-HYPERDOC ?PAGE))))
     :EXECUTION-GATES
     ((REMOTE-FETCH-GATE :TASK (!FETCH-REMOTE-PAGE-JSON WHAT-GRAPHVIZ-DOES)
       :REQUIRES EXPLICIT-EXECUTION-STAGE-PERMISSION)
      (FORK-ACTION-GATE :TASK
       (!CONSTRUCT-EXPLICIT-FORK-JOURNAL-ACTION WHAT-GRAPHVIZ-DOES) :REQUIRES
       (REMOTE-PAGE-JSON-FETCHED T SOURCE-JOURNAL-LAST-DATE-KNOWN T))
      (PAGE-JSON-WRITE-GATE :TASK
       (!WRITE-REMOTE-FORK-MATERIALIZATION-ENTRY WHAT-GRAPHVIZ-DOES) :REQUIRES
       (REMOTE-FORK-MATERIALIZATION-ENTRY-CONSTRUCTIBLE T
        EXPLICIT-FORK-ACTION-CONSTRUCTED T))
      (ASDF-LOAD-GATE :TASK
       (!LOAD-PAGE-ASDF-ASSET-WRITER-SYSTEM :SYSTEM
        ":HYPERDOC/FEDWIKI-ASDF-ASSETS")
       :REQUIRES EXPLICIT-EXECUTION-STAGE-PERMISSION)
      (ASDF-WRITE-GATE :TASK
       (!ATTACH-READER-LAYER-AS-PAGE-ATTACHED-ASDF WHAT-GRAPHVIZ-DOES)
       :REQUIRES
       (PAGE-ASDF-ASSET-WRITER-SYMBOLS-FBOUND T PAGE-JSON-FORK-MATERIALIZED T))
      (SQLITE-GATE :TASK (!CREATE-SQLITE WHAT-GRAPHVIZ-DOES) :STATUS DEFERRED))
     :CANONICAL-FEDWIKI-BOUNDARIES
     ((PRESERVE-SOURCE-STORY-ITEM-IDS T) (PRESERVE-SOURCE-STORY-ORDER T)
      (PRESERVE-SOURCE-JOURNAL T) (APPEND-CANONICAL-FORK-ACTION T)
      (CANONICAL-FORK-ACTION-SHAPE
       ((TYPE "fork") (SITE "does.ward.dojo.fed.wiki")
        (DATE :EXECUTION-TIME-MONOTONIC-EPOCH-MILLIS)))
      (DO-NOT-ADD-HYPERDOC-ONLY-PROVENANCE-TO-CANONICAL-PAGE-JSON T)
      (DO-NOT-EXECUTE-GRAPHVIZ T) (DO-NOT-NORMALIZE-PLUGIN-ITEMS T))
     :HYPERDOC-ONLY-PROVENANCE
     ((SOURCE-SITE "does.ward.dojo.fed.wiki")
      (SOURCE-SLUG "what-graphviz-does") (TARGET-SITE "wiki.ralfbarkow.ch")
      (TARGET-SLUG "what-graphviz-does")
      (READER-PURPOSE "dense paragraph -> jargon fragments -> hierarchy")
      (ROUTE HYPERDOC-LOCAL-MATERIALIZATION-ROUTE))
     :ACCEPTANCE-FOR-CURRENT-TASK
     ((CANDIDATE-CHILD-PLAN-REVISED T)
      (FORK-JOURNAL-CONSTRUCTOR-DESIGN-INTEGRATED T)
      (REMOTE-FORK-MATERIALIZATION-DESIGN-INTEGRATED T)
      (PAGE-ASDF-LOAD-BOUNDARY-INTEGRATED T) (SQLITE-DEFERRED T)
      (EXECUTION-GATES-EXPLICIT T) (CANONICAL-FEDWIKI-BOUNDARIES-EXPLICIT T)
      (HYPERDOC-ONLY-PROVENANCE-SEPARATED T) (NO-LOAD-PERFORMED T)
      (NO-FETCH-PERFORMED T) (NO-PAGE-JSON-WRITTEN T) (NO-ASDF-WRITTEN T)
      (NO-SQLITE-CREATED T))
     :EXECUTION-READINESS
     (:STATUS REVISED-PLAN-VALID-BUT-NOT-EXECUTED :REASON
      "The revised candidate child plan is coherent and gate-complete, but it still requires a later execution-stage boundary before fetching, loading, writing, or creating SQLite.")
     :NEXT-TASK
     (!INSPECT-REVISED-CANDIDATE-CHILD-MATERIALIZATION-PLAN
      WHAT-GRAPHVIZ-DOES))
 :RECORDED-INSPECTION
 (:PARENT-TASK
  (!REVISE-CANDIDATE-CHILD-MATERIALIZATION-PLAN-WITH-DESIGNED-OPERATORS
   WHAT-GRAPHVIZ-DOES)
  :CURRENT-TASK
  (!INSPECT-REVISED-CANDIDATE-CHILD-MATERIALIZATION-PLAN WHAT-GRAPHVIZ-DOES)
  :STAGE-BOUNDARY
  ((MAY-INSPECT-REVISED-CANDIDATE-CHILD-PLAN T)
   (MAY-FETCH-REMOTE-PAGE-JSON NIL) (MAY-CONSTRUCT-FORK-JOURNAL-ACTION NIL)
   (MAY-LOAD-MISSING-SOURCE-FILES NIL) (MAY-WRITE-LOCAL-PAGE-JSON NIL)
   (MAY-WRITE-PAGE-ATTACHED-ASDF NIL) (MAY-CREATE-SQLITE NIL))
  :PLAN-PRESENT-P T :PLAN-OBJECT #1# :INSPECTION-FINDINGS
  ((REVISED-PLAN-PRODUCED :STATUS SATISFIED :EVIDENCE
    "The plan object contains REVISED-CANDIDATE-CHILD-MATERIALIZATION-PLAN with task (!MATERIALIZE-LOCAL-FORK-FROM-JSON WHAT-GRAPHVIZ-DOES).")
   (FORK-JOURNAL-CONSTRUCTOR-INTEGRATED :STATUS SATISFIED :EVIDENCE
    "The method now uses !CONSTRUCT-EXPLICIT-FORK-JOURNAL-ACTION with canonical type fork, source site does.ward.dojo.fed.wiki, and execution-time monotonic date.")
   (HYPERDOC-PROVENANCE-SEPARATED :STATUS SATISFIED :EVIDENCE
    "The method keeps source-slug, target-site, and target-slug in !RETAIN-HYPERDOC-ONLY-FORK-PROVENANCE rather than in canonical page JSON.")
   (REMOTE-FORK-MATERIALIZER-INTEGRATED :STATUS SATISFIED :EVIDENCE
    "The generic !MATERIALIZE-LOCAL-PAGE-JSON-AS-FORK step has been replaced by !ADAPT-FEDWIKI-MATERIALIZATION-ENTRY-FOR-REMOTE-FORK-PAGE followed by !WRITE-REMOTE-FORK-MATERIALIZATION-ENTRY.")
   (REMOTE-WRITE-STILL-GATED :STATUS SATISFIED :EVIDENCE
    "The PAGE-JSON-WRITE-GATE requires both REMOTE-FORK-MATERIALIZATION-ENTRY-CONSTRUCTIBLE and EXPLICIT-FORK-ACTION-CONSTRUCTED.")
   (ASDF-LOAD-BOUNDARY-INTEGRATED :STATUS SATISFIED :EVIDENCE
    "The method includes !LOAD-PAGE-ASDF-ASSET-WRITER-SYSTEM followed by !VALIDATE-PAGE-ASDF-ASSET-WRITER-SYMBOLS before attaching the reader layer.")
   (ASDF-WRITE-STILL-GATED :STATUS SATISFIED :EVIDENCE
    "The ASDF-WRITE-GATE requires PAGE-ASDF-ASSET-WRITER-SYMBOLS-FBOUND and PAGE-JSON-FORK-MATERIALIZED.")
   (CANONICAL-FEDWIKI-BOUNDARIES :STATUS SATISFIED :EVIDENCE
    "The plan preserves source story item IDs, story order, source journal, appends a canonical fork action, does not add HyperDoc-only provenance to canonical JSON, does not execute Graphviz, and does not normalize plugin items.")
   (SQLITE-DEFERRED :STATUS SATISFIED :EVIDENCE
    "The SQLITE-GATE has status DEFERRED and the method contains !DEFER-PAGE-LOCAL-SQLITE-READER-LAYER.")
   (SIDE-EFFECT-BOUNDARY :STATUS SATISFIED :EVIDENCE
    "The acceptance list records NO-LOAD-PERFORMED, NO-FETCH-PERFORMED, NO-PAGE-JSON-WRITTEN, NO-ASDF-WRITTEN, and NO-SQLITE-CREATED."))
  :EXECUTION-READINESS
  (:STATUS REVISED-PLAN-VALID-BUT-NOT-EXECUTED :REASON
   "The revised child plan is coherent and gate-complete. It is still not a runnable execution plan because fetch, fork-action construction, ASDF load, page JSON write, ASDF write, and SQLite creation remain outside the current stage boundary.")
  :PREPARATION-READINESS
  (:STATUS PREPARATION-COMPLETE :REASON
   "The preparation task has located existing operators/contracts, classified gaps, designed the missing fork/materialization adaptations, inserted the ASDF load boundary, and produced an inspected revised child plan.")
  :REMAINING-BEFORE-EXECUTION
  ((EXPLICITLY-OPEN-EXECUTION-STAGE-BOUNDARY :REQUIRED T)
   (FETCH-REMOTE-PAGE-JSON :TASK (!FETCH-REMOTE-PAGE-JSON WHAT-GRAPHVIZ-DOES)
    :REQUIRES EXPLICIT-EXECUTION-STAGE-PERMISSION)
   (CONSTRUCT-EXPLICIT-FORK-JOURNAL-ACTION :TASK
    (!CONSTRUCT-EXPLICIT-FORK-JOURNAL-ACTION WHAT-GRAPHVIZ-DOES) :REQUIRES
    (REMOTE-PAGE-JSON-FETCHED T SOURCE-JOURNAL-LAST-DATE-KNOWN T))
   (WRITE-REMOTE-FORK-MATERIALIZATION-ENTRY :TASK
    (!WRITE-REMOTE-FORK-MATERIALIZATION-ENTRY WHAT-GRAPHVIZ-DOES) :REQUIRES
    (REMOTE-FORK-MATERIALIZATION-ENTRY-CONSTRUCTIBLE T
     EXPLICIT-FORK-ACTION-CONSTRUCTED T))
   (LOAD-PAGE-ASDF-ASSET-WRITER-SYSTEM :TASK
    (!LOAD-PAGE-ASDF-ASSET-WRITER-SYSTEM :SYSTEM
     ":HYPERDOC/FEDWIKI-ASDF-ASSETS")
    :REQUIRES EXPLICIT-EXECUTION-STAGE-PERMISSION)
   (ATTACH-READER-LAYER-AS-PAGE-ATTACHED-ASDF :TASK
    (!ATTACH-READER-LAYER-AS-PAGE-ATTACHED-ASDF WHAT-GRAPHVIZ-DOES) :REQUIRES
    (PAGE-ASDF-ASSET-WRITER-SYMBOLS-FBOUND T PAGE-JSON-FORK-MATERIALIZED T))
   (CREATE-SQLITE :TASK (!CREATE-SQLITE WHAT-GRAPHVIZ-DOES) :STATUS DEFERRED))
  :ACCEPTANCE-FOR-CURRENT-TASK
  ((REVISED-CANDIDATE-CHILD-PLAN-INSPECTED T)
   (FORK-JOURNAL-CONSTRUCTOR-INTEGRATION-CONFIRMED T)
   (REMOTE-FORK-MATERIALIZATION-INTEGRATION-CONFIRMED T)
   (ASDF-LOAD-BOUNDARY-INTEGRATION-CONFIRMED T) (EXECUTION-GATES-CONFIRMED T)
   (CANONICAL-FEDWIKI-BOUNDARIES-CONFIRMED T)
   (HYPERDOC-ONLY-PROVENANCE-SEPARATION-CONFIRMED T)
   (SQLITE-DEFERRED-CONFIRMED T) (PREPARATION-COMPLETE T) (NO-LOAD-PERFORMED T)
   (NO-FETCH-PERFORMED T) (NO-PAGE-JSON-WRITTEN T) (NO-ASDF-WRITTEN T)
   (NO-SQLITE-CREATED T))
  :NEXT-VALID-TASKS
  ((!RECORD-CANDIDATE-CHILD-MATERIALIZATION-PLAN WHAT-GRAPHVIZ-DOES)
   (!CLOSE-PREPARE-HYPERDOC-LOCAL-FORK-MATERIALIZATION-PLAN WHAT-GRAPHVIZ-DOES)
   (!OPEN-EXECUTION-STAGE-FOR-LOCAL-FORK-MATERIALIZATION WHAT-GRAPHVIZ-DOES))
  :RECOMMENDED-NEXT-TASK
  (!RECORD-CANDIDATE-CHILD-MATERIALIZATION-PLAN WHAT-GRAPHVIZ-DOES) :NOT-YET
  ((!FETCH-REMOTE-PAGE-JSON WHAT-GRAPHVIZ-DOES)
   (!CONSTRUCT-EXPLICIT-FORK-JOURNAL-ACTION WHAT-GRAPHVIZ-DOES)
   (!WRITE-REMOTE-FORK-MATERIALIZATION-ENTRY WHAT-GRAPHVIZ-DOES)
   (!LOAD-PAGE-ASDF-ASSET-WRITER-SYSTEM :SYSTEM
    ":HYPERDOC/FEDWIKI-ASDF-ASSETS")
   (!WRITE-PAGE-ATTACHED-ASDF WHAT-GRAPHVIZ-DOES)
   (!CREATE-SQLITE WHAT-GRAPHVIZ-DOES)))
 :EXECUTION-READINESS
 (:STATUS REVISED-PLAN-VALID-BUT-NOT-EXECUTED :REASON
  "This artifact records the prepared child materialization plan. It does not execute the plan.")
 :EXECUTION-GATES
 ((REMOTE-FETCH-GATE :TASK (!FETCH-REMOTE-PAGE-JSON WHAT-GRAPHVIZ-DOES)
   :REQUIRES EXPLICIT-EXECUTION-STAGE-PERMISSION)
  (FORK-ACTION-GATE :TASK
   (!CONSTRUCT-EXPLICIT-FORK-JOURNAL-ACTION WHAT-GRAPHVIZ-DOES) :REQUIRES
   (REMOTE-PAGE-JSON-FETCHED T SOURCE-JOURNAL-LAST-DATE-KNOWN T))
  (PAGE-JSON-WRITE-GATE :TASK
   (!WRITE-REMOTE-FORK-MATERIALIZATION-ENTRY WHAT-GRAPHVIZ-DOES) :REQUIRES
   (REMOTE-FORK-MATERIALIZATION-ENTRY-CONSTRUCTIBLE T
    EXPLICIT-FORK-ACTION-CONSTRUCTED T))
  (ASDF-LOAD-GATE :TASK
   (!LOAD-PAGE-ASDF-ASSET-WRITER-SYSTEM :SYSTEM
    ":HYPERDOC/FEDWIKI-ASDF-ASSETS")
   :REQUIRES EXPLICIT-EXECUTION-STAGE-PERMISSION)
  (ASDF-WRITE-GATE :TASK
   (!ATTACH-READER-LAYER-AS-PAGE-ATTACHED-ASDF WHAT-GRAPHVIZ-DOES) :REQUIRES
   (PAGE-ASDF-ASSET-WRITER-SYMBOLS-FBOUND T PAGE-JSON-FORK-MATERIALIZED T))
  (SQLITE-GATE :TASK (!CREATE-SQLITE WHAT-GRAPHVIZ-DOES) :STATUS DEFERRED))
 :CANONICAL-FEDWIKI-BOUNDARIES
 ((PRESERVE-SOURCE-STORY-ITEM-IDS T) (PRESERVE-SOURCE-STORY-ORDER T)
  (PRESERVE-SOURCE-JOURNAL T) (APPEND-CANONICAL-FORK-ACTION T)
  (CANONICAL-FORK-ACTION-SHAPE
   ((TYPE "fork") (SITE "does.ward.dojo.fed.wiki")
    (DATE :EXECUTION-TIME-MONOTONIC-EPOCH-MILLIS)))
  (DO-NOT-ADD-HYPERDOC-ONLY-PROVENANCE-TO-CANONICAL-PAGE-JSON T)
  (DO-NOT-EXECUTE-GRAPHVIZ T) (DO-NOT-NORMALIZE-PLUGIN-ITEMS T))
 :ACCEPTANCE-FOR-CURRENT-TASK
 ((CANDIDATE-CHILD-MATERIALIZATION-PLAN-RECORDED T) (PLAN-ARTIFACT-WRITTEN T)
  (RECORDED-PLAN-IS-NON-EXECUTED T) (EXECUTION-GATES-RECORDED T)
  (CANONICAL-FEDWIKI-BOUNDARIES-RECORDED T) (NO-LOAD-PERFORMED T)
  (NO-FETCH-PERFORMED T) (NO-PAGE-JSON-WRITTEN T) (NO-ASDF-WRITTEN T)
  (NO-SQLITE-CREATED T))
 :NEXT-VALID-TASKS
 ((!CLOSE-PREPARE-HYPERDOC-LOCAL-FORK-MATERIALIZATION-PLAN WHAT-GRAPHVIZ-DOES)
  (!OPEN-EXECUTION-STAGE-FOR-LOCAL-FORK-MATERIALIZATION WHAT-GRAPHVIZ-DOES)))
