(:TASK
 "(!LOAD-PAGE-ASDF-ASSET-WRITER-SYSTEM :SYSTEM :HYPERDOC/FEDWIKI-ASDF-ASSETS)"
 :PARENT-TASK
 "(!NORMALIZE-PAGE-ATTACHED-ASDF-HOME-EVIDENCE-DESCRIPTORS WHAT-GRAPHVIZ-DOES)"
 :STAGE-BOUNDARY
 ((MAY-LOAD-PAGE-ASDF-ASSET-WRITER-SYSTEM T)
  (MAY-VALIDATE-PAGE-ASDF-ASSET-WRITER-SYMBOLS T)
  (MAY-WRITE-PAGE-ATTACHED-ASDF NIL) (MAY-CREATE-SQLITE NIL) (MAY-COMMIT NIL))
 :LOAD-ATTEMPT
 (:SYSTEM-NAME "HYPERDOC/FEDWIKI-ASDF-ASSETS" :LOAD-SUCCEEDED-P NIL
  :SYSTEM-FOUND-AFTER-LOAD-P T :CONDITION
  (:CONDITION-TYPE-NAME #A((28) BASE-CHAR . "ASDF/PLAN:SYSTEM-OUT-OF-DATE")
   :CONDITION-MESSAGE #A((32) BASE-CHAR . "system alexandria is out of date")))
 :REQUIRED-SYMBOLS
 ((:PACKAGE-NAME #1="HYPERDOC" :PACKAGE-PRESENT-P T :SYMBOL-NAME
   "MAKE-PAGE-ASDF-ASSET-SPEC" :SYMBOL-PRESENT-P T :SYMBOL-STATUS-NAME
   #2=#A((8) BASE-CHAR . "EXTERNAL") :SYMBOL-DESIGNATOR
   #A((35) BASE-CHAR . "HYPERDOC::MAKE-PAGE-ASDF-ASSET-SPEC") :FBOUND-P NIL)
  (:PACKAGE-NAME #1# :PACKAGE-PRESENT-P T :SYMBOL-NAME "WRITE-PAGE-ASDF-SYSTEM"
   :SYMBOL-PRESENT-P T :SYMBOL-STATUS-NAME #2# :SYMBOL-DESIGNATOR
   #A((32) BASE-CHAR . "HYPERDOC::WRITE-PAGE-ASDF-SYSTEM") :FBOUND-P NIL)
  (:PACKAGE-NAME #1# :PACKAGE-PRESENT-P T :SYMBOL-NAME "LOAD-PAGE-ASDF-SYSTEM"
   :SYMBOL-PRESENT-P T :SYMBOL-STATUS-NAME #2# :SYMBOL-DESIGNATOR
   #A((31) BASE-CHAR . "HYPERDOC::LOAD-PAGE-ASDF-SYSTEM") :FBOUND-P NIL))
 :VALIDATION
 (:ALL-REQUIRED-SYMBOLS-FBOUND-P NIL :NO-PAGE-ATTACHED-ASDF-WRITTEN T
  :NO-SQLITE-CREATED T :NO-COMMIT-PERFORMED T)
 :ACCEPTANCE-FOR-CURRENT-TASK
 ((PAGE-ASDF-ASSET-WRITER-SYSTEM-LOAD-ATTEMPTED T)
  (PAGE-ASDF-ASSET-WRITER-SYSTEM-LOADED NIL)
  (REQUIRED-WRITER-SYMBOLS-OBSERVED NIL) (NO-PAGE-ATTACHED-ASDF-WRITTEN T)
  (NO-SQLITE-CREATED T) (NO-COMMIT-PERFORMED T))
 :NEXT-TASK
 "(!VALIDATE-PAGE-ASDF-ASSET-WRITER-SYMBOLS :REQUIRED (\"HYPERDOC:MAKE-PAGE-ASDF-ASSET-SPEC\" \"HYPERDOC:WRITE-PAGE-ASDF-SYSTEM\" \"HYPERDOC:LOAD-PAGE-ASDF-SYSTEM\"))")
