(:TOPIC-ID "task:materialize-zettel-9124-dmx-topicmap-view" :TITLE
 "Materialize Zettel 9124 DMX topic-map view" :KIND :SHOP3-PLANNED-VIEW-TASK
 :STATUS :MATERIALIZED :PARENT-PLAN "plan:zettel-9124-pdf-reading-as-web"
 :SOURCE-DB "var/dmx-associative-mirror.sqlite" :VIEW-TOPIC
 "view:zettel-9124-dmx-topicmap" :DECISION
 (:USE-SHOP3 T :ROLE
  "SHOP3 owns decomposition and next-task choice; the offline view must not depend on a live SHOP3 image.")
 :SHOP3-DOMAIN
 (DEFDOMAIN ZETTEL-9124-DMX-TOPICMAP-VIEW
  ((:OPERATOR (!PROJECT-DMX-SQLITE-TO-TOPICMAP-IR ?DB ?VIEW) NIL NIL
    ((TOPICMAP-IR-PROJECTED ?VIEW)))
   (:OPERATOR (!RENDER-TOPICMAP-IR-AS-LIVE-LISP-VIEW ?VIEW)
    ((TOPICMAP-IR-PROJECTED ?VIEW)) NIL ((LIVE-LISP-VIEW-RENDERED ?VIEW)))
   (:OPERATOR (!RENDER-TOPICMAP-IR-AS-OFFLINE-HTML ?VIEW)
    ((TOPICMAP-IR-PROJECTED ?VIEW)) NIL ((OFFLINE-HTML-RENDERED ?VIEW)))
   (:OPERATOR (!PERSIST-VIEW-TASK-TO-DMX-SQLITE ?VIEW)
    ((TOPICMAP-IR-PROJECTED ?VIEW)) NIL
    ((VIEW-TASK-PERSISTED-TO-DMX-SQLITE ?VIEW)))
   (:OPERATOR (!FILE-OUT-TOPICMAP-VIEW-ARTIFACTS ?VIEW)
    ((LIVE-LISP-VIEW-RENDERED ?VIEW) (OFFLINE-HTML-RENDERED ?VIEW)) NIL
    ((TOPICMAP-VIEW-ARTIFACTS-FILED-OUT ?VIEW)))
   (:METHOD (!MATERIALIZE-DMX-TOPICMAP-VIEW ?DB ?VIEW) NIL
    ((!PROJECT-DMX-SQLITE-TO-TOPICMAP-IR ?DB ?VIEW)
     (!RENDER-TOPICMAP-IR-AS-LIVE-LISP-VIEW ?VIEW)
     (!RENDER-TOPICMAP-IR-AS-OFFLINE-HTML ?VIEW)
     (!PERSIST-VIEW-TASK-TO-DMX-SQLITE ?VIEW)
     (!FILE-OUT-TOPICMAP-VIEW-ARTIFACTS ?VIEW)))))
 :SHOP3-PROBLEM
 (DEFPROBLEM ZETTEL-9124-DMX-TOPICMAP-VIEW-PROBLEM
  ZETTEL-9124-DMX-TOPICMAP-VIEW
  ((DMX-SQLITE "var/dmx-associative-mirror.sqlite")
   (VIEW "view:zettel-9124-dmx-topicmap"))
  ((!MATERIALIZE-DMX-TOPICMAP-VIEW "var/dmx-associative-mirror.sqlite"
    "view:zettel-9124-dmx-topicmap")))
 :SELECTED-SHOP3-PLAN
 ((!PROJECT-DMX-SQLITE-TO-TOPICMAP-IR "var/dmx-associative-mirror.sqlite"
   "view:zettel-9124-dmx-topicmap")
  (!RENDER-TOPICMAP-IR-AS-LIVE-LISP-VIEW "view:zettel-9124-dmx-topicmap")
  (!RENDER-TOPICMAP-IR-AS-OFFLINE-HTML "view:zettel-9124-dmx-topicmap")
  (!PERSIST-VIEW-TASK-TO-DMX-SQLITE "view:zettel-9124-dmx-topicmap")
  (!FILE-OUT-TOPICMAP-VIEW-ARTIFACTS "view:zettel-9124-dmx-topicmap")))