#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: tools/install-dreyeck-hyperdoc-mcp-sidecar.sh [--target-dir DIR] [--package-path PATH]

Install a host-owned HyperDoc MCP module copy and sidecar config for dreyeck.

Default target directory:
  /etc/nixos/hyperdoc

Behavior:
- copies nix/modules/hyperdoc-mcp-release.nix into the target directory
- renders dreyeck-hyperdoc-mcp-sidecar.nix in the target directory
- pins services.hyperdocMcp.packagePath to a concrete /nix/store path string

Options:
  --target-dir DIR    install into DIR instead of /etc/nixos/hyperdoc
  --package-path PATH use PATH instead of building .#hyperdoc-release
  -h, --help          show this help
EOF
}

target_dir="/etc/nixos/hyperdoc"
package_path=""

while [ "$#" -gt 0 ]; do
  case "$1" in
    --target-dir)
      target_dir="${2:?missing value for --target-dir}"
      shift 2
      ;;
    --package-path)
      package_path="${2:?missing value for --package-path}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

script_dir="$(cd -- "$(dirname -- "$0")" && pwd)"
repo_root="$(cd -- "$script_dir/.." && pwd)"
module_source="$repo_root/nix/modules/hyperdoc-mcp-release.nix"
module_target="$target_dir/hyperdoc-mcp-release.nix"
sidecar_target="$target_dir/dreyeck-hyperdoc-mcp-sidecar.nix"

if [ -z "$package_path" ]; then
  package_path="$(nix build "$repo_root#hyperdoc-release" --no-link --print-out-paths)"
fi

install -d "$target_dir"
install -m 0644 "$module_source" "$module_target"

cat >"$sidecar_target" <<EOF
{ lib, ... }:
{
  # Generated by tools/install-dreyeck-hyperdoc-mcp-sidecar.sh.
  #
  # This is the hardened steady-state path for dreyeck:
  # - host-owned import path inside /etc/nixos
  # - repo module copied into the host config tree
  # - MCP executable root pinned as a quoted /nix/store path
  #
  # Refresh after a new HyperDoc release by rerunning the installer.
  imports = [
    ./hyperdoc-mcp-release.nix
  ];

  services.hyperdocMcp = {
    enable = true;
    packagePath = "$package_path";
    bindAddress = "127.0.0.1";
    port = 8787;
    dataDir = "/var/lib/hyperdoc/mcp";
    workspaceTopicmapId = 919822;
    dmxBaseUrl = "https://dmx.ralfbarkow.ch";
    enableLiveWrites = false;
    allowedOrigins = [
      "https://mcp.dreyeck.ch"
    ];
    reverseProxyHost = "mcp.dreyeck.ch";
    reverseProxyPath = "/mcp";
  };

  security.acme.certs."mcp.dreyeck.ch".email =
    lib.mkDefault "ralf.barkow@me.com";
}
EOF

cat <<EOF
Installed host-owned MCP module copy:
  $module_target
Installed host-owned MCP sidecar:
  $sidecar_target
Pinned package path:
  $package_path

Import the sidecar from the authoritative host config, for example:
  ./hyperdoc/dreyeck-hyperdoc-mcp-sidecar.nix
EOF
